### ISSUE TITLE
The pieces desapear

### ISSUE THREAD

**Issue by fabionavarroescritor** [hicetnunc2000/hicetnunc#1000]
hello guys
so I enter at the site right now and discover that all my pieces were taken out from the first market and I receive a lot of messages from the site to swap again all my pieces, so I'll have to spend money that I don't have to make everything again
what's happenning?
And my photo profile was erased
please I wanna know what's going on and what I have to do to to fix?
thanks.

and if I enter at the  v1 swaps menu I can't erase the swap and only can make batch transactions

and now, besides the fact that my photo profile was gone and I have to make the tezo's profile, I discorver that mistereously I bought something two or thre days ago, and surprise!!
I wasn't one line that day
so
once again I ask please someone could tell me what's going on?
thanks

**Comment by crzypatchwork** [comment]
we are in a migration phase and you need to delist and relist your pieces if you wish. if you can't cancel swaps there might be a number of reasons for this. node instabilities etc. one need to be aware of the context we're experimenting. profiles are being updated for us to have a decentralized sign in. updates are expected on the official twitter and on the website to assist the community as a whole.

**Comment by fabionavarroescritor** [comment]
all right.

so there's two more questions:

a) what about the buying of piece that  I don't bought it?

b) I couldn't add my twitter account 'cos everytime there's a error message on the twitte lines that the tezo's profile site produce

**Comment by fabionavarroescritor** [comment]
thanks for the answers ultill now

**Comment by skenaja** [comment]
a) what's your wallet address, some more information about the mystery piece would be useful too, e.g. the objkt number.

b) tz profiles has a support group on Telegram: http://t.me/tezosprofiles

**Comment by fabionavarroescritor** [comment]
Hi skenaja

the wallet's adress is tz1YUtv1rGPToF5Qo3tiUUfMcXjqdVZXTmV7

and I still can't add my twitter account 'cos of the same error tha before

one more question?

I still have to re-mint every piece that was on the site before?

thanks

**Comment by fabionavarroescritor** [comment]
and one more thing

on my wallet now appears operations that I didn't make
like this

https://tzkt.io/opNnRdCuG8JhVvaD2NTx5cBZDLiztiNaVfdJ1BiWYZGnXDupjCt

**Comment by fabionavarroescritor** [comment]
hello!??

**Comment by fabionavarroescritor** [comment]
to update the issue (if there's someone from the site interessed). 
I'm talking with Kalamint suppport and from the first look that the guys made, it seems that was a copy minter that made the transaction. 
I wanna know if the copy minter made his way through from the  secondary market from HEN or from kalamint

**Comment by crzypatchwork** [comment]
regarding the migration: you don't need to remint pieces. you just need to cancel swaps and relist them on the market.

about twitter verification you should ask tezos profile for support. 

and about transactions from your wallet that "you didn't make" keeping your wallet/private keys safe is your responsibility. 

if you have any other issues open a new one as there are inumerous unrelated issues being discussed in this conversation.
