### ISSUE TITLE
5 Transactions stuck in pending status

### ISSUE THREAD

**Issue by potatoes2** [hicetnunc2000/hicetnunc#1001]
**Describe the bug**
Five separate hen purchases all showing pending status in Temple. Some over 2 hours some going back 5 days.

**To Reproduce**
1) Go to activity
2) view transactions 
3) shows 'pending' after word 'interaction'

**Expected behavior**
Expect the operation to be completed by now. 

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 Pro
Firefox  90

**Additional context**
tz1cHBbJBXfYU7Ei2wEcHS23rvBHFuF9o7NY

**Comment by crzypatchwork** [comment]
pending transactions are a blockchain/network issue not related to the app. transactions are reverted in this case.
