### ISSUE TITLE
Can't swap multiple 1/1's or view owner under the collectors tab

### ISSUE THREAD

**Issue by TJohanson82** [hicetnunc2000/hicetnunc#1002]
I have a couple 1/1's I purchased before V2 integration and I no longer have control or the ability to swap. I purchased #105640 on 05/30/2021 and #127418 on 6/11/2021. My wallet ID# is tz1VsHt47xnob2e4A99Vx5qEeT2Rd4yUqg5Z

**Comment by crzypatchwork** [comment]
all assets that one had in market before june 28th must migrate to a new version of the marketplace. you need to cancel your listings to retrieve your assets. manage assets > v1 swaps > cancel swaps

**Comment by TJohanson82** [comment]
I cancelled everything before the migration using v1 swaps and those are the only 2 1/1s I have that didn't transfer correctly. When I completed the V1 Swaps it said there are no longer any OBJKT's remaining, but now when I look those two are showing up. Thank You!
