### ISSUE TITLE
Someone has stolen my NFTs

### ISSUE THREAD

**Issue by Renderburger** [hicetnunc2000/hicetnunc#1004]
https://www.hicetnunc.xyz/Render%20burger/creations

This account is fake and has stolen my works.
I want Hicetnunc to remove him and report this guy.

There is no other way to message Hicetnunc and its very weak for the platform.

**Comment by kylegrover** [comment]
Hi @Renderburger this account has been removed already today.  We're working on new moderation systems, for now the fastest way to contact mod team is in Discord in the #report-copyminting channel

**Comment by Renderburger** [comment]
Thanks but another one is just here:
https://www.hicetnunc.xyz/RemilNft/creations
This is not good

**Comment by kylegrover** [comment]
This account has also been banned already by the time I saw this git issue comment. For fastest response use the Discord channel
