### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#1008]
My objkt does not display when i click on it 

![Untitled-1](https://user-images.githubusercontent.com/83771575/126346571-64c30f5d-8b68-4787-a623-2127be29052a.jpg)

![image](https://user-images.githubusercontent.com/83771575/126346583-90716a1d-413f-4fef-a1cf-ba560ae7d2dc.png)

**Comment by crzypatchwork** [comment]
ipfs instability on your side
