### ISSUE TITLE
Can't submit TzKT Listing Application

### ISSUE THREAD

**Issue by aviad44** [hicetnunc2000/hicetnunc#1010]
I have tried few times to fill the lisring application and submit it (I filled all of the fields including the transaction hash), but every time i press submit I get an error message: "something went wrong".
Can you help me?

**Comment by violetforest** [comment]
hey, which form? https://tzprofiles.com/ this one or the baking bad?

**Comment by aviad44** [comment]
hi,
This:
https://docs.google.com/forms/d/e/1FAIpQLSdlHVqzIxPFL-gAXNxEefyBtI3g3_wiCgcf80bX4tYsXC7b5A/viewform
If you can help somehow I'll be thrilled.
Thanks,
Aviad

**Comment by skenaja** [comment]
You now need to use https://www.hicetnunc.xyz/config to manage your profile (it's also in the menu on Hicetnunc as "Settings")
