### ISSUE TITLE
glsl .frag media type

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [hicetnunc2000/hicetnunc#102]
Hi! I would be interested on adding single frag shaders as media types. I have efficient 2D sandbox I use for thebookofshaders.com that would be perfect

https://github.com/patriciogonzalezvivo/glslCanvas

Needs so updating, but if you thinks this would be a good candidate I can work on it.

The nice features it have are:
- self contain single .frag (text) file as input
- it's 100% glsl 
- there is no wrappers of hidden functions/macros/uniforms
- is well documented and adopted
- support multiple buffers (back buffers)
- texture images can be added to the code as base64 images

Plus is part of a wider ecosystem use in:
- Online editor https://github.com/patriciogonzalezvivo/glslEditor
- Online gallery https://github.com/patriciogonzalezvivo/glslGallery
- OpenGL ES equivalent (runs on Raspberry Pi, Linux, MacOS and Windows) https://github.com/patriciogonzalezvivo/glslViewer
- Visual Code plugin: https://marketplace.visualstudio.com/items?itemName=circledev.glsl-canvas
- OpenFrameworks addon: https://github.com/patriciogonzalezvivo/ofxShader
- Blender Plug in: https://github.com/patriciogonzalezvivo/glslTexture
- OpenFrame https://openframe.io/
- Shader Doodle: https://github.com/halvves/shader-doodle
- The Book of Shaders: https://thebookofshaders.com/
- The Book of Shaders Editor: https://thebookofshaders.com/edit.php
- Pixel Spirit Deck: http://pixelspiritdeck.com/
- Pixel Spirit Deck Editor http://editor.pixelspiritdeck.com/
- Joanie Le Mercier Mapping tool: https://joanielemercier.com/mapping/

There are a lot of artist that already are using this format and I'm sure it will be well received by artist in general.

**Comment by illus0r** [comment]
I know few alternaitves:
- ISF — also supports multipassing, but no mouse control and the json metadata looks redundant.
- Shadertoy — everybody use it. It can export, but all my shaders go into a single json, not clear what to do with it next.
- p5 — can be used not for shaders only. But I'd prefer something more convenient.

I vote for @patriciogonzalezvivo's editor! How can I help with integration?

**Comment by djangobits** [comment]
It sounds definitely interesting (had to look up what frag shaders are first). But remember, the tokens are minted on chain and the content is uploaded to ipfs. So wallets like kukai and other platforms like kalamint will also be able to display and trade these NFTs on their marketplaces. so it might be possible that if a platform is not prepared to integrate that, these NFTs would not be properly displayed. I do not say that it shouldnt be done, but if the support for the media type is too niche, it might be hard to display them everywhere properly. But hey. hicetnunc is an experiment as stated on the about page... where if not here.. haha

**Comment by andrevenancio** [comment]
I welcome this idea! I've mentioned it a bit all over the place (Twitter, discord, and GitHub).

I have a few questions.

1) obviously I could implement a shadertoy type of renderer where you could use the same uniforms and literally copy paste, but with copy paste comes people who actually just do that and publish other people's work. So I'm happy to discuss advantages/disadvantages of mirroring our renderer to an existing WebGL renderer being it Patricio's renderer or Inigo's.

2) on shadertoy you are able to select images and ping pong buffers around. But on our platform we are only allowing to upload 1 file per mint. Which means we either have a set of shared images that we inject automatically via uniform or, we are going to be a little bit limited creatively.

3) WebGL2 is still poorly (not) supported on iOS, which means our shaders would have to either be written in glsl or glsl 3.0es and then converted by the renderer to "normal" glsl if the device doesn't support it. I've done it in the [past](https://github.com/andrevenancio/lowww/blob/master/packages/core/src/core/renderer.js) but it's a bit fiddly to get right. I wonder if Patricio's renderer already takes care of this, and if not what's the best strategy to allow shaders that play across device both now and in the future when apple decides do upgrade to webgl2


I have a couple of things on my todo list but I'm totally happy to pick up this feature once we draft a roadmap for this. Or, if you want to create a PR that's even better. I think [this](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/media-types/index.js) is pretty self explanatory. Do have a look at how I've implemented the [glb/gltf](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/media-types/glb/index.js) renderer as there's some css quirks to render it across all different components where it gets embedded.

I'm super down for this feature 🙌🏻

**Comment by MateSteinforth** [comment]
would it be possible for the frag shader content to live directly on the blockchain?

**Comment by andrevenancio** [comment]
I think we can close this now! For anyone looking at this in the future, there's a couple of GLSL templates available
