### ISSUE TITLE
Cannot load assets via base64 encoded data urls in iframe for interactive objkts

### ISSUE THREAD

**Issue by 0x00000010** [hicetnunc2000/hicetnunc#1026]
![image](https://user-images.githubusercontent.com/86648416/127310780-ce0ce6ca-a847-4366-8ee6-cb49b450aaaf.png)

` src: url(data:application/x-font-woff;charset=utf-8;base64,.....b64data.....)` urls do not load in the iframe, they receive a content security policy violation error

**Comment by kylegrover** [comment]
Fixed here: https://github.com/hicetnunc2000/hicetnunc/pull/1027#event-5082944122
