### ISSUE TITLE
OBJKT#22891 stuck in purgatory

### ISSUE THREAD

**Issue by Criptocromo** [hicetnunc2000/hicetnunc#1028]
Can't burn, swap or do a thing to my OBJKT#22891 (I minted it, is a 1/1 piece) 

Whenever I try to swap it, transaction fails

![image](https://user-images.githubusercontent.com/79951878/127399992-3a7edad7-f6a0-4a32-b9a6-f7da2c56dcb1.png)

If I try to burn it, it says I've got no editions!.

Do you know what happened?, is it beacuse HEN migration issues?.

Wallet address: tz1ZcywWijJmZ3EPm8uMW5QXSxf7YngzSKd5
OBJKT#22891

https://www.hicetnunc.xyz/objkt/22891  

Thanks

**Comment by crzypatchwork** [comment]
this objkt is in the objktswap v1 contract you need to access https://hicetnunc.xyz/tz/tz1ZcywWijJmZ3EPm8uMW5QXSxf7YngzSKd5/v1 and cancel all swaps to retrieve the objkt and reswap it

**Comment by Criptocromo** [comment]
Excuse me!, didn't know that...
 Thanks a lot!.

**Comment by rvorias** [comment]
Can someone post a screenshot where to click or something? I am missing something ..
