### ISSUE TITLE
Do you accept help on UI and UX?

### ISSUE THREAD

**Issue by marcofugaro** [hicetnunc2000/hicetnunc#103]
The overall user journey and experience on the website could be greatly improved.

Do you accept any external directions or you intend to leave the UX as is, making it part of the experience?

Or maybe you have some improvements in mind but haven't gotten around them yet?

**Comment by djangobits** [comment]
Hey! Help is always welcome. I just want to direct you to that discussion we had here:

https://github.com/hicetnunc2000/hicetnunc/issues/40

These are just a few of the comments going all into the same direction. The community made it clear that the "brutalist minimalism" of the page is definitely part of the experience and something that attracts these people. So it will be a fine line to find the right way to move forward. In the discord channel, other devs come together to talk. Join! https://discord.gg/jKNy6PynPK

**Comment by marcofugaro** [comment]
Thanks! Yes I like as well the brutalism style and wording! 🙂 I was talking about some UX patterns. I'll join discord!
