### ISSUE TITLE
Pointer events blocked via CSS on container element of (interactive) SVGs

### ISSUE THREAD

**Issue by ertdfgcvb** [hicetnunc2000/hicetnunc#1031]
Interactive SVGs are embedded trough an `iframe`.
The container `div` of the `iframe` has the CSS property `pointer-events` set to `none`, blocking all possible pointer interactions on itself and its children.
In the specific case the culprit is the `styles_container__16Osc` class, but there might be other classes and other situations where this might happen. 

**To Reproduce**
Upload an interactive SVG which has an active `click` or `mousedown` listener; when clicked nothing happens. 
There is an exception: in the preview the interactions still work (the class may not yet be assigned to the parent `div`).

**Expected behavior**
Pointer events should be fired in the embedded iframe/SVG.

**System**
OS: macOS 10.15.7
Browser: Safari 14.1.2

**Comment by ertdfgcvb** [comment]
An example test SVG that used to work before:
https://www.hicetnunc.xyz/objkt/15105

Working as expected if accessed directly via IFPS (no blocking `pointer-events` in CSS):
https://ipfs.io/ipfs/QmVgWo1BvK2AStdrkSsBGMDs6fuRBErzdo8PQrrupuPkvW

**Comment by kylegrover** [comment]
seems like this was fixed in 3fdc7a633e151a14e9af791bc0b87d9b2b79a828
