### ISSUE TITLE
Outgoing transaction was not initiated by me

### ISSUE THREAD

**Issue by Asong64** [hicetnunc2000/hicetnunc#1032]
Lost XTZ to an outgoing transaction that I did not initiate.

**To Reproduce**
1. Received a notification via Tezos Notifier Bot on Telegram.
2. I was not at my computer when this happened.
3. Went to computer to check wallet.
4. Wallet Activity feed indicates an outgoing transfer of 3xtz was applied at 3:40PM PST
5. Viewing on explorer block shows that it was sent to : tz1itfYQ4YipCDfMHpdui3UNWx2rjAgsLkao
6. Am not able to identify the user the xtz was sent to.

**Expected behavior**
No xtz should have been sent since I was never at my computer, no NFT's were added to my HEN collection. I never sent anyone 3xtz.

**Screenshots**
<img width="523" alt="Screen Shot 2021-07-29 at 11 18 04 PM" src="https://user-images.githubusercontent.com/85418875/127609645-98b1cc59-4fb2-410e-a8e2-9230e58a5efe.png">
<img width="351" alt="Screen Shot 2021-07-29 at 10 55 10 PM" src="https://user-images.githubusercontent.com/85418875/127609650-ce0eba09-39d9-4edb-9285-59a029268f9e.png">

**Desktop (please complete the following information):**
 - Mac OS Big Sur
 - Chrome browser
 - Version 92.0.4515.107 (Official Build) (x86_64)

**Additional context**
I have never sent anyone xtz since I only use my wallet to purchase and mint NFT's.

**Comment by crzypatchwork** [comment]
such issue might be related to your own security practices
