### ISSUE TITLE
Pieces appear in wallet but show as blank pages when clicked

### ISSUE THREAD

**Issue by fractaldreams** [hicetnunc2000/hicetnunc#1034]
**Describe the bug**
I purchased 2x pieces from HEN which were functional when bought.  Soon after my purchase, I decided to click on my pieces to view on single screen (something that worked on these pieces previously), however the screen shows a blank page and does not load.  I also noticed the creator of these pieces is no longer active (perhaps deleted the account), so possibly has something to do with this.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/FractalDreams/collection (this is my collection)
2. Click on the 3rd or 4th OBJKT in the list (the man's face or the morphing 3d shape)
3. The page appears blank - when attempting to go back the page is also blank until a page refresh is done.
*OBJKTS that are behaving like this are as follows: https://www.hicetnunc.xyz/objkt/172667 + https://www.hicetnunc.xyz/objkt/172524

**Expected behavior**
I expected the OBJKT to show in a single screen and show details - as it did previously and does for all other pieces.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome + Firefox

**Comment by crzypatchwork** [comment]
these are likely copyminter pieces you can send them to a burn address if that's the case. we expect to add a burn method on the dApp for such cases. as well we intend to mark accounts verified on twitter.
