### ISSUE TITLE
Stuck on Loading when minting P5.js compressed file

### ISSUE THREAD

**Issue by alia0021** [hicetnunc2000/hicetnunc#1038]
Hi there!

I've followed the steps for "html-p5js-template/" but whenever I click "preview" to mint it gets stuck on loading... My files are all in there and made sure the folder was zipped before uploading. Pls, let me know if I'm missing something. Thx!

<img width="1680" alt="Screen Shot 2021-08-02 at 2 29 28 AM" src="https://user-images.githubusercontent.com/43006219/127814015-da00b1fc-0175-4aba-82e1-80a30380a169.png">

<img width="1680" alt="Screen Shot 2021-08-02 at 2 16 14 AM" src="https://user-images.githubusercontent.com/43006219/127814281-e50a9ce8-66f0-481c-9f01-cf54ef27eadf.png">

**Comment by crzypatchwork** [comment]
there are any errors in the console?
