### ISSUE TITLE
Firefox temple wallet extension not detected

### ISSUE THREAD

**Issue by optimus007** [hicetnunc2000/hicetnunc#104]
![Screenshot 2021-03-13 002533](https://user-images.githubusercontent.com/6885294/110985688-c21bd580-8392-11eb-99a7-65cd638db9b2.png)

firefox v 86.0.1

**Comment by guidoschmidt** [comment]
This works for on Firefox 86.0.1 on macOS (11.2.2). @optimus007 could you check the developer console for errors?

**Comment by andrevenancio** [comment]
Is this still happening @optimus007 ?

**Comment by optimus007** [comment]
Yes @andrevenancio 
![tex](https://user-images.githubusercontent.com/6885294/111485891-07f2e800-875d-11eb-9562-2045105742a8.png)

**Comment by andrevenancio** [comment]
Might need @crzypatchwork to have a look at it

**Comment by crzypatchwork** [comment]
one might need to refresh the page or clean the local storage. we've updated the taquito SDK to possibly treat such wallet connectivity issue.

**Comment by optimus007** [comment]
any way to do a manual connection ?

**Comment by skenaja** [comment]
@optimus007 is this still an issue? I've not seen recent reports on Discord/Twitter.

Reply here & I'll re-open if you're still experiencing difficulties.
