### ISSUE TITLE
#OBJKT links dont work on my creations page

### ISSUE THREAD

**Issue by VGA414** [hicetnunc2000/hicetnunc#1043]
After Last mint my creations tab doesnt allow clicking objkts, objkt links dont work at all on my Creations tab. Collection tab works as usual.

1. Go to https://www.hicetnunc.xyz/tz/tz1L6tKhgfqfnkxb8edJ5UWtNJ4gjkMhfb8V/creations
2. Click on any objkt
4. Link wont work

I want my links working again, only way to get to objkts page is through direct link to objkt..

 - OS: Windows 
 - Browser Chrome
 - Version latest

 - Device: Samsung
 - OS: Android
 - Browser Chrome
 - Version latest 

This started when my Last mint appeared on my creations as gray metadata on queue placeholder, only that objkt link worked. Like my iframes doesnt have link overlays anymore or something..

**Comment by VGA414** [comment]
Added pointer-events: none; clearly fixed this problem, thanks!

**Comment by VGA414** [comment]
Adding pointer-events:none; to collection iframes CSS could fix this issue, atleast on my browser Chrome it fixed anchor to OBJKTs.

**Comment by ertdfgcvb** [comment]
Wild speculation here but this might be a regression due to the fix of #1031. 
`pointer-events:none;` was probably added to solve this exact issue, but should only exist in the thumbnail view.

**Comment by crzypatchwork** [comment]
https://github.com/hicetnunc2000/hicetnunc/commit/556bb976b4bb66c17ea260ee2f0c52f7d2813bb3
