### ISSUE TITLE
My NFT artwork is Disappeared.

### ISSUE THREAD

**Issue by Jryadyr** [hicetnunc2000/hicetnunc#1045]
Hi Hic et Nunc,

Since last night, I found my NFT artwork is disappeared on your platform.
I don't know what's going on. I cannot access my artwork on the Creations in the Manage Assets folder. It's just gone. here I attached the screenshots.

![image](https://user-images.githubusercontent.com/88422988/128202043-c5232813-e748-46f7-9e35-65838bd55095.png)

here's the link on the Manage Assets,
https://www.hicetnunc.xyz/tz/tz1WRP8Py94HxUnor8iRYS3xnTwLnd1vjjd2/creations

Please kindly fix.

Thanks

**Comment by crzypatchwork** [comment]
https://github.com/hicetnunc2000/hicetnunc/commit/556bb976b4bb66c17ea260ee2f0c52f7d2813bb3

**Comment by Zepraxis** [comment]
Hello, this happened to me and I'm so confused, It says my wallet has 0 Objekts and my Hicetnunc accounts are empty, I can't find any of my art that has sold either...
