### ISSUE TITLE
Add 2.5% site fees on curation

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#105]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/1014562/110988180-85d77d80-8370-11eb-96e5-fba0a6cfe8dd.png">

Under curate, add a disclaimer about the site fees. This fee (2.5%) appears in a few places ([the manifesto](https://hicetnunc2000.medium.com/objkt-swap-62dbaf776336)), but it should be up front.

**Comment by andrevenancio** [comment]
good idea

**Comment by djangobits** [comment]
agree!

**Comment by andrevenancio** [comment]
done
