### ISSUE TITLE
Why ARE MOST OF MY COLLECTED WORK FOR SALE?

### ISSUE THREAD

**Issue by CryptoBIH** [hicetnunc2000/hicetnunc#1051]
Why items in my collection (images I’ve collected) are for sale when I never put them for sale? Shouldn’t they all say NOT FOR SALE unless I swap and put on secondary market or am I confused? These are the images in questions of works I collected from other artist and are currently for sale when I click on the image.
https://www.hicetnunc.xyz/objkt/119486
https://www.hicetnunc.xyz/objkt/115514
https://www.hicetnunc.xyz/objkt/107888
https://www.hicetnunc.xyz/objkt/101135
https://www.hicetnunc.xyz/objkt/96579
https://www.hicetnunc.xyz/objkt/96302
https://www.hicetnunc.xyz/objkt/95236
https://www.hicetnunc.xyz/objkt/47206
https://www.hicetnunc.xyz/objkt/67800
https://www.hicetnunc.xyz/objkt/43592
https://www.hicetnunc.xyz/objkt/52542
https://www.hicetnunc.xyz/objkt/21383

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by kylegrover** [comment]
@CryptoBIH can you fill out the other fields from the issue template (browser etc) or at least delete them? It would also be pertinent to know your wallet/url

**Comment by kylegrover** [comment]
![image](https://user-images.githubusercontent.com/26558614/128563236-3d3adbc3-88ce-4a92-88da-7673a21df0ed.png)
They're for sale because other people bought them, and are selling them. You own them but are not selling them, but you don't own every edition.
