### ISSUE TITLE
Not Swapping But also Can't Cancel and Burn - in limbo! 

### ISSUE THREAD

**Issue by KonstantFlux** [hicetnunc2000/hicetnunc#1053]
**Describe the bug**
Hi There,
I have swapped out my token after minting however it is displaying not for sale.
https://www.hicetnunc.xyz/objkt/196206
The transaction is approved https://tzkt.io/ooxHRC9BQesvPwgB3XjL3AkE2dzfq2nXwXxYFq2dZiEZ9wJL17Z
However it is still not displaying.
I also cannot cancel the sale to burn as it is displaying not for sale.
Please help, I had promoted a drop for 1 hour ago and now I can't follow through.
Cheers,
Jimmy.

**To Reproduce**
Click swap, fill out how many and how much and then swap. 

**Expected behavior**
It should have made my token available for SALE. 

**Desktop (please complete the following information):**
- OS 10.13.6
-CHROME
 -Version 92.0.4515.131 (Official Build) (x86_64)

**Additional context**
tz1hNCgcjbCFY5yDuLjzxspuiZEHAkHbPQM2
https://tzkt.io/ooxHRC9BQesvPwgB3XjL3AkE2dzfq2nXwXxYFq2dZiEZ9wJL17Z
https://www.hicetnunc.xyz/objkt/196206

**Comment by dankonino** [comment]
Ehm seems more people have problems now, I can't even buy something. I was waiting 4hours to get my tez to wallet from binance. Chill and wait till it gets bit better, but for sure maybe one place for informing about these issues wouldn't be bad idea.

**Comment by crzypatchwork** [comment]
API glitch/delay do Tezos Granada update. Those glitches can happen not only on h&n but also on wallets as it's a system which involved multiple other services.

**Comment by KonstantFlux** [comment]
Thanks for the reply.
Love HEN and glad its sorted.
Have a great day.
Cheers,
Jimmy.
