### ISSUE TITLE
My profile data doesn't appear, such as name, description, twitter and instagram

### ISSUE THREAD

**Issue by Riyandi95** [hicetnunc2000/hicetnunc#1054]
**Describe the bug**
My profile data doesn't appear, such as name, description, twitter and instagram
https://www.hicetnunc.xyz/tz1N4t5qBUmhtWHjox1DzrjU2X8QLvEmZcxo/creations

**Screenshots**
![image](https://user-images.githubusercontent.com/88572248/128589599-4bb8a954-f16f-4b41-8e30-801d1742cddb.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [92.0.4515.131]

**Additional context**
Please include the wallet address (tz1N4t5qBUmhtWHjox1DzrjU2X8QLvEmZcxo) and/or the OBJKT number.

**Comment by dankonino** [comment]
Hi @Riyandi95 if you submitted to update this, wait at least day and something so it's reviewed and then approved. I did this 2x and I got it in a day appearing. There is also original form that you can submit through google. But if you do that through approving on your wallet that takes time. It's not a bug at the moment it's the functionality

**Comment by skenaja** [comment]
@Riyandi95 you need to use https://www.hicetnunc.xyz/config to manage your profile (it's also in the menu on Hicetnunc as "Settings")
