### ISSUE TITLE
OBJKT in temple wallet but not in collection?

### ISSUE THREAD

**Issue by GeorgeKellygr** [hicetnunc2000/hicetnunc#1059]
Hi, I purchased OBJKT 197092, NFTKids #1920. 
I can see the purchase in my wallet but not in my collection. The NFT is still available to collect too.
Any ideas why?

I am on desktop using brave.
Thanks

Wallet: tz1U8PUDWy6Xxs1wjAeMew7JBt4kRSYVgLj1

<img width="516" alt="OBJKT 197092-1290" src="https://user-images.githubusercontent.com/88608473/128623191-33f71d56-23a0-4840-9978-5e4ebdc54c66.png">
<img width="277" alt="WALLET" src="https://user-images.githubusercontent.com/88608473/128623192-72c9e515-431f-46fc-a81d-02ba3f09101b.png">

**Comment by crzypatchwork** [comment]
see https://github.com/hicetnunc2000/hicetnunc/issues/1060
