### ISSUE TITLE
objkts title is missing

### ISSUE THREAD

**Issue by driangle** [hicetnunc2000/hicetnunc#106]
For some reason several of my objkts are missing their title. I know I entered it when minting, but after creation the title is missing. The description is there, but not the title.

Here is an example objkt and corresponding transaction:

https://hicetnunc.xyz/objkt/5042
https://tezblock.io/transaction/oovnAt7QpPbjQbAamsB57rqdspUuXihWFpbVa9bmbgyTPi19424

<img width="553" alt="Screen Shot 2021-03-12 at 11 44 16 PM" src="https://user-images.githubusercontent.com/292845/111006339-f096b200-838c-11eb-8e28-7a16650e653b.png">

**Comment by andrevenancio** [comment]
fixed.
