### ISSUE TITLE
500 error - Counter X already used for contract

### ISSUE THREAD

**Issue by driangle** [hicetnunc2000/hicetnunc#107]
When trying to curate an objkt I occasionally (~10% of the time) receive the following error:

```
{"kind":"temporary","id":"failure","msg":"Error while applying operation 
op53rct3BdyLQthpATDPZXDGx9i4S1GTdWDLTUT7DGaM91g4RQ2:\nbranch refused (Error:\n Counter 11389729 already used for contract tz1hkZdm9r2L6N77hXuK34PDCw
```
<img width="467" alt="Screen Shot 2021-03-12 at 11 49 30 PM" src="https://user-images.githubusercontent.com/292845/111007042-356f1880-838e-11eb-8609-17a8e9a51b66.png">

If I refresh the page and sync/curate again it usually works, although sometimes I get the error again.

using Temple wallet on Chrome.

**Comment by andrevenancio** [comment]
Not directly related with the website as the error happens on the Temple wallet popup, which we have no control over.

If this happens again, can you provide a screenshot of the developer tools of website? The only possibility I see is if an error occurs on our end and we send broken data to Temple. But unlikely
