### ISSUE TITLE
GLB mint fails

### ISSUE THREAD

**Issue by radorossum** [hicetnunc2000/hicetnunc#1075]
**Describe the bug**
Attempting to mint GLB fails with error "File format invalid. supported formats include: ... glb .....
even though the preview before mint shows a fully functional glb (e.g. this screenshot https://twitter.com/radorossum/status/1425487937152638982/photo/1)

**To Reproduce**
1. start minting process
2. upload a valid GLB file
3. verify that it is functional in the preview
4. press mint

**Expected behavior**
mint should proceed

**Screenshots**
https://imgur.com/okVQxZu

**Desktop (please complete the following information):**
 - OS: Mac OS 11.5
 - Browser brave, chrome, safari 
 - Version 1.27.11

**Smartphone (please complete the following information):**
N/A

**Additional context**
this used to work before (august 2021?) and there are plenty of GLB objects on h=n. several people reported the same issues in the discord 
wallet: radorossum.tez

**Comment by violetforest** [comment]
Hello, did you get this to work?

**Comment by yungcloud** [comment]
i am having same issue
