### ISSUE TITLE
SOMEONE HAS STOLEN MY WORK!

### ISSUE THREAD

**Issue by COMPLAINTSTEAL** [hicetnunc2000/hicetnunc#1082]
Hi, SOMEONE HAS STOLEN THE WORK OF SOME ARTISTS INCLUDING ME !

My stolen art: https://www.hicetnunc.xyz/objkt/206736
The Thief: https://www.hicetnunc.xyz/HernanPolis/creations

I know another stolen artist in this thief profile is Stephen Ong TW: @stephenonguk and the rest looks familiar... Stealing at
Why is so hard to report an stealin on HEN I'm trying to report this!!! And this is the only way I found.

Here you can see the original art: https://foundation.app/@bertoneeduardo

Please proceed ASAP, some collectors at HEN are buying fake OBJKTs

THANKS!

**Comment by COMPLAINTSTEAL** [comment]
![Captura de pantalla 2021-08-14 a las 11 10 35](https://user-images.githubusercontent.com/88927701/129443507-9862af97-b9c3-497b-b575-7dddf8452b27.png)

STOLEN ARTWORKS!

**Comment by kylegrover** [comment]
This account was banned yesterday. Please contact us in the #report-copyminting discord channel for fastest response, new reporting systems will be integrated in the site soon.
