### ISSUE TITLE
Collected Art + Artist Won't Load

### ISSUE THREAD

**Issue by karimala** [hicetnunc2000/hicetnunc#1083]
I purchased 5 NFTs of 6 from an artist last night and wanted to buy his other available artwork this morning. When I click on the artist's username from the link in the purchased artwork, all the page did was spin and wouldn't load. Now the page doesn't even appear. The spinning icon has disappeared along with everything else. But worse than that, when I click on the artwork I purchased, now it also goes to a blank page. See screenshot.

1. Go to https://www.hicetnunc.xyz/Karimala/collection
2. Click on animated man in black https://www.hicetnunc.xyz/objkt/206769
3. If you can access that, click on the artist's name to go to his gallery.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome 92.0.4515.131, Safari 4.1.1 (16611.2.7.1.4)
 - 
![Screen Shot 2021-08-14 at 12 40 02 PM](https://user-images.githubusercontent.com/11904032/129457364-258a4af0-7755-4d84-9f94-73f7536424e2.png)

**Comment by karimala** [comment]
Still having the same issue with the same artist. I also tried loading the page on my iPhone without luck.

**Comment by karimala** [comment]
Still having the same problem.

**Comment by karimala** [comment]
A friend looked at the coding and found some errors. Here's a copy for your review.

![E9sVZ4jUYAIqhFH](https://user-images.githubusercontent.com/11904032/131055852-f2c6f269-e8e1-4e5c-a58f-38b06bbf9414.jpeg)

**Comment by violetforest** [comment]
Hello, this profile now shows as a restricted account, meaning it was reported for being a copyminter.

https://www.hicetnunc.xyz/Jerofillo32/creations

**Comment by violetforest** [comment]
Please let me know if you have questions and I will reopen
