### ISSUE TITLE
Invisibility bug

### ISSUE THREAD

**Issue by Bananath** [hicetnunc2000/hicetnunc#1089]

**Comment by karimala** [comment]
I'm having the same issue with an NFT I bought and the artist's page. https://github.com/hicetnunc2000/hicetnunc/issues/1083

**Comment by Bananath** [comment]
Yes, i saw your post, also tried to click at man in black, nothing happens, that artist has the same problem as i do. I can't see neither my creations nor collection, and my collectors also have the same issue as you. I hope they will fix it soon, i will inform you if i find out anything
