### ISSUE TITLE
Art not transferring to my collection after purchase.

### ISSUE THREAD

**Issue by philthyiam** [hicetnunc2000/hicetnunc#1092]
I just purchased 4 different pieces, and none of them have transferred to my collection. The edition count on these pieces did not go down either. My tezos has been taken though.

Here are the 4 transactions:

https://tzkt.io/onyANob8ow5LseFMzCCkPbm2okV5KPxUMwbM65PoCh6tm5daZiB

https://tzkt.io/onr3KF1WsFTCAHHcvx1E9gd9AmdtXvuKJq3BubAVvNF1ip19FH6

https://tzkt.io/oonDPe8jBPThkEhR3BMJPjzmGHb6geS5QUF6oDNubdyD1aHrcAy

https://tzkt.io/oopK4AtmY85ggZfCoQUJfzbRVscEbKfuN4DNMaxrsKfxQ7ceCji

Please fix this issue.

**Comment by NoOne511** [comment]
Same here, did this transaction:
https://tzkt.io/onhm3VUHZRAwGtUBFJ2mVSZbRUCAdyQwi5GFcGFymfPkFZuBShu
Tezos are gone but the object is not appearing in my collection and the counter didn't go down.

**Comment by thaphuong** [comment]
Me too. I did 6 transactions, and none of them showed up on my collection. However, the wallet did show their transactions.

https://tzkt.io/op8pDgE4USiSJ5HdGshUdZQ5VNuWpGRyNZLB457MzPdMtx6s82d
https://tzkt.io/ooU8ummgvduYg1dbLPEZrBPGsbqGyXBMMfcrst6GnXN9To8CX3J
https://tzkt.io/onuk6MiSJnTrJ8uPg5w4CsoDHCVVLraSrnuLi2HdfxSuSatQh8v
https://tzkt.io/ooHBgSjrEspYvXiHcjZN7a82kkj7kjwciqxGFJvcTHsTQ5aNvRb
https://tzkt.io/opM7KNG1m1Qaf4bRhPEHi1EUg2NEQDXHgeGkDcf492MJtGYCWsb
https://tzkt.io/opaFbfvCFa6S8VVziCWuNsBiVYwNrTtzZj3EVozW7tyrG4Akhgh

Please fix this problem. I stop buying at this point. Thanks.

**Comment by violetforest** [comment]
if this is still not working please let me know and I will reopen

**Comment by thaphuong** [comment]
Thank you so much, Violet.
Nam

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 13, 2021 at 11:31 AM, Violet ***@***.***> wrote:   


Closed #1092.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
