### ISSUE TITLE
failed to access manage asset

### ISSUE THREAD

**Issue by Rensiardinta** [hicetnunc2000/hicetnunc#1094]
**Describe the bug**
After I mint and its already suceeded because I check on my wallet, I can’t swap. If I hit manage assets, it only shows collection and creations( like the pic attached). It’s been 7 hours after the mint now. Pls help. Thanks!

**Screenshots**
![7CB0A51B-A7D2-404A-833E-3020E313CF72](https://user-images.githubusercontent.com/89154625/129941536-4090cb23-96d6-4096-acfd-198834270f8f.jpeg)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 14.7.1
 - Browser chrome

**Additional context

Wallet addres
tz2QcES9PuqXCxa35d5Ps6cBKjip5WKxUXhY

**Comment by FarshadIzadi** [comment]
I have the exact same problem on chrome but this time on windows 8.1

**Comment by Rensiardinta** [comment]
> I have the exact same problem on chrome but this time on windows 8.1

Hi! How do you fix it in chrome?Thank you :)

**Comment by asmaralaya** [comment]
i have the same problem here, this week cant see and so i cant swap

**Comment by violetforest** [comment]
this might have been when the site was done. if it is not fixed please send your profile link
