### ISSUE TITLE
I minted this https://www.hicetnunc.xyz/objkt/149295 nothing sold and now it says not for sale. and I cant even burn cause itt says I owe 0. How is that?

### ISSUE THREAD

**Issue by malkenza** [hicetnunc2000/hicetnunc#1095]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
Hello, please filter your assets with the "for sale" filter, and then cancel the swaps, and reswap. I will close but if you have more questions please let me know and I will reopen.
![swap](https://user-images.githubusercontent.com/8921838/133142008-0efc56d0-62fa-4bfe-ba12-22154efa9ba1.PNG)
