### ISSUE TITLE
my art is gone

### ISSUE THREAD

**Issue by malkenza** [hicetnunc2000/hicetnunc#1096]
I minted this https://www.hicetnunc.xyz/objkt/149295 nothing sold and now it says not for sale. and I cant even burn cause it says I owe 0. How is that?

**Comment by violetforest** [comment]
Hello, please look at your assets, filter the for sale, and you should see the cancel swap v1 objkts option. You can then reswap it.

**Comment by violetforest** [comment]
![swap](https://user-images.githubusercontent.com/8921838/133137001-0757d2f8-dfd8-4923-aeba-3af78ec9d60a.PNG)
