### ISSUE TITLE
Objkt stuck at objktswap v1

### ISSUE THREAD

**Issue by rvorias** [hicetnunc2000/hicetnunc#1102]
**Describe the bug**
Objkts are stuck at objktswap v1, tried to add v1 to my link but can't see any other buttons. 

**To Reproduce**
https://www.hicetnunc.xyz/objkt/8045

**Expected behavior**
Can someone please show me how to cancel this swap and put a new one out?

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chrome

**Comment by benjarier** [comment]
Having the same issue, Objkts are stuck at objktswap v1 and no cancel option

**Comment by kromond** [comment]
I am also having this.  I would like to relist my v1 items, but swap transactions fail with both temple and kukai app
example: https://www.hicetnunc.xyz/objkt/82440

**Comment by rvorias** [comment]
@benjarier , @kromond 
I was able to solve it by logging into henext.xyz, then going to my listings and do the cancel swap!

**Comment by rvorias** [comment]
Wow there were two object swaps, one for 3tez, one for 1tez
After canceling the 1tez is gone!! :0 watch out for this guys

**Comment by zencatt** [comment]
@rvorias thank you so much! Been dealing with this issue for weeks.  Never even heard of the site and it's so much better than hic itself.
