### ISSUE TITLE
Please Help Me! Posted Over A Week Ago

### ISSUE THREAD

**Issue by karimala** [hicetnunc2000/hicetnunc#1104]
https://github.com/hicetnunc2000/hicetnunc/issues/1083

I'm also having issues with my own artwork. I'd like to burn it, but it says I don't own it. No one bought my art, so I don't understand why it says I don't own it.

https://www.hicetnunc.xyz/objkt/206627

**Comment by violetforest** [comment]
Hey, Please cancel the listing first and then burn it

**Comment by violetforest** [comment]
let me knw if you need more help and I will reopen the issue
