### ISSUE TITLE
Reorganize collects from Collection

### ISSUE THREAD

**Issue by miguelzinhe** [hicetnunc2000/hicetnunc#1112]
**Is your feature request related to a problem? Please describe.**
I'm new to hicetnunc and I'm still exploring the site to collect my first objects and I noticed that there's no way to rearrange the objects in the collection tab of the profile. Some artists I know are doing art series and it would be interesting if, as the collector collects the object, they can also rearrange these objects in a beautiful order to be seen.

I was wondering if we could discuss together implementing a feature that would be possible to do a custom filtering of objects beyond the order when the collector collected. Maybe filters by author, by object types, and also a drag and drop customization to organize the way the person wants! That would greatly increase the chances of a collector buying objects to make the gallery beautiful, you know?

what do you think, people? let's talk about it!

**Describe the solution you'd like**
For the drag and drop feature, I was thinking about something like [Draggable](https://github.com/Shopify/draggable).

**Describe alternatives you've considered**

**Additional context**
I'm available to help! 🧚🏼‍♀️ 💕

**Comment by crzypatchwork** [comment]
we are focusing on making the app and some features as stable as possible. but it would be possible to configure those for example as additional information along each-one's profiles/gravatars https://github.com/hicetnunc2000/hicetnunc/blob/7600ca88e9b5d83ede87d32bbdc938c0ff885609/src/pages/config/index.js#L117
