### ISSUE TITLE
Remove letter-spacing from Input to have better reading (a11y)

### ISSUE THREAD

**Issue by miguelzinhe** [hicetnunc2000/hicetnunc#1113]
**Describe the bug**
What if we removed the letter-spacing property of Input to get better readability of the labels? I think it's important for people who are dyslexic and visually impaired. 

Is there any reason this letter-spacing exists?

**Expected behavior**
<img width="678" alt="Captura de Tela 2021-08-26 às 19 20 37" src="https://user-images.githubusercontent.com/20358128/131044002-f72cf8a7-34ed-4262-bd5c-48f0cd65b52c.png">

**Screenshots**
<img width="730" alt="Captura de Tela 2021-08-26 às 19 20 29" src="https://user-images.githubusercontent.com/20358128/131044026-46b38dc5-66df-421b-a123-8d3077a90ab9.png">
<img width="449" alt="Captura de Tela 2021-08-26 às 19 20 40" src="https://user-images.githubusercontent.com/20358128/131044030-e4993460-6974-4420-8b20-089a8bf049d5.png">

**Desktop (please complete the following information):**
 - Browser:  Chrome and Firefox.
 
**Additional context**
I can make the alteration, if you allow!

**Comment by violetforest** [comment]
this should be fixed
