### ISSUE TITLE
glTF/ GLB animations not playing fix

### ISSUE THREAD

**Issue by leonardschoelch** [hicetnunc2000/hicetnunc#112]
Hey, I looked into why the animations in glTF/ GLB files aren't playing on hicetnunc and as we suspected it was a simple property.
I am not a webdev and just compared different implementations of the google glb viewer.
What was missing is the an autoplay property. It tested it on hicetnunc and it works.

<img width="732" alt="mspaint_FoXwEGdggM" src="https://user-images.githubusercontent.com/6728197/111026621-6e89a600-83eb-11eb-8165-de8534ed173c.png">

**Comment by fraguada** [comment]
Can confirm that this works for playing the first animation cycle by messing with it in dev tools: 
![autoplay](https://user-images.githubusercontent.com/1014562/111135186-a411c900-857c-11eb-89fd-2939cfdb937f.gif)

Seems it is already in the code: https://github.com/hicetnunc2000/hicetnunc/blob/9a1c03e1fd78df6db892465e27f1a80ac2385290/src/components/media-types/glb/index.js#L13

**Comment by leonardschoelch** [comment]
Awesome. The change is already in the develop branch and should release soon :)

**Comment by supergraphik** [comment]
> Awesome. The change is already in the develop branch and should release soon :)

Hey thanks for looking into this —My question is - if I mint my GLTF before your 'autoplay': true' fix - will it work once the fix is implemented?

thx
SG

**Comment by leonardschoelch** [comment]
> > Awesome. The change is already in the develop branch and should release soon :)
> 
> Hey thanks for looking into this —My question is - if I mint my GLTF before your 'autoplay': true' fix - will it work once the fix is implemented?
> 
> thx
> SG

This was implemented two months ago and should still work as far as I know :)

**Comment by supergraphik** [comment]
er... hmmm that's very interesting - I wanted to mint a GLTF - and it works perfectly in every other player such as:  https://github.khronos.org/glTF-Sample-Viewer-Release/

However when I preview it in H=N you can only just move the object about...  take a look...

https://user-images.githubusercontent.com/84778837/119492812-676e0500-bd57-11eb-918a-4ce53744d135.mov


https://user-images.githubusercontent.com/84778837/119492885-810f4c80-bd57-11eb-90b7-3d71cd1ed543.mov

**Comment by supergraphik** [comment]
Could it be something I'm not exporting that H=N needs?

thx
SG

**Comment by supergraphik** [comment]
I figured it out!! - OK for the benefit of all others - it is a Blender GLTF export setting that is hidden away : I you have different animation tracks - then you must uncheck 'Group by NLA Track' - before you export! 

![GLTF_Blender](https://user-images.githubusercontent.com/84778837/119495997-eca6e900-bd5a-11eb-8e72-863eefee5275.jpg)
