### ISSUE TITLE
Cant show manage asset

### ISSUE THREAD

**Issue by asmaralaya** [hicetnunc2000/hicetnunc#1123]
**Describe the bug**
i can mint but cant show manage asset, loading all day long

**Screenshots**
cant show manage asset, so i cant swap to sell
![Screen Shot 2021-09-01 at 23 23 51](https://user-images.githubusercontent.com/89912484/131708395-d7ae5ddb-1983-4268-b58f-391908099a64.png)

**Desktop (please complete the following information):**
 - OS: [MacOs Catalina 10.15.7]
 - Browser Chrome
 - Version Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
the wallet address tz2PbCr17aTSfZNGxJy8sgWyFrtNzy7R9XU8

**Comment by jeditetsu** [comment]
Hi I have the same issue, have an nft in collections, but cant view or swap

**Comment by bvb-79** [comment]
I've had this issue for 3+ days

**Comment by violetforest** [comment]
this should be working now, this was when the site was down. if you have other questions please let me know
