### ISSUE TITLE
Unable to save user profile

### ISSUE THREAD

**Issue by heurihermilab** [hicetnunc2000/hicetnunc#1126]
**Describe the bug**
I am unable to save my user profile using the form at https://www.hicetnunc.xyz/config

**To Reproduce**
1. Go to https://www.hicetnunc.xyz, click 'sync', and connect to Kukai wallet.  Tezos wallet ID appears in  'sync' field, indicating success.
2. Go to https://www.hicetnunc.xyz/config
3. Enter username and description; upload avatar image.
4. Click 'Save Profile'.

**Expected behavior**
The profile options would be saved.

**Actual behavior**
After contacting Kukai, the process fails with an 'invalid parameter' message (attached).

**Screenshots**
<img width="358" alt="Screen Shot 2021-09-02 at 9 08 31 PM" src="https://user-images.githubusercontent.com/26681465/131949314-123ee6c5-bd54-4f20-b3bf-64f185f3523f.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (fully updated)
 - Browser Safari
 - Version 14.1.2

**Additional context**
I initially tried using Firefox 91.0.2 with H=N but couldn't get full functionality.
Wallet: tz1VsS6YQd989uDRaXCH6UH2bpNbY7dSMvQ6

**Comment by violetforest** [comment]
Hello, are you still having this issue?

**Comment by heurihermilab** [comment]
No. But it looks like I was trying to sync a wallet that was in some way not completely initialized. As a test, I created another Tezos wallet and was able to successfully connect it with H=N, and now have a user profile working.

Thanks for asking. I'm not sure that there's an action item here, other than asking for better error messages, and in this case that would be the responsibility of Beacon or Kukai, not H=N.

**Comment by Vrob7** [comment]
Hello There, I have the exact same problem with Temple Wallet, any idea how to fix it ...? Thanks !
