### ISSUE TITLE
NFT theft/issues

### ISSUE THREAD

**Issue by malkenza** [hicetnunc2000/hicetnunc#1127]
I minted an image, then paid to make it available for purchase, made sure it was for sale. But then then when I came back to check on it few days later it was Not for sale again and I dont understand why. Also my userpic disappeared. And now I tried to burn the image to upload it to a more reliable platform, it does not allow me to burn, says I dont owe it! How could that be? Noone purchased it, I didnt receive anything for it, how come its not mine any more? Where did it go?
that is rergarding obj https://www.hicetnunc.xyz/objkt/149295

**Comment by violetforest** [comment]
Hello, you need to filter your assets with the "for sale" filter, and then cancel the swaps. Once you do this you can reswap.

Please let me know if you have questions and I can reopen.
![swap](https://user-images.githubusercontent.com/8921838/133144190-bd1dbfcb-628a-47cc-977d-81d768b8feb4.PNG)
