### ISSUE TITLE
Count of edition and count of possible swap do not match

### ISSUE THREAD

**Issue by EMES77** [hicetnunc2000/hicetnunc#113]
It seems, like swap is Edition -1. I relased an edition of can and could count up swap to 9 max.

**Comment by andrevenancio** [comment]
Any more info you can share? links for example?

**Comment by EMES77** [comment]
I'll try to reconstruct it tomorrow and make screenshots. 
Today it happend with OBJKT#5284 
https://www.hicetnunc.xyz/objkt/5284

**Comment by EMES77** [comment]
It is working now, i'm closing the issue

**Comment by Quasimondo** [comment]
I think this issue needs to be reopened since there is now an error in the "total edition size" count which is now sometimes showing values smaller or larger than the actual amount minted.
