### ISSUE TITLE
i minted an object and it doesn't appear in my collections.

### ISSUE THREAD

**Issue by drdrsto** [hicetnunc2000/hicetnunc#1130]
hello i have a problem i minted an object and it doesn't appear in my collections.

"amount": 
"5" ,
"token_id": 
"260713" ,
"token_info": 
{
"697066733a2f2f516d5a4b4337514e736141683678725071346856774737317634436e71336666343535764d386443426f454c4e52"

**Comment by violetforest** [comment]
hello, it looks like this is working. if not please let me know and i will reopen
