### ISSUE TITLE
i minted an object and it doesn't appear in my collections and also i buy art and it doesnt appear too

### ISSUE THREAD

**Issue by rsydrdh** [hicetnunc2000/hicetnunc#1131]
tz1aKo887hGkozc9q3DggaFdDKo9sp8nv6Db and objkt that i buy is OBJKT#260484

![image](https://user-images.githubusercontent.com/90066200/132057152-ffd9b353-3a21-4314-9454-95c326120507.png)
![image](https://user-images.githubusercontent.com/90066200/132057179-92482381-e9ef-48e4-aef9-5b7ca61cbd13.png)

**Comment by drdrsto** [comment]
ok i'm not alone. maybe update??

**Comment by rsydrdh** [comment]
> ok i'm not alone. maybe update??

ion kno it, it doesnt appear, collecting some artwork an hour ago and mint something,, lets wait until they answerin us

**Comment by darkpiny** [comment]
having the same issue, NFT doens't appear in manage asset page

**Comment by indroidkitkat** [comment]
Same problem here, what we have to do guys?

**Comment by suissemaxx** [comment]
### Update: My issue is solved – the NFTs now show in my collection

> Same here. Bought two NFTs with new Kukai wallet. Tezos and tokens appear to have been exchanged. 
> 
> However, 
> 
> - the NFTs do not show in my collection
> - my ownership doesn't show in the objects history
> - the counter on the objects page isn't decreased
> 
> Any ideas how to fix this?
> 
> Thanks in advance for any help!

**Comment by drdrsto** [comment]
Can someone do a test mint to see if other objects do the same?
but it looks like hen will update again or other difficulties..

**Comment by gtsiliakos** [comment]
having the same problem here guys ,minted 20 pieces and not showing anything

**Comment by drdrsto** [comment]
ok fuck!!

**Comment by gtsiliakos** [comment]
is there a possibility to lose it all ?

**Comment by drdrsto** [comment]
no I don't think so .. they are in your tez wallet...

**Comment by xmm-t** [comment]
Same issue. Newly minted tokens not appearing under 'Manage Assets' and I sold a token this morning but its counter did not decrease.
When I navigate to the objkt by going to my wallet and clicking 'View on hic et nunc' the page just loads forever.

**Comment by VGA414** [comment]
hicdex not indexing those objkts - current status: https://api.hicdex.com/status.json
lag: 1643

**Comment by violetforest** [comment]
Hello, are you still having this issue? Should be fixed, if not let me know and I can reopen it
