### ISSUE TITLE
i minted and i cant see my collection

### ISSUE THREAD

**Issue by ariannatafa** [hicetnunc2000/hicetnunc#1132]
i minted an object and i cant see it on my collections

**Comment by mfused** [comment]
same here!!!!! i see it as token in my wallet but not in 'creations'. is it some temporary bug? i tried again, same again.
are you on it, HEN devs, fixing it?
many thanx for your hard work!!!!!

**Comment by violetforest** [comment]
@ariannatafa Hello, please send a link to your profile so we can help you
