### ISSUE TITLE
Swap an art, and it never was listed, neither had an error on operation, and it says I don't own it anymore!

### ISSUE THREAD

**Issue by RecklessDog** [hicetnunc2000/hicetnunc#1133]
I bought an art today, and I've swapped it around an hour ago. It's not shown for sale, the operation was completed, but I can't see it listed or for sale. It's gone from my tokens. 

It's tz1fyt8Fjo2Yo1BFXCnrbLMB8RPbWDPaQ5vN wallet, objkt https://www.hicetnunc.xyz/objkt/259837

**Comment by violetforest** [comment]
hello, it looks like this is working now. please let me know and i can reopen
