### ISSUE TITLE
Unable to mint svg files with scripting

### ISSUE THREAD

**Issue by VGA414** [hicetnunc2000/hicetnunc#1135]
I cant mint any svg files with scripting inside, even tried with one file that has been already minted into my collection - always get this error and the minting process doesn't get started: 

/mint:1 Access to fetch at 'https://api.nft.storage/upload' from origin 'https://www.hicetnunc.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
lib.js:90 POST https://api.nft.storage/upload net::ERR_FAILED

1. Go to https://www.hicetnunc.xyz/mint
2. Add svg file with scripting
3. Mint

I already have 4 files like this minted and running on my collection, what has changed? What to do to fix this problem?
Already running with exactly same content: https://www.hicetnunc.xyz/objkt/243753

![image](https://user-images.githubusercontent.com/88363986/132114554-26658f23-996d-4a96-94df-ae0afad617f3.png)

**Comment by mairod** [comment]
I have the exact same issue. Tried to upload some scripted svg but I have a CORS issue...

**Comment by MAKIO135** [comment]
same error

**Comment by MAKIO135** [comment]
The issue has been resolved by switching back to Infura.io
