### ISSUE TITLE
an nft that I bought disappeared

### ISSUE THREAD

**Issue by damian3lo** [hicetnunc2000/hicetnunc#1136]
**Describe the bug**

**To Reproduce**
1. Go to 'collection'
2. Click on 'OBJKT 262407'
3. Error: the object does not exist (black screen)

**Expected behavior**
**I expected to enter the nft that I acquired and it was not available**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Additional context**
OBJKT number [262407]([url]([url](url)))
![captura](https://user-images.githubusercontent.com/90141617/132128838-c1285759-247a-4df7-9afe-292e97285bc5.png)
![captura1](https://user-images.githubusercontent.com/90141617/132128839-5f5bb9c9-96f3-465c-91fd-c5220393ccef.png)

**Comment by violetforest** [comment]
Hello, is this still broken? Looks like it has been fixed. Please let me know and I can reopen

**Comment by damian3lo** [comment]
todavia esta roto, la cuenta está restringida. Tengo más de un NFT en el
mismo estado. ¿Pertenecen a cuentas scam? o porque desaparecen?

**Comment by violetforest** [comment]
ah perdon, si, esta cuenta esta restringida por ser scam

**Comment by damian3lo** [comment]
tengo otros 2 NFT que pertenecen a una cuenta scam. Hay posibilidad de
revisar eso y recuperar los XTZ que invertí?

**Comment by damian3lo** [comment]
hola, espero respuesta

**Comment by violetforest** [comment]
desafortunadamente, no es posible recuperar los XTZ. lo unico que puedas hacer es contactar los artistas y preguntarlen si de hecho la cuenta es scam
