### ISSUE TITLE
Webpage not loading IPFS content [SOLVED]

### ISSUE THREAD

**Issue by AlejoHarris** [hicetnunc2000/hicetnunc#1138]
**Describe the bug**
The webpage doesn't load any content and doesn't let to update profile

**To Reproduce**
Is easy to see in the Chrome inspector, and the console throw a lot of errors, one in particular is:
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

**Expected behavior**
It should be able to visualize the content and update profile information

**Screenshots**
![image](https://user-images.githubusercontent.com/14794157/132175195-d63deb4e-243a-47fb-bd99-c585479adfee.png)

**Desktop:**
 - OS: Windows 10 V19043.1165
 - Browser: Chrome
 - Version: 93.0.4577.63

**Also Smartphone:**
 - Device: OnePlus6T
 - OS: Android 10
 - Browser: Chrome
 - Version: 93.0.4566.62

**Comment by violetforest** [comment]
Hello, is this still working? please send the link to your profile

**Comment by violetforest** [comment]
Since this is most likely related to the website being down a couple of days ago, I will close this but if you still need help I can reopen it.

**Comment by AlejoHarris** [comment]
Hi @violetforest, unfortunately the problem persists and I can't visualize anything nor update my profile from my computer. However, it works now from my phone.

**Comment by AlejoHarris** [comment]
Could it be something from the OS?

**Comment by AlejoHarris** [comment]
Link of my profile: 

https://www.hicetnunc.xyz/tz/tz1b29qvLJi6bZupYCeFxtNQtb3PsvrLZqG6

**Comment by violetforest** [comment]
Hello, I see your profile as this 
![Screen Shot 2021-09-16 at 3 38 05 PM](https://user-images.githubusercontent.com/8921838/133675263-cbec3a09-19fb-4b28-95fe-a96905943cca.png)


Also when I use this tool to look up this wallet address, I dont see any creations listen under the account http://hicdex.com/

**Comment by AlejoHarris** [comment]
Hi, I made my account using my phone and also minted some arte doing it the same way. For some reason neither a macbook or a windows laptop can load the page correctly in my house. I don't know if it could be some kind of restriction.

**Comment by AlejoHarris** [comment]
Hello Everyone, if you find yoursel with this problem, I just got the answers. Seems like some routers have a default DNS server, sometimes the one from the router manufacturer itsefl.

So what you have to do is try to configure the DNS servers manually in your router to ask Cloudfare for DNSs, in this case used the servers 1.1.1.1 and 1.0.0.1

This DNS server recognized IPFS requests and now and can see everything on HEN. If you're not familiar with changing the DNS from the router, you can do it yourself in Windows or Mac inside Network Settings.

This problem didn't have to do with HEN, but with IPFS requests. 

Thanks @violetforest for being so kind, and hopefully this helps everyone else is facing the same issue I had.
