### ISSUE TITLE
I can't edit my profil, I can't do Objekt

### ISSUE THREAD

**Issue by Touky333** [hicetnunc2000/hicetnunc#1139]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
Hello, please send a link to your profile

**Comment by Touky333** [comment]
Hello, Here is the link to my profil : https://www.hicetnunc.xyz/tz/tz1S8zxuJn1dQv1jLUHr9YyMqUj1WPANxU7H/creations

Thank you !
    Le lundi 13 septembre 2021, 20:05:31 UTC+2, Violet Forest ***@***.***> a écrit :  
 
 


Hello, please send a link to your profile

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by violetforest** [comment]
Do you have any errors in your wallet when you do the transaction for the config at https://www.hicetnunc.xyz/config?

What exactly is the problem? can you give more details please?

**Comment by Touky333** [comment]
When i want to édit my profil i can upload a pic, enter my name but nothing happens when i want to save. My wallet is well connected. I can buy Objkts. 
In addition, when i want to mine objekts, i can load an image, indicate its name and choose the number of édition and the percentage of commission. I can préview but when i run mining, "peparing the objkts runs for several hours with no results... 
Thank you to help me... !
    Le jeudi 16 septembre 2021, 21:20:00 UTC+2, Violet Forest ***@***.***> a écrit :  
 
 


Do you have any errors in your wallet when you do the transaction for the config at https://www.hicetnunc.xyz/config?

What exactly is the problem? can you give more details please?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FormeDOnda** [comment]
Hi. I have the same problem. Seems that i can manage profile and collections, but i can't save changes. Also, in hicetnunc.xyz site my collection is completely empty, while i see correctly my 3 nfts on objkt.com. 
My profile on objkt is:  https://objkt.com/profile/tz1esq3ji2mmzFC8WAUH7XBC9g9VyicNKRWB, on hicetnunc: https://www.hicetnunc.xyz/tz/tz1esq3ji2mmzFC8WAUH7XBC9g9VyicNKRW
Seems that it resets all changes that i make.
Please give me a feedback as soon as you can.
Thanks in advance

**Comment by violetforest** [comment]
@FormeDOnda the profile link you pasted doesn't work but thats because there is a letter missing off of the end of the wallet address

https://www.hicetnunc.xyz/tz/tz1esq3ji2mmzFC8WAUH7XBC9g9VyicNKRWB
this works for me

**Comment by violetforest** [comment]
![prof](https://user-images.githubusercontent.com/8921838/134438904-415c4caf-f7d6-46d2-98ee-91eb9fbc9f5e.PNG)
I see your profile as this @Touky333 

were you able to mint? did you try a different browser/ internet connection / computer?

**Comment by tabreturn** [comment]
Please let us know what the fix is. 

I go to: https://www.hicetnunc.xyz/config and enter my details, but the "Save Profile" button does nothing. I expect it to save my details.

Firefox 92.0.1, Linux Mint.
Account: tz1MCSJwEEdw7bvcs7c7pgry29EmZ8pnzmeH

EDIT: I cannot mint either -- it just hangs, displaying the message "preparing OBJKT" (even after an hour of waiting)

**SOLVED: Firewall issue. hicetnunc.xyz uses some unusual ports (5001)**

**Comment by Mirotvoritel** [comment]
I have the same problem, I'm using temple wallet, google chrome, windows 10 pro 64 bit.

When i try to save the changes made to the profile, nothing happens, only a pop up appears saying this "Request sent to 
Temple - Tezos Wallet (ex. Thanos)". Here my wallet address : tz1Y8Dyg2ERkJHe99mrqU8NNrgzquXcCFDwC .

**Comment by tabreturn** [comment]
Perhaps this might help diagnose the issue I'm encountering --

![Screenshot from 2021-09-27 11-53-59](https://user-images.githubusercontent.com/9858145/134826956-7dab1539-60c9-474b-baa5-0cadfe248770.png)
