### ISSUE TITLE
profile stolen

### ISSUE THREAD

**Issue by frading** [hicetnunc2000/hicetnunc#1143]
**Describe the bug**
I used to have the profile https://www.hicetnunc.xyz/gui, but I see now someone else is using is occupying this address.

**To Reproduce**
go to: https://www.hicetnunc.xyz/gui
Until a few days ago, you could see my profile, which is now visible here: https://www.hicetnunc.xyz/tz/tz1ZnkBRp14TaCqt3CVRsJkg2Qf4YyRhuKJZ/

**Expected behavior**
Going to https://www.hicetnunc.xyz/gui should show my profile ( https://www.hicetnunc.xyz/tz/tz1ZnkBRp14TaCqt3CVRsJkg2Qf4YyRhuKJZ/creations )

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by kylegrover** [comment]
We switched username systems a month or two ago, someone must have claimed 'gui' within that time. I'd recommend just registering another name for now at the settings page.
