### ISSUE TITLE
items not on sale anymore

### ISSUE THREAD

**Issue by frading** [hicetnunc2000/hicetnunc#1144]
**Describe the bug**
My items on my profile ( https://www.hicetnunc.xyz/tz/tz1ZnkBRp14TaCqt3CVRsJkg2Qf4YyRhuKJZ/creations ) used to be on sale. They are not any more.

I recall seeing somewhere that hicetnunc was upgrading the backend, although I cannot find that information any more. Could that be the reason? Is there something I need to do to have my items on sale again? I can't seem to find any documentation about this, it would be great if someone could point me to it.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/109540
2. The item states "not for sale"

**Expected behavior**
1. Go to https://www.hicetnunc.xyz/objkt/109540
2. It should be possible to buy the item.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by violetforest** [comment]
Hello, please go into the "For sale" of your assets, and then cancel the swaps 
![swap](https://user-images.githubusercontent.com/8921838/133140214-40c6fa9f-826e-4613-9086-fdc45a156d58.PNG)


please let me know if you have questions and I will reopen

**Comment by rvorias** [comment]
Hey @violetforest,

I don't get that menu! This object is stuck really hard: https://www.hicetnunc.xyz/objkt/8045
