### ISSUE TITLE
wallet problem

### ISSUE THREAD

**Issue by Marsior** [hicetnunc2000/hicetnunc#1148]
I created a new wallet '' tz1WM3EP96SYmubkkkVi5SyaUD9GjyaVQFHk '' 

The issue is my tokens (not) are not connected with HEN ' s collection part.

Please connect them. 

This is also my old wallet tz1TZMxsHghvjhhvyjDFu8nkgQVBQ4RipESU

Thanks.

**Comment by violetforest** [comment]
Hello, you must send your objkts to your new wallet. I will close but please let me know if you have other questions and I will reopen
