### ISSUE TITLE
My whole Hen profile is down, cant see my collection or creations

### ISSUE THREAD

**Issue by IanGrantIT** [hicetnunc2000/hicetnunc#1151]
I was in the middle of minting a new objkt and I accidentally closed the tab to my kukai wallet when the transaction was being sent over so i reloaded the Hen page and tried reminting and it said the transaction went through this time but now my whole profile is down and my collection is down. Even the links to my pieces don't work anymore. Is there a way to reset this? I don't understand whats happening. You can't even see my profile heading or avatar anymore. My wallet still works but my Hen page is down. Also, Hen is still working, just my profile isn't.

**Comment by IanGrantIT** [comment]
https://www.hicetnunc.xyz/IanGrantArt is my profile

**Comment by nathanielstern77** [comment]
SAME ISSUE https://www.hicetnunc.xyz/nathanielstern

**Comment by IanGrantIT** [comment]
How long have you had this issue Nathaniel

**Comment by nathanielstern77** [comment]
I'm not entirely sure. I haven't viewed my profile in about 3 days, but now all my info and NFTs are gone, or just appear to be loading forever.

**Comment by IanGrantIT** [comment]
Okay, this just happened to me just now.

**Comment by nathanielstern77** [comment]
Probably me, too then.

**Comment by IanGrantIT** [comment]
bruh now it kinda seems like Hen is down. I was sketched out because some some of it is working still

**Comment by nathanielstern77** [comment]
Still seems working to me, just slow...

**Comment by IanGrantIT** [comment]
this shit gives me so much anxiety lmao

**Comment by nathanielstern77** [comment]
same. I just got a bunch of new followers on twitter and thought maybe they bought... now I know even if they wanted to, they couldn't (and I fear my NFTs are gone, too)...

**Comment by IanGrantIT** [comment]
you can still use https://henext.xyz to view your profile and swap and trade when hen is down. i dont think you can mint though

**Comment by nathanielstern77** [comment]
LOL my ISP blocks it on my laptop, but at least I can see I still own the NFTs on my phone. My profile info seems to be gone, though...

**Comment by jjclark** [comment]
I am having the same problem. My profile is empty (default) and none of my NFTs are there anymore (just an empty screen).

**Comment by dreamawaypsd** [comment]
im haing the same problem. This is a link of one of my work and cant get it. And also cant see my profile. 
https://www.hicetnunc.xyz/objkt/281563

**Comment by xmm-t** [comment]
Similar issue, I can see my creations from before 2-3 days ago but none after that. Everything is still there if I check on hicdex, just not visible on HEN.

**Comment by dreamawaypsd** [comment]
I am attesting that this GitHub handle dreamawaypsd is linked to the Tezos account tz1hfhLfW29w8Gy3yRycGZsN2ng9tmN6mFqP for tzprofiles

sig:edsigtnCPUppKNmanmG9cqHePgXznLrrTRmX4gZC2VeTvDULbhHBaK1LrieRJ7vB3C1rVwQSV6LJfy1TZ9zcNeNi42gjusTysQJ

**Comment by violetforest** [comment]
we've been going through some infrastructure changes, is this working now? also please join the discord for latest developer announcements https://discord.gg/WtbnVbcJ

**Comment by dreamawaypsd** [comment]
Yes its working. Thanks!
