### ISSUE TITLE
profile empty and NFTs gone

### ISSUE THREAD

**Issue by nathanielstern77** [hicetnunc2000/hicetnunc#1152]
**Describe the bug**
https://www.hicetnunc.xyz/nathanielstern does not show my information or any creations

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/nathanielstern

Creations, too

**Expected behavior**
I expect to see my picture, bio, and links, my two minted NFTs

**Screenshots**
attached

**Desktop (please complete the following information):**
I tried on both Safari and Chrome on Mac OS.

Please include the wallet address (tz...) and/or the OBJKT number.
https://www.hicetnunc.xyz/objkt/251855
https://www.hicetnunc.xyz/objkt/241014

tz1avKxgBtiW75fnKGPgrvVB5S3oxGDB1zPV

<img width="813" alt="Screen Shot 2021-09-09 at 12 45 11 PM" src="https://user-images.githubusercontent.com/85973845/132736583-3db0af7a-25ed-4947-9283-a5012d17af06.png">
<img width="785" alt="Screen Shot 2021-09-09 at 12 45 06 PM" src="https://user-images.githubusercontent.com/85973845/132736584-5370207d-8b73-466b-a0e9-c310c996c306.png">
<img width="447" alt="Screen Shot 2021-09-09 at 12 44 56 PM" src="https://user-images.githubusercontent.com/85973845/132736586-6368a85c-0b36-4955-8534-848004422820.png">

**Comment by IanGrant666** [comment]
SAME ISSUE: hicetnunc.xyz/IanGrantArt

**Comment by IanGrantIT** [comment]
SAME ISSUE: https://www.hicetnunc.xyz/IanGrantArt

**Comment by CSEEEE** [comment]
SAME ISSUE: https://www.hicetnunc.xyz/tz/tz1TsUHtiL52A2j9MTapS32KoX6BY1SC5w9v

**Comment by violetforest** [comment]
@kylegrover lots of people reporting their profiles not working, is this related to copyminter bans?

**Comment by violetforest** [comment]
I am able to see all these profiles that are linked, the issue may have been due to the site been down those days. I will close this issue unless anyone else is still having problems
