### ISSUE TITLE
Пропали объекты из продажи

### ISSUE THREAD

**Issue by GorovoyW** [hicetnunc2000/hicetnunc#1153]
Исчезли все объекты из продажи.

**Comment by violetforest** [comment]
Hello, can you please send us a link to the profile and to the objkts

**Comment by GorovoyW** [comment]
My profile:
https://www.hicetnunc.xyz/tz/tz1NGubjGBQgL1KRRVUiCXbYLgkSQb9ud536/creations
Objkts that are missing:
https://www.hicetnunc.xyz/objkt/72417
https://www.hicetnunc.xyz/objkt/72703
https://www.hicetnunc.xyz/objkt/72720
https://www.hicetnunc.xyz/objkt/72743
https://www.hicetnunc.xyz/objkt/72754
https://www.hicetnunc.xyz/objkt/76219
https://www.hicetnunc.xyz/objkt/116940
https://www.hicetnunc.xyz/objkt/124932
https://www.hicetnunc.xyz/objkt/124942
https://www.hicetnunc.xyz/objkt/124958

**Comment by GorovoyW** [comment]
I look forward to hearing

**Comment by violetforest** [comment]
please cancel and reswap your objkts 

![swapv1](https://user-images.githubusercontent.com/8921838/134437612-80a6c566-34de-4556-a7ba-f30c8361a57b.PNG)

if that doesnt work you can try https://www.henext.xyz/ to cancel

**Comment by GorovoyW** [comment]
I paid the money for the accommodation. I need help getting money back. Who will return my wasted time?

**Comment by violetforest** [comment]
we have a disclaimer on the site that says "This is an experimental dApp, use it at your own risk."

We cant give refunds unfortunately, we apologize about that.

**Comment by GorovoyW** [comment]
![image](https://user-images.githubusercontent.com/90416493/134724125-d5ff02d9-8995-4390-bff3-69837e937cd7.png)

Why I can't replace my OBJCTs again? How I can republish them if they were stolen? It is written that they belong OBJCTSWAP V1. Who is this?

**Comment by skenaja** [comment]
That's the old hicetnunc marketplace contract. use the "cancel" button to unlist. and then you will be able to relist the items for sale.
