### ISSUE TITLE
objkts are missing!

### ISSUE THREAD

**Issue by skinjob77** [hicetnunc2000/hicetnunc#1154]
**Describe the bug**
there are multiple nfts (at least 5) that I have collected in the last several days that are suddenly missing from my collection. ALSO: my pfp avatar has changed back to a version from earlier in the week. it's as if the last 2 days on transactions have disappeared from my collection page.

the transactions appear in my kukai wallet. they were there yesterday. gone today.

<img width="396" alt="Screen Shot 2021-09-09 at 3 19 15 PM" src="https://user-images.githubusercontent.com/90420685/132757144-44d550e0-817c-40ab-aa7b-6af093d7b762.png">
<img width="632" alt="Screen Shot 2021-09-09 at 3 18 40 PM" src="https://user-images.githubusercontent.com/90420685/132757161-62d6ca98-466b-43ed-b596-a03e3c783e28.png">

my collection is at: https://www.hicetnunc.xyz/skinjob/collection

i've attached screenshots from my kukai wallet showing some of the NFTs in my collection, bought yesterday and today, that are not showing up.

**Additional context**
it's interesting that my pfp avatar has reverted back to what it was a few days ago. it's as if hic et nunc is showing me a cached version of my collection instead of the most current.

missing nfts attached below:

<img width="394" alt="Screen Shot 2021-09-09 at 3 25 15 PM" src="https://user-images.githubusercontent.com/90420685/132757879-ea922912-e6a1-4f95-9d50-83f6d75cfc5f.png">
<img width="392" alt="Screen Shot 2021-09-09 at 3 25 44 PM" src="https://user-images.githubusercontent.com/90420685/132757893-e596e764-c21a-4180-b3c1-18f35aa2db26.png">
<img width="389" alt="Screen Shot 2021-09-09 at 3 25 31 PM" src="https://user-images.githubusercontent.com/90420685/132757902-2551893f-ad49-4b50-8e7d-8f61ea49710f.png">
<img width="390" alt="Screen Shot 2021-09-09 at 3 26 17 PM" src="https://user-images.githubusercontent.com/90420685/132757910-6bb7e0d0-6b33-4595-935b-366a7f4a76d4.png">
<img width="393" alt="Screen Shot 2021-09-09 at 3 26 04 PM" src="https://user-images.githubusercontent.com/90420685/132757924-32a32836-8fcf-4e0c-88d9-b9f1ccec2ffa.png">

**Comment by skinjob77** [comment]
UPDATE:
some of the NFTs have reappeared.

the one I am still trying to track down now is this one:
<img width="390" alt="Screen Shot 2021-09-09 at 3 26 17 PM" src="https://user-images.githubusercontent.com/90420685/132766276-388e9cc2-c6e4-4597-8d04-326de242ae2d.png">

it appears in my kukai wallet transactions:
<img width="1153" alt="Screen Shot 2021-09-09 at 4 38 38 PM" src="https://user-images.githubusercontent.com/90420685/132766411-4c0a9807-4c4d-4a30-853d-38915e4c3e69.png">

but still does not show up in my collection.

**Comment by violetforest** [comment]
Hey is this issue still happening? what is the objkt number?

**Comment by skinjob77** [comment]
it solved itself.  seems like hen overload for an afternoon or something. all the objkts eventually appeared. interesting though, my pfp never updated after it reverted back to that older version. so it seems like some (minor?) transactions on the tez chain got nuked...

**Comment by violetforest** [comment]
yes we are going through some infrastructure changes. please join the discord to stay up to date with announcements https://discord.gg/WtbnVbcJ
