### ISSUE TITLE
I'm trying to swap an NFT I just minted but it's not listing...

### ISSUE THREAD

**Issue by Baloguna16** [hicetnunc2000/hicetnunc#1156]
I just minted an OBJKT which worked! I have my OBJKT but now I'm trying to swap it, and the swap is not working. I want to list 9 of 10 editions of the OBJKT on the marketplace, and every time I initiate the swap, I get the transaction notification in my wallet, but I guess it doesn't go through...

0. Mint an OBJKT
1. It says 'Not for Sale' so go to manage assets and then swap on the OBJKT you just minted
2. Enter the number of editions you want to mint and their price etc
3. Click 'swap', and Spire connects to mobile wallet
4. Approve transaction in wallet!

That should work right? Am I doing something wrong?

Desktop:
 - OS: MacOS running Big Sur v11.4
 - Browser: Brave
 - Web Wallet: Spire
 - Mobile Wallet: Galleon

Smartphone:
 - Device: iPhone 12
 - OS: iOS 14

My XTZ Wallet:
Address: tz1Lp25hqP5EMp6JyhWcVNhDa9tqKrMRPghc
OBJKT: #280258

**Comment by violetforest** [comment]
Hello, are you getting errors in your wallet? Have your tried Kukai or Temple wallet? They are more widely supported.

**Comment by Baloguna16** [comment]
Not getting any errors actually. Whenever I try to swap, it says that it goes through (both in my mobile wallet and on the spire connection), but no funds are ever deducted from my account, and my OBJKT still says "not for sale" on HEN. Any thoughts?

**Comment by violetforest** [comment]
You can try to ask others in the Discord #help channel but those wallets aren't widely used so it may be difficult to get help. Its best to have more than 2 different kinds of wallets available just in case one isnt working. For example temple can have problems so people use Kukai as a backup. 

You can import the wallet using the same keys so that you dont have to create new accounts

**Comment by Baloguna16** [comment]
Actually I have a question! I just realized that there are two types of Tezos public keys for wallets: HD and Legacy. I have a legacy public key. Would that be the issue?

**Comment by Baloguna16** [comment]
Never mind! You were right, i think it was a bug in Galleon. I just switched to Kukai and it worked like a charm. Thank you!
