### ISSUE TITLE
OBJKTs had gone - Name Registry does not work

### ISSUE THREAD

**Issue by ComPressOrk** [hicetnunc2000/hicetnunc#1158]
1. I minted a lots of OBJKT today and now all gone. Everything went perfectly, I see them all for hours then all gone, just my old minted OBJKT has seen: 
https://www.hicetnunc.xyz/tz/tz1QXGY9z6RWC6Toy88ixFfsXFKwEN9q5khd/creations

But I see them on: 
https://objkt.com/profile/tz1QXGY9z6RWC6Toy88ixFfsXFKwEN9q5khd/creations

My profile pic has also gone.

---------------------------------------------

2. My old account cracked by scammers: 
https://www.hicetnunc.xyz/tz/tz1PXmUnJDh9zPKQxZLtSZ11DZbPki6XmWfP

I can't change my profile pic and my description in my old account. I did a lots of name registry:
https://tzkt.io/tz1PXmUnJDh9zPKQxZLtSZ11DZbPki6XmWfP/operations/

---------------------------------------------

3. I hope my new tzkt.io profile pic and data will change soon, because I made the verification on https://tzprofiles.com/.
I think it just need much more time: 
https://tzkt.io/tz1QXGY9z6RWC6Toy88ixFfsXFKwEN9q5khd/operations/

--------------------------------------------
more: chrome, desktop

Thank you so much, 
Tamas

**Comment by Royalurbanart** [comment]
Having the exact same issue.

**Comment by ComPressOrk** [comment]
I just wanna say 1. & 2. issue solved for the morning...

**Comment by violetforest** [comment]
@ComPressOrk have you tried updating your profile info on https://www.hicetnunc.xyz/config?

**Comment by ComPressOrk** [comment]
> @ComPressOrk have you tried updating your profile info on https://www.hicetnunc.xyz/config?

Yes, of course. The 2. issue solved already. 
Don't you know how can I change my tzkt.io profile? My old account has my profile pic, I wanna delete that, and in my new ac I would like to see my new profile pic. Thanks a lot!

**Comment by ComPressOrk** [comment]
old ac: https://tzkt.io/tz1PXmUnJDh9zPKQxZLtSZ11DZbPki6XmWfP/operations/
new ac: https://tzkt.io/tz1QXGY9z6RWC6Toy88ixFfsXFKwEN9q5khd/operations/

**Comment by violetforest** [comment]
https://baking-bad.org/blog/2021/05/01/f-a-q-hic-et-nunc/

try this verification process

**Comment by ComPressOrk** [comment]
Yes, thanks this link. Baking Bads occured to me meanwhile and already verified again.
