### ISSUE TITLE
I minted an OBJKT and it doesn't load or appear

### ISSUE THREAD

**Issue by eviltypo** [hicetnunc2000/hicetnunc#1159]
**Describe the bug**
When minting on hicetnunc, after approving the transaction in my wallet, the screen went black and nothing happened after that. The art shows up in objkt.com but not HEN.

**To Reproduce**
1. Visit https://www.hicetnunc.xyz/objkt/293922

**Expected behavior**
It should show up on HEN

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Brave
 - Version 1.29.79

tz1Qcxuuxf4hQn9q91BQiUq2vjXzjQferPj7
https://objkt.com/asset/hicetnunc/293922

**Comment by violetforest** [comment]
Hello, does this issue still exist? I am able to see the objkt that you linked
