### ISSUE TITLE
My HEN profile wont show and my Collected Items don't appear. 

### ISSUE THREAD

**Issue by marcobozidar** [hicetnunc2000/hicetnunc#1160]
**Describe the bug**

**To Reproduce**
1. Go to [https://www.hicetnunc.xyz/bzdr/collection]

**Expected behavior**
I keep on creating a profile and it is not saving... I sign it in my Temple like three times..
Here is an example of the transaction : [https://tzkt.io/opJt5qhJpU3pH2DSer7u3o8V73Hpwp7fHk3kQovrgf51DpBwY1c]

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
Hello are you still having this issue?

**Comment by violetforest** [comment]
I see your profile info and your collection. I will close, please let me know if you need more help and I will reopen.

**Comment by marcobozidar** [comment]
Thankyou ! Yes it was fixed. I appreciate the help!
*Best,*

*Marco Bozidar Erdenberger*
@marco_bozidar

E: ***@***.***
M: +1 973.747.4638
