### ISSUE TITLE
NFTs listed as not for sale and listed under ed.OBJECTSWAP V1. This has happened for a number of my NFTs that I own and used to be for sale. Now they are listed as being under ed.OBJECTSWAP V1

### ISSUE THREAD

**Issue by audri** [hicetnunc2000/hicetnunc#1161]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by audri** [comment]
https://www.hicetnunc.xyz/objkt/71500 
 This used to be for sale,none have been sold and it was listed under ed.OBJECTSWAP V1 when I try to swap it , I can not.

**Comment by violetforest** [comment]
Hello, please filter your assets with the "For Sale" filter, and then cancel the swaps and reswap them.

Please let me know if you have other questions and I will reopen.

![swap](https://user-images.githubusercontent.com/8921838/133140524-a9337c53-71bf-4a18-bb31-5604306a829c.PNG)

**Comment by audri** [comment]
How do you cancel a listing? Does that mean you burn the nft?

Do I need to cancel all my NFTs?

 

thanks

**Comment by violetforest** [comment]
hello, the screenshot I attached shows you where to cancel the listing "cancel swap"

you have to cancel and reswap the ones that say OBJECTSWAP V1

**Comment by audri** [comment]
Very sorry- but your example does not work for me. There is no batch cancel setting that I can find.

Please look at the examples. In addition it looks like some of my NFTs have been sold yet I never received the coin from the sales.

I would greatly appreciate any help you could give to me.

 

Onwards with the speed of the wind off the wings of hummingbirds,

Audri

**Comment by violetforest** [comment]
The objkt that you sent a link to in the beginning doesn't show that it is swapped under OBJKTSWAP 1 anymore, so thats a good thing. Have you tried reswapping it again?

http://hicdex.com/objkt?objkt=71500 this has info about your swaps

Can you try going to objkt.com or https://henext.xyz/ and syncing your wallet, then canceling any V1 swaps from there?

I dont have links to the objkts you're referring to that you sold. can you send them?

**Comment by audri** [comment]
I did try swapping it again and I was told the transaction was invalid-

 

Here are the details- 

he transaction is invalid and the node did not accept it.

[

  {

    "kind": "temporary",

    "id": "proto.010-PtGRANAD.michelson_v1.runtime_error",

    "contract_handle": "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"

  },

  {

    "kind": "temporary",

    "id": "proto.010-PtGRANAD.michelson_v1.script_rejected",

    "location": 962,

    "with": {

      "string": "FA2_INSUFFICIENT_BALANCE"

    }

  }

]

 

Thanks- any help appreciated!

 

Crickets,

Audri Phillips

**Comment by audri** [comment]
I did try swapping it again and I was told the transaction was invalid- also under listings it is still listed to Objectswap v1

 

Here are the details- 

he transaction is invalid and the node did not accept it.

[

  {

    "kind": "temporary",

    "id": "proto.010-PtGRANAD.michelson_v1.runtime_error",

    "contract_handle": "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"

  },

  {

    "kind": "temporary",

    "id": "proto.010-PtGRANAD.michelson_v1.script_rejected",

    "location": 962,

    "with": {

      "string": "FA2_INSUFFICIENT_BALANCE"

    }

  }

]

 

Thanks- any help appreciated! I know your job is not easy! Stay Safe

 

Crickets,

Audri Phillips

**Comment by crzypatchwork** [comment]
under listings are you able to cancel the obktswap v1?

**Comment by audri** [comment]
I did also try going to henext.xyz and canceling V1 swaps with no luck- synced my wallet up as well. 

How did my NFTs even get there?

 

Also it says that metakid owns some of my pieces- but I can’t track down if they were ever paid for…maybe I am not reading my wallet activity correctly.

Objects it says he/she owns- OBJKT#88955 OBJKT#88955 OBJKT#138316  OBJKT#57222  OBJKT#71580 hopefully they did pay for them….if so I am grateful for their patronage!

 

These are my objects that are mysteriously on henext and have OBJKTSWAP VI

OBJKT#120378 OBJKT#55141 OBJKT#57222 OBJKT#88955 OBJKT#52284

 

Once again- thanks for any help

**Comment by audri** [comment]
No I can’t

**Comment by audri** [comment]
Correction- I just tried again on https://henext.xyz/ and was able to unswap most of them!
