### ISSUE TITLE
Unable to mint after long time wait it gives an error 

### ISSUE THREAD

**Issue by sv07071974** [hicetnunc2000/hicetnunc#1163]
It says preparing object and finally give following error message with red cross mark. This happened yesteday and after 3 hours of trying it worked. now again i am not able to mint. Need help
<img width="1440" alt="Screen Shot 2021-09-12 at 6 41 31 PM" src="https://user-images.githubusercontent.com/79800573/132992192-79434c41-d025-437a-8744-073f05e544e1.png">

"an error occured X"

**Comment by violetforest** [comment]
hello, have you tried a different browser / computer / internet connection?

**Comment by trislaz** [comment]
Hello, got the same problem here ! have tried on a different browser, internet connection : it does not change it. 
EDIT : tried with an other computer, I still get the same error

**Comment by trislaz** [comment]
Ok, that's weird but it works fine if I set Royalties to another value than the default 10% !

**Comment by violetforest** [comment]
glad it works, @kylegrover does this sound like a bug?
