### ISSUE TITLE
GTLF 3D objects show only the AR  ICON when viewing creations.  Cannot preview or view 3D GTLF objects

### ISSUE THREAD

**Issue by data2700** [hicetnunc2000/hicetnunc#1164]
I have 4  GLTF files that are 3D objects.  

They minted without problem but when I view them on my computer using Windows 10 Desktop and  Chrome (only browser I use is Chrome, so have not tested with other browsers) the only thing shown is an square Icon that says 'AR' .

Also when I click Manage Assets I get the same result - all of my assets that are GLTF show the square AR icon, but not the creation.  When I open my android phone I can see everything without a problem. in both my collection and when viewing separately.

Attached is what I see when viewing my collection via  Windows 10 desktop and Chrome

![HEN](https://user-images.githubusercontent.com/6796716/132993468-c294bcb6-a692-4cee-a57c-c51a254d20a8.PNG)

What should happen is that I should be able to see the preview and objects on both Chrome desktop and mobile devices

Here are the object GLTFs that show the square AR icon when viewing via Windows 10 Chrome.  

https://www.hicetnunc.xyz/objkt/292754
https://www.hicetnunc.xyz/objkt/292121
https://www.hicetnunc.xyz/objkt/288623
https://www.hicetnunc.xyz/objkt/266937

Standard files .png objects preview fine and are available for viewing as objects without a problem on both desktop and Android.

Here is a standard .png file that I can view with no problem as a part of my assets and as an object for sale.

https://www.hicetnunc.xyz/objkt/296224

Thanks in advance for your help

**Comment by violetforest** [comment]
I cannot reproduce this. has the problem been fixed?

**Comment by data2700** [comment]
@violetforest  Thank you for checking. Yes, this appears to be fixed.  I checked this morning and everything was fine and it has been working without a problem throughout the day.  I will close this  issue :)
