### ISSUE TITLE
Counterfeit art being sold

### ISSUE THREAD

**Issue by MurataNFT** [hicetnunc2000/hicetnunc#1165]
Hello - It was brought to my attention on twitter that someone is illegally selling an nft I made on HEN. Will you please remove, or let me know how I can do that? Here's the tweet:
https://twitter.com/Rouxcoucou/status/1436977659515478020
Original work is here:
https://foundation.app/@takeshimurata/larry-cove-35825
Thanks

**Comment by violetforest** [comment]
hicetnunc.xyz/yann-kermi/creations

this profile has been restricted

I will close but please let me know if you need to open
