### ISSUE TITLE
profile bio and image missing

### ISSUE THREAD

**Issue by datsla** [hicetnunc2000/hicetnunc#1168]
**Describe the bug**
my bio and pic are missing from my H=N profile

both iphone and desktop views

https://www.hicetnunc.xyz/datsla

**Comment by violetforest** [comment]
Please resubmit your info at https://www.hicetnunc.xyz/config

**Comment by violetforest** [comment]
this looks like its working for me, I will close and if the issue persists please let me know and I will reopen

**Comment by datsla** [comment]
thanks.. Its fine now that I re-submitted all the info. curious as to why it disappeared in the first place?

**Comment by violetforest** [comment]
we changed the way the profiles are set up, let me know if you need more help
