### ISSUE TITLE
"Report profile" button to easier report copyminters

### ISSUE THREAD

**Issue by NeoktaLabs** [hicetnunc2000/hicetnunc#1169]
**Is your feature request related to a problem? Please describe.**
To help fighting against copyminters, I believe it would be really useful to have a "report" button on each profile in order to report copyminters.
Getting to discord to report a profile can be painful and add extra steps that could be removed by implementing a "report profile" button type of thing.

**Describe the solution you'd like**
When getting to an artist page, we could have a "report profile" button to directly report copyminters profiles.
The request would then go to the H=N staff/moderators for review/block the profiles

**Describe alternatives you've considered**
The current alternative solution is to use the H=N discord and report the profiles manually there.

**Additional context**
Inspiration from facebook or instagram profiles.

**Comment by kylegrover** [comment]
This has already been planned and developed and should be launched very soon.

**Comment by NeoktaLabs** [comment]
Thanks I have closed this.
