### ISSUE TITLE
Missing NFTs in artist profiles

### ISSUE THREAD

**Issue by oldominion** [hicetnunc2000/hicetnunc#117]
Since the latest upgrades that significantly improved site responsiveness, only a subset of artist works are showing up in some artist profiles, e.g. https://www.hicetnunc.xyz/tz/tz1demsQU1EN5T8eUo1eCJms7X19L6CjtaRt

**Comment by oldominion** [comment]
NFTs that should be in that profile..
https://twitter.com/Juzou21119599/status/1370781375196930052?s=19

**Comment by guidoschmidt** [comment]
I am, too, missing some of my early mints on my creations profile:
https://www.hicetnunc.xyz/tz/tz1Z9s59QUmYTs4NKf48uHhcgeY5wimpFWiX

for example https://www.hicetnunc.xyz/objkt/1190

**Comment by msurguy** [comment]
Same problem with my profile, a bunch of older works is missing! 

https://www.hicetnunc.xyz/tz/tz1ScnxV6dRwQ3rDM8eTs6Gn7isnHHx4bk1r

**Comment by veqtor** [comment]
This is solved now so you can close

**Comment by oldominion** [comment]
Resolved

**Comment by ghost** [comment]
Hi, Hope you're keeping well. I just minted my first artwork :). I don't have the option to "curate" even if the wallet is connected.

Thanks for your help.

https://www.hicetnunc.xyz/tz/tz1WzpRbYJx4ma3PgAuhdsL6Yb8gmUEVANRK

**Comment by skenaja** [comment]
Answered in separate issue
