### ISSUE TITLE
Restricted Account under Manage Assets

### ISSUE THREAD

**Issue by bvb-79** [hicetnunc2000/hicetnunc#1171]
I am receiving this message when trying to access my Objkts.  How do I fix it?  It may be due to three errors made when first minting on HEN which I think could be considered copyminting.  I purchased the Objkts correctly and recently tried to burn the three problematic Objkts in my Kukai wallet.

**Comment by violetforest** [comment]
Hello, please dispute your case in the #report-copyminters channel on the Discord
