### ISSUE TITLE
Restricted account 

### ISSUE THREAD

**Issue by Harris15000** [hicetnunc2000/hicetnunc#1175]
Hi, I am a creator and collector at hicetnunc.xyz. today I got my account restricted as I uploaded an object that I shouldn’t have done… The rest of my account (40 creations) and a very big collection was fully legal and ok. I spent hours and hours for months … is there any way to burn that item and get back my account? I learnt my lesson, please help me out in any way possible, I really need to get my account back. I was very active over there. Any tips would help. Thanks

I didn't know I wasn't allowed to upload the objkt I uploaded

- hicetnunc.xyz/Freeman/creations
- tz1Y5sJV97PyihZs5PvReaAgRr9UrVvbxVBY
- All of my objkts

**Expected behavior**
Please get my account back on action with my objkts back please, for 1 mistake in 1 or 2 objkts I am getting my whole collection and account affected. I feel this is unfair

**Comment by tortulez** [comment]
Hello, I think you need to send your PORN objkts to the burn address > tz1burnburnburnburnburnburnburjAYjjX

Then you may ask on the Discord to be unlocked...
I hope you will I've collected some of your creations.

Best regards.

**Comment by Harris15000** [comment]
Hello, thanks for your help. Yes I wanted to burn the objkets but with my account restricted I don't have any access to even burn it. Is there any other way I can do that?

**Comment by tortulez** [comment]
1. Get the OBJKT IDs 315891, 315774, 315742 
2. Go to your Wallet, find the OBJKTS 
3. click Send, enter the nulber of copies (all) and destination > tz1burnburnburnburnburnburnburjAYjjX

Other way would be a batch but this will be more difficult.

Don't forget to send ALL Copies and to take care of your reputation ! ;)

Have fun.
