### ISSUE TITLE
RPC node is temporarily unreachable.

### ISSUE THREAD

**Issue by GuigaToledo** [hicetnunc2000/hicetnunc#1176]
Can´t put an art to sell :(
i just put the object to sell... choose a price when i click to swap and  confirm on tezos temple wallet that message shows up..

""
Error
Failed to send request to https://mainnet-node.madfish.solutions/chains/main/blocks/head/helpers/forge/operations. Invalid request provided or RPC node is temporarily unreachable.
""
""
[ { "destination": "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton", "kind": "transaction", "amount": 0, "storageLimit": "100", "parameters": { "entrypoint": "update_operators", "value": [ { "prim": "Left", "args": [ { "prim": "Pair", "args": [ { "string": "tz1aqdfLHiLoAHpeMpJ2jwFybreRz8UQiyNp" }, { "prim": "Pair", "args": [ { "string": "KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn" }, { "int": "273104" } ] } ] } ] } ] } }, { "destination": "KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn", "kind": "transaction", "amount": 0, "storageLimit": "270", "parameters": { "entrypoint": "swap", "value": { "prim": "Pair", "args": [ { "prim": "Pair", "args": [ { "string": "tz1f4V314WFsUzYwVBudTLN7nPoB79HZKsdD" }, { "int": "1" } ] }, { "prim": "Pair", "args": [ { "int": "273104" }, { "prim": "Pair", "args": [ { "int": "250" }, { "int": "65790000.00000001" } ] } ] } ] } } } ]
""

 https://www.hicetnunc.xyz/guigatoledo
 tz1aqdfLHiLoAHpeMpJ2jwFybreRz8UQiyNp
 https://www.hicetnunc.xyz/objkt/273104

**Desktop (please complete the following information):**
Windows 10 Home Single Language
 Microsoft Edge
Versão 93.0.961.47 (Compilação oficial) (64 bits)

Temple Tezos Wallet

**Comment by skenaja** [comment]
these are usually temporary issues.
