### ISSUE TITLE
Cannot mint objkt

### ISSUE THREAD

**Issue by jammmmmm11** [hicetnunc2000/hicetnunc#1179]
I have been trying to mint an objkt for 2 days using Mac Chrome and Temple wallet on my iPhone 4g hotspot. No success. It worked a few days ago, though. I was able to mint 2 pieces but that's it. The file is only 1 mb. I tried both jpg and png.

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link: https://www.hicetnunc.xyz/thesovereigntii
- tezos wallet address: (Temple) tz1ZDU8PZMmF2JBm283CHqjwXd4BGJHEcm5d
- objkt #'s that are being affected: Not minted

**To Reproduce**
1. Go to 'preview'
2. Click on 'mint objkt'
3. Result: Sending request to Temple wallet
4. No error message. Endless sending.

**Expected behavior**
I expected the objkt to mint, but nothing happened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Up to date 93.etc

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by ben-haas** [comment]
Same thing is happening to me. I get this error in console:
![image](https://user-images.githubusercontent.com/13275388/133893593-833b0ede-e1d8-44e4-8141-558cd9fee0c6.png)

**Comment by jammmmmm11** [comment]
Do you know what is causing it? I tried everything within my own limited trouble-shooting repertoire lol. This world is pretty new to me.

**Comment by ben-haas** [comment]
I'm currently using Starlink internet at home where the minting is not working. I also noticed that saving changes to my profile doesn't work either. I remoted into my work computer and everything worked fine. Maybe some sort of network issue?

**Comment by jammmmmm11** [comment]
maybe! i will try downstairs closer to the router. maybe my hotspot doesn't work and I need to use the wifi. I'll let you know! thank you for sharing your process.

**Comment by mehdiafsharart** [comment]
Almost same thing here. it's been several days that I cant mint any file format. if it's JPEG, "an error occurred" shows up, any other file formats, "preparing OBJKT" shows up and never sends anything to my wallet and nothing happens!
![Screenshot (329)](https://user-images.githubusercontent.com/91176573/134808847-09dcefec-7b9a-422e-83a3-d5a99f99160d.png)
![Screenshot (331)](https://user-images.githubusercontent.com/91176573/134808868-3ccc6d71-2960-4e75-8e4c-b0af45dff6e1.png)

**Comment by skenaja** [comment]
These are usually network/connectivity issues unfortunately. Trying with a different ISP often helps.
