### ISSUE TITLE
Bought an NFT. After the transaction is complete, the objkt and the creator account have been labeled as 'restricted'. What should I do with my NFT now?

### ISSUE THREAD

**Issue by amitlalwani7** [hicetnunc2000/hicetnunc#1183]
![image_2021-09-20_05-22-03](https://user-images.githubusercontent.com/86951058/133947001-1e1845a1-ea35-4557-b92b-f05a7cf928ef.png)

**Comment by BadFragments** [comment]
Same thing has happened to me
![restrictedHeN](https://user-images.githubusercontent.com/91087778/134053318-f2fa96e0-9fbd-4ed3-a355-1c0191d79337.png)

**Comment by bearcthulhu** [comment]
Hate to break it to you. The piece you bought was a forgery of another artist's work from a copyminter. 

The accounts and pieces have been restricted because the art work did not belong to the account you bought it from.

**Comment by BadFragments** [comment]
that sucks, but good to know

**Comment by amitlalwani7** [comment]
Never ever buying any NFT on Tezos!

**Comment by violetforest** [comment]
here is a guide on the wiki on how to avoid copyminters https://github.com/hicetnunc2000/hicetnunc/wiki/Beware-copyminters!
