### ISSUE TITLE
Manage Assets page says I own editions, but says I own zero when I try to burn

### ISSUE THREAD

**Issue by BadFragments** [hicetnunc2000/hicetnunc#1185]
**Describe the bug**
I own editions of my OBJKTS, and the history/listing says I own them.
However, when I try to burn, it says I own zero.
It says "collect for [x] tez" and when I click that, my Kukai wallet shows an entirely different wallet address as the recipient.
Has someone somehow duplicated my identity so the money goes elsewhere? Shouldn't the recipient address be mine?

**Please give us your profile link, tezos wallet address, and objkt numbers**
- https://www.hicetnunc.xyz/badfragments/creations
- tz1f65Fb7vUakhx5c7wUK49eBDDzwxMjV8f6
- all my objkts are affected but you can see it one at https://www.hicetnunc.xyz/objkt/314760

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/badfragments/creations
2. Click on any objkt
3. Scroll down to history/listings

**Expected behavior**
I need to be able to burn some objkts. I was able to yesterday, and now all my objkts say I own 0 editions to burn, even though the history/listings show me as the minter and only owner

**Screenshots**
![ownership1](https://user-images.githubusercontent.com/91087778/134054356-e3fc331e-1ffc-49e4-977d-bc5acc21d8cd.png)
![ownership4](https://user-images.githubusercontent.com/91087778/134054358-d657c601-b0f0-47bc-80d7-8b142dec278e.png)
![ownership2](https://user-images.githubusercontent.com/91087778/134054359-8018710e-1dda-41cc-80c0-16b5b78785b4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Bing

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by BadFragments** [comment]
Is anyone from H=N going to get back to me on this?

**Comment by jondevoid** [comment]
i have the same problem, did you find the solution?

**Comment by BadFragments** [comment]
> i have the same problem, did you find the solution?

Does yours say OBJKTSWAP V1 in the listings? 
I was reading an unrelated post and the dev/mod said something about updating the system from OBJKTSWAP V1 to V2 and told the person they would have to cancel and then reswap the token.
But this seems unfair because it costs 0.08 tez to cancel, then another 0.08 to swap, then another whatever to list editions, so it's going to cost 0.2 tez for every relist. 

No one from H=N is getting back to me, either here on on Twitter.

**Comment by violetforest** [comment]
You need to cancel your swaps before you burn them. This is detailed in the wiki https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5

**Comment by BadFragments** [comment]
> You need to cancel your swaps before you burn them. This is detailed in the wiki https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5

This isn't the issue, it says I own zero editions and offers for me to collect my own work.
If I click "collect", the XTZ leaves my wallet and then comes back to my wallet...look at the screenshot I am providing here:
![bought it from myself](https://user-images.githubusercontent.com/91087778/134510068-92776a3c-cdb0-47db-b8f6-bd46464de124.png)

**Comment by BadFragments** [comment]
This shows that I sent 0,5 tez, then I get 0.4875 from myself into the wallet...that wasn't happening before
