### ISSUE TITLE
I cant Mine Objkt any more... 

### ISSUE THREAD

**Issue by Touky333** [hicetnunc2000/hicetnunc#1186]
Hello, 
When i Try to mine Objkt, "preparing objkt" run for hours.. and not works. 

- My  profile link : https://www.hicetnunc.xyz/touky333/collection
-My  tezos wallet address : tz1S8zxuJn1dQv1jLUHr9YyMqUj1WPANxU7H

**Screenshots**
![image](https://user-images.githubusercontent.com/84917864/134137202-530da246-028f-4286-a702-c0443c35f4f4.png)

**Comment by kylegrover** [comment]
Please check if there are any errors in the browser console and post those here

**Comment by Touky333** [comment]
Sorry, I dont know what a browser console is...

**Comment by violetforest** [comment]
@Touky333 if you are on chrome, right click on the page, press "inspect", then send a screenshot of the console please
![console](https://user-images.githubusercontent.com/8921838/134564393-292e40eb-81ec-47da-93dd-2b8273752189.PNG)

**Comment by SIRHAMY** [comment]
Hiya - I'm running into the same issue. I can sync fine with Kukai but when I try to mint, no request goes through to Kukai for me to accept.

Here's a screenshot of my console:

![image](https://user-images.githubusercontent.com/2686931/136385841-ea0a2cb8-0a9f-4a53-be95-da4d33bf6830.png)

EDIT: Okay hold up - it looks like a request did eventually make it to Kukai - but it took several minutes. Enough time for me to wonder if it was actually working or not.
