### ISSUE TITLE
broken links to all my collections

### ISSUE THREAD

**Issue by insovia** [hicetnunc2000/hicetnunc#1188]
**Describe the bug**
none of the links to my "creations" work. leads potential collectors to a blank or black screen without anything there.
To Reproduce

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link
- https://www.hicetnunc.xyz/insovia
- tezos wallet address
- tz2MD2WSkAcvLb9Uxua5mWWcnEdMRRxDyxm9
- objkt #'s that are being affected
- https://www.hicetnunc.xyz/objkt/335727
- https://www.hicetnunc.xyz/objkt/338504

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by insovia** [comment]
i can see my profile and my creating but i cant swap my art
[
![03FBE855-861C-495B-A10A-04DEDE4F8D46](https://user-images.githubusercontent.com/91155993/134341858-4e7fe6b4-d8b7-45ed-b909-455846337965.png)
](url)

**Comment by violetforest** [comment]
there were issues on the site yesterday. the objkt links are working for me. those objkts also show that they are already swapped
