### ISSUE TITLE
i cant see my colecctions or my profile info.

### ISSUE THREAD

**Issue by camial123** [hicetnunc2000/hicetnunc#1189]
I cant see any of my objets in my collection, or any actualizations on my profile, such as my username, description, etc.

my hec profile is https://www.hicetnunc.xyz/tz/tz1YvYBd2fe6s68YSY4oarvXThSDemgZa1hX/creations

and my wallet is Kukai tz29KCH4AazbdGh4KV6FM7znFVN4UmihR6gH

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
hey, you are linking to two different wallets, this is not a bug. they are two different wallets.

https://www.hicetnunc.xyz/camix/creations
https://www.hicetnunc.xyz/camixx/creations
