### ISSUE TITLE
Problem with my profiles

### ISSUE THREAD

**Issue by unitedjerks** [hicetnunc2000/hicetnunc#1192]
Hi, i want to mint new artwork, but I can't see my profile or any of my objkt in my collection.

My HEN profile is https://www.hicetnunc.xyz/tz/tz2UXNHTXhgK4YMCcXmyqLuCUYie9nRsDYaw/creations

and my wallet is Kukai tz2UXNHTXhgK4YMCcXmyqLuCUYie9nRsDYaw

**Comment by violetforest** [comment]
there were issues on the site yesterday. this is working now.
