### ISSUE TITLE
I can't see my assets :(

### ISSUE THREAD

**Issue by Aemewang** [hicetnunc2000/hicetnunc#1193]
hi, i can not see all my assets only the first one minted and the first one collected.

**Please give us your profile link, tezos wallet address, and objkt numbers**
https://www.hicetnunc.xyz/aemea_xi/creations
tz1UFtAQaKY7cKEpo45mtoCzPDK9hdf3BUfs
https://www.hicetnunc.xyz/objktid/337450
https://www.hicetnunc.xyz/objktid/309001
and the one I collected is this one 
https://www.hicetnunc.xyz/objkt/332789

**To Reproduce**
1. my profile
2. Click on creations (appears only one. I minted 3) and collection appears only one i have one more

**Expected behavior**
to see all my assets normally, is not happening.

**Screenshots**

![image](https://user-images.githubusercontent.com/89555207/134241372-2348a64f-59b0-4e35-9902-5200fa09fbe3.png)
![image](https://user-images.githubusercontent.com/89555207/134241412-69e6caf2-009b-4cc4-b3a6-1da2ea32efce.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by Aemewang** [comment]
![image](https://user-images.githubusercontent.com/89555207/134277921-6ef14d5c-830a-4149-8104-0466348705cd.png)
![image](https://user-images.githubusercontent.com/89555207/134277938-5c720dba-8745-4333-b694-c5a7691b843c.png)
now I see two of the three I minted. one is missing. the same with the ones I collected appears only one. two are missing. I have three in total by now.

**Comment by violetforest** [comment]
there was a problem on the site yesterday. this should be working now.

**Comment by violetforest** [comment]
https://www.hicetnunc.xyz/objktid/337450
https://www.hicetnunc.xyz/objktid/309001

the above that you posted is not the right link

it should be this:
https://www.hicetnunc.xyz/objkt/337450
https://www.hicetnunc.xyz/objkt/309001

**Comment by Aemewang** [comment]
thank you a lot, everything seems to be fixed now. I was worried mostly because I did not knew what was going on. sorry.
