### ISSUE TITLE
I can't see my profile and objkt :(

### ISSUE THREAD

**Issue by fedegrabina** [hicetnunc2000/hicetnunc#1194]
Hi,  I can't see my profile or any of my objkt in my collection.

**Please give us your profile link, tezos wallet address, and objkt numbers**
- https://www.hicetnunc.xyz/federicograbina
- tz1NJ213DKYwG7NwK3mxzK7fmGMfoXaphduJ

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I edited my profile yesterday and i mint my first NTF today

**Comment by enaisikey23** [comment]
Hello, I have same trouble. Can’t see my profile, objk, and collections.
here is my profile on H=N 
https://www.hicetnunc.xyz/enaisikey23/creations or

https://www.hicetnunc.xyz/nick23/creations that I newly set up (profile change) during that time. 

is there any something wrong I did?
How do I solve it?

**Comment by fedegrabina** [comment]
idk, I guess we just have to wait ...
today I mint my first nft and this happens, bad luck mine :(
I tried to enter your profile but nothing appears

I leave my profile here, would you do me a favor to enter and tell me if you see something?
https://hicetnunc.xyz/federicograbina

**Comment by pilipaint** [comment]
My account and objkt disappeared. If you click the link the page it keeps loading forever.
Also when I click " edit profile" all infos are blank (avi, username, description)

profile https://www.hicetnunc.xyz/pilipaint
wallet address https://wallet.kukai.app/account/tz2DqRoXtAYtdemBtLPiTvm8nE9RmTSptsab
objkt hicetnunc.xyz/objkt/339032

**Comment by enaisikey23** [comment]
Hello Fedegabrina and Pilipaint are your account still dissapearing? because I can see both of your profile, but still I can’t see mine :(

![5008DDC8-CC93-43B2-93F6-13D61042D14B](https://user-images.githubusercontent.com/91166357/134288420-c49562df-5d41-4d96-a1f1-e30045ac3d90.jpeg)
![3D04441E-10D8-4EBB-9932-5B3960539992](https://user-images.githubusercontent.com/91166357/134288423-961f1a98-7ad5-4095-a724-73e8d885616d.jpeg)

**Comment by enaisikey23** [comment]
so weird I can open the Enaisikey23 profile but still creation and collections are missing,
let me know if you guys can see my full profile. Thank you

![288FD099-A3B7-4D7E-B960-F57B3F2D3138](https://user-images.githubusercontent.com/91166357/134288860-23dfbeb2-ab37-4b00-baa8-da7f4a10e0f0.jpeg)

**Comment by enaisikey23** [comment]
update: I can finally see them, my enaisikey23 profile,objkt, and collections
but I’m guessing it may still have something bugs or error . 
it’s okay for now.

![2AC89799-F5B1-47B2-9956-9DCA8162B42D](https://user-images.githubusercontent.com/91166357/134289817-0d25ab75-0384-4fdb-a0cd-455b9998c49e.jpeg)

**Comment by dewisnuartana** [comment]
hi there, same issue as mine I guess..
just minted my first objkt but it didn't appear on my creation tab, still need a few more step ahead to set up the objkt to avail for purchase. 
even though my Kukai wallet is confirmed the objkt already minted.

any advice, please?

![Screenshot 2021-09-22 at 5 45 02 PM](https://user-images.githubusercontent.com/91191702/134330081-48a382a2-469d-44e4-a2b6-ddec92c82729.png)
![Screenshot 2021-09-22 at 5 45 37 PM](https://user-images.githubusercontent.com/91191702/134330144-bceb6375-0687-4738-ad0c-228010fab61e.png)

**Comment by violetforest** [comment]
there was a problem on the site yesterday. this should be working now.

@dewisnuartana if its still not working, please link a profile or objkt # so i can help u

**Comment by dewisnuartana** [comment]
@violetforest according to the 🗨dev-announcements as today 23sept indexer and swap are stable. but I'm still stuck on swap issue. 

![Screenshot 2021-09-23 at 4 11 30 PM](https://user-images.githubusercontent.com/91191702/134481874-5929bf0e-e9ca-4a4d-9113-79e166c450c2.png)

here is my objkt link [https://www.hicetnunc.xyz/objkt/341251](url)

many thanks..
