### ISSUE TITLE
My profile went back to two days ago

### ISSUE THREAD

**Issue by marcociceri** [hicetnunc2000/hicetnunc#1195]
**Describe the bug**
Yesterday I changed my profile name, profile picture and minted one objkt (100ed.) successfully.
Tonight I tried to mint another object and at first, it did not work (I also waited for an hour).
Then I changed network and re-synced my wallet and I saw the interaction in my wallet, but not the objkt. The objkt would not appear on my profile either.
I minted again and after a bit the 100 editions appeared on my wallet, but not on my HEN profile.
My profile instead had gone back in time to two days ago!
The new URL with my new name did not work, the old one did. The objkt I minted yesterday is disappeared and there is no trace of the one I minted today.

**Please give us your profile link, tezos wallet address, and objkt numbers**

- https://www.hicetnunc.xyz/marcoc.ttt (old)
- https://www.hicetnunc.xyz/marco-mondo (new disappeared)

- tz1M4Js29Gdd2iGds79bZrFE72kTpmBqb82d

- objkt #335553 (disappeared)
- two objkt (never got onto my profile)

**Comment by violetforest** [comment]
there was a problem on the site yesterday. this should be working now.

**Comment by marcociceri** [comment]
It is, thanks Violet
