### ISSUE TITLE
All my objkt desapeard exept the fist mint

### ISSUE THREAD

**Issue by dmtvision** [hicetnunc2000/hicetnunc#1196]
**Describe the bug**
All my objkt desapeard exept the fist mint

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link : https://www.hicetnunc.xyz/dmt_vision
- tezos wallet address : tz1XoEt76N3nsnmBrCQjmrrUnq2ebqcYpfZU
- objkt #'s that are being affected : all

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by Amorphousartt** [comment]
My profile same issue 😞😞😞
All my assets gone except first one
#335063 , #330262 , #330419 ,#331029 , #330220 >>> all gone and disappeared

**Comment by Seeleyb** [comment]
Having same issue

**Comment by tiborsaas** [comment]
Same thing. 

https://www.hicetnunc.xyz/objkt/336716
https://hicdex.com/objkt?objkt=336716

Current holder is:

`Contract: HEN swap v2KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn`

**Comment by tiborsaas** [comment]
Probably a hicetnunc issue, it's displaying correctly on https://objkt.com/

**Comment by TheSmileGhost** [comment]
Ditto for me as well.

**Comment by momomeatmaker** [comment]
I have the same issue :s

profile link 
https://www.hicetnunc.xyz/momomeatmaker/creations
tezos wallet address 
tz1LX2rUXBCWEhwNm13QuWtXNd761Fn8bVwm 
objkt link 
https://www.hicetnunc.xyz/objkt/338906

profile screenshot
https://ibb.co/1vyhmY0

objkt page screenshot
https://ibb.co/K0DY3Ch

Desktop:
    OS: windows 10
    Browser: firefox
    Version: 92.0 (64-bit)

**Comment by dmtvision** [comment]
back to normal for now !

**Comment by violetforest** [comment]
there was an issue on the site yesterday, it should be working now
