### ISSUE TITLE
hi, i can not see all my assets only the first one minted.

### ISSUE THREAD

**Issue by saut-saudraw** [hicetnunc2000/hicetnunc#1197]
**Describe the bug**

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link
- tezos wallet address
- objkt #'s that are being affected

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by SIRHAMY** [comment]
Also experiencing this: https://www.hicetnunc.xyz/hamy.art/creations

* Can only see the first objkt I minted
* Cannot see the second objkt I minted in either the creations or collections tab even though I 1) created it and 2) held onto one of them

OBJKT: 331853

**Comment by violetforest** [comment]
there was a problem on the site yesterday. this should be working now.
