### ISSUE TITLE
https://www.hicetnunc.xyz/config Edit Profile section. Add file image as avatar. Description. 

### ISSUE THREAD

**Issue by copyplanetdotxyz** [hicetnunc2000/hicetnunc#1198]
**Describe the bug**

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link
- tezos wallet address
- objkt #'s that are being affected

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
Hi, there is information missing in this and I dont know how to help you.

I need links to profile links and objkts that are affected, and I need a clear detail of what the problem is.

**Comment by copyplanetdotxyz** [comment]
The problem is solved. All works fine now! Thank you!
