### ISSUE TITLE
Also lost user profile and all objkts when trying to connect

### ISSUE THREAD

**Issue by TheSmileGhost** [hicetnunc2000/hicetnunc#1200]
**Describe the 

I was able to mint then everything vanished. My wallet Id is

tz2TS3Qpju29p2RKSaWmzvPyzwD3CcrNZsh3

User ID smileghost

https://www.hicetnunc.xyz/smileghost/creations

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link
- tezos wallet address
- objkt #'s that are being affected

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by ephraimtan25** [comment]
Same here from
https://www.hicetnunc.xyz/tz/tz1Yg6JXXREDHoef21A7N4wSUBnwgM5tBWbT
wallet adress: tz1Yg6JXXREDHoef21A7N4wSUBnwgM5tBWbT

**Comment by punkmasters** [comment]
Same Issue.
Everything was going smoothly. I edited my profile name last day and confirmed the transaction. It was working fine. After a few hours, I tried to sync with my wallet and it didnt show my creations. After few hours, it's showing my profile like it was before 2 days ago. All the sold, burnt nfts are appearing in my wallet now. 

tz1Xa7PW2kh1NBi2pVpftA3B7MrhmXHmFzkD

**Comment by pilipaint** [comment]
My account and objkt disappeared. If you click the link the page it keeps loading forever.
Also when I click " edit profile" all infos are blank (avi, username, description)

profile https://www.hicetnunc.xyz/pilipaint
wallet address https://wallet.kukai.app/account/tz2DqRoXtAYtdemBtLPiTvm8nE9RmTSptsab
objkt hicetnunc.xyz/objkt/339032

**Comment by violetforest** [comment]
there were issues on the site yesterday, I believe all of these profiles/objkts are loading now
