### ISSUE TITLE
profile and objkts disappeared

### ISSUE THREAD

**Issue by antiwork1** [hicetnunc2000/hicetnunc#1201]
My account and objkt disappeared. If you click the link the page it keeps loading forever.
Also when I click " edit profile" all infos are blank (avi, username, description)

profile https://www.hicetnunc.xyz/antiwork
wallet address tz1MDf4icr7iWa5V4PVGBeETFQyg8Deavqxj
objkt https://www.hicetnunc.xyz/objkt/339833

Thank you

**Describe the bug**

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link
- tezos wallet address
- objkt #'s that are being affected

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by fedegrabina** [comment]
Same problem :(

**Comment by ephraimtan25** [comment]
Same here from
https://www.hicetnunc.xyz/tz/tz1Yg6JXXREDHoef21A7N4wSUBnwgM5tBWbT
wallet adress: tz1Yg6JXXREDHoef21A7N4wSUBnwgM5tBWbT

**Comment by pilipaint** [comment]
My account and objkt disappeared. If you click the link the page it keeps loading forever.
Also when I click " edit profile" all infos are blank (avi, username, description)

profile https://www.hicetnunc.xyz/pilipaint
wallet address https://wallet.kukai.app/account/tz2DqRoXtAYtdemBtLPiTvm8nE9RmTSptsab
objkt hicetnunc.xyz/objkt/339032

**Comment by Zepraxis** [comment]
I had the same issue, now it's all back but it's going slow, by slow I mean making a swap/mint takes around 5 hours.... The swap goes through, but on HEN's side it just doesn't update... On Objkt.com it's already done. HEN is having some real issues atm

**Comment by violetforest** [comment]
there were issues on the site yesterday, I believe all of these profiles/objkts are loading now
