### ISSUE TITLE
My NFT artwork is Disappeared.

### ISSUE THREAD

**Issue by valardss** [hicetnunc2000/hicetnunc#1202]
Hi Hic et Nunc,
Around one hour ago, I found my NFT artwork is disappeared on your platform.
I don't know what's going on. My latest artwork and latest collection are disappeared.
Here is my screenshot, my wallet and page address.

![Untitled-1](https://user-images.githubusercontent.com/91169194/134271680-bc1ddb92-4ee4-4195-ab96-62f5b1a7aeaf.jpg)

wallet address : tz2FPX6KATGAiUUCQHBEcYs8txWyVYFchDrM
page address : https://www.hicetnunc.xyz/valard.ss/creations

There is only one artwork that have been minted and listed and i posted on my twitter. this is the link of it : 
https://twitter.com/valard_ss/status/1440246330106912769?s=20

hicetnunc.xyz/objkt/338090 (this was my objkt link)

PLEASE LET ME KNOW WHAT HAPPEN

**Comment by violetforest** [comment]
there were issues on the site yesterday, I believe all of these profiles/objkts are loading now
