### ISSUE TITLE
Profile edit doesn't work

### ISSUE THREAD

**Issue by botanicalbandit** [hicetnunc2000/hicetnunc#1205]
**Describe the bug**
After pressing 'Save Profile' nothing happens, but the wallet transactions still working.

**Please give us your profile link, tezos wallet address, and objkt numbers**
- https://www.hicetnunc.xyz/tz/tz1avx9TeFXsZv7f6dBG4L6MxyNBfRjiHk6p/
- tz1avx9TeFXsZv7f6dBG4L6MxyNBfRjiHk6p

**To Reproduce**
1. Click 'Edit Profile'
2. Choose File ( Avatar )
3. Add username
4. Add description
5. Click 'Save Profile' 

**Expected behavior**
The profile still the same as before.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Microsoft Edge
 - Version 93.0.961.52 (Official build) (64-bit)

**Comment by drakeliemmore** [comment]
same, i got the same issue. i tried to save profile like 6/7 times. my kukai wallet balance is taken but the profile is not saved.

**Comment by violetforest** [comment]
rib4ldi

experimenting on visual assets. mostly working on illustration, photography, and video.

0 ○


This is what I see your profile as, is that not correct?
@botanicalbandit

**Comment by botanicalbandit** [comment]
@violetforest yes it actually worked already, my profile is now updated
