### ISSUE TITLE
"Not for sale" problem

### ISSUE THREAD

**Issue by dejureacademic** [hicetnunc2000/hicetnunc#1208]
Hi,

I minted the  https://www.hicetnunc.xyz/objkt/341677

See Tx: https://tzkt.io/ooSRyL6nSsaCGKGkSHk6gNACiVkjWR2cZyYQv9d2gmQY3ffcfeg

I swapped it. See Tx: https://tzkt.io/ooasJhRPs81CU6MrMsGER4knJtr9uL3ucj2QpLfE5rq2uUu1yTn

But it seems "not for sale" . See: http://prnt.sc/1t8hlo5

So I can not sell my NFTs.

Pls solve the problem.

**Comment by diegolazzarin** [comment]
I have the same problem!
https://www.hicetnunc.xyz/objkt/342121
https://tzkt.io/op8beAW9TsvxwLYHDVQgM579BWcKkDKTdmN5mdUaDuqFQF74SGs
Yesterday all my objects disappeared and reappeared today... maybe there is a problem with my profile... please help!

**Comment by MoreirArt** [comment]
Same here

Obj: [https://www.hicetnunc.xyz/objkt/342093](url)

Tx: [https://tzkt.io/oo3tYkYjRnR1jg47szhawxzLWKi2nevmRj5WUaFcJiqYDa2XyMe](url)

**Comment by violetforest** [comment]
@dejureacademic please try canceling and then reswap
@diegolazzarin the site was having issues with the indexer yesterday, this should be solved now

**Comment by violetforest** [comment]
@MoreirArt did you cancel your swaps? can you try to reswap please?

**Comment by SIRHAMY** [comment]
@violetforest - Just did a reswap (cancel then do swap) and looks like swap still sent to V1 and `Not for Sale` - https://www.hicetnunc.xyz/objkt/340913

![image](https://user-images.githubusercontent.com/2686931/134436894-5af41d3b-c69d-4b4b-b3a9-72c689a5b658.png)

**Comment by violetforest** [comment]
@SIRHAMY can you try to cancel the swap like this and then reswap?

![swapv1](https://user-images.githubusercontent.com/8921838/134437057-862a7331-a3e4-4424-a4f7-bdd6231a1207.PNG)

**Comment by SIRHAMY** [comment]
@violetforest  - Okay just did it and now it works.

So maybe problem was that I still had a few OBJKTs for sale that were in the V1? So maybe when I tried to swap a new one, it put it in V1 as opposed to the correct place?

Confirmed swap works for:
* https://www.hicetnunc.xyz/objkt/340913
* https://www.hicetnunc.xyz/objkt/342099
* https://www.hicetnunc.xyz/objkt/342166

**Comment by violetforest** [comment]
yep that looks like its working now @SIRHAMY we had a problem on the site yesterday that caused this issue

**Comment by MoreirArt** [comment]
> @MoreirArt did you cancel your swaps? can you try to reswap please?

Yes, I canceled. I tried the swap again a few minutes ago. It worked! Thanks!
