### ISSUE TITLE
Bug "Not for sale"

### ISSUE THREAD

**Issue by AndressaCatelan** [hicetnunc2000/hicetnunc#1209]
Hello, i made the mint of this objkt:
https://www.hicetnunc.xyz/objkt/342157

And after that I swapped, which was confirmed
TRANSACTION:
https://tzkt.io/op13ADy92Zz8FShe85ThcAYPSy8cuaZAL8TpeFNofxsVUo7u27m

But my editions appear "NOT FOR SALE"

My tezos wallet address:
tz2WfC4nd3BM6ZkY4cQx8VZ2vH35YQ9qEVVS
My profile link:
https://www.hicetnunc.xyz/andressacatelan/creations

Can you solve my problem please?

**Comment by dejureacademic** [comment]
Same problem, see issue 1208 was reported by me

**Comment by diegolazzarin** [comment]
Same problem, see issue 1208 Thanks!

**Comment by AndressaCatelan** [comment]
look what a friend sent me:
https://pbs.twimg.com/media/E_5ou6aVkAAtnBk?format=jpg&name=medium

**Comment by dejureacademic** [comment]
After "batch cancel", can we swap again? And will we face same problem? Must we pay again and again mint fee, gas fee, swap fee, cancel fee? Any idea? HEN is starting to become a regret for me.

**Comment by densapid** [comment]
I did swap again, but it's still like it's "not for sale"

**Comment by jsom** [comment]
Same on https://www.hicetnunc.xyz/objkt/340828 - tried cancelling and swapping again but same issue.

**Comment by dewisnuartana** [comment]
hi josh, did you been charge for re-swap? I do have same question in my mind with dejureacademic (author this thread) 
up to know my objkt also still "not for sale" issue [https://www.hicetnunc.xyz/objkt/341251](url)

**Comment by violetforest** [comment]
There was a site issue on HEN yesterday where things were automatically swapped onto V1 instead of V2. You can cancel the V1s and then reswap them
