### ISSUE TITLE
I cant burn my nft, theere is people have hacked my 2 drop on H=N

### ISSUE THREAD

**Issue by nadhifad** [hicetnunc2000/hicetnunc#1212]
I get an error at 2 nft drop on H=N, someone has taken both of my artworks so I can't swap or burn. on the H=N website  its always said "Not For Sale". and I can't burn both of my works myself.
this person: 
https://www.hicetnunc.xyz/tz/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/collection
https://www.hicetnunc.xyz/tz/KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq/collection
both of them already stoled my nft work and I cant do anything.

- profile link : https://www.hicetnunc.xyz/nadhif/creations
- tezos wallet address : tz1c19p7xTGoqkrPZf5KgtJii1pQfdfD3Buw
- objkt #'s that are being affected : OBJKT#342370 and OBJKT#342751

I need your help to fix this or burn both of my object. 
<img width="1341" alt="Screen Shot 2021-09-23 at 14 24 19" src="https://user-images.githubusercontent.com/91245328/134468972-563e31a9-6fa1-4540-87e8-c6df55894762.png">
<img width="1341" alt="Screen Shot 2021-09-23 at 14 23 46" src="https://user-images.githubusercontent.com/91245328/134469004-67d8d8e4-147e-4cd5-89aa-dc7d41cbffb0.png">

PLEASE HELP ME.
Thanks

**Comment by yusufziyaunel** [comment]
Hey same issue is occured to me too. I think the objekt holder one of hic et nunc's worker address. But it is still a problem because we can't sell it or we can't manage it. If one of hic et nunc developer helps us, it would be perfect. It stucked here.

> tezos address: tz1bcaZTEBjHA3Uy6TmsD2R5jhBeyoGNkCgR

> objkt link: https://www.hicetnunc.xyz/objkt/341699

> objkt number: OBJKT#341699
![problem](https://user-images.githubusercontent.com/37000658/134474073-b3fab009-8d75-47ba-b505-7b95060590e9.png)

**Comment by nadhifad** [comment]
Sabar mas hehe

**Comment by violetforest** [comment]
http://hicdex.com/objkt?objkt=342370
https://hicdex.com/objkt?objkt=342751

@nadhifad this tool shows that those objkts are being owned by objkt.com. have you used objkt.com to manage your assets?

@ujubu you need to cancel your swaps and then reswap them. 
![swapv1](https://user-images.githubusercontent.com/8921838/134564228-62f411e3-03ba-42ce-a29a-9e90cd415dcb.PNG)

**Comment by nadhifad** [comment]
yes I have do thaat, but im still cant burn that

**Comment by violetforest** [comment]
you can only burn something if its not swapped. you have to cancel all swaps before burning.

this is because the OBJKT is sent from your wallet to the HEN escrow wallet when you swap. When you cancel the swap it comes back to your wallet and then you can burn it.

**Comment by nadhifad** [comment]
<img width="1673" alt="Screen Shot 2021-09-24 at 12 43 15" src="https://user-images.githubusercontent.com/91245328/134624171-5ee56702-3393-4456-ba49-bbe09583b591.png">

<img width="1673" alt="Screen Shot 2021-09-24 at 12 43 00" src="https://user-images.githubusercontent.com/91245328/134624186-1074bf29-5ddc-4a2e-9a58-02e8f9de19aa.png">

yees im already do that, I have cancel the swap but ypu cann see that. Idk why please seee the image that I send

**Comment by violetforest** [comment]
@nadhifad that wallet address belongs to objkt.com. Are you sure you weren't putting it for sale there?

**Comment by melMass** [comment]
As explained by violet addresses starting with KT are contracts, meaning these tokens are currently listed (swapped) you need to unlist first
