### ISSUE TITLE
I updated the price of the NFT, now it's not visible anymore. 

### ISSUE THREAD

**Issue by megascal** [hicetnunc2000/hicetnunc#1215]
Hello everyone! I just did something stupid, I put the wrong price. 
Then I canceled the listings, I saw the approval on my wallet and I did the listings again, with the right price. 
Now If I go to the NFT page it doesn't load it, and it's not visible on the creations anymore. 
I even saw that someone bought it, luckily with the updated price.

Profile link: https://www.hicetnunc.xyz/Joe%20Tamponi/creations
TZ wallet address: tz1bq1uTvHvEP9Hzc8uyR7vnHFQHC7kxU9FP
OBJKT number: 345841
Page that doesn't load anymore: https://www.hicetnunc.xyz/objkt/345841

I already tried to sync the wallet again. What should I do? 
Thanks a lot

**Comment by violetforest** [comment]
https://hicdex.com/objkt?objkt=345841

its best to wait a couple of hours to see if the issue clears up on HEN's side but in the meantime you can use this tool and see that it was in fact swapped with HEN

**Comment by megascal** [comment]
That's weird, because here on Henext (https://www.henext.xyz/o/345841)  is still at 20tez, but I sold the pieces at 5 tez, which was my original idea and the last update I did! 

The sequence was: mint -> swap at 20 tez -> erase the listings -> swap at 5tez

**Comment by violetforest** [comment]
are you sure you  sold that piece?

https://hicdex.com/sold?address=tz1bq1uTvHvEP9Hzc8uyR7vnHFQHC7kxU9FP

This doesn't show that it was sold

**Comment by megascal** [comment]
<img width="460" alt="Screenshot 2021-09-23 at 20 50 20" src="https://user-images.githubusercontent.com/91283319/134566518-bd6cb20f-e3f9-44e4-b7a6-d1ba97fa30da.png">

Yeah check this out, I don't have other pieces on HEN! I guess that was the hobo's history, shows even the sales from the secondary market. 

I guess that the one with no sales was the one with the 20tez contract, which had no sales because I canceled the listings. But I can't understand how could have been sold since the page is not visible

**Comment by violetforest** [comment]
Looks like there could be problems with the indexer not being caught up, the issue should resolve itself within 24 hrs at most.

I checked and you're right that the transactions came from that objkt#345841

**Comment by megascal** [comment]
Now it's back, but it has the old 20 tez price. Pretty messed up

**Comment by violetforest** [comment]
looks like the indexers caught up and its at 5 tez again

**Comment by violetforest** [comment]
gonna close this, sorry about the trouble. let me know if you still need more help.
