### ISSUE TITLE
Scam https://www.hicetnunc.xyz/thepprojecturs

### ISSUE THREAD

**Issue by HyunHur** [hicetnunc2000/hicetnunc#1218]
Hi

This site is scam. please delete it.
https://www.hicetnunc.xyz/thepprojecturs

official Website of The Project URS is this: On Opensea.
https://opensea.io/collection/theprojecturs 

Thank you

**Comment by bearcthulhu** [comment]
account has been restricted so it can no longer sell these.

Please if you can join the HEN discord and report copyminters in the Support > report-copyminters channel
