### ISSUE TITLE
Collect Problem Only in My Profile

### ISSUE THREAD

**Issue by king-mograp** [hicetnunc2000/hicetnunc#1219]
**Describe the bug**

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link : https://www.hicetnunc.xyz/king.mograp/creations
- tezos wallet address : tz1fAhH4k4UEw74AKNEnDqFZWbzqtizui78h
- objkt #'s that are being affected : https://www.hicetnunc.xyz/objkt/341543

**To Reproduce**
1. Go to 'my pofile link'
2. Click on 'collect for 0.8 tez'
3. Accept the transaction

**Expected behavior**
normaly they can collect it like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/91358711/134756867-40a7a9b5-9600-44c4-a486-bebc8fb04b2b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : Version 94.0.4606.61 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Version : Version 94.0.4606.61 (Official Build) (64-bit)

**Additional context**
in link bellow : 
https://www.henext.xyz/tz1fAhH4k4UEw74AKNEnDqFZWbzqtizui78h
my objkt is already sold out
Please Fix this issue

**Comment by violetforest** [comment]
1 ed of the objkt is owned by the follow address:
https://www.hicetnunc.xyz/tz/KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq/creations

that address is the objkt.com wallet.

did you put it for sale on objkt.com? if thats the case then you can only buy it on objkt.com
