### ISSUE TITLE
OBJKT not Transferred - BUG -

### ISSUE THREAD

**Issue by paulpsky** [hicetnunc2000/hicetnunc#1220]
OBJKT not transferred to my account after purchase.

https://www.hicetnunc.xyz/quasi
tz1eBtjYSRqfwbGBBxtSVej1hp14pch5XfHZ
https://www.hicetnunc.xyz/objkt/228512

I can see on block explorer the transaction and funds going to artist and HEN but the asset has not appeared in my account!

Here is the block explorer link:
https://tzkt.io/opBhbcdiXyaQTAk6tdo9tRbxpxzKzez1xMar1CiLKk1UgemJutE

**Comment by violetforest** [comment]
hey i see this in your collection, the problem is that its taking a while to load on the collection page (its all the way at the bottom). and it shows on the objkt that you purchased it.
