### ISSUE TITLE
Mint “aplied” but it can't appear on h=n

### ISSUE THREAD

**Issue by Junieawanbagaskara** [hicetnunc2000/hicetnunc#1221]
Hello, I made Mint from this Objkt:
https://www.hicetnunc.xyz/objkt/355894.

In this "Aplied" Recent Activity:

https://tzkt.io/ookwwWaoeAwxVBzBWokwM4wmhbv48F9Cogc7hJwZxr8FKMSTreq

But in Manage Profile Hicetnunc yet, how is this?

**Comment by crzypatchwork** [comment]
this usually is a indexer lag. the indexer is currently up to date so everything should be working properly.
