### ISSUE TITLE
The OBJKT I minted a few hours ago does not appear in my creations

### ISSUE THREAD

**Issue by ggustin93** [hicetnunc2000/hicetnunc#1222]
**Describe the bug**
The OBJKT I minted a few hours ago does not appear in my creations (but does in my Tezos wallet)

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link: https://www.hicetnunc.xyz/gus/creations
- tezos wallet address: KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton
- objkt #'s that are being affected: https://www.hicetnunc.xyz/objkt/355875

**Comment by ephraimtan25** [comment]
Same here with
https://www.hicetnunc.xyz/cup-ramen/creations
tezos wallet address: tz1Yg6JXXREDHoef21A7N4wSUBnwgM5tBWbT

**Comment by diegolazzarin** [comment]
Same problem here! 
https://www.hicetnunc.xyz/diego_lazzarin/creations

**Comment by ggustin93** [comment]
Disconnecting from Tezos wallet + deleting the cookies did the trick for me

**Comment by crzypatchwork** [comment]
https://github.com/hicetnunc2000/hicetnunc/issues/1221 if possible could we not create the same issues all over and over again and read which responses were given to similar issues?
