### ISSUE TITLE
Impossible to swap OBJKT

### ISSUE THREAD

**Issue by craackland** [hicetnunc2000/hicetnunc#1223]
I have been trying to swap two objkts for weeks using windows Chrome and Temple wallet on Computer windows 10. No success.  jpg file format

Please give us your profile link, tezos wallet address, and objkt numbers

profile link: https://www.hicetnunc.xyz/craackland/creations
tezos wallet address: (Temple) tz1bq38cA7B3oSF7V9HgvFCbMMt44hRADFt6
objkt #'s that are being affected: OBJKT#340298 & OBJKT#117713
To Reproduce

Go to 'manage assets'
Click on 'objkt #340298'
Click on 'add my OBJKT amount & my price per OBJKT'
Click on 'swap'
Result: Sending request to Temple wallet
No error message. 
Expected behavior
I expected the objkt to swap, but nothing happened.

Screenshots
![image](https://user-images.githubusercontent.com/72502069/134776521-c99c8676-b413-48ac-988a-5650c042f957.png)

Desktop (please complete the following information):

OS: [e.g. iOS] WINDOWS 10
Browser : Chrome
Version [e.g. 22] Version 94.0.4606.61

Additional context
Please include the wallet address (tz...) and/or the OBJKT number.
![Capture d’écran 2021-09-25 172226](https://user-images.githubusercontent.com/72502069/134776673-7b20606e-612a-4c9b-932c-87b8888875d7.png)

**Comment by crzypatchwork** [comment]
could you cancel the objktswap_v1 and retry?
