### ISSUE TITLE
my hen account has been closed! why.

### ISSUE THREAD

**Issue by atiexe** [hicetnunc2000/hicetnunc#1225]
https://www.hicetnunc.xyz/ati.exe

I was just buying art. I haven't published any work yet. right now "restricted account"

Can you open my hen account?

**Comment by violetforest** [comment]
Hello, it looks like your account has been flagged a copyminter account. Please go into the #report-copyminters channel in the Discord and state your case so we can remove the flag. https://discord.gg/CWXGJgV5
