### ISSUE TITLE
HEN requests do not reach Kukai

### ISSUE THREAD

**Issue by LSileiko** [hicetnunc2000/hicetnunc#1228]
The problem:
A few days ago I wanted to buy a mint in Hen and the request never reached kukai. Today, 3 days later, I wanted to mint an object and the request did not arrive either.

**Please give us your profile link, tezos wallet address, and objkt numbers**
https://www.hicetnunc.xyz/leonelsileiko/creations
tz1W42Q5zyMa3EchV2SVXVnbsVCNLvk4kUQX

**Comment by violetforest** [comment]
did you have your kukai tab open next to your HEN tab?

**Comment by crzypatchwork** [comment]
fixed with https://github.com/hicetnunc2000/hicetnunc/pull/1252
