### ISSUE TITLE
Burned nft but not really burned

### ISSUE THREAD

**Issue by capactiyvirus** [hicetnunc2000/hicetnunc#1240]
**Describe the bug**
So I minted an nft this morning and first i got a meta data queue bug which i cant show right now but the image was white and said meta data on it, i got this before so i decided im gonna burn it and re mint. When i did that i got a weird issue after the image was minted. 

The image wouldnt swap it kept giving me a transaction failed issue, its still on my profile and if i try to burn it it says this 

![image](https://user-images.githubusercontent.com/46537188/135155316-5d6f86c5-0354-4755-a5e7-5e6cb718f74c.png)

which i understand its not in my wallet but it shows up on the hicetnunc site like i do have it

![image](https://user-images.githubusercontent.com/46537188/135155392-8bfb4e2a-5477-40a2-807c-3065482f5f6f.png)

The second image is the burned one and the first one is the regular minted one that i can swap.

this is the second one 
![image](https://user-images.githubusercontent.com/46537188/135155466-f40b9c06-242c-4afe-a107-16b9718cfe66.png)
as u can see it says x/12 

this one is the real version
![image](https://user-images.githubusercontent.com/46537188/135155509-63a7fff4-58c3-4fa3-bf97-ceff7c413c98.png)
it has some value out of 12 since i sold some

I dropped these links to show the contracts of what happend i hope this helps 
https://tzkt.io/ooRgvXNEgh6CyhMMwcHU2QX7zcD1FTxxE6hH7YqFeQvEsB8DhDt/26724130/50

https://tzkt.io/onoGFeHE3wL77SK8UAqFvsH1fPiq1CdVGiK6v8S5mGRQpMe25dm/26724131

at the bottom of this page you can see the tokens i burned with the object 
![image](https://user-images.githubusercontent.com/46537188/135155905-bc3975a9-f3bb-4567-990c-efc4ccdfeedf.png)

https://tzkt.io/tz1SFQD7VLwDVkiWBmyeR8PoyFaifRtaeKTa/tokens

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link : https://www.hicetnunc.xyz/capacityvirus/creations
- tezos wallet address : tz1SFQD7VLwDVkiWBmyeR8PoyFaifRtaeKTa
- objkt #'s that are being affected : OBJKT#368958

**To Reproduce**
I have no idea how to reproduce this all ik its the image is stuck on my profile and i cant burn or remove it. 

**Expected behavior**
It was supposed to burn and be removed from my profile

**Screenshots**
I posted ss above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chome 
 - Version newest up to date

**Smartphone (please complete the following information):**
Did not mint on phone or use phoen

**Comment by crzypatchwork** [comment]
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5#troubleshoot
