### ISSUE TITLE
Restricted account

### ISSUE THREAD

**Issue by Degenadis** [hicetnunc2000/hicetnunc#1242]
Hello,

Please advise what must i do so you remove the restrictions on my account?
This is my profile https://www.hicetnunc.xyz/degenadis/creations
Thanks

**Comment by violetforest** [comment]
Hello, it looks like your account has been flagged a copyminter account. Please go into the #report-copyminters channel in the Discord and state your case so we can remove the flag. https://discord.gg/CWXGJgV5
