### ISSUE TITLE
Restricted account

### ISSUE THREAD

**Issue by Meinhast22** [hicetnunc2000/hicetnunc#1244]
My account has been restricted. Please advise why and how I can correct it?

https://tzkt.io/oohPuDpjtxWGuLTyvD36e3TshyRsWLADeNG5CfyitJA9K7pTzdN

**Comment by violetforest** [comment]
Hello, it looks like your account has been flagged a copyminter account. Please go into the #report-copyminters channel in the Discord and state your case so we can remove the flag. https://discord.gg/CWXGJgV5
