### ISSUE TITLE
I reset my pc and forgot my Seed.

### ISSUE THREAD

**Issue by EddgaArtist** [hicetnunc2000/hicetnunc#1245]
I want to remove the old account and all of my works because I really forgot the Seed phrase. My old account is https://www.hicetnunc.xyz/eddga_art. Now I didn't create a new one yet so is it possible to transfer assets to my new account? if not then can u remove my old account so I can create and repost my works. Thank you.

**Comment by violetforest** [comment]
Hey, unfortunately losing the seed phrase in the crypto world means theres nothing that can be done.

At the moment we cant remove your account to stop showing up on HEN but we can flag it as copyminter so it says "restricted account".

**Comment by EddgaArtist** [comment]
Oh, that's ok. Thank you for helping :) please flag it as copyminter, and if you can do please delete my name so people won't confusing.

**Comment by EddgaArtist** [comment]
How long will it take to flag my account as copyminter?

**Comment by violetforest** [comment]
Hey, do you have your account flagged as copyminter you need to go to the discord and state why you want your account flagged in the #report-copyminters channel
