### ISSUE TITLE
resrticted account

### ISSUE THREAD

**Issue by hicetgraph** [hicetnunc2000/hicetnunc#1246]
i do not know why my account got restricted
for verify my account my twitter is on my profile and link of my work on hicetnunk is available on my twitter
please help me

profile link - https://www.hicetnunc.xyz/hicetgraph/creations
tezos wallet address - tz1cMBogsXWthkh29KDVCNEqFzSzbPdK2gSk

**Comment by violetforest** [comment]
Hello, it looks like your account has been flagged a copyminter account. Please go into the #report-copyminters channel in the Discord and state your case so we can remove the flag. https://discord.gg/CWXGJgV5
