### ISSUE TITLE
Screen stuck 'preparing OBJKT'

### ISSUE THREAD

**Issue by copyplanetdotxyz** [hicetnunc2000/hicetnunc#1248]
**Describe the bug**

Enough Tezos in my Kukai Wallet. All in Sync. 
Trying to mint new NFT. Screen is stuck 'preparing OBJKT' - Request sent to Kukai Wallet ( not sending ) 

![Uploading Screen Shot 2021-09-30 at 8.40.26 AM.png…]()

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link ( https://www.hicetnunc.xyz/copyplanetdotxyz/creations )
- tezos wallet address ( tz1ezzPv77tQ3ybWmqAXqxri8bTFke2qiH7V )
- objkt #'s that are being affected 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by jeffromeo123** [comment]
I have the same issue.

**Comment by violetforest** [comment]
hey, your screenshot is not loading @copyplanetdotxyz 

you can also try requesting help in the discord in the #help channel https://discord.gg/Yx6UN5SkCd


is your kukai tab open next to your HEN tab? can you try resetting your browsers cache and setting up your kukai tab and HEN?
can you try temple wallet? have you tried temple wallet? you can import your wallet into temple with the same seed phrase

**Comment by copyplanetdotxyz** [comment]
hey, thank you for the reply and info 
i did a full browsers cache and it works now 
cheers violet forest :)
