### ISSUE TITLE
stuck in failed transaction after collecting objkt

### ISSUE THREAD

**Issue by pipindanupin** [hicetnunc2000/hicetnunc#1249]
Collected a drop on hen, in the midst of inputting my credentials onto kukai, there was a problem with my connection but eventually the operation showed up as pending. After a while I noticed that I didn't have the Objkt in my wallet and I checked and it says "failed transaction" as seen here:
https://tzkt.io/oo2nG4R2J1MrbpWwFg7R5y2hMfzdm39FGbEBQrh7GQj8UMFSNbM/15048701

_"Script failed
A FAILWITH instruction was reached 

Script runtime error
Toplevel error for all runtime script errors"_

Any idea why this could happen? and how to get the tz back if possible? Or prevent it from happening in the future?

**Comment by violetforest** [comment]
hey, i would need more context, like objkt number, what wallet you were using etc

**Comment by pipindanupin** [comment]
> hey, i would need more context, like objkt number, what wallet you were using etc

Hi okay so the details are:
Objk number: #375762
Wallet: Kukai

Let me know should I provide anything else

**Comment by skenaja** [comment]
Looks like it had already sold out when you submitted the purchase request
