### ISSUE TITLE
my objekt can't swap, and an extra mint was created in another HEn collection!

### ISSUE THREAD

**Issue by jeansaucisse** [hicetnunc2000/hicetnunc#1253]
First, excuse my broken english, i'm french (and tired ^^')

When I've minted my new Objkt(https://www.hicetnunc.xyz/objkt/376453)  another one was created in another wallet as it show when I go to listing https://www.hicetnunc.xyz/tz/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/creations
 Since that I can't swap my object to put it on sale!

**Please give us your profile link, tezos wallet address, and objkt numbers**

- https://tzprofiles.com/view/tz1RTyG19vPkLKBghpvn14gzkJNfqDuNiBFu
- tz1RTyG19vPkLKBghpvn14gzkJNfqDuNiBFu
- https://www.hicetnunc.xyz/objkt/376453

**To Reproduce**

1.I've been on my collection to click on my new object and went to swap it
2. i've clicked on swap, put 6 on 7 to Sell at a price of 2 $Xtz
3. then I've clicked on swap; it communicate with my wallet but then
4. I receive this error :_Parameters Invalid Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again._

**Expected behavior**
It should be on sale

**What 'ive noticed**

Someone is listed as owning one of my mint, even if it wasn't even on sale, this adress :
https://www.hicetnunc.xyz/tz/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/collection
 https://tzkt.io/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/operations/

I don' really know why, and how, but it happened directly after the minting
in the other account(https://www.hicetnunc.xyz/tz/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/collection) collection there are some objkt that appeared to be minted in the same lapse of time

![error hen 2](https://user-images.githubusercontent.com/91661354/135422390-80ea657f-e283-4f8e-a812-8f7063e1a927.jpg)

I receive a message on my wallet saying "Simulation error: A FAILWITH instruction was reached {"int":"706"}"

![error wallet hen 3](https://user-images.githubusercontent.com/91661354/135423406-e3be13b2-7e78-42c0-a851-b91895709d08.jpg)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Firfox
 - Version [92.0.1]

**Smartphone (please complete the following information):**
 -not on smartphone

**Additional context**

I've firstly tried to add more funds in my wallet, but it did'nt work, then i saw the extra mint in another wallet and create the account here to submit what happened!

Any clues? Thank you for your time and response and help!

**Comment by jeansaucisse** [comment]
Oh, I forgot another screenshot:
![bug hen 4](https://user-images.githubusercontent.com/91661354/135427817-876c8183-a399-43fa-8211-dea221f8d287.jpg)
: 

Thanks for the help!

**Comment by jeansaucisse** [comment]
After a nap I update the problem :

The extra account in listings doesn't show anymore, but the swap of my work still doesn't work : in my kukai wallet it still says "Simulation error: A FAILWITH instruction was reached {"int":"706"}" 

My work inside the other HEN account collection is not showing anymore btw.

I will try to burn one to see if it fix the issue, but even if it solve the problem, I would be thankfull for the help! I wish to understand why did it happen! :)

_Edit: Ok, the Burn did'nt work, it send the same "Simulation error: A FAILWITH instruction was reached {"int":"706"}" in wallet and "Parameters Invalid Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again."in the HeN interface._

**Comment by jeansaucisse** [comment]
And now I've found it there !!  It's listed in this HEN account as his creation and so I can't swap my own work!

Does anyone have an explanation please?

![my work in this collection as creation!!!](https://user-images.githubusercontent.com/91661354/135524582-50605b57-a8d6-49de-b389-1c4deb76132b.jpg)

**Comment by jeansaucisse** [comment]
Here is the account of asmarsal on tzkt. io : https://tzkt.io/tz1QNKFfaBJk1RU5MxLWUZDBk1p6BypXo5rB/operations/
his HEC https://www.hicetnunc.xyz/asamarsal/creations
and his twitter : https://twitter.com/asamarsal

**Comment by jeansaucisse** [comment]
I was able to finally swap my work ( I don't know why it finally worked )  but my art objkt https://www.hicetnunc.xyz/objkt/376456 
is still listed in his creations collection (https://www.hicetnunc.xyz/asamarsal/creations) under the same objkt number!

**Comment by jeansaucisse** [comment]
here are the screenshots : 
![Sans titre-1](https://user-images.githubusercontent.com/91661354/135532696-2003a174-eaa8-4420-b765-6f36a3cd1a41.jpg)
![Sans titre-2](https://user-images.githubusercontent.com/91661354/135532825-f474890f-c882-4899-9d47-db3758ba8a34.jpg)


It obviously happened while minting

**Comment by jeansaucisse** [comment]
And another proof that it's my work, my name tag is here

![Sans titre-3](https://user-images.githubusercontent.com/91661354/135534168-1cecc290-a280-432d-aed4-4bae8d27db15.jpg)

**Comment by violetforest** [comment]
https://www.hicetnunc.xyz/tz/KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU/creations

this address is the objkt.com wallet address. were you trying to put this objkt for sale on objkt.com?

**Comment by jeansaucisse** [comment]
Hi & thx for the response!

No I didn't ; I've only passed through hicetnunc.xyz so far...I'm quite new to Nft so I don't disperse myself much yet! What I found the most weird is the fact that the minting was like "cloned" during the process.

**Comment by jeansaucisse** [comment]
So is there a way to burn my artwork from this copyminter wallet? I'm eager to be able to begin to promote my work without risking any problems! 

Also there is many things I don't understand  in this situation... (how can his name be on the same object number, why in the Objkt.com wallet? what is the "Simulation error: A FAILWITH instruction was reached {"int":"706"}") and so on )

I'll be glad if someone can explain to me what is happening! Is this a hack?

**Comment by jeansaucisse** [comment]
The problem seems to have been solved with another objkt number on my edition (thank you mysterious helper), so I will close this thread !

However it would have been nice to understand what happened! my drawing("the penitent") is still in asamarsal account on HEN, (account who has been renamed exluminate : https://www.hicetnunc.xyz/exluminate )

**Comment by jeansaucisse** [comment]
Well it  beginned again; my art  was unswapped and do simulation error: A FAILWITH instruction was reached {"int":"706"}")

Good news is it's not in exluminate/asamarsal wallet anymore, but it was unswaped and i can't put it back ; it was switched to the number of the beginning again : https://www.hicetnunc.xyz/objkt/376453 and the newest one who has worked in between don't work...(https://www.hicetnunc.xyz/objkt/376456)

 I really don't understand anything of what is happening...  please help...

**Comment by jeansaucisse** [comment]
and it beginned again...  my work was unswapped and disappeared  again .... being  put back in the asamarsal/exluminate account (https://www.hicetnunc.xyz/objkt/376453)  ; this  is driving me nuts because it is also fucking up my art sale ; this work was already sold to some and it dispappeard for them too!

**Comment by jeansaucisse** [comment]
I had  a response on the discord, it is an index error, thx to mel for the help!
