### ISSUE TITLE
Simulation error: A FAILWITH instruction was reached |  WrongCondition: (sp.amount == sp.mul(sp.fst(sp.ediv(self.data.swaps[params.swap_id].xtz_per_objkt

### ISSUE THREAD

**Issue by Sam-Blade** [hicetnunc2000/hicetnunc#1254]
**Describe the bug**

I keep getting an error message when trying to purchase this NFT: 377141 
The creator cannot cancel the listing nor burning it and several other users tried to purchase the listing using different wallets and browsers. 

Simulation error: A FAILWITH instruction was reached | WrongCondition: (sp.amount == sp.mul(sp.fst(sp.ediv(self.data.swaps[params.swap_id].xtz_per_objkt, sp.mutez(1)).open_some()), sp.mutez(1))) & (self.data.swaps[params.swap_id].objkt_amount != 0)

**Please give us your profile link, tezos wallet address, and objkt numbers**
- profile link : https://www.hicetnunc.xyz/objkt/377141
- tezos wallet address : tz1fgnBqgTGNsWm1Nnob8Dg7icouV3SYEGvB
- objkt #'s that are being affected :  377141 

**To Reproduce**
1. Go to ' https://www.hicetnunc.xyz/objkt/377141'
2. Click on 'Collect for 1 tezos.'
3. Error will pop up in the right hand corner of Hicetnunc and on your kukai wallet.

**Expected behavior**
No sale and error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/34589310/135478674-c75484d2-7d73-49cd-8253-631b297c418e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: the latest

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/34589310/135481594-22382867-4dbc-4ae9-8c09-aca5546cdc4b.png)

Please include the wallet address (tz1fgnBqgTGNsWm1Nnob8Dg7icouV3SYEGvB) and/or the OBJKT number: 377141'

**Comment by violetforest** [comment]
hey, are you sure you have tez in your wallet? i just collected the objkt with no problem using kukai

**Comment by Sam-Blade** [comment]
I think someone whose capable of posting on GitHub would know if they have Tez in their wallet or not 🤷🏽‍♂️😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by violetforest** [comment]
you would be surprised 😵‍💫 you didnt have any luck in the discord? tag @vjthor

**Comment by violetforest** [comment]
also, have u tried temple wallet? import your wallet with the seed phrase
