### ISSUE TITLE
My OBJKT has disappeared!

### ISSUE THREAD

**Issue by Patstini** [hicetnunc2000/hicetnunc#1256]
Wallet: 
https://tzkt.io/tz1i7g7SfizixusXBF2euT5pgYjXGygAbCvg
User:
https://www.hicetnunc.xyz/Patstini/
Assets:
https://www.hicetnunc.xyz/Patstini/creations
OBJKT (Missing)
https://www.hicetnunc.xyz/objkt/377254
Browser:
Chrome and Safari
OS:
OSX 10.14.6
Detail:
I minted an OBJKT (see above) on Hicetnunc at 1500 GMT. It subsequently disappeared about an hour later. 

Patstini

**Comment by crzypatchwork** [comment]
await for indexers to catch up
