### ISSUE TITLE
Restricted account

### ISSUE THREAD

**Issue by SolNFTs** [hicetnunc2000/hicetnunc#1261]
Hi there today I've noticed you restricted my account without even notifying me

https://www.hicetnunc.xyz/solart/creations

I contact you in discord and still didn't get any response

All the works minted in hen is my arts

It's my only collection 

You can check my git webpage also

Https://solnfts.github.io

**Comment by crzypatchwork** [comment]
I'll review it, sorry about the inconvenient. Restricting addresses against copyminters happens manually and accidents can happen.
