### ISSUE TITLE
Missing art

### ISSUE THREAD

**Issue by yojyo333** [hicetnunc2000/hicetnunc#1262]
I minted a piece by fiedler.jpeg and its gone. My wallet is tz1S9bpHdTwnQegkQhdHueJ2uecWS2yay21b and the piece was OBJKT#41836 PL∆=c˚MØM. In the history I see when I listed it. swap 2021-06-13T00:01:26+00:00
 tz1S9...ay21b
1 ed. 500 tez
Please let me know how I can get it back in my wallet.

**Comment by crzypatchwork** [comment]
the editions count seems about right. under listings you should be able to cancel the old swap named as 'OBJKTSWAP_V1' as the v1 contract is deprecated.

**Comment by joaoricardocefalialmeida** [comment]
same here I can't find my minted objkt in my profile
