### ISSUE TITLE
Hen profile is not working 

### ISSUE THREAD

**Issue by Elmitodaniel** [hicetnunc2000/hicetnunc#1263]
my hen profile is not working I cannot see my creations or my collection i do not know why my account got restricted
for verify my account my twitter is on my profile and link of my work on hicetnunk is available on my twitter
please help me

profile link - https://www.hicetnunc.xyz/TheMyth
tezos wallet address - tz1TiWU3EHwzg17XqwhswaAmgEBXWF5hTNdR

**Comment by ddriftter** [comment]
hi there, same thing just happened to me. I cannot see my creation, also I am having problems updating my profile, it doesnt seem to be saving. It did once, but when i came back to the site it was gone, same as my creations. 

https://www.hicetnunc.xyz/mhinter
tezos address - tz1irzr9qMdeg3e6ukbo2TaeEBbFv57iUcYo

**Comment by amregulus** [comment]
İts same as for me.my account Verifyed but my info dosent appear on my profile, and icant update it at all( name,avatar anything) the SAVE PROFİLE button dosent work.
https://www.hicetnunc.xyz/tz/tz2HSUDYPdT2eyDd9T8GssdAG1MGUqrwjHw1
tezos add: tz2HSUDYPdT2eyDd9T8GssdAG1MGUqrwjHw1

**Comment by Vrob7** [comment]
Hello There ! Bit of a problem for me as well : I can't edit my profile, despite it's connected to my wallet, when I confirm via the wallet, it says it failed... And despite I have Tezos on my wallet AND I've been deducted a small amount of xtz for that...
So basically, I paid for nothing... Any idea how to solve it ? Thanks a lot

**Comment by Vrob7** [comment]
Okay I fixed the issue by restarting my computer ^^
Sorry !

**Comment by Titani7174N** [comment]
hello.. Why is my account suddenly restricted?https://hicetnunc.art/7174n
