### ISSUE TITLE
Cannot mint NFT because "An Error Occurred"

### ISSUE THREAD

**Issue by dadmancat** [hicetnunc2000/hicetnunc#1267]
Hello,

I am trying to mint my NFT but it keeps failing every time and it says An Error Occured".
I changed the web browser and network as well but the same issue ticks. It always fails at the stage of after previewing NFT.

Only a possible reason that I suspect is, that I wrote some foreign language and letters (other than latin alphabets) in the description. Hicetnunc does not say it causes an error, but would it be the reason?

I would love to hear your assistance.
Thanks.

**Comment by GIOVANNIDEAMBROSIO** [comment]
this morning I tried to mint an object without any description, or title or other, and i get the same error...so it may be an error related to those description fields.

**Comment by daannh** [comment]
Hi, I'm having the same issue. I signed up 3 days ago, collected 4 pieces fine, but trying to mint I get the same error. I've tried different browsers and also PC and macbook  
account: https://www.hicetnunc.xyz/dannh

(I just noticed one of the pieces I collected is now a 'restricted OBJKT' from a restricted account, maybe this is the issue??)
