### ISSUE TITLE
In an Interactive OBJKT determine if viewer owns a copy of the object

### ISSUE THREAD

**Issue by torinmb** [hicetnunc2000/hicetnunc#1273]
With the interactive website OBJKTs you currently have the ability to get the viewer and creator's wallet id. Is it also possible to have a flag passed through the URLSearchParams to determine if the viewer owns a copy of the object and potentially how many they own? 

Obviously, this isn't the most secure method because someone could inspect the page and manually change the query parameters on the iframe(if you have a secure way that'd be amazing), but this would allow creators to make a unique experience for someone that owns a copy of the object.

**Comment by pwetherbee** [comment]
Using the hicdex api (which is allowed by HEN) you can query the objkts that an address has collected, and search for the objkt ID in the result. https://hicdex.com/collector-gallery

**Comment by pwetherbee** [comment]
```javascript
const query = `
  query collectorGallery($address: String!) {
    hic_et_nunc_token_holder(where: {holder_id: {_eq: $address}, quantity: {_gt: "0"}, token: {supply: {_gt: "0"}}}, order_by: {id: desc}) {
      token {
        id
      }
    }
  }
`;

async function fetchGraphQL(operationsDoc, operationName, variables) {
  const result = await fetch("https://api.hicdex.com/v1/graphql", {
    method: "POST",
    body: JSON.stringify({
      query: operationsDoc,
      variables: variables,
      operationName: operationName,
    }),
  });

  return await result.json();
}

async function doFetch(address) {
  const { errors, data } = await fetchGraphQL(query, "collectorGallery", {
    address: address,
  });
  if (errors) {
    console.error(errors);
  }
  const result = data.hic_et_nunc_token_holder;
  console.log({ result });
  return result;
}

async function checkHasOBJKT(id, address) {
  const objkts = await doFetch(address);
  return !!objkts.filter((objkt) => objkt.token.id == id).length;
}

const run = async function () {
  const objktID =  1234//your objkt ID
  const viewerAddress = ""; //the viewers address
  const hasOBJKT = await checkHasOBJKT(objktID, viewerAddress);
  console.log(hasOBJKT);
};
run();
```

**Comment by torinmb** [comment]
Thank you! This is super helpful. 

Just to confirm. Is it possible to run this query inside an OBJKT? Based on the description in the examples projects it sounds like all outgoing connections are blocked, but from what you're describing it sounds like you allow requests to the hicdex API.

**Comment by pwetherbee** [comment]
Hicetnunc has a list of allowed APIs that you can access here: https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs
I've been experimenting with a couple on my projects and they work! Just be aware that the hicdex api can be a bit unstable at times and I had to burn some objkts when they weren't updated properly, so make sure to test before you swap too many. The indexes eventually get resolved, but it can take a few days.
