### ISSUE TITLE
It is like this more than 24h now - Metadata on que - Please help

### ISSUE THREAD

**Issue by treedinst** [hicetnunc2000/hicetnunc#1280]
![image](https://user-images.githubusercontent.com/62435155/136568576-a5a6a96e-654c-44fe-9540-ab068c07a148.png)

**Comment by crzypatchwork** [comment]
it seems you need to swap/cancel swap those objects to debug it for now

**Comment by DocLollipop** [comment]
i have same problem now

**Comment by GIOVANNIDEAMBROSIO** [comment]
the swap solved it in my case
