### ISSUE TITLE
Cant Update my accounts İnfo

### ISSUE THREAD

**Issue by amregulus** [hicetnunc2000/hicetnunc#1282]
My account Verifyed but my info dosent appear on my profile,and i cant update it at all( name,avatar anything) the SAVE PROFİLE button dosent work in profile setting.

https://www.hicetnunc.xyz/tz/tz2HSUDYPdT2eyDd9T8GssdAG1MGUqrwjHw1
tezos add: tz2HSUDYPdT2eyDd9T8GssdAG1MGUqrwjHw1
https://twitter.com/regulus_am

**Comment by iagovrs** [comment]
i think i'm having the same problem. i started yesterday at night on hen, updated my profile and collected an objekt but none of these changes is refreshed on the site. nonetheless the xtz was deducted.
https://www.hicetnunc.xyz/tz/tz1YrkXrvZh3bR3VCRCGjYsZ8Ca3MYSun17G

**Comment by amregulus** [comment]
I've been trying for 5 days.
