### ISSUE TITLE
Metadata on queue

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#1288]
I have an issue with my last work. 

![photo_2021-10-11_20-04-42](https://user-images.githubusercontent.com/83771575/136825416-0658b09e-a810-48dc-ab22-9e55e02a1115.jpg)

https://www.hicetnunc.xyz/objkt/417818

**Comment by Wrinkledlight** [comment]
I am having this same issue as well.

**Comment by equinoccio** [comment]
Yo tambien con el mismo problema, mi primera ves minteando.  https://www.hicetnunc.xyz/objkt/421196

**Comment by PxlDdy** [comment]
I have the same issue as well. Is there a way to fix this? Or do I have to burn my mint and start over?
<img width="360" alt="Screen Shot 2021-10-13 at 5 16 18 PM" src="https://user-images.githubusercontent.com/92484385/137214394-92ee56c3-69fa-49fb-aadc-ae2b0b727ed5.png">

**Comment by mitijia** [comment]
I am having this same issue as well.
https://www.hicetnunc.xyz/objkt/433776

**Comment by mitijia** [comment]
https://www.hicetnunc.xyz/objkt/433654

**Comment by DocLollipop** [comment]
Same

**Comment by shrodin93r** [comment]
https://www.hicetnunc.xyz/objkt/430311

Same issue, file is a vector pdf.
I've minted it, burned it and reuploaded it and it bugged again.

I managed to upload another art without any problem.

**Comment by JTA1082** [comment]
Same issue here. Metadata on queue for 4 days

**Comment by crzypatchwork** [comment]
it's needed to swap the OBJKT and it will be fixed. otherwise you need to burn/remint. no ETA for fixing such issue, just this parcial fix.
