### ISSUE TITLE
burn copyminted image

### ISSUE THREAD

**Issue by dahliamania** [hicetnunc2000/hicetnunc#1289]
Hi, I'm new to HEN and bought a copyminted image by mistake. I'd like to burn it but it is restricted. Can I remove it from my collection?

**Comment by Shishkebabhabibi** [comment]
Sorry to hear you got caught. It's happened to me twice so I know how you feel. Burning fakes is a noble act so kudos to you. 

When you click on the object in HEN you should see the options Info/Listings/History/Swap/Burn. If you don't see these options you may have the object listed for sale so you need to cancel that listing first.
Clicking Burn will take you through the steps -> enter 1 as number of objects to burn -> Click burn - >Are you sure...
You can also send an object directly from your wallet to tz1burnburnburnburnburnburnburjAYjjX

Stay safe out there!
