### ISSUE TITLE
My Objkt was frozen in HEN wallet

### ISSUE THREAD

**Issue by AlexanderS98** [hicetnunc2000/hicetnunc#1301]
Hello,

I was minting a new OBJKT, this was transferred to the smart contract, but it got frozen in the HEN wallet for some reason I don't have it anymore and can't withdraw it.

I would like you to please burn or return it to me, the token ID is: #260759.

The wallet address is: KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton

This is the HEN account, there is the asset: https://www.hicetnunc.xyz/tz/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/collection

Thank you very.

**Comment by crzypatchwork** [comment]
what's your objkt id? you need to cancel all swaps in objkt swap v1 under the collectors list.

**Comment by AlexanderS98** [comment]
Objkt ID is:  #260759.

Link objkt: https://www.hicetnunc.xyz/objkt/260759

how to cancel all swaps in objkt swap v1 in collector list?
