### ISSUE TITLE
site doesnt load

### ISSUE THREAD

**Issue by mahsasafarian** [hicetnunc2000/hicetnunc#1303]
![Untitled](https://user-images.githubusercontent.com/92721224/137707309-a552a5cd-56cf-4baf-b43b-b26dfc8d6607.png)
Hi
site does not show any pictures for me.
even after 1 hour nothing has been loaded ;(
 
 please answer me via email : m.safarian2014@gmail.com

**Comment by crzypatchwork** [comment]
it might depend on your internet bandwidth we are researching for improvements
