### ISSUE TITLE
I have NFTs, that I didn't buy

### ISSUE THREAD

**Issue by Xajen00** [hicetnunc2000/hicetnunc#1308]
I had no NFTs in my account, and all of the sudden I have two, all from the same account named compdreams. I don't have any transactions in my wallet, I didn't pay for them. They popped in my "collection" section from nowhere. 
My Hic Et Nunc account: https://www.hicetnunc.xyz/tez-toucans
What to do now, I see something like this for the first time.

**Comment by violetforest** [comment]
Hey, this is not a bug. Someone "airdropped" you NFTs, it is common in the crypto world to "air drop" unsolicited things.

You can burn it or keep it.
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5
