### ISSUE TITLE
Manage Assets Page wont load

### ISSUE THREAD

**Issue by lockoutxx** [hicetnunc2000/hicetnunc#1309]
Here is the link to my page...for some reason all of a sudden, my "manage Assets page wont load. 

https://www.hicetnunc.xyz/tz/tz2UVWXhPH5rtrFWMXEySGqxfRPoZwr9byxw

I have tired numerous browsers, OS's, and even mobile. Not sure what else to do.
<img width="1028" alt="Screen Shot 2021-10-20 at 10 48 48 PM" src="https://user-images.githubusercontent.com/92902168/138203180-02c1040b-549c-45a4-a062-9febdd89e303.png">

**Comment by lockoutxx** [comment]
I can see my assets from my main wallet and Objkt, just not from HEN, 

Help Please

**Comment by tom-101** [comment]
Same

**Comment by crzypatchwork** [comment]
the system can suffer instabilities on it's live version being necessary to be patient until it stabilizes
