### ISSUE TITLE
I cant refresh my username info and I cant see my minted nft

### ISSUE THREAD

**Issue by scifinft** [hicetnunc2000/hicetnunc#1310]
https://www.hicetnunc.xyz/scifinft im having issues burning and mintint, even changing my info account / username, the trasaction was efective and confirmed, but it doesnt display any changes

**Comment by scifinft** [comment]
I already lost 0.5 tezo :S

**Comment by crzypatchwork** [comment]
the system can suffer instabilities on it's live version being necessary to be patient until it stabilizes
