### ISSUE TITLE
I have minted an item (3/3 editions), and on HEN it appears: " you own 0 edition ", thus i can not put it on sale or burn it. On OBJKT, it appears on my own account but still show " 0 owned "

### ISSUE THREAD

**Issue by tom-101** [hicetnunc2000/hicetnunc#1314]
If you need help with minting or managing assets, we ask to please wait at least 24 hours for issues to clear up. 

Here are some useful tools that you can use to troubleshoot without us in the meantime:

*See transaction history for an objkt*
https://hicdex.com/objkt

*See transaction history for your wallet address*
https://hicdex.com/sold

Please note that the discord is usually the best place to get the fastest support as there are mostly likely others experiencing the same issues as you and active HEN team members assisting with troubleshooting. Please seek help in the #help channel, and read recent dev updates in #dev-announcements. You can join the discord here: https://discord.gg/HhSYY7q5A8 

-----------------------------------------------
*Please fill out the following Bug Report Template

**Describe the bug**

**If you need help with minting or managing assets, please give us the following information**
- your profile link
- any other profile links affected
- tezos wallet address
- objkt #'s that are being affected

**Screenshots**
- screenshots of your minting process
- screenshots of profiles affected
- screenshots of the browser console (in chrome windows, press ctrl + shift + j to open the developer console)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
hey i am closing this until you please fill out the template so I can help you. Thanks

If you need help with minting or managing assets, please give us the following information

your profile link
any other profile links affected
tezos wallet address
objkt #'s that are being affected

**Comment by tom-101** [comment]
Hello Violet,

Thanks for your reply,

Describe the bug:
On sale on OBJKT, but not on HEN and displaying " Not owned " in my profile.

If you need help with minting or managing assets, please give us the
following information:

   - your profile link: https://www.hicetnunc.xyz/goldenleo
   - any other profile links affected:
   https://objkt.com/profile/tz1PnvbycnsvAHQ4gJs8ozTR2xM41T5DJi5J/activity
   - tezos wallet address:  tz1PnvbycnsvAHQ4gJs8ozTR2xM41T5DJi5J
   - objkt #'s that are being affected: N°457591

Screenshots attached.

Thank you,

Golden leo

**Comment by violetforest** [comment]
Hello, this objkt number shows that 3 are in objkt.com's escrow wallet (wallet address KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq)

Did you put your objkt for sale on objkt.com? Because it seems its in their escrow wallet. Try to cancel it from objkt.com

https://tzkt.io/KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq/operations/

**Comment by violetforest** [comment]
https://discord.gg/SXksAJQesT You can get help from objkt.com here. We are not affiliated with objkt.com

**Comment by violetforest** [comment]
more info about your objkt here https://hicdex.com/objkt?objkt=457591

If you go to hicdex.com you will see lots of useful tools to analyze your account.

**Comment by violetforest** [comment]
Describe the bug:
On sale on OBJKT, but not on HEN and displaying " Not owned " in my profile.

Since objkt.com and hicetnunc.xyz are not affiliated, you have to choose one or the other to sell something. Its either going to go into HEN's escrow wallet or objkt.com. You cant sell on both at the same time.

**Comment by tom-101** [comment]
Hi,

My wallet: tz1PnvbycnsvAHQ4gJs8ozTR2xM41T5DJi5J
All my items are well registrered on OBJKT, but still appears 0 owned like
on HEN.
I don't see the escrow wallet you mention.
Photos attached

Golden Leo

**Comment by violetforest** [comment]
I dont see the photos you attached, youll probably have to insert them with github.

this is a photo of what i see:
![Caasddpture](https://user-images.githubusercontent.com/8921838/138928563-730edf21-3feb-4179-8a43-9bea70eb6fca.PNG)

**Comment by tom-101** [comment]
Items number: #463146 / #463053 / #458287 / #458201 / #457591

**Comment by tom-101** [comment]
I Have contacted someone on Discord, the trouble is resolved.

Golden Leo

**Comment by violetforest** [comment]
what was the problem?
