### ISSUE TITLE
I bought my work when it had not even have a price?! how it can be possible :( 

### ISSUE THREAD

**Issue by atefehsoubati** [hicetnunc2000/hicetnunc#1321]
I was at the time of publishing my work and when I had not yet entered the price of the work. It made a few mistakes in the middle by the wallet, and I started publishing my work from the beginning, but in the end I did not succeed. But now I see that my wallet is empty and I bought all 5 samples of my work myself !!!!! 
Is it possible for this fee to be returned to my wallet and my work to be released?

my account is: atefehsoubati
and my work: https://www.hicetnunc.xyz/objkt/475748 

I bought 5 edition of my work and I did not even put the price on it! have it can be possible!
please help me and put my money back to my wallet.
than you

**Comment by violetforest** [comment]
can you please link to the transactions you are talking about on the blockchain explorer?

https://tzkt.io/tz1V4FZPqaincpaELFfnw9SpUQxKe7t6vtQL/operations/

I dont see where you see that you "bought 5 editions of your work"

The site shows that you own 5 but that just means you minted 5 and they are in your wallet

**Comment by atefehsoubati** [comment]
Thank you response
I pressed swap to put a price on my artwork, and there was a message about
something failing in my wallet connection ( I had enough money in my
wallet the problem wasn't about money) so I repeated it again and again.
and my last work wasn't published with price, in my managed assets.
Last time when I wanted to swap it again, I checked my wallet before and I
was shocked, wallet was empty and I checked the listing and I found out I
bought my work?!
I didn't know how it happened, because I just clicked on swap to put the
price on it.
Is it possible to put my money back in my wallet?
How can I republish this artwork again? Because  now 5 edition is sold out.

llink: https://www.hicetnunc.xyz/objkt/475748

[image: Screen Shot 2021-10-27 at 9.13.01 AM.png]

**Comment by atefehsoubati** [comment]
[image: Screen Shot 2021-10-27 at 11.08.55 AM.png]

Hello
look , there is no money in my wallet? please put it back if it is
possible. I don't want any of my work in my listings, I just want to sell
them.
I am from Iran and this bug cost me lots of money. 😭😭😭

**Comment by melMass** [comment]
You never bought your pieces back the only Tezos you payed was 0.01 to burn them.
For this kind of issue I think the discord is more appropriate 

https://discord.gg/98vCQHNz
