### ISSUE TITLE
I can't minting my first nft, the loading on screen preparing OBJKT its so long.

### ISSUE THREAD

**Issue by Mons65** [hicetnunc2000/hicetnunc#1322]
I try to minting my first artwork but its can't the loading on screen preparing OBJKT its taking to long untill 4 hours and no have any response,i have been tried 5 or 6 time to minting again since yesterday but i cant' the problems its still on screen preparing OBJKT. for the first try i use temple wallet then i try again use kukai wallet but same account.
please help for the issue !! thanks. 

![249359144_1051440962095845_1986913695313122726_n](https://user-images.githubusercontent.com/93363657/139447877-c82d7afd-2126-437b-bd67-addcf5d5ebc9.jpg)

**Comment by Mons65** [comment]
This is my link account : https://www.hicetnunc.xyz/mons

**Comment by nowhereelsestudio** [comment]
How did it go @Mons65 I having the same problem since yesterday?

**Comment by Mons65** [comment]
Its working fine, i solved the problem.
 if you use wifi connection change it with ethernet cable on your phone
with 4G/5G and using kukai wallet.
