### ISSUE TITLE
Expose edition number

### ISSUE THREAD

**Issue by santi-grau** [hicetnunc2000/hicetnunc#1328]
Not sure if this would be possible but...
For those of us that work with generative content on interactive OBJKTs would be great to get the edition number to use as a hash/parameter. This way a single OBJKT could have different outputs based on edition number.

``` 
const creator = new URLSearchParams(window.location.search).get('creator')
const viewer = new URLSearchParams(window.location.search).get('viewer')
const edition = new URLSearchParams(window.location.search).get('edition')

```
?viewer={VIEWER_ADDRESS}&creator={CREATOR_ADDRESS}&edition={EDITION_NUMBER}

**Comment by skenaja** [comment]
There are no edition numbers, each OBJKT is the same
