### ISSUE TITLE
hi, i wanna know if i can upload Shibari content to the plataform

### ISSUE THREAD

**Issue by jjcastillom** [hicetnunc2000/hicetnunc#1329]
![IMG-4671](https://user-images.githubusercontent.com/93833233/140616694-9187cb17-1084-486d-af4a-c765f33d7a7e.PNG)
 

hi, my artwork is like this, I wanna know if it will be accepted by the page?

**Comment by kylegrover** [comment]
Thanks for checking, it's always a complicated decision how to handle adult content on an open platform. We generally allow nudity and adult themes but not explicitly sexual or pornographic content. To me this work is definitely acceptable.

**Comment by kylegrover** [comment]
Closing for now. I'm not the final arbiter, anyone else is free to weigh in.
