### ISSUE TITLE
Missing twitter handle icon on profile

### ISSUE THREAD

**Issue by momomeatmaker** [hicetnunc2000/hicetnunc#1339]
Twitter handle icon missing on profile page since 24 hrs ago, I've checked my tezos profile, still linked to my twitter account

your profile link: https://www.hicetnunc.xyz/momomeatmaker

**Screenshots**

- screenshots of profiles affected

![Screenshot_2](https://user-images.githubusercontent.com/91171070/140715550-2aa2e223-1123-4e5f-8b23-52903a4caef5.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/91171070/140715501-0e82f557-e5d0-4c7a-8f03-941c85de1fce.jpg)

**Expected behavior**
Twitter handle icon should appear on my profile

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: firefox 
 - Version 94.0.1 (64-bit)

my wallet address: tz1LX2rUXBCWEhwNm13QuWtXNd761Fn8bVwm

**Comment by nowhereelsestudio** [comment]
I also have the same problem. :(

**Comment by skenaja** [comment]
I can see twitter handles on HEN mirror https://hicetnunc.art/momomeatmaker - must have been a temporary issue
