### ISSUE TITLE
cannot swap "Simulation error: A FAILWITH instruction was reached > FA2_INSUFFICIENT_BALANCE"

### ISSUE THREAD

**Issue by makalele09** [hicetnunc2000/hicetnunc#1352]
I can't do swap in OBJKT#540281, when I try to swap it always shows a message like this

Error message: Parameters Invalid Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.

Kukai message: Simulation error: A FAILWITH instruction was reached > FA2_INSUFFICIENT_BALANCE

when I look at https://hicdex.com/objkt?objkt=540281 my OBJKT holder is KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton

**If you need help with minting or managing assets, please give us the following information**
https://hicetnunc.art/umamamu
https://hicetnunc.art/objkt/540281
tz1hkGCcrECWqPhcQAjfbLjWX1vubZwwVSyw
OBJKT#540281

**Expected behavior**
I was expecting to be able to do a swap to activate the sale, with editions: 8 | 1 tez

**Desktop (please complete the following information):**
Windows 10
Microsoft Edge
Version 95.0.1020.53 (Official build) (64-bit)

**Screenshot**
![error](https://user-images.githubusercontent.com/94708645/142713263-89a9287b-1248-426f-bf0c-47ada9202f9c.png)
![ss error](https://user-images.githubusercontent.com/94708645/142713264-9bb96cd6-c16b-41a3-947e-db8586c6dc86.png)

**Comment by xat** [comment]
According to your operation history, you sent all 20 tokens to the address KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton. This was before you tried to swap. It looks like you now have no token left, which is why the swap operation fails.

Did you send the tokens on purpose?

**Comment by makalele09** [comment]
@xat since I'm new to the NFT world, I didn't know that it would make me unable to swap.

can it be cancelled?

**Comment by skenaja** [comment]
They're stuck unfortunately.
