### ISSUE TITLE
UMAMI ERROR. 

### ISSUE THREAD

**Issue by sunavaunt** [hicetnunc2000/hicetnunc#1360]
If you need help with minting or managing assets, we ask to please wait at least 24 hours for issues to clear up. 

Here are some useful tools that you can use to troubleshoot without us in the meantime:

*See transaction history for an objkt*
https://hicdex.com/objkt

*See transaction history for your wallet address*
https://hicdex.com/sold

Please note that the discord is usually the best place to get the fastest support as there are mostly likely others experiencing the same issues as you and active HEN team members assisting with troubleshooting. Please seek help in the #help channel, and read recent dev updates in #dev-announcements. You can join the discord here: https://discord.gg/HhSYY7q5A8 

-----------------------------------------------
*Please fill out the following Bug Report Template

**Describe the bug**
ERROR MESSAGE WHEN TRYING TO CONNECT TO UMAMI WALLET.
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at App.<anonymous> (/Applications/umami.app/Contents/Resources/app.asar/electron-starter.js:187:16)
    at App.emit (events.js:315:20)

**To Reproduce**
CLICK TO  SYNC. GET ERROR INSTANTLY.

I HAD MY WALLET SYNCED WHEN I FIRST CREATED MY PROFILE. I ADDED 2 NFTS, WOULD NOT LOAD SMOOTHLY. 
TRIED TO " currate and was given Insufficiant funds error. but have oveR 5 tz in wallet?
after waiting 12 hrs. wallet won't connect. 

**Screenshots**

**Desktop (please complete the following information):**
  - OS: [e.g. iOS8.1] OS- 10.12.6 
 - Browser [e.g. stock browser, safari] BRAVE
 - 
 - Version Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.
UMAMI WALLET- tz1MmBYUUsaqt8fRVuFfAAriJbbFBGYpT5F7

**Comment by skenaja** [comment]
That's a Umami error, please report to their dev team here:  https://gitlab.com/groups/nomadic-labs/umami-wallet/-/issues
