### ISSUE TITLE
FAQ: [objkt doesn't play if I use any mobile device]

### ISSUE THREAD

**Issue by 4layers** [hicetnunc2000/hicetnunc#1363]
Hey guys I was wondering if u could help me out with something.
I uploaded an objkt earlier on hic et nunc and objktcom
 
So when I am trying to play it from my phone I get this sign.
Any ideas why???
![FFoWjL0XEAgQZ6u](https://user-images.githubusercontent.com/95447302/144504459-80c797e1-eb82-4a8e-a49b-c0bca9bf3f9f.jpeg)

**Comment by skenaja** [comment]
Probably a codec issue. What is the objkt numberr?
