### ISSUE TITLE
Unity WebGL mint previews are cropped in full screen mode

### ISSUE THREAD

**Issue by vectris-dev** [hicetnunc2000/hicetnunc#1375]
**Describe the bug**
When a user uploads a unity webGL build the full screen preview is cut off at the top

**To Reproduce**
1. Upload a Unity WebGL build as an interactive objkt
3. Open the preview 
3. Click the fullscreen button

**Expected behavior**
The webGL build would take up the entire screen

**Screenshots**
![Screenshot 2021-12-07 175414](https://user-images.githubusercontent.com/34930772/144981107-da1491f5-3cd0-4823-acfd-6f2d1e0935ab.png)

**Desktop**
 - OS: Windows 10
 - Chrome
 - Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by dystopiancreatives** [comment]
Hey Steve, I have the same issue as you. Did you figure out a way?
![04_17_25_05_chrome_XzulSsKTno](https://user-images.githubusercontent.com/97116573/148091650-20520719-97dd-4f56-930f-9d39cb0684ae.png)
![04_17_25_12_chrome_jO9CKB6E0p](https://user-images.githubusercontent.com/97116573/148091653-327b8ca4-28cb-49ca-94d4-0d2c154c573b.png)

**Comment by hanexperience** [comment]
@dystopiancreatives we found out it was only the preview that was cropped, not the actual mint so we just hacked the preview with CSS and then minted.

**Comment by LeonoraGolin** [comment]
Sorry but I did not understand what are you talking about.
Could you explain better?
I had my first mint yesterday.


________________________________
De: hanexperience ***@***.***>
Enviado: terça-feira, 4 de janeiro de 2022 21:05
Para: hicetnunc2000/hicetnunc ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [hicetnunc2000/hicetnunc] Unity WebGL mint previews are cropped in full screen mode (Issue #1375)


@dystopiancreatives<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdystopiancreatives&data=04%7C01%7C%7Cbf2ce29318ee439c48ac08d9cfdf08d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769379099250837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dNs31s%2BI1OcMWKSTLPOunUTTRsWSOw785ydiMjkSHL8%3D&reserved=0> we found out it was only the preview that was cropped, not the actual mint so we just hacked the preview with CSS and then minted.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhicetnunc2000%2Fhicetnunc%2Fissues%2F1375%23issuecomment-1005265655&data=04%7C01%7C%7Cbf2ce29318ee439c48ac08d9cfdf08d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769379099260790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=moxWdC82BsPrPsbiZzB4Ku%2FcnIiVK91hkuxauN8eKMA%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADWGVRO2U5LLFGTI4DOWI6TUUODLHANCNFSM5JQPI3RQ&data=04%7C01%7C%7Cbf2ce29318ee439c48ac08d9cfdf08d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769379099260790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ilYJlqgl%2F%2F6umyu%2BELwBhdGrRfkOEzubeSIL%2FPyy5%2BE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cbf2ce29318ee439c48ac08d9cfdf08d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769379099270756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nUUWftScyfK6AEtV9KxSt74M1aeQgF4OCaz%2FJ4iqkMY%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cbf2ce29318ee439c48ac08d9cfdf08d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769379099270756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xw7yhYhoZpgFBAc%2BJS1PDt5ZluqB2ynvXEjFG9sXFkg%3D&reserved=0>.

**Comment by hanexperience** [comment]
So it's only the preview of the mint that's cropped, not the actual mint itself. In order to preview the mint correctly one of our web developers modified the CSS in order to display the preview correclty (only temporarily of course because this was all done on the client side), however this is not essential. For now you can still mint, it's only the preview that will be cropped, nothing else.

In terms of an actual fix that would require contributers / people with access to the codebase to update the website.

**Comment by melMass** [comment]
As Hanexperience explained this is only affecting the preview page for all generative tokens
