### ISSUE TITLE
"Account restricted" for no reason...

### ISSUE THREAD

**Issue by arialyseyes** [hicetnunc2000/hicetnunc#1392]
Hello,

My account got banned for no reason in HeN and in OBJKT, when I opened the profile it says "account restricted" but I did not do anything wrong... Could someone please help me to unlock my account?

username in HEN is: Arialyseyes
It has 3 NFT's in total, the profile was set up like 5 days ago or so and there is absolutely no reason to ban it...

This is my first time reporting something like this. Hope this is the right place to do so.

Thanks in advance.

Arialyseyes

**Comment by l444u** [comment]
did u get an answer?

**Comment by skenaja** [comment]
If you haven't already done so, please ask for support in the Discord #report-copyminters channel https://discord.gg/Rf5FrkPg
