### ISSUE TITLE
My Hic profile isnt loading 

### ISSUE THREAD

**Issue by keanasears** [hicetnunc2000/hicetnunc#1393]
Hello

I have been having a persistent issue with my hic profile not loading, my name, bio and profile picture show for a second then vanish. Iv reached out to people in the community and spent some time trying to fix it with no joy.

I'm not sure if I'm asking in the right place but if someone could take a look or point me in the right direction it would be much appreciated.

Wallet address -
tz1aPnfjrtK9SzRWUQzk6MAsaxuEx68AQMRf

User Name -
Ke Visuals 

Thanks,
Keana

**Comment by crzypatchwork** [comment]
try a username without whitespaces
