### ISSUE TITLE
minted object doesn't appear on my profile

### ISSUE THREAD

**Issue by joaoricardocefalialmeida** [hicetnunc2000/hicetnunc#1394]
Ive just minted an objkt but it doesn't show on my creations tab.
Please help
Thanks

**Comment by mjesunce** [comment]
same thing şs hapenning to me at the moment... my mint is not on my profile... #1262

**Comment by nftjolly** [comment]
[Same problem ... ](https://github.com/hicetnunc2000/hicetnunc/issues/1405
)
