### ISSUE TITLE
media types

### ISSUE THREAD

**Issue by crzypatchwork** [hicetnunc2000/hicetnunc#14]
- audio
- text
- 3D (unity/webassembly)
- pdf?

**Comment by fraguada** [comment]
3d format could start with glTF, and perhaps others. Making a viewer should be straightforward with three.js. I guess it would be somewhere around [here](https://github.com/hicetnunc2000/hicetnunc/blob/master/src/components/Feed.js#L97-L109). Would be good to make a reusable media component. I'm more experienced with vue, but curious to try it out for react.

**Comment by andrevenancio** [comment]
I'm happy to create a component that renders .gltf's, .obj's and other common 3d file types. However, they normally just define a 3D model (vertices, faces, etc) and textures. They don't define light, camera (fov, distance, near and far planes etc.)

Another potential problem with allowing this media type is that not all 3d artist have the knowledge to produce 3d models that can render in real-time. Normally a 3d artist working on movie VFX would have no concerns over the number of polygons as they rely on render farms to render their models/animations offline. However, to display them in the browser, they would have to be optimised. Allowing these files without any checks for max file size, a max number of vertices etc can potentially crash the browser.

Its an original and interesting idea, but just requires a bit of thought before implementing.

**Comment by farfromorigin** [comment]
Agreed. Maybe it would be good to have a "preview" before minting so people know what their 3d will look like. Perhaps also a "poster" image that could serve as a preview for scenes that take more time to load.

**Comment by fraguada** [comment]
All good points. We can extract the appropriate information from glTF and other file types which aren't purely binary (or where binary data can be easily peeked).

**Comment by fraguada** [comment]
Not sure if model viewer includes some sort of limit parameters on verts, etc. That should be easy enough to extract from json, and if it passes, it can be loaded with https://github.com/google/model-viewer

Also suggested here: https://twitter.com/thespite/status/1368510216636145666?s=20

**Comment by spite** [comment]
glb would be the format that is self contained and binary https://en.wikipedia.org/wiki/GlTF#GLB, and model-viewer supports it.

**Comment by bentstamnes** [comment]
I’d very much appreciate audio, and since an NFT should have some real value, supporting WAV is essential. FLAC is an alternative for non-lossy audio. And then I would also provide an MP3 for ease of use.

Supporting private albums on BandCamp can also be an option, but for raw file formats, the above would be a good start.

**Edit: WAV, MP3 and FLAC are all natively supported** by most browsers through the <audio> tag already: https://en.m.wikipedia.org/wiki/HTML5_audio

**Comment by mrdoob** [comment]
SuperRare uses https://github.com/google/model-viewer to display glb files 👍

Some examples:
https://superrare.co/artwork-v2/you-are-here-16036
https://superrare.co/artwork-v2/starry-night-sky-18966
https://superrare.co/artwork-v2/star-20020

**Comment by fraguada** [comment]
FYI on file size limits on SuperRare: http://help.superrare.co/en/articles/4199365-faq-tokenizing-3d-art-on-superrare

> What are the file size limits?
> Artwork file: 50MB
> Thumbnail: 10MB

**Comment by andrevenancio** [comment]
Interesting. I'm helping doing a bit of cleanup across the site, once things are more stable I'll look into this. Thanks for all the resources!

**Comment by mrdoob** [comment]
viv3 also uses modelviewer 🤓

https://viv3.com/products/1084

**Comment by andrevenancio** [comment]
I'm all in for this. but how do you guys think they handle:

1. Different scale models
2. Potentially large geometries from a 3d artist that never exported for real time graphics
3. Light setup?

We can use that "old" library (three.js) (you guys might have heard of it) and use the box bounding box to calculate a distance to the camera or maybe to change the scale of it? How would you implement something so generic @mrdoob @spite ?

**Comment by mrdoob** [comment]
> We can use that "old" library (three.js) (you guys might have heard of it)

I'm starting to forget what that is... 😁

1. modelviewer takes care of that
2. They'll have to learn to optimize for realtime. They can use this [tester](https://model-viewer-tester.glitch.me/).
3. No custom lights support. It uses a single environment image (Performance is predictable. Apple does the same in their USDZ viewer).

SuperRare instructions:
http://help.superrare.co/en/articles/4199365-faq-tokenizing-3d-art-on-superrare

If anything I think it's a good start.

Disclosure: I've worked on [modelviewer](https://github.com/google/model-viewer/graphs/contributors). We did it because making a viewer is actually not super easy.

**Comment by andrevenancio** [comment]
Is your advice to use the modelviewer instead of building a custom one @mrdoob ? 

@crzypatchwork what do you think? should we start aiming to introduce this 3d media type?

**Comment by mrdoob** [comment]
Yes, I recommend starting with modelviewer and build a custom one further down the road if required.

Integrating modelviewer should be pretty straighforward:

If the NFT is a glb file we need include this script (can be hosted in hicetnunc too):

```html
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
```

And then use the custom element, just as if it was a `<img>` tag:

```html
<model-viewer src="file.glb" auto-rotate camera-controls></model-viewer>
```

For the gallery sections I recommend this configuration instead:

```html
<a href><model-viewer src="file1.glb" auto-rotate></model-viewer></a>
<a href><model-viewer src="file2.glb" auto-rotate"></model-viewer></a>
<a href><model-viewer src="file3.glb" auto-rotate></model-viewer></a>
<a href><model-viewer src="file4.glb" auto-rotate></model-viewer></a>
...
```

This will make sure complex 3d files don't affect the page's responsiveness.

The dimensions can be set via css like any other element:

```css
model-viewer {
  width: 383px;
  height: 383px;
}
```

**Comment by andrevenancio** [comment]
Thanks for this. I've just done a quick test and everything seems to be working fine out of the box. I was looking into more detail about the [tester](https://modelviewer.dev/examples/tester.html) you shared earlier and it got me thinking...

Right now the "magic" of the platform is that you drag a file (let's say a `.glb`), you mint it and it will be automatically uploaded.

Here's where I'm not sure and all feedback is welcome.
When we're on the feed page with multiple assets being loaded and displayed at the same time, should we:

1. Display a `poster` image, instead of loading the 3D model and once the user clicks it, it takes you to the detail page, and there you have the interactive 3d model?

Or should we

2. Display the component on the feed page, allowing the user to interact with it before choosing to open it in detail.

The PRO and CONS for option 1
**PRO**
- Improves user experience by loading a smaller asset instead of a potentially large 3D model

**CONS**
- It requires us to update the Mint page and require a poster image if the user uploads a `.glb` or `.gltf` file

The PRO and CONS for option 2
**PRO**
- The user is able to interact with the 3d model on the feed page, making it easy for them to preview the object before leaving the feed page.
- "We" don't have to implement an over-engineered mint form where we need to upload an extra `poster` image for the 3d model.

**CONS**
- It can potencially degrade the user experience if the feed has a lot of large 3d models.

Any thoughts?

**Comment by elalish** [comment]
`<model-viewer>` is designed for efficient page load; it lazy loads by default and has a lot of interaction customizability. It sounds like you might be interested in `reveal="interaction"`, which only loads the model and dismisses the poster when the user interacts: https://modelviewer.dev/docs/#entrydocs-loading-attributes-reveal

Our posters offer seamless transition from 2D to 3D, even with an unknown aspect ratio of the `<model-viewer>` element, so I'd recommend keeping the poster with the element to take advantage of that.

**Comment by mrdoob** [comment]
@andrevenancio

Yes, I vote for 2 as it treats glb files just like the site currently treats images and videos. Plus no need to change the submission form.

However, I proposed using `interaction-prompt="none"` for performance reasons, but I forgot to mention that I do not think 3d models should be interactive in gallery pages and that parameters solves that too. I would make them interactive only in the artwork page.

**Comment by andrevenancio** [comment]
Just published the very first one https://www.hicetnunc.xyz/objkt/4132 It should be available at some point today after @crzypatchwork pushes to production

**Comment by spite** [comment]
seems to be working already? very cool!

**Comment by mrdoob** [comment]
Nice! I want to collect it! 😁

**Comment by mrdoob** [comment]
@andrevenancio

Would it be possible to remove the `camera-controls` parameter when not in the item's page?
Right now the UX is a bit confusing plus it steals mousewheel events and breaks the scrolling navigation.

**Comment by andrevenancio** [comment]
Yeah, I'm all in for advice on that component. I'm updating it now, but I don't have deployment permissions. so it might be a few hours until it gets merged

**Comment by andrevenancio** [comment]
> Nice! I want to collect it! 😁

I think mattdesl was quicker than you :)

**Comment by mrdoob** [comment]
Grrrr!

**Comment by andrevenancio** [comment]
@mrdoob I might have missed something...
Basically on the objkt detail page we're allowing it to be interactive, and on the feed we're not. but I can still interact with it on the feed. Am I setting the wrong prop?

```jsx
import React from 'react'
import styles from './index.module.scss'

/* DOCS: https://modelviewer.dev/ */
export const GLBComponent = ({ src, interactive = false }) => {
  console.log('is interactive', interactive)
  return (
    <div className={styles.container}>
      <model-viewer
        className={styles.glb}
        src={src}
        auto-rotate
        camera-controls
        interaction-prompt={interactive ? 'when-focused' : 'none'}
      ></model-viewer>
    </div>
  )
}
```

**Comment by mrdoob** [comment]
Sorry, I was wrong.

I think it should be like this:

```js
import React from 'react'
import styles from './index.module.scss'

/* DOCS: https://modelviewer.dev/ */
export const GLBComponent = ({ src, interactive = false }) => {
  console.log('is interactive', interactive)
  return (
    <div className={styles.container}>
      <model-viewer
        className={styles.glb}
        src={src}
        auto-rotate
        {interactive ? 'camera-controls' : ''}
      ></model-viewer>
    </div>
  )
}
```

**Comment by mrdoob** [comment]
Also, `data-js-focus-visible` removes the blue outline:

```js
import React from 'react'
import styles from './index.module.scss'

/* DOCS: https://modelviewer.dev/ */
export const GLBComponent = ({ src, interactive = false }) => {
  console.log('is interactive', interactive)
  return (
    <div className={styles.container}>
      <model-viewer
        className={styles.glb}
        src={src}
        auto-rotate
        data-js-focus-visible
        {interactive ? 'camera-controls' : ''}
      ></model-viewer>
    </div>
  )
}
```

**Comment by andrevenancio** [comment]
Can I mint a screenshot of you saying you're wrong? 😹 (joke).

Thanks appreciate it! will commit the changes!

**Comment by andrevenancio** [comment]
You can now upload .glb and .gltf! Go crazy 🥳

**Comment by SableRaf** [comment]
Could we possibly add html canvas to the list? The possibilities would be out of this world! Especially with p5.js https://p5js.org/ 👀

**Comment by crzypatchwork** [comment]
I've seen some interesting things on itch.io as well but I'm not sure how they embed games

**Comment by pichiste** [comment]
Adding website (an html/js/css/etc bundle?) as a media type in general would be amazing. Thinking of AR/VR, interactive, generative works, etc. It would cover the p5.js and Unity scenarios mentioned above!

**Comment by mmetaa** [comment]
i would like to mint a pdf of a very large & complex vector illustration i have made. this is a complex piece with a lot of layers, transparencies, etc and trying to view it in a browser brings everything to a halt for a minute or so while it renders. (you can see some images of it here: http://meta.am/cr4trev2/) 

ideally, the pdf would be minted but not viewable or downloadable from the artwork page. instead there would be multiple jpg previews to give a sense of the overall piece & the detail involved, and then only the buyer would get access to the actual vector pdf file. could this be made possible?

**Comment by mrdoob** [comment]
Uploading a zip file that contains a website could be interesting indeed.

The first thing that comes to mind are bad actors though (trackers, ransomware, etc).

I've not tested this but I think `<iframe src="index.html" sandbox="allow-scripts"></iframe>` should be able to solve that by only allowing running the scripts within the iframe and disallow making connections to other websites.

**Comment by pichiste** [comment]
Yeah it seem like iframe with `sandbox="allow-scripts"` would be the way to go. It would keep the iframe from having any access to the containing page, which is maybe the main security concern? 

Don't think there's a way of keeping the iframe from requesting arbitrary web resources, but maybe that's ok, and even desirable/necessary for some artworks.

I could imagine a version of this where listings of type website are hidden behind an image/video thumbnail with a "Click to launch" overlay, so the iframe is never embedded until clicked on.

**Comment by mmmerl** [comment]
@pichiste @mrdoob If you really wanted to keep things safe and require self contained zips (no external files), you could inject a CSP meta tag on upload.

**Comment by andrevenancio** [comment]
I've implemented a similar solution for interactive SVGs
[here for the code](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/media-types/vector/index.js) and [here for the iframe](https://github.com/hicetnunc2000/hicetnunc/blob/main/gh-pages/sandbox-svg.html)

I imagine a similar solution can be done for that.

**Comment by mrdoob** [comment]
@andrevenancio [I have made a game with SVG](https://www.hicetnunc.xyz/objkt/7177). Seems like the site is not using `<iframe>`s yet?

**Comment by andrevenancio** [comment]
Yeah... I tag @crzypatchwork every 5minutes but he might have a lot on his plate. Only him is able to make deployments. I can only help with the code and merge and review stuff. But there's a "manual" continuous integration 😂 process in place

**Comment by mrdoob** [comment]
No rush! 😁

**Comment by mrdoob** [comment]
Seems like the resizing code has some issues on desktop... 😕

https://www.hicetnunc.xyz/objkt/7577

**Comment by andrevenancio** [comment]
I was just coming here to let you know that it got deployed! But I guess you sleep less than me. I can see it, but I can't interact with it. what are we missing? Click events? Keyboard events?

**Comment by pichiste** [comment]
@andrevenancio @mrdoob Hey I've been experimenting with html support via zip archive and have something working. Basically it lets you load a zip file that contains an index.html file and all related resources (js, css, images, etc), and displays it in a sandboxed iframe.

As suggested it's based on the component/sandbox pattern from your svg implementation (thanks!). The trickiest bit is that 
all resources are extracted as `Blobs` from the zip archive, so paths referenced in html/js/css point to nowhere. The best solution I could come up with was to use a service worker to intercept all http requests and respond with the `Blob` data for the given resource.

I know it's a convoluted approach but couldn't think of any other way to do it if we have to stick to uploading a single zip file to ipfs. Maybe there's an easier way?

I should note I haven't gotten as far as actually uploading anything to ipfs – just displaying in the preview window on the mint page, but imagine that should just work.

If you're open to contributions I'm happy to help on this, let me know!

![ezgif-3-211c425665fa](https://user-images.githubusercontent.com/111979/111667693-4350ed80-8815-11eb-9359-f02302292536.gif)

**Comment by spite** [comment]
Speaking of iframes and potential html content... what do we think about permissions like camera or microphone? i've made https://www.hicetnunc.xyz/objkt/7770 using getUserMEdia but it fails due to permissions.

**Comment by elalish** [comment]
A glTF (same as many file formats) is just a zip archive with internal URLs pointing to included files. So it seems like there must be an easier way. Three.js is loading these and various other zip-based formats, so perhaps a pattern from there would be useful?

**Comment by mrdoob** [comment]
@pichiste Nice exploration!

I think we can start by supporting single html files with everything embedded in it? (like demoscene 4k and js13k games do it)

**Comment by pichiste** [comment]
@mrdoob Makes a lot of sense!

I guess ultimately something like this would be ideal: https://web.dev/web-bundles/

**Comment by pichiste** [comment]
Submitted a PR for single page HTML support: https://github.com/hicetnunc2000/hicetnunc/pull/189

**Comment by veqtor** [comment]
> @andrevenancio @mrdoob Hey I've been experimenting with html support via zip archive and have something working. Basically it lets you load a zip file that contains an index.html file and all related resources (js, css, images, etc), and displays it in a sandboxed iframe.
> 
> As suggested it's based on the component/sandbox pattern from your svg implementation (thanks!). The trickiest bit is that
> all resources are extracted as `Blobs` from the zip archive, so paths referenced in html/js/css point to nowhere. The best solution I could come up with was to use a service worker to intercept all http requests and respond with the `Blob` data for the given resource.
> 
> I know it's a convoluted approach but couldn't think of any other way to do it if we have to stick to uploading a single zip file to ipfs. Maybe there's an easier way?
> 
> I should note I haven't gotten as far as actually uploading anything to ipfs – just displaying in the preview window on the mint page, but imagine that should just work.
> 
> If you're open to contributions I'm happy to help on this, let me know!
> 
> ![ezgif-3-211c425665fa](https://user-images.githubusercontent.com/111979/111667693-4350ed80-8815-11eb-9359-f02302292536.gif)

I think the proper way to do this is to upload a "folder" to IPFS which is a feature they already support.
This is the recommended way to upload a complete "website" to IPFS with multiple resources.

https://tarunbatra.com/blog/decentralization/Deploy-your-website-on-IPFS-Why-and-How/

**Comment by pichiste** [comment]
(Sorry to duplicate from discord, but just in case some people aren't there)

Good to know! And completely in favor of letting people upload a zip file without having to deal with any bundling friction.

The problem still remains when displaying the preview on the mint page, since the files aren't on IPFS yet. But the service worker solution above seems to work well for that context. Thoughts? 

Re: cover image, what about having a convention where the user can just include a `cover.jpg` image in the zip file and it will automatically get picked up as the cover? It could also be a separate upload field, in case we want this applied to other media types.

**Comment by pichiste** [comment]
Could also disable the preview for HTML/ZIP case? Though I imagine people want would to see their work in context before uploading...

**Comment by andrevenancio** [comment]
closing this! Thank you all for the feedback! HTML is up and running
