### ISSUE TITLE
restricted account 

### ISSUE THREAD

**Issue by zizzizi** [hicetnunc2000/hicetnunc#1409]
To whom it may concern

I had another wallet with a few items on hicetnunc with this address... Unfortunately, I lost my private keys and couldn't access them anymore. So I've decided to publish my art with a new account which is...

I made a mistake and published one of my arts, which was already on my lost account. Would you please check it again and let me access my account and remove this item? I don't want to lose my account again.

Thanks for understanding
Any help appreciated

Looking for your reply

**Comment by wfdj** [comment]
I have almost this exact same issue. https://tzkt.io/tz1Vfy595rsJnYkGt975eU5J87gMfzMwC95z/operations/

**Comment by skenaja** [comment]
If you haven't already done so, please ask for support in the Discord #report-copyminters channel https://discord.gg/Rf5FrkPg
