### ISSUE TITLE
restricted account

### ISSUE THREAD

**Issue by zizzizi** [hicetnunc2000/hicetnunc#1410]
Hello To whom it may concern

I had another wallet with a few items on hicetnunc with this address https://www.hicetnunc.xyz/objkt/157744  Unfortunately I lost my private keys and couldn't access it anymore. So I've decided to publish my arts with a new account which is https://hicetnunc.art/objkt/635280

I did a mistake and published one of my arts which was already on my lost account. Would you please check it again and let me access to my account and remove this item? I don't want to lose my account again.

Thanks for understanding
Any help appreciated

Looking for your reply

**Comment by skenaja** [comment]
If you haven't already done so, please ask for support in the Discord #report-copyminters channel https://discord.gg/Rf5FrkPg
