### ISSUE TITLE
Restricted account

### ISSUE THREAD

**Issue by Sexyartsbrazil** [hicetnunc2000/hicetnunc#1414]
![acoount](https://user-images.githubusercontent.com/101452337/158011995-37b7f5e8-d6ed-4ee1-b4b5-8238114a340e.png)

Hello good morning, I would like to know why my account was banned without any prior notice, and if this is reversible ?

**Comment by skenaja** [comment]
If you haven't already done so, please ask for support in the Discord #report-copyminters channel https://discord.gg/Rf5FrkPg
