### ISSUE TITLE
restricted account

### ISSUE THREAD

**Issue by arslanazimzadeh** [hicetnunc2000/hicetnunc#1416]
Hello, my account has been restricted in Hicetnunc for several days and it is not possible to access it, and I have no idea why it was closed ,I do not know why it was closed. During these days, collectors wanted to buy my tokens, but they told me that we do not have access to your account, without knowing the reason, I went and saw that my account was restricted, and I was shocked by this. What has caused such a disaster on my account? Tell me the reason I do if something needs to be fixed. Please tell me the reason, regards

my account:
 hicetnunc.art/arslanazimzadeh

**Comment by skenaja** [comment]
If you haven't already done so, please ask for support in the Discord #report-copyminters channel https://discord.gg/Rf5FrkPg
