### ISSUE TITLE
restricted account

### ISSUE THREAD

**Issue by imansh7** [hicetnunc2000/hicetnunc#1430]
Hi, my account has been restricted in Hicetnunc many days ago and I can not possibly access it, I don't know why it happened!?

What has caused such a disaster on my account? Tell me the reason I do if something needs to be fixed. Please tell me the reason?

my account:
https://www.hicetnunc.xyz/iman

Best regards

**Comment by skenaja** [comment]
Looks like this was sorted in the HEN discord

**Comment by imansh7** [comment]
> Looks like this was sorted in the HEN discord

Thank you . my problem solved in HEN
