### ISSUE TITLE
Error canceling/swapping

### ISSUE THREAD

**Issue by kheelk** [hicetnunc2000/hicetnunc#1451]
So this is my gallery
https://hicetnunc.art/Kheelk
tried to cancel/swap some of the works (idk if saying which works is helpful?)
I clicked cancel > it went to my kukai wallet > confirmed
and it still shows on hicetnunc that i have all the tokens for sale so it didnt get cancelled?

when i try to cancel again though, it sends the request to kukai and gives me an error there
i got my canceled works as tokens in my wallet - so somehow kukai recognized that works got cancelled but hicetnunc didnt?
Id appreciate help! Thanks~

**Comment by melMass** [comment]
Hi @kheelk, yes this is "normal".
The cancel operation went through on the blockchain, but the indexer did not pick it up yet.
There are ongoing delays ever since the Tezos upgrade from last week, for now there is no ETA on this matter.
