### ISSUE TITLE
OBJKT is not showing

### ISSUE THREAD

**Issue by artgeroftorres** [hicetnunc2000/hicetnunc#1452]
I uploaded an object three times to mint and it does not appear in my manage assets

profile link: https://hicetnunc.art/art_geroftorres

**To Reproduce**
1. Go to https://hicetnunc.art/art_geroftorres
2. There should be 3 uploaded items in my creations, but they are not

my OBJKTS uploaded to do not appear in the MANAGE ASSETS

Browser: Brave

wallet adress:
tz1b97AoazFAWk5dDW9VrVuwb2qyJmFbYPYW

**Comment by crzypatchwork** [comment]
theres currently no backend available so this service is discontinued for an undetermined period of time
