### ISSUE TITLE
hicetnunc status page

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#149]
Would be nice to have an external status page that reports the status of the various parts to hicetnunc.xyz. Similar to https://www.githubstatus.com/

Driving poeple there would clean up discord questions a bit perhaps and prevent people from trying to mint/swap when services are down.

**Comment by fraguada** [comment]
Made one here: 
src: https://github.com/fraguada/hicetnuncstatus
live: https://hicetnuncstatus.herokuapp.com/

**Comment by andrevenancio** [comment]
Closing this, as it has no actions on the development part. My personal opinion @fraguada is that we could have a subdomain status.hicetnunc.xyz with your code. But that's something for @crzypatchwork to decide/implement. Closing this for now
