### ISSUE TITLE
statistics/ranks

### ISSUE THREAD

**Issue by crzypatchwork** [hicetnunc2000/hicetnunc#15]

**Comment by crzypatchwork** [comment]
https://arronax.io/tezos/mainnet/operations/query/eyJmaWVsZHMiOlsiZGVzdGluYXRpb24iLCJhbW91bnQiLCJmZWUiXSwicHJlZGljYXRlcyI6W3siZmllbGQiOiJraW5kIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsidHJhbnNhY3Rpb24iXSwiaW52ZXJzZSI6ZmFsc2V9LHsiZmllbGQiOiJzdGF0dXMiLCJvcGVyYXRpb24iOiJlcSIsInNldCI6WyJhcHBsaWVkIl0sImludmVyc2UiOmZhbHNlfSx7ImZpZWxkIjoiZGVzdGluYXRpb24iLCJvcGVyYXRpb24iOiJlcSIsInNldCI6WyJLVDFIa2c1cWVOaGZ3cEtXNGZYdnE3SEdaQjl6MkVubUNDQTkiXSwiaW52ZXJzZSI6ZmFsc2V9LHsiZmllbGQiOiJwYXJhbWV0ZXJzX2VudHJ5cG9pbnRzIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsiY29sbGVjdCJdLCJpbnZlcnNlIjpmYWxzZX0seyJmaWVsZCI6ImFtb3VudCIsIm9wZXJhdGlvbiI6Imd0Iiwic2V0IjpbIjAiXSwiaW52ZXJzZSI6ZmFsc2V9LHsiZmllbGQiOiJ0aW1lc3RhbXAiLCJvcGVyYXRpb24iOiJhZnRlciIsInNldCI6WzE2MTIxNTU2MDAwMDBdLCJpbnZlcnNlIjpmYWxzZX1dLCJvcmRlckJ5IjpbeyJmaWVsZCI6ImRlc3RpbmF0aW9uIiwiZGlyZWN0aW9uIjoiZGVzYyJ9XSwiYWdncmVnYXRpb24iOlt7ImZpZWxkIjoiYW1vdW50IiwiZnVuY3Rpb24iOiJzdW0ifSx7ImZpZWxkIjoiZmVlIiwiZnVuY3Rpb24iOiJzdW0ifV0sImxpbWl0IjoxMDAwfQ

**Comment by fraguada** [comment]
If you mean "leaderboard", I think it's the worst "feature" I've seen from other platforms. IMHO.
