### ISSUE TITLE
UX - Mint & Curate confusion 

### ISSUE THREAD

**Issue by elhoucine** [hicetnunc2000/hicetnunc#150]
Hi,

Like in Rarible I think users are expecting minting/curating in one single form, I've read some comments in Twitter where people saying the price field is missing.

Maybe a message on the minting page (or after minting complete) completes indicating that the item is not for sale yet and that it should be curated from the collection tab.

Good work by the way (y)

**Comment by raynt** [comment]
Having the swap separate allow for more control for how the artist releases their work. It's a benefit to be able to release parts of an edition over time and adjust pricing.

**Comment by andrevenancio** [comment]
as @raynt explained, this is intentional. You're free to go on Dribble and lobby with the community to change it, but as for now, this is expected behavior.
