### ISSUE TITLE
Cannot buy NFTs

### ISSUE THREAD

**Issue by ssplashh** [hicetnunc2000/hicetnunc#1507]
**Describe the bug**
Cannot buy nft
- your profile link https://objkt.com/profile/tz1SyLyryd5GzKmiCaBV87e4UhxBrc6n4v1r/created
- tezos wallet address: tz1SyLyryd5GzKmiCaBV87e4UhxBrc6n4v1r
- objkt affected:  https://objkt.com/asset/hicetnunc/838879

**To Reproduce**
1. Go to ['...'](https://objkt.com/asset/hicetnunc/838879)
2. Click on "buy"
4. See error: Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.
Also on my wallet page: Simulation error: A FAILWITH instruction was reached | ADDR_NF

**Expected behavior**
Pay gas and tz and buy NFT

**Screenshots**
![image](https://github.com/hicetnunc2000/hicetnunc/assets/128165996/03f3b940-11be-4b94-88dc-58c679590382)
![image](https://github.com/hicetnunc2000/hicetnunc/assets/128165996/736d8aef-d57b-48a3-b212-36628026a044)

---

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Brave

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Browse Samsung browser, Edge, Chrome

**Comment by melMass** [comment]
Hi ssplashh,

This is related to the OBJKT.com marketplace you can find their support on discord here: https://discord.gg/sK4gnRXExB

The common reason for what you describe is caching issues. Can you try unsyncing and resyncing to objkt.com?

**Comment by ssplashh** [comment]
Thank you so much, actually, I think what happened was that the collection had not been verified. I'll close the issue now. Thanks so much for your help :)
