### ISSUE TITLE
Add backoff when API requests fail

### ISSUE THREAD

**Issue by AndreasGassmann** [hicetnunc2000/hicetnunc#154]
Currently, because the server infrastructure is having problems, the frontend keeps spamming the backend every second or so.

Failed API requests should not immediately trigger a retry, it should wait for a couple of seconds before trying again and maybe eventually stop completely and show the user that there is a problem and he should try again later.

**Comment by andrevenancio** [comment]
You're right. this was fixed on the `main` branch, but not a different version was deployed. This should be fixed now.
