### ISSUE TITLE
site loads blank

### ISSUE THREAD

**Issue by mikestjean** [hicetnunc2000/hicetnunc#156]
Site doesn't seem to load any NFTs, even when I go directly to a link:
https://www.hicetnunc.xyz/objkt/5831

I have sync'd my Temple wallet and can see the other pages "mint / about", but when I go to the main page or the direct-NFT link, I just get a 'loading' pulsing black dot ... Thoughts?

**Comment by neverhood311** [comment]
@mikestjean The site's been down all day. Looks like they're doing their best to get it back up. https://twitter.com/hicetnunc2000/status/1371469693412859906

**Comment by andrevenancio** [comment]
The site was down due to a 3rd party we rely on was down... So we're trying to get API responses from a server that wasn't responding. This should now be fixed.
