### ISSUE TITLE
Site doesn't load. CORS Issues

### ISSUE THREAD

**Issue by utdrmac** [hicetnunc2000/hicetnunc#157]
<img width="1111" alt="Screen Shot 2021-03-15 at 3 32 31 PM" src="https://user-images.githubusercontent.com/4413670/111217583-b5ba9700-85a3-11eb-8f93-a9cd5900aab9.png">

**Comment by andrevenancio** [comment]
Occasionally when our 3d party Better Call Dev time's out the API fails with a cors issue, but its not a cors issue. Its just catching errors not properly implemented on the API. I believe this has now been fixed. Eventually, if the 3rd party fails again you might have this error again... but you should have a "mint mint mint" message. which basically says: site broken! :)
