### ISSUE TITLE
amount available / amount minted

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#162]
There seems to be a semi confusing issue with the editioning. The current layout shows "amount available / amount swap" it should show the "amount available / amount minted".

Example: 5 copies of this token were minted
https://www.hicetnunc.xyz/objkt/6332

Three were swapped and available. The site is showing 3/3. 
It should probably show 3/5 as the owner holds two copies. It's important for the collector to know the total minted.

**Comment by presstube** [comment]
Just wanted to chime in and second this opinion. When I'm collecting it's very helpful to see the total number of OBJKTS minted: 

Available / Total

Thanks!

**Comment by Quasimondo** [comment]
![image](https://user-images.githubusercontent.com/182098/111320088-ee6f7480-8666-11eb-9d77-6d2949af9349.png)

There seems also to be an issue with sold out editions showing "NaN" instead of 0 available

**Comment by raynt** [comment]
I see this is labelled both bug and enhancement. I don't have any experience with Github and the function of labels but I hope this issue is being taken into account as a bug. The editioning of an artwork is extremely important. 

Currently, an edition of 100 could be minted and if only one is swapped it would show up on the site as 1/1 which is very problematic because it is not transparent and breaks one of the benefits of an NFT.

**Comment by Quasimondo** [comment]
I would like to amend this enhancement request. Ideally I would like to see 3 numbers:
items for sale / items still held in issuer's wallet (not on market) / total edition size

**Comment by raynt** [comment]
@Quasimondo this is a good idea. I always reference the last 5 letters shown in the issuer's line to holders in the owners tab. to see how many are unreleased.

**Comment by Pamicel** [comment]
I would argue
items for sale / items swapped / total edition size
as it reads
items for sale **portion of** items swapped **portion of** total edition size
which i find more intuitive
