### ISSUE TITLE
hicetnunc says: undefined alert box

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#164]
When buying an OBJKT I currently see an alert popup that says "undefined". The sale does still work, but of course it is confusing. (I am using the Temple wallet, if that is important to know)

![image](https://user-images.githubusercontent.com/182098/111325720-3d6bd880-866c-11eb-8185-7ec93004e8a8.png)

**Comment by andrevenancio** [comment]
I think in an effort to fix the broken website 2 days ago, crzypatchwork committed some code that breaks this. There's in fact a lot of NaN and undefined going on right now. They're mainly due to API changes that got pushed before they got implemented on the website.

**Comment by andrevenancio** [comment]
should be fixed.
