### ISSUE TITLE
Videos on iPhone always go fullscreen

### ISSUE THREAD

**Issue by EMES77** [hicetnunc2000/hicetnunc#166]
When i open a profile on iPhone (model 7 with latest iOS) and the profile has videos in it, all the videos go fullscreen one over the other. I havn't checked it on other iOS devices, yet.

I have to tap on each video and close it, then see the underlaying video, tap, close it... repeat

happens extensively on this profile https://www.hicetnunc.xyz/tz/tz1gzBtm1r59EtsWMfGMdpnZjtyuQ2fKkjAx

**Comment by andrevenancio** [comment]
I'm using latest iOS on an iPhone 11 Pro Max. The videos are playing in their containers. they only go fullscreen when you select them. I'm not able to replicate this issue.

**Comment by EMES77** [comment]
On iPhone 7 it still happens. I click on a link on twitter. On the OBJKT Page i click on the link to the profile. 
I'll attach a screencast

https://user-images.githubusercontent.com/7556420/111465821-cf361d00-8722-11eb-8a7a-7395c0881a02.mov
