### ISSUE TITLE
Own Creations page only shows 10 OBJKTs

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#167]
The user's own Creations page seems to display 10 OBJKTs max, so you can only see the 10 last pieces of an artist (or your own). Could that be API related (pagination returns 10 per default?)

**Comment by andrevenancio** [comment]
There is no limit on the frontend. This should probably go into the API repository. Frontend always renders everything the API returns either 1 or 10 or 100.
