### ISSUE TITLE
Unable to Burn or Cancel Swap

### ISSUE THREAD

**Issue by FirzenYogesh** [hicetnunc2000/hicetnunc#170]
Whenever I try to cancel a swap, I am getting the error "NatValidationError" with a message "[0] Value is not a number: NaN". I can see it on the inspector window.
The UI redirects to the profile page after clicking on cancel button.

When you try to burn, it straight up throws error on the UI itself. In the Inspector Window it says the same error mentioned above.

Cancel Error Logs:
![image](https://user-images.githubusercontent.com/11814661/111452453-8be6a900-8738-11eb-914e-6fd166a69f53.png)

Burn Error Logs:
![image](https://user-images.githubusercontent.com/11814661/111452378-76717f00-8738-11eb-9592-7a4cf551c138.png)

Edit: Added Images

**Comment by Marion2** [comment]
Same issue here !
