### ISSUE TITLE
Incomplete artwork image after minting. 

### ISSUE THREAD

**Issue by ModulatorUK** [hicetnunc2000/hicetnunc#174]
It happened twice. I minted the artwork but then it shows incomplete, even in the front page when you scroll down you can see only a small part of the art piece. I tried to burn it and it and there is some kind of problem.

![Screenshot 2021-03-17 at 18 03 18](https://user-images.githubusercontent.com/77488033/111515777-1a642600-874b-11eb-9018-0d613f952c51.png)

**Comment by tgreiser** [comment]
I had a similar issue. Possibly related to a large filesize. Image is cut off about half way.

https://www.hicetnunc.xyz/objkt/7497

**Comment by ModulatorUK** [comment]
> I had a similar issue. Possibly related to a large filesize. Image is cut off about half way.
> 
> https://www.hicetnunc.xyz/objkt/7497

Try to clear the cache and cookies. Mine got solved after doing that. If you see the full image in the preview before minting the art piece it means the photo is correct, it could be a cookies issue when loading the page. Also try to load it from a different browser.

**Comment by veqtor** [comment]
Please close the issue, this was problem with cloudflare yesterday, not hic et nunc
