### ISSUE TITLE
FA2_INSUFFICIENT_BALANCE

### ISSUE THREAD

**Issue by HQZ2020** [hicetnunc2000/hicetnunc#176]
Hello, Im trying to swap my nft, but wallet send me error code : FA2_INSUFFICIENT_BALANCE "an operation tried to exceed the gas limit", but I have 3 tokens balance
can't get what im doing wrong :(
thanks

**Comment by violetforest** [comment]
How many objkts did you mint and how many do you have in your wallet?

**Comment by HQZ2020** [comment]
HELLO
thank you for your answer 
I tried to swap 1 and i couldn’t but then i mint and swap a second onjkt with no problem, the 1st one still unable to swap or burn….

**Comment by violetforest** [comment]
If you already swapped one time before on the object, you need to cancel it first, and then do the swap again.

If you try to swap more OBJKTs than you have in your wallet then you will see "insufficient balance" in the wallet. 

This is explained more in the FAQ https://github.com/hicetnunc2000/hicetnunc/blob/main/FAQ.md

**Comment by HQZ2020** [comment]
yes i've tried but after press cancel it just stay there without make action

**Comment by MateSteinforth** [comment]
I have the same issue, I cannot swap any object...
