### ISSUE TITLE
Support for WebGL

### ISSUE THREAD

**Issue by leonardschoelch** [hicetnunc2000/hicetnunc#183]
This would allow uploading interactive art and small games made in Unity3D. Getting the build size to a few MB is possible with Unity web builds.

**Comment by veqtor** [comment]
Would be nice but we'd need to disable it in feed. For this we ought to make some kind of optional thumbnail etc
Possibly it could work to be able to upload a single-page app and the creator needs to be aware that it will be displayed within some square-ratio.

**Comment by andrevenancio** [comment]
I think we're opening pandora's box soon. allowing to embed html. we're just figuring out what's the cons. but will allow p5.js canvas webgl type of content. and Forms! Everyone like's forms!

**Comment by andrevenancio** [comment]
closing this. HTML will be out tomorrow (if everything is okay...) follow us on twitter for the announcement. You should be able to use WebGL.

In regards to Unity. I would advise against it. as Unity builds are normally 50MB+ You can achieve much smaller files using three.js
