### ISSUE TITLE
Sync button

### ISSUE THREAD

**Issue by somaticbits** [hicetnunc2000/hicetnunc#187]
From my experience, and from other ones, the flow to mint is not really clear. 
A sync button that unlocks the mint button - right next to it - could be a solution?
Or for starters, maybe a simple indication that the "sync" text/button actually has an effect (I never tried to click before I read the documentation)

**Comment by andrevenancio** [comment]
Appreciate the feedback. we might review the UX, but this is highly experiencial website.

**Comment by somaticbits** [comment]
And this is exactly what makes hicetnunc so fresh and exciting - keep up the good work!

**Comment by andrevenancio** [comment]
The sync should now be fixed.
