### ISSUE TITLE
NaN available editions

### ISSUE THREAD

**Issue by erasta** [hicetnunc2000/hicetnunc#195]
After minting and swapping without problems, got 100/NaN editions for my item:
https://www.hicetnunc.xyz/objkt/8372
<img width="341" alt="Screen Shot 2021-03-19 at 4 44 50 PM" src="https://user-images.githubusercontent.com/7118772/111798126-71483780-88d2-11eb-8147-aa0cd0aa59b8.png">

**Comment by crzypatchwork** [comment]
such information and others are being recovered/aggregated in the API
