### ISSUE TITLE
Burn is pending forever

### ISSUE THREAD

**Issue by erochOnGit** [hicetnunc2000/hicetnunc#196]
It's pretty much it : 
I'm trying to burn : https://www.hicetnunc.xyz/objkt/3345
And it's pending forever.
![image](https://user-images.githubusercontent.com/24712827/111800349-27f4e980-88cc-11eb-8935-c0aa4921f37d.png)

**Comment by andrevenancio** [comment]
That's a 30MB File. Its bound to take some time to upload. This is available now. closing
