### ISSUE TITLE
Burn UI wording could be improved

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#202]
I am not sure if the burn mechanism already works, now but the current description in the UI does not make me want to try it:
![image](https://user-images.githubusercontent.com/182098/111873528-f4c85e00-8990-11eb-8267-c571c389e981.png)

"Burning will remove all OBJKT#:id from your possession to a burn address." - whilst this is probably just a display issue where "id" has not been replaced with the actual number, it makes me uneasy to try since it almost looks like a wildcard.

**Comment by skenaja** [comment]
Looks like this issue was fixed in 939cd2edfa55e777241e84c7d9af00a5e4378f87

**Comment by Quasimondo** [comment]
Great! Then we can close this issue.
