### ISSUE TITLE
Reddit button on artist pages has broken link from an incorrect '"' character

### ISSUE THREAD

**Issue by mathMakesArt** [hicetnunc2000/hicetnunc#209]
Recently I submitted my information to the Tezos Baking Bad team so that my name, description, website, and other links will display on [**my HicEtNunc artist profile**](https://www.hicetnunc.xyz/tz/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71).

All of the links on my Artist Page appear to function properly, ***with the exception of the Reddit link***.

On [**my TzKT Explorer Page**](https://tzkt.io/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71/operations/), Reddit works properly and links to: `https://www.reddit.com/user/mathmakesart`
But on my HicEtNunc Artist Page, the Reddit button points to: `https://reddit.com/"user/mathmakesart`

### There is a doublequote (") character being inserted directly before the "user" in the Reddit URL which breaks the link.

I'm not sure where in the website code this is being done, I did a search of the repository code for "reddit" and couldn't find anything relevant. But I figured it should be pointed out as I expect this affects other users as well.

**This is a low-urgency issue, I don't use Reddit much anyway but I just wanted the HicEtNunc dev community to be aware**

**Comment by skenaja** [comment]
I've submitted a PR to fix this
