### ISSUE TITLE
Add mime type video/quicktime to support *.mov videos as well

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#21]
MOV videos are not being played. IMHO the player needs to get the correct mimetype, which in this case is "video/quicktime" instead of "Video/mp4".

Examples:
https://www.hicetnunc.xyz/objkt/702
https://cloudflare-ipfs.com/ipfs/QmcC9LehSsrrZC1pe2Z9Ujx3vknsU7wyDQQrKGjUDugjBr (Metadata)

https://www.hicetnunc.xyz/objkt/688
https://cloudflare-ipfs.com/ipfs/QmaF8GyGBzdBcAqHRS8aJBccGUYSYPTM7s345ETZmQNatK

I guess that's in /src/components/Display.js

**Comment by djangobits** [comment]
Not sure if that video/quicktime tag works in all browsers or if there are issues because of streaming quicktime differently from ipfs...

**Comment by martinpospech** [comment]
I think you should use something like WebM with AV1 for faster loading and better use of space.

**Comment by crzypatchwork** [comment]
one of the points I've been thinking is to add a displayUri field on the .json metadata for videos and images. for images it would resize it from an API. for better loading. 

I believe that storing data in WebM format would be interesting also. but we would need to implement a similar method of conversion/resizing.

**Comment by djangobits** [comment]
Just by any mean avoid to convert the original file. These people make art. Independently on how you judge their works, you shouldn't touch the original file of a digital artist. You wouldn't cut a masterpiece of a painting in two pieces just because its easier to get it into your car...

There might be people fiddling for hours and maybe finding the perfect spot of the pixels in their animation but when they upload it, the compression algos ruin it.

**Comment by crzypatchwork** [comment]
k keep it like that. maybe should be interesting something covering the image till it loads at least

**Comment by andrevenancio** [comment]
I think when loading the OBJKT page directly YES we should display the asset as it was uploaded. however, its probably a good idea to display an optimised version for the main feed.

Lets say you upload an image of 4k and its 10MB, it will reduce the user experience to have to load that asset alongside all other assets coming in the feed. Its probably a good idea to employ some kind of optimisation for the sake of user experience.

It would also allow metadata to load properly on twitter and other social platforms.

related: https://github.com/hicetnunc2000/hicetnunc/issues/18

**Comment by MAKIO135** [comment]
Agree with @andrevenancio, as I said on discord: we already have to fight with compression on every social platform, using compressed versions on the main feed or galleries seems legit and would speed up the navigation which is really good, but it is necessary for anyone to know the actual quality of the NFT before buying it.

**Comment by andrevenancio** [comment]
I've added `video/quicktime` mimeType to available video types. It works! Waiting on @crzypatchwork to push to production.
