### ISSUE TITLE
Burn disabled?

### ISSUE THREAD

**Issue by renatachebel** [hicetnunc2000/hicetnunc#210]
I had an issue minting a piece and it ended up being minted twice. Now I need to burn them and it won't let me. It says burning is temporarily disabled. any idea when it will be back?

**Comment by presstube** [comment]
Hi, just wondering where in the priority order the "burn" feature is? 

Got some messes I'd love to clean up : )

**Comment by presstube** [comment]
Oh I just tried and it seems to work! 

Huzzahhhh!
