### ISSUE TITLE
Responsiveness for interactive/live OBJTKs (hacky SVG / HTML / JS)

### ISSUE THREAD

**Issue by SandroMiccoli** [hicetnunc2000/hicetnunc#216]
Hello all!
First, thanks for these developments on new media types inside hicetnunc, very exciting :)

I'm still a little lost on the best practices in using the hacked SVG for interactive OBJKTs. I've currently minted two OBJKTs ([8066](https://www.hicetnunc.xyz/objkt/8066) and [9340](https://www.hicetnunc.xyz/objkt/9340)) using the hacky-SVG approach and, although they look ok when inside the OBJTK link, the preview image is getting cropped:
![image](https://user-images.githubusercontent.com/2353389/112012620-a26e7500-8b29-11eb-9286-aecc80ce3435.png)

Viewing it on mobile even inside the OBJKT link the image gets cropped...

So, my main question here is: how to set the **size** of the SVG, or if uploading an HTML file, how should the dimensions be set? Normally I would get the windowWidth/Height, but not sure how this will interact with the iframe that's holding the SVG.

Now I see that HTML/JS is supported (#189) but not sure the best way to use it. Can I just upload a plain HTML file that calls other js libraries (p5js, threejs, aframe...)? How should this be scaled so it looks nice on the OBJKT page and also in preview?

Maybe a "Creative Coding - FAQ" could be compiled in order to explain the "Do's and Don'ts" when uploading this kind of work... This also relates to #203.

**Comment by pichiste** [comment]
Hi @SandroMiccoli, the HTML support is actually disabled at the moment pending some changes. It was originally going to involve uploading a single HTML file, but now you'll be able to zip up a folder containing an index.html file and related scripts/assets.

There's a PR [here](https://github.com/hicetnunc2000/hicetnunc/pull/208) that is very close to complete but needs a bit of work, so hopefully that will be done soon. Stay tuned!

**Comment by SandroMiccoli** [comment]
OK, great! Thanks for the reply @pichiste, will keep an eye on that PR! :)

**Comment by andrevenancio** [comment]
Once the HTML is released we'll release some templates with best practices.
