### ISSUE TITLE
change IPFS gateway to another one that allows videos

### ISSUE THREAD

**Issue by martinpospech** [hicetnunc2000/hicetnunc#22]
WebM file mints fine, but then is not displayed in the website, since the Cloudflare gateway gives: `ipfs: video streaming is not allowed`. Switch to another gateway that works with videos to fix this. I tried `https://dweb.link/ipfs/<hash>` and it seems to work fine.

File for testing: https://www.hicetnunc.xyz/objkt/841

**Comment by andrevenancio** [comment]
Depending on the browser the user is using they might not be able to see that asset. We can add the mimeType to the list of acceptable video mimetypes but then we're excluding users using this browsers https://caniuse.com/?search=webm

**Comment by andrevenancio** [comment]
this has been done.
