### ISSUE TITLE
Posibility to favorite artists 

### ISSUE THREAD

**Issue by PureSpider** [hicetnunc2000/hicetnunc#224]
As the title says - a followup for this would be to have a separate "favorite" stream, next to "all".

**Comment by PureSpider** [comment]
See also #49

**Comment by gianflavio** [comment]
Yeah, a way to follow or favorite artists would be great. Maybe even a Timeline or filter where you only see your favorited artists' creations or collections.

**Comment by violetforest** [comment]
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/49
