### ISSUE TITLE
Meta data 'Title' shown in wallet for sold NFT

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#225]
When purchasing an NFT the title of the work is shown when it is added to the buyer's wallet.
Is it possible to show the title of a sold work when the tez is added to the seller's wallet. 

Right now it says:
Received x.xx tez from Hic et nunc minter.
I'm not sure if there is a way to see which work sold?

Of course, it would be great to see the collector's address in the from field but I understand the transaction happens from hic et nunc minter because it is holding the swap tokens.

![Screen Shot 2021-03-23 at 9 09 31 AM](https://user-images.githubusercontent.com/17106015/112151352-80bbcf00-8bb7-11eb-8f48-01377761bf98.png)

**Comment by andrevenancio** [comment]
This is something specific to your wallet not the hicetnunc website.

**Comment by raynt** [comment]
Good to know, was curious if the data is being made available to the wallet. I'll test some other wallets.
