### ISSUE TITLE
list of fixes

### ISSUE THREAD

**Issue by crzypatchwork** [hicetnunc2000/hicetnunc#226]
some fixes that we need that are UI related.

- [x] display model/gltf+json from older objkts
- [x] **infinite scroll on random/hDAO/latest feeds**
- [x] max vh and no max vw or full screen on /objkt page
- [x] preview/mint fixes
- [ ] **multiple resolution formats on metadata/displayUri for mp3**
- [x] persistent sync (me)
- [ ] cancel swap fixes/burn (me)
- [ ] secondary market (me)
- [ ] mint from a mobile/grids for mobiles

**Comment by andrevenancio** [comment]
I'll pick up some of these tonight. first one is done!

**Comment by mescalina** [comment]
Possibility to see the history of prices paid for an OBJKT or at least the last price paid (With the date)

**Comment by mescalina** [comment]
When you want mint an OBJKT you get redirected to an intermediate page with the mint button on it. In this page you cannot see the title, the description and the quantity specified in the previous page. It would be cool to see all this information also on this page so you can double check that everything is correct.

**Comment by mescalina** [comment]
When you mint an OBJKT if you leave the "amount" field empty you end up minting an NFT with 0 as amount value actually wasting a transaction (Maybe there is an utility in minting a 0 amount NFT that I cannot see). The page should at list alert the user when the amount is 0.

**Comment by crzypatchwork** [comment]
infinite scroll is a easy one ppl
