### ISSUE TITLE
Tezos Faucet /  obtaining Tezos

### ISSUE THREAD

**Issue by Hamburgerhans** [hicetnunc2000/hicetnunc#229]
I understand that the faucet in question is depleted, which is not a problem, however I seem to find it difficult to boy Tezos. I have some in my binance wallet but am unable to transfer them to the Tezo Blockchain. Any ideas how to get that done? any help is highly appreciated. thank you!

**Comment by crzypatchwork** [comment]
you would need to install Temple, Kukai, Galleon or AirGap wallet to interact with the dApp at the present state. You should create a public address with them and keep your private seed/key safe. You'll have a tz public address with which you can transfer Tezos from Binance or other exchange to it.

the interaction from wallets with the dApp happens following this standard [TZIP-10 Wallet Interaction Standard](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-10/tzip-10.md)
