### ISSUE TITLE
HELP! Minted and Swaped, but it appears "not for sale" 

### ISSUE THREAD

**Issue by Gigas807** [hicetnunc2000/hicetnunc#240]
Theres already 4 objkts I've swaped, the transaction went through and it didnt appears as for sale. I dont know more what to do, somebody please help

**Comment by glkt** [comment]
I confirm this issue on my side. Also, all newly minted OBJKTS since 12004 show as "editions : /0". Looks weird

**Comment by travisleroy-gh** [comment]
I also have an issue similar. I canceled a token and they went back to my wallet but then after I swap them again it still says "not for sale" seems to have gone through my Temple wallet okay

**Comment by glkt** [comment]
Looks like a UI display problem for newly minted OBJKT. The "not for sale" is actually clickable and will open a wallet popup asking for the correct amount.
