### ISSUE TITLE
Burning all editions vs. burning some editions

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#243]
When an artists decides to burn tokens, she could decide:

a. to burn all editions of a token, while he didn't yet sell a single edition
b. to burn all remaining editions, while she already sold at least one edition or to burn only a part of the remaining editions

These two cases should be treated differently on the UI level. The proposal could be:

a. if all editions of a token (eg 10/10) are to be found on the "official" burn address, the NFT completely disappears from the platform
b. if less than all editions of a token (eg 9/10) can be found on the "official" burn address, a marker is added to the artwork (on all views) that indicates there was a partial burn.

That would probably be enough for a start to help artists and collectors to have a transparent burn process. On partially burned editions users could still check the owners to see how many were burned 🔥.

**Comment by crzypatchwork** [comment]
I believe the first version of this implementation will burn all NFTs in one's possession.

**Comment by andrevenancio** [comment]
done
