### ISSUE TITLE
I want to change my website url from my artists profile.

### ISSUE THREAD

**Issue by Abhinav427** [hicetnunc2000/hicetnunc#248]
I want my website link to be this - https://www.artstation.com/abhinavtyagi

My account details:
https://www.hicetnunc.xyz/tz/tz1XxLT26NCaaYpqnq5hpdST9gyKfFf5SQ4J

**Comment by andrevenancio** [comment]
Please read the FAQ's the account information is not managed by us but https://tzkt.io/

In fact you would have already contacted them the first time around to add your details. So just need to contact them again.
