### ISSUE TITLE
can't edit my assets

### ISSUE THREAD

**Issue by babypicasso** [hicetnunc2000/hicetnunc#256]
hello. i created two assets but i need to edit them. the menu bar is gone. i can't see anything like burn/swap/edit etc.

what should i do?

thanks

**Comment by andrevenancio** [comment]
Press your wallet ID above next to the hamburger menu. It should automatically display the menus after that.

**Comment by babypicasso** [comment]
i think still i can't see. thanks.

**Comment by babypicasso** [comment]
https://www.hicetnunc.xyz/tz/tz1X9AWSPUZfsAT9m9Vh3UuNdU15cYS8vyAS
