### ISSUE TITLE
HTML: get('viewer') still returns false even if user is sync

### ISSUE THREAD

**Issue by antinomy-studio** [hicetnunc2000/hicetnunc#259]
Great job at adding HTML support! This is very interesting.
I've added a quick test demo to try it out, and I am still getting 'false' even if my wallet is synced.

```javascript
// If you want to create OBJKT's with different seeds, you can access the creator and viewer wallet ids. This values will only be injected once the piece has been minted
// they will not work locally.
// if the user is not sync, the viewer comes in as false
const creator = new URLSearchParams(window.location.search).get('creator')
const viewer = new URLSearchParams(window.location.search).get('viewer')
```

![Screen Shot 2021-03-25 at 5 01 59 PM](https://user-images.githubusercontent.com/58088022/112504220-dea11000-8d8b-11eb-87df-b784c4ff11f5.png)

You can see it here: https://www.hicetnunc.xyz/objkt/12796

Any ideas why?
Cheers!

**Comment by PureSpider** [comment]
Click the adress to sync and the variable will be set
