### ISSUE TITLE
Minted objects but not showing issuer

### ISSUE THREAD

**Issue by f1nasf1** [hicetnunc2000/hicetnunc#260]
Hello,

I minted the following objects but my address does not show as issuer:

https://www.hicetnunc.xyz/objkt/12352
https://www.hicetnunc.xyz/objkt/12333
https://www.hicetnunc.xyz/objkt/12330

Here is my address:
https://www.hicetnunc.xyz/tz/tz1fFCF6FogyPLLjSk3FNTG7gVdDWfPCWVni

And here are the transactions showing the above objects:
https://tzkt.io/tz1fFCF6FogyPLLjSk3FNTG7gVdDWfPCWVni/operations/

Thank you,
f1nasf1

**Comment by andrevenancio** [comment]
When did you mint this? the creator is coming up as null

**Comment by f1nasf1** [comment]
I minted it yesterday.  You can check the transactions in the tezos explorer above.

**Comment by crzypatchwork** [comment]
this happened in the moment we were having an update and such info unfortunately was not registered in the metadata (it was a timelapse of 45 minutes~ ). I would suggest to await the burning feature till the end of the week-weekend. and possibly do a remint of it. any help we're at disposal.

**Comment by f1nasf1** [comment]
but how can I burn those if my address is not showing as the issuer? :)

**Comment by andrevenancio** [comment]
I think you can do it from your wallet. by sending it to the burn wallet. am I right @crzypatchwork ?

**Comment by f1nasf1** [comment]
Aha, right.  What is the burn wallet address? This should work.

**Comment by andrevenancio** [comment]
This is how we're calling the [burn](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/context/HicetnuncContext.js#L153) feature. the burn wallet address is `tz1burnburnburnburnburnburnburjAYjjX`

**Comment by andrevenancio** [comment]
Also, apologies. we messesdup yesterday when uploading the HTML the first time around (I think it might have been me). sorry.

**Comment by f1nasf1** [comment]
Is it ok to try and upload those art pieces again and mint them?
