### ISSUE TITLE
OBJKT 12609 Link Not Working

### ISSUE THREAD

**Issue by mrseiden** [hicetnunc2000/hicetnunc#262]
Hi Hic Et Nunc,

Thank you so much for creating this platform. I minted my first piece last night. A few friends told me just now that unfortunately, when they type in or click the link to my piece from an art site, it's broken. Oddly enough, it's working for me on desktop. I cleared my cache to make sure. But on my iPhone, all I'm seeing is a blank screen from the link. Please let me know why this might be happening for them on desktop and me on phone, and if there's a good workaround.

Thanks,
Miles

**Comment by andrevenancio** [comment]
Is there any chance you can provide a bit more feedback? Like the objkt number? Otherwise its hard to guess.

**Comment by PureSpider** [comment]
It says "OBJKT 12609" in the issue title.

**Comment by mrseiden** [comment]
Hi there, thank you so much for writing back. The issue seems to be resolved now!
