### ISSUE TITLE
Accidentally Swap'd OBJKT

### ISSUE THREAD

**Issue by tomvona** [hicetnunc2000/hicetnunc#266]
Hello!
I accidentally swapped an Object from my collection. I am not the creator, I bought the object some time ago from the creator and it was in my collection until recently. 
My Adress: tz2Lqs8WFf2HDG1RoxG3EAtuHjDS27XQANWT
Transaction ID: oom9gVZm74qrEyVr37A1rcnou528LywUf1jEQe8fWk27ysoQWhT
Object i swapped: 
https://www.hicetnunc.xyz/objkt/477

Am i still the owner of the product? 
If not, is there the possibility to undo this mistake..
Thank you very much!

**Comment by crzypatchwork** [comment]
yes, you can undo the swap :) there will be changes in the UI to better visualize it.
