### ISSUE TITLE
"not for sale" Bug

### ISSUE THREAD

**Issue by dreizehnutters** [hicetnunc2000/hicetnunc#273]
Many NFTs appear to be "not for sale", but if you click the button you can purchase the work.

examples:
https://www.hicetnunc.xyz/objkt/12323
https://www.hicetnunc.xyz/objkt/14751

hash of "illegal" transaction: [opBVFbReK6wxNa8Lwkdez5HhjRPhix3w4JKutH3nHLsyVzRcwuo](https://tzkt.io/opBVFbReK6wxNa8Lwkdez5HhjRPhix3w4JKutH3nHLsyVzRcwuo)

**Comment by daveyang** [comment]
Happened to me also. It was my freebie for #OBJKT4OBJKT today:

https://www.hicetnunc.xyz/objkt/14850

24 of 25 were taken, then 1/25 showing with Not for Sale. I clicked on it and was charged 6.00 tez (roughly USD 24.66)!

opMa6JJ3QmEMv62tWvRQoy8matBESVQcsnoUcWsgQMrHvumKqWK

**Comment by crzypatchwork** [comment]
pls take care while signing a transaction. this issue is gonna be debugged as it's in production, there being a partical misconfiguration on swaps because of the secondary market. I'll return with updates in this issue for both of you.

**Comment by daveyang** [comment]
@crzypatchwork Thanks for looking into this. Galleon (my wallet) is showing that I purchased my own freebie for 6.00 tez:

<img width="786" alt="Screen Shot 2021-03-27 at 8 59 39 PM" src="https://user-images.githubusercontent.com/347403/112739124-b6f2a900-8f3f-11eb-95c9-e0cff5063895.png">

**Comment by dreizehnutters** [comment]
@crzypatchwork
I signed the transaction so it is my fault + I want to keep the token.
I just made the issue to help other collectors.

**Comment by skenaja** [comment]
This now resolved, the Collect tab on the OBJKT display page now shows lowest available price
