### ISSUE TITLE
Add Gitlab CI

### ISSUE THREAD

**Issue by guidoschmidt** [hicetnunc2000/hicetnunc#28]
Would be nice if the repo had a CI job running for error checking and auto deployment. Doesn't even have to be Github CI

**Comment by andrevenancio** [comment]
This is a good idea. We could use git-flow approach doing PR from feature branches into `develop` and once we're happy with the develop branch merge it to `master`. That will kick up the CI and deployment.

**Comment by andrevenancio** [comment]
Closing this for now. thanks for the suggestion
