### ISSUE TITLE
Blank screen - warning hidden under fixed header

### ISSUE THREAD

**Issue by codewithfeeling** [hicetnunc2000/hicetnunc#283]
I'm getting this a lot today on both mobile and desktop:

![image](https://user-images.githubusercontent.com/262516/112751017-966c3280-8fc3-11eb-881a-65201b62d9a6.png)

The message "verify your operations while executing transactions." is hidden under the fixed header.

It should also show something more helpful on how to resolve - "Please unsync and resync your wallet" as that appears to be the only solution.

**Comment by Quasimondo** [comment]
Probably related, I only get an empty page when clicking on "manage assets" and can only get to my profile page by directly entering the full address with my wallet id.

**Comment by skenaja** [comment]
My workaround after blank screen was to click the tz... link, then click "manage assets" again - this populated the wallet id into the URL rather than the empty `https://www.hicetnunc.xyz/tz/` url.

**Comment by skenaja** [comment]
I've been able to reproduce the error.

1. visit an objkt page eg https://www.hicetnunc.xyz/objkt/15463
2. force refresh the page (ctrl+F5)
3. menu > manage assets

expected: 
- my list of assets at `https://www.hicetnunc.xyz/tz/tz....`

actual: 
- URL changes to `https://www.hicetnunc.xyz/tz/`
- blank page as per [screenshot](https://github.com/hicetnunc2000/hicetnunc/issues/283#issue-842721435) in first comment

**Comment by codewithfeeling** [comment]
> My workaround after blank screen was to click the tz... link, then click "manage assets" again - this populated the wallet id into the URL rather than the empty `https://www.hicetnunc.xyz/tz/` url.

Actually this works and is way quicker.
