### ISSUE TITLE
Storage quota exceeded for the operation

### ISSUE THREAD

**Issue by evilpupil** [hicetnunc2000/hicetnunc#286]
Hi,
I'm getting this error a lot for the past 2 days.

Storage quota exceeded for the operation
A script or one of its callee wrote more bytes than the operation said it would

1st I tried to upload a 34mb MP4, 3 times without success. I tried a fourth time and it worked this morning. Then I tried to upload a 7mb PNG and got the same error. 

Thank you

**Comment by andrevenancio** [comment]
This error is on your wallet not on the platform itself.
