### ISSUE TITLE
two instagram logo on my profile

### ISSUE THREAD

**Issue by onurshafak** [hicetnunc2000/hicetnunc#287]
hello. @TezosBakingBad verified my profile but on my profile it looks like i have two same instagram button. i asked him, he said it looks fine on his side and he showed me, my tez wallet profile but what can problem be? thanks. 

this is my profile
https://www.hicetnunc.xyz/tz/tz1NrRdCofDBpPGNqUc2UVkckLCwQNqvkTz1

<img width="1280" alt="Screenshot 2021-03-28 at 16 36 01" src="https://user-images.githubusercontent.com/81525876/112759694-14dcca80-8fec-11eb-8b86-b7c78ceb887d.png">

**Comment by onurshafak** [comment]
@skenaja so i didn't understand. where should i paste that code? sorry.

**Comment by skenaja** [comment]
Thanks for reporting the bug. A developer has made a fix for it in https://github.com/hicetnunc2000/hicetnunc/pull/282, and it is just waiting to be deployed to the hicetnunc website

**Comment by onurshafak** [comment]
> Thanks for reporting the bug. A developer has made a fix for it in #282, and it is just waiting to be deployed to the hicetnunc website

thank you.

**Comment by VartanMarkarian** [comment]
![2](https://user-images.githubusercontent.com/81528775/112762283-84ac7e80-9007-11eb-8782-130b09471217.jpg)
 Good day! I have the same problem with two Instagram accounts, is it possible to fix it and add a link to a personal website? And is it possible to add a link to the FB as well? Thanks!

**Comment by LeithBA** [comment]
The double Instagram issue is now fixed!

@VartanMarkarian please fill [this form](https://docs.google.com/forms/d/e/1FAIpQLSdlHVqzIxPFL-gAXNxEefyBtI3g3_wiCgcf80bX4tYsXC7b5A/viewform) to add your website and fb links.

FB links are not supported on hicetnunc yet but they will be soon
