### ISSUE TITLE
Different avatar than what I uploaded

### ISSUE THREAD

**Issue by mauriciomessa** [hicetnunc2000/hicetnunc#290]
I had uploaded an image for the avatar in the form I filled out. But the same image as my Tezos Explorer profile appears on my profile. Can I change?

**Comment by ries9112** [comment]
This is managed by Baking Bad, you should contact them I think: https://twitter.com/TezosBakingBad

**Comment by LeithBA** [comment]
You can also [fill this form ](https://docs.google.com/forms/d/e/1FAIpQLSdlHVqzIxPFL-gAXNxEefyBtI3g3_wiCgcf80bX4tYsXC7b5A/viewform) to edit your tzkt profile
