### ISSUE TITLE
Add burn address to blocked list?

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#303]
We can currently view the nft graveyard https://www.hicetnunc.xyz/tz/tz1burnburnburnburnburnburnburjAYjjX 
Is this desired? On the one hand, it's interesting to see, on the other, if people are burning it means they want to remove that token, so keeping it around via the burn address is counter to that.

**Comment by djangobits** [comment]
I think it's ok, because then it's transparent what's on the burn address.

**Comment by djangobits** [comment]
I'll close this for now.
