### ISSUE TITLE
Sold instead of "not for sale"

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#31]
Is it possible to state "Sold" instead of "not for sale" once the edition is sold out. I saw this on one of my sold-out editions and made me think there was an error.

**Comment by andrevenancio** [comment]
From what I understand, from when a user mints an NFT until they curate it, that's when you see that "not for sale" message.

Are you suggesting if a user sells it to display another message instead?

**Comment by raynt** [comment]
I believe this edition of mine (10) sold out but then switched back to "not for sale"
https://www.hicetnunc.xyz/objkt/1000

I just checked and it is allowing me to curate it again.

**Comment by djangobits** [comment]
**not for sale** could mean all which were up for sale were sold but it can also mean that the NFT has net yet been put up for sale. I think that ambiguity is necessary at the moment. Beacuse if you wanted a clear overview of how many were sold, how many stay with the creator, you would need to pull data about all sales from the block explorers api. Thats way more to do than just to check how many are up for sale. 

@raynt did you put up all 10 for sale on the first time curating? I guess not, thats why you had the possibility to curate again...

**Comment by raynt** [comment]
Thanks for the comment @djangobits 
I missed the fact that you could list a portion of the edition when you choose to "curate". I now understand that when you mint the coin initially that sets the number of the edition and curate means how many are being released at that time.

The release I mentioned in the previous post had 10 pieces minted and when curated I released all 10. I remember seeing them sell and when I checked back it says 'not for sale'. I have to learn to use the block explorer to confirm the specific sales but when I add up the total sales it appears that the edition did sell all 10 and says 'not for sale'
