### ISSUE TITLE
Dependabot target branch configuration

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc#310]
Dependabot currently creates pull requests targeted on `main` branch (Eg https://github.com/hicetnunc2000/hicetnunc/pull/304 )

Should the target branch not be `develop` given the use of git flow?

This allows a check for tests/compatibility issues prior to deploy

**Comment by andrevenancio** [comment]
I shouldn't be a problem afaik

**Comment by andrevenancio** [comment]
I changed the default branch to be develop, but someone else changes it back to main. I'm assuming @crzypatchwork
