### ISSUE TITLE
HTML template is returning "false" for "NFT viewer" when "sync"

### ISSUE THREAD

**Issue by SandroMiccoli** [hicetnunc2000/hicetnunc#311]
This was ok and working yesterday but now two of my OBJKTs ([15459](https://www.hicetnunc.xyz/objkt/15459) and [9340](https://www.hicetnunc.xyz/objkt/9340)) that use the viewers hash aren't working properly:

![image](https://user-images.githubusercontent.com/2353389/112898553-44213380-90e1-11eb-9d38-b5151fcccdbf.png)

Actually, what's happening is that when the page initially loads, the "viewer" returns the right value and displays the correct image. But when the user clicks on their hash (old _sync_), the "viewer" returns "false", rendering a wrong image.

Not sure if this is a bug or if I messed up with this line:

```js
const viewer = new URLSearchParams(window.location.search).get('viewer')  || 'tz1Q4r6CMMNRvvQBZUFU5za4aTFZpC43rX8G'
```

Any ideas?

**Comment by andrevenancio** [comment]
Yes. the viewer is not logged in properly. they need to click on the sync button again.

**Comment by andrevenancio** [comment]
you should expect viewer=false if people are looking at your nft and aren't logged in.

**Comment by SandroMiccoli** [comment]
Thanks for the reply @andrevenancio!

Sorry to come back at this, but something seems a little odd:

If I open one of these objects  ([15459](https://www.hicetnunc.xyz/objkt/15459) or [9340](https://www.hicetnunc.xyz/objkt/9340)), they display correctly, since I'm logged in properly.

But, if I click on my hash (the old "sync" button), I receive viewer=false. But I'm logged in.

On the print I posted initially you can see that the viewer returns the correct value when loading for the first time, but when I click on "sync", it returns false.

Am I missing something here?

**Comment by SandroMiccoli** [comment]
Hey @andrevenancio, sorry to keep insisting on this, but I strongly believe that somethings is not right here...

I just minted a new object ([23092](https://www.hicetnunc.xyz/objkt/23092)) and it's behaving the same way. I added a different logic to it, creating a conditional to test if the viewer value was "null" or "false", and apparently, that's happening when the user clicks on their ID to try to sync...

Here's a print that shows that the first time the page loads, the NFT viewer returns the correct value:

![image](https://user-images.githubusercontent.com/2353389/113521310-f0a75d80-9598-11eb-8fb2-0f8170a512e3.png)

But after clicking on my ID ("old sync"), it returns "null":

![image](https://user-images.githubusercontent.com/2353389/113521321-03219700-9599-11eb-94f2-54934e03fd93.png)

This is how I'm dealing with the viewer value inside my code:

```js
const creator = new URLSearchParams(window.location.search).get('creator')
let viewer = new URLSearchParams(window.location.search).get('viewer')

if (viewer==null || viewer==false) {viewer='false'}

console.log('NFT created by', creator)
console.log('NFT viewed by', viewer)
```

Any ideas of what's causing this?
