### ISSUE TITLE
Minted art has disappeared from my profile, but appears in other users' collections

### ISSUE THREAD

**Issue by ArtZumo** [hicetnunc2000/hicetnunc#313]
This minted art has disappeared from my hic et nunc profile, but it appears in the collections of the users who collected it.

https://www.hicetnunc.xyz/objkt/14211

**Comment by andrevenancio** [comment]
Seems like you burned it right?

**Comment by skenaja** [comment]
One of the 5 copies [was burned](https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=14211), so it's a duplicate of #280
