### ISSUE TITLE
i minted a 35 serie but appears 0 not for sale and it have no collectors

### ISSUE THREAD

**Issue by YgorMarotta** [hicetnunc2000/hicetnunc#314]
i minted a 35 serie but appears 0 not for sale and it have nothing to swap.
anyone have experiencing this?

https://www.hicetnunc.xyz/objkt/17036

**Comment by mcnft** [comment]
Aconteceu comigo tambem. Mintei novamente mas aconteceu 2 vezes. nao consigo apagar.

**Comment by rancherodulce** [comment]
im having the same exact issue. in my wallt the token is labeled as "unknown token" and it wont show token metadata on my kukai wallet. 

https://www.hicetnunc.xyz/objkt/17056

**Comment by mcnft** [comment]
https://www.hicetnunc.xyz/objkt/17063

**Comment by mcnft** [comment]
https://www.hicetnunc.xyz/objkt/17046    nao consigo apagar nenhum dos 2.

**Comment by joeantani** [comment]
> im having the same exact issue. in my wallt the token is labeled as "unknown token" and it wont show token metadata on my kukai wallet.
> 
> https://www.hicetnunc.xyz/objkt/17056

same problem here: https://www.hicetnunc.xyz/objkt/17082
listed 36 of them, it shows 0 and not for sale. Not able to burn. I had to re mint it so now I have two of them on my creations.

**Comment by monotype13** [comment]
Same issue, I minted an edition of 50 but it displays 0 and not for sale, no option visible to swap or burn: https://www.hicetnunc.xyz/objkt/17010

**Comment by destroysound** [comment]
same symptoms here, all of these seem to be close in id so i am guessing its the same issue

https://www.hicetnunc.xyz/objkt/17037

**Comment by mvsc1** [comment]
same issue!

https://www.hicetnunc.xyz/objkt/17557

**Comment by shig2k1** [comment]
I also have this issue
https://www.hicetnunc.xyz/objkt/17579

**Comment by YgorMarotta** [comment]
report:
now it appears the option for swap, and it have 35. i choose 10 and swaped for 4 tezos. 
but now appears 45 copies. automatic add 10 more copies to that nft. I 
so i cancel swap and tried to burn, i tried twice.
now my feed have 2 fenix, OBJKT#17036 (x35) and OBJKT#13402 (x1)

**Comment by shig2k1** [comment]
This is fixed for me now.
