### ISSUE TITLE
All OBJKTS Missing

### ISSUE THREAD

**Issue by pandar511** [hicetnunc2000/hicetnunc#318]
I am unable to see any of my creations or my collections in the manage assets tab. The tokens are in my Kukai wallet, and able to be previewed. Also if I use a direct link with my OBJKT number in it, I am able to view it.

**Comment by pandar511** [comment]
Edit: I am able to preview the NFTs in Kukai, but nothing shows up in my creations or collections still. I attempted to mint a new NFT and its on the blockchain, but not showing up

**Comment by skenaja** [comment]
@pandar511 what's the wallet address and/or objkt number?

**Comment by pandar511** [comment]
tz2WYko4XXaV4B5mzjguTeRkkgw8LyB2jA2d

**Comment by andrevenancio** [comment]
The API isn't returning anything for you.

**Comment by pandar511** [comment]
I was able to access this via an old link. It shows that I issued the OBJKT
but if hit the creation link it’s doesn’t show up.

**Comment by djangobits** [comment]
@pandar511 It is because your wallet is banned. 

It was because of this piece:
https://www.hicetnunc.xyz/objkt/3266

Minted here:
https://tzstats.com/onfrrCHtncvTbFE85AUz5SaS7snnq4juBRHAnSvKu7cPceHKZpm/42880990

on IPFS here:
https://ipfs.tzstats.com/ipfs/QmTvyUjjXqLzoM7fgavqTEXU7Cjrtt2RpRrhrtJ1Jm9xCz

Google reverse search shows that it it is a widely distributed wallpaper image, that can be found in bigger resolutions and crop sizes on various pages. On the risk that you might be the original creator, I decided to ban.

Are you the original creator?

**Comment by pandar511** [comment]
Yes I am the original creator. This image is something I created over 10
years ago

**Comment by djangobits** [comment]
Well @pandar511 anonymous accounts posting widely available wallpapers (and nothing else) are usually three red flags. Is there a portfolio or a website or an instagram account where you have other works?

**Comment by pandar511** [comment]
If it’s wide usage is cause for an issue I can unmint that particular piece
and stick to some of my more recent non-commercial art

**Comment by pandar511** [comment]
My Twitter handle is ziggo511 and that is NOT the only thing that I had
minted. That was my second piece that I minted and then I minted a third
that was an original hand drawn image.

**Comment by pandar511** [comment]
And the first image I minted was an original photo of campfire using copper
to alter to colors of the flame.

**Comment by djangobits** [comment]
@pandar511 all good. Sorry for having blocked your pictures. I did it because I've seen so many red flags. If the picture is your, then it's Ok. It's just one of the situations that shows us the limits of checking (a task I hate anyway).

**Comment by djangobits** [comment]
I removed it, should be visible within some minutes.

**Comment by pandar511** [comment]
Thank you kindly :) I’m sure you guys constantly have to be on your toes
checking for these things. It’s got to be tiring at times. Thanks for your
work :)
