### ISSUE TITLE
Royalty rate selectable when minting.

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#32]
Original the minter was able to select the chosen royalty rate. I assume this was removed for a production reason as the buyer would need to see what the royalty rate is if it's not static.

**Comment by andrevenancio** [comment]
Why would be buyer need to see the royalty rate? It should be easy to add next to the rest of the info. @crzypatchwork thoughts?

**Comment by raynt** [comment]
The buyer should be aware of the royalty rate the artist is claiming. Some collectors will want to know this as it affects future sales. What if the artist claimed 100% royalty rate?

**Comment by andrevenancio** [comment]
I think @crzypatchwork changed so now a 10% royalty is pre-defined

**Comment by crzypatchwork** [comment]
there's a limit of 25% for royalties. I've set 10% as default on th UI to avoid bugs which sometimes were even combined with this issue https://github.com/hicetnunc2000/hicetnunc/issues/36

it would be interesting to set royalties displaying on the objkt page. but it's a matter of UI also. I could try to bring this info with the API.

**Comment by andrevenancio** [comment]
When you have it on the API, assign it to me.

**Comment by crzypatchwork** [comment]
k gonna aggregate it

**Comment by mlsnark** [comment]
Question related to royalties.  I'm assuming that the current contract only issues the royalty % to the creator.  We have a couple of projects where the artist wants to split the royalty between them and an artist foundation.  I'm assuming this is very custom, just curious how complicated such additional functionality would be to add?  Essentially to specify additional wallets to split the royalty.

**Comment by raynt** [comment]
@mlsnark Split royalties would be a great option to have, just remember once they are in the contract they are set. So if the artist's foundation closes or something happens to their wallet the secondary sales royalty will be lost. It might be best for you to act as a guardian and transfer the sales once they come in? You can then exchange TEz to whatever currency the foundation needs as many won't know what to do with Tez (at least right now)

**Comment by mlsnark** [comment]
@raynt Thanks.  I get that, just not always logistically easy to do, so the preference is to decentralize/automate the process.  Similarly we work with artist collaborations (where the creator is a team of individuals) and no one wants to be the custodian in charge of splitting the proceeds, especially when collaborations are temporary but the work is theoretically permanent.

**Comment by raynt** [comment]
Agreed, collaborative royalties will be a game-changer. Interested to hear how difficult it would be to implement. I know there's a lot of ETH-based platforms that have been talking about it for a while and haven't implemented so there may be some roadblocks, maybe Tezos is different.

**Comment by crzypatchwork** [comment]
such split would be based on a new smart contract which would be interesting to develop with the community

**Comment by mlsnark** [comment]
I believe that the best way to develop this is to allow the setting of:
1. Overall royalty % on the token level ("royalty")
2. Allow the artist to then specify 1 or more wallets and the corresponding % ("royalty_wallet_1", "split_pct_1", ... , "royalty_wallet_N", "split_pct_N") such that the sum(split_pct_1, ..., split_pct_N)=1.

And then the flow should be fairly simple.  Let's say I'm a team of creators or I'm an artist that wants to split royalties with someone.  I set the royalty at 10% for example.  And specify the Artist Wallet at 80% and another Additional Wallet at 20%.  When the sale happens (let's say for $1000), the smart contract would send $900 (90%) to the seller and the royalty of $100  (10%) would be split between the artist $80 ($1000x10%x80%) and the additional  wallet $20 ($1000x10%x20%).  

The artist can set this up to any configuration of royalty % and the split for some reasonable number of collaborators and do this on the token level.  Also think about so many musical compositions or video artworks that include small teams whose individual creativity goes into a single tokenized digital creation.  They can all agree and then program the token appropriately.      We are certainly looking for this functionality for our platform and have a number of projects that would fit this model of distribution and artist royalty mechanics.

**Comment by dribnet** [comment]
> there's a limit of 25% for royalties. 

Why this limit on royalties? Having the platform enforce any particular royalty limit seems like an unnecessary restriction.

**Comment by raynt** [comment]
Now that royalty rates are adjustable up to 25% it should be listed on the OBJKT sale page.

**Comment by skenaja** [comment]
> Now that royalty rates are adjustable up to 25% it should be listed on the OBJKT sale page.

This has now been logged as #449

**Comment by Quasimondo** [comment]
> Why this limit on royalties? Having the platform enforce any particular royalty limit seems like an unnecessary restriction.

I agree with @dribnet - except for certain technical limitations (like making sure that the 2.5% platform fee is still payable) this limitation seems arbitrary. I would like to know the rationale behind this.

**Comment by skenaja** [comment]
It's technically amendable, but would need a new version of the smartcontract. You can see the limitation hardcoded here:

https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/code

`  { PUSH string WrongCondition: (((params.amount > 0) & ((params.royalties >= 0) & (params.royalties <= 250))) & (sp.len(params.metadata) == 53)) & (params.amount <= 10000) ;`

**Comment by Quasimondo** [comment]
Oh well, looks like nothing we can do about this now. Off-topic, but I how would a transition to a new version of the contract work? Would the old contract first have to uncurate all swapped OBJKTs and then everyone would have to reswap them manually?

**Comment by andrevenancio** [comment]
I'm sure Rafael choose it with something in mind.

but what would the percentage be like then? 100%? So I buy something for 1 tez, I resell it for 2 tez and with royalties set to 100% means that I make no money the artist already sold the piece in the first place. this are royalties over sales as the art moves hands. Which, I'm not sure happens in the Art world? (might be wrong on that).

**Comment by DevopsSnark** [comment]
Being from the art world and running a platform on Ethereum for 3 years, I would say that there are certainly projects where a high royalty (even a 100%) can be an artistic element of the artwork.  But realistically, oftentimes the collectors are unaware of the embedded royalties and find out about them only when they try to sell the art, so the royalty mechanic and its size need to be VERY transparent.  On Ethereum most platforms right now are gravitating towards about a 10% level so that it is consistent across all artworks on the platform, which helps with the transparency for the collectors.

**Comment by mlsnark** [comment]
Being from the art world and running a platform on Ethereum for 3 years, I would say that there are certainly projects where a high royalty (even a 100%) can be an artistic element of the artwork. But realistically, oftentimes the collectors are unaware of the embedded royalties and find out about them only when they try to sell the art, so the royalty mechanic and its size need to be VERY transparent. On Ethereum most platforms right now are gravitating towards about a 10% level so that it is consistent across all artworks on the platform, which helps with the transparency for the collectors.

**Comment by Quasimondo** [comment]
@mlsnark I agree that the royalties for a piece should be clearly visible which is why I added #449 as a feature request

@andrevenancio Of course 100% would only be a artistic statement, but some people actually suggested that number for free OBJKT giveaways. I think the number should have allowed up to 50%, but higher values are not total fantasy, for example Dadabots has 80% artist royalty.

**Comment by andrevenancio** [comment]
If the royalties param comes in the API, I'll be able to do it on my end. If not, it requires @crzypatchwork to help out.

**Comment by skenaja** [comment]
I'm going to close this ticket as royalties can now be specified when minting (which was the original issue).

Feel free to raise feature requests for alternative approaches discussed here (eg royalties splitting), but check first to ensure they've not already been requested.
