### ISSUE TITLE
Recent collectors are not appearing at the OBJKT page

### ISSUE THREAD

**Issue by ArtZumo** [hicetnunc2000/hicetnunc#325]
Recent users who collected the OBJKT are not appearing and the number of collections still the same.

Example:
https://www.hicetnunc.xyz/objkt/15670

Interaction of the last OBJKT minted available:
oor4xrrk4n9Vpv85NJpZ1XM8y5VVaaz2K1CxUiixhwka9dvyrky

**Comment by mathMakesArt** [comment]
It can take some time for the web UI to update and reflect new transactions. Typically this takes 5 minutes or less, but in my experience it can sometimes take longer.

Could you respond to indicate whether this issue is still occurring after 2 days?
If not, can the issue be closed?
