### ISSUE TITLE
OBJKTs not transferring to collection

### ISSUE THREAD

**Issue by codewithfeeling** [hicetnunc2000/hicetnunc#327]
I bought a few copies of wxly's "Cellular automata". One the other day, then 2 more today.

The transaction IDs are:

1. opGv8fQqwD5TmKfrsQC5SxSZwotqhp6L9HSDp6WREPBmSNaeqPP
2. oneSANeuKrJAEwufN4jzJJAth9EKRsXQFGYLKnimwrviv48d2Y8

My Temple wallet shows -1ꜩ, +1 OBJKT for as you'd expect, and I should have 3 in total. However, they are not showing in my collection, the collector list on the creator page shows me with ONE objkt, and the edition count is wrong on the creator page.

![image](https://user-images.githubusercontent.com/262516/113025730-2eaf1680-9180-11eb-86e3-c839f425fe78.png)

![image](https://user-images.githubusercontent.com/262516/113025355-c3654480-917f-11eb-9bc0-60f2d0c9e4b5.png)

Is this a common issue and how can it be resolved? I also still have pieces that I've lost while trying out secondary market features, but I assume this is because once I've swapped 1 OBJKT with only 1 in my possession, I am no longer seen as the owner of that asset. Hopefully this will resolve soon.

**Comment by MarkusLaeng** [comment]
Is that still the case? somtimes the status is not up to date

**Comment by codewithfeeling** [comment]
Yes it is still the case.

It was an edition of 10. Only 7 are showing up on the creator “collectors” list with one beside my name but I have definitely bought 3

**Comment by codewithfeeling** [comment]
This seems to be resolved now. I unchecked the asset in my Temple wallet, re-checked it and now it seems to be OK.
