### ISSUE TITLE
Info button - accessing meta data

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#33]
Info button does not work in Brave or Safari tested on MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
Brave: Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)

**Comment by andrevenancio** [comment]
@crzypatchwork I'll pick up this one. assign it to me.

**Comment by djangobits** [comment]
Did it ever work? It also doesn't work on OSX Firefox 86.0 or Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by andrevenancio** [comment]
Not sure it will. but I'll add this today. then Its up for @crzypatchwork to merge when convenient.

**Comment by andrevenancio** [comment]
This should be fixed.
