### ISSUE TITLE
Burned OBJKTs still visible

### ISSUE THREAD

**Issue by Matan100100** [hicetnunc2000/hicetnunc#330]
OBJKTs that I've burnt and were gone are now visible on my creations section. I do not have the option to burn them again, and it says that they are collected by tz1burnburnburnburnburnburnburjAYjjX.

**Comment by MarkusLaeng** [comment]
Yes, that is how burning works. They are sent to a burn address, in this case tz1burnburnburnburnburnburnburjAYjjX which is a Tezos address nobody has the private key to. That's how burning works on all blockchains. 

Currenlty the application detects if an objkt has an edition on the burn address and then stops displaying it under creations. In the future this might be more elaborated, so also partial burns will be handled.

**Comment by Matan100100** [comment]
Thanks for you response.
Until the past few hours, my burnt objkts were not displayed in my creations after I burnt them. but in the past few hours they re-appeared there and I do not have the option to burn them again. Is there any way to stop them from being displayed in my creations?

**Comment by andrevenancio** [comment]
This was reverted by @crzypatchwork . Not sure when it will be fixed.

**Comment by flygohr** [comment]
+1

**Comment by mikesizz** [comment]
This can be closed now. 

https://github.com/hicetnunc2000/hicetnunc-api/pull/23

**Comment by Matan100100** [comment]
Thanks!
