### ISSUE TITLE
Burn button

### ISSUE THREAD

**Issue by ninjaspirulina** [hicetnunc2000/hicetnunc#333]
Hey,
When I  click the burn button on an Objkt that I minted, it's not connecting to my wallet as usual. Instead, it's loading for a long time.

**Comment by pindarvanarman** [comment]
Hapenning to me also.

**Comment by mathMakesArt** [comment]
Hi @ninjaspirulina and @pindarvanarman, could you provide more information about the nature of the problem?

What wallet software are you using? What platform (mobile device or computer) are you browsing the website from?

As a further suggestion, I find that the site's features work best when I sync to begin with, then click the button (as opposed to relying on the button click to initiate the sync).

**Comment by santi-grau** [comment]
Can't burn:

"[amount] Value is not a number: NaN"

Synced with Temple Wallet.
tz1TQDnNCwU6DYTGFY7HZrFHivNBJW1LthbS
https://www.hicetnunc.xyz/objkt/24221
