### ISSUE TITLE
Content Security Policy problem with ASM.js content (emscripten)

### ISSUE THREAD

**Issue by arielm** [hicetnunc2000/hicetnunc#334]
Hi, I'm trying to mint [this](https://www.hicetnunc.xyz/objkt/14601) very simple ASM.js test. The [html zip](https://drive.google.com/file/d/1P1z6nhiP0v7k5hRxWBZL53oHGjRa22Vs/view?usp=sharing) is here for reference.

The problem is that if fails with this error on Chrome:
> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'".

> at new Function (<anonymous>)
    at createNamedFunction (cloudflare-ipfs.com/ipfs/Qmdtp3rtJhNg6BoJ6ojYetkePhvKT2kjH9eWRyb5HKZDPj/Basic.js:1)
    at extendError (cloudflare-ipfs.com/ipfs/Qmdtp3rtJhNg6BoJ6ojYetkePhvKT2kjH9eWRyb5HKZDPj/Basic.js:1)
    at cloudflare-ipfs.com/ipfs/Qmdtp3rtJhNg6BoJ6ojYetkePhvKT2kjH9eWRyb5HKZDPj/Basic.js:1

I wonder if someone succeeded minting ASM.js content made with emscripten?

**Comment by andrevenancio** [comment]
iframes are sandboxed for security reasons. I would start small and see what is it that in your minified script is causing it.

Its minified, so not easy to help.

**Comment by arielm** [comment]
The minified script has been automatically generated by emscripten.

Using Safari, I'm able to see the line which caused the error:
```
function createNamedFunction(name, body) {
    name = makeLegalFunctionName(name);
    return (new Function("body", "return function " + name + "() {\n" + '    "use strict";' + "    return body.apply(this, arguments);\n" + "};\n"))(body)
}
```
The error occurs at the 2nd line of the function. It seems like this function is part of emscripten's inner machinery. I don't see what can be done here...

Except maybe trying to find the right Content Security Policy and apply it to the html page via meta tag?
For example (this one doesn't help):
`<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval'" />`

**Comment by arielm** [comment]
Update: It works now!
Here is a test made with emscripten: [OBJKT#17964](https://www.hicetnunc.xyz/objkt/17964)

The solution was to use -s NO_DYNAMIC_EXECUTION=1. One downside: embind stuff will be disabled.
More details [here](https://stackoverflow.com/a/64814360/50335).
