### ISSUE TITLE
Stuck on burning

### ISSUE THREAD

**Issue by arielm** [hicetnunc2000/hicetnunc#339]
Hi, I have tried to burn [OBJKT#15716](https://www.hicetnunc.xyz/objkt/15716) but it's stuck on "burning NFT" status for more than 10 hours.

**Comment by skenaja** [comment]
It's definitely burned (you can see the `tz1burnburn.,.` address on the collectors tab). It's showing on your profile page due to bug #330

**Comment by arielm** [comment]
Thanks. You're right.

But I also tried to burn [OBJKT#15699](https://www.hicetnunc.xyz/objkt/15699) and [OBJKT#14601](https://www.hicetnunc.xyz/objkt/14601) and after a while, it still didn't transfer ownership to tz1burnburn...

**Comment by skenaja** [comment]
Looks like the L2 data that HEN uses is not up-to-date. Raised a query with the upstream BCD API maintainers via their Telegram group:

> Hi, is there currently a lag between these two endpoints? (the first is showing correct data)
> https://better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=15699
> https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=15699
> 
> The transfer is showing correctly in both, and it was carried out on 31/03 
> https://api.better-call.dev/v1/tokens/mainnet/transfers/tz1burnburnburnburnburnburnburjAYjjX?token_id=15699

**Comment by skenaja** [comment]
@arielm Looks like the API is now returning correct results, those 2 are now showing as being owned by the burn address.

**Comment by arielm** [comment]
Correct, thanks for updating. Now waiting for bug #330 to be solved.
