### ISSUE TITLE
Allow local data: and blob: protocols in the Content-Security-Policy for HTML assets

### ISSUE THREAD

**Issue by mikedotalmond** [hicetnunc2000/hicetnunc#343]
Would it be possible to modify the Content-Security-Policy tag that gets injected into the uploaded index.html to allow local loading of `data:` and `blob:` types like:

`<meta http-equiv="Content-Security-Policy" content="default-src data: blob: 'self' 'unsafe-inline';">`

I have a project that loads base64 encoded images using `data:` and audio as a binary `blob:` - in my testing I needed to update the CSP meta tag to include those in order to get it to work.

I'm not sure if this would introduce any security issues... but presumably if it's only allowing local sources and the embedded code can't call out anywhere, it should be safe?

Originally mentioned this in the issue linked but it got lost in the thread and that issue is now closed.

_Originally posted by @mikedotalmond in https://github.com/hicetnunc2000/hicetnunc/issues/250#issuecomment-809662232_

**Comment by pichiste** [comment]
I think we need to look at the security implications first. From the docs:

![Screen Shot 2021-03-31 at 2 40 57 PM](https://user-images.githubusercontent.com/111979/113145789-2bbf2f00-922f-11eb-8dca-3d1b621dcbca.png)

source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src#sources

Does it need to be loaded in that format? Can you load files instead?

**Comment by mikedotalmond** [comment]
Ok, yeah that seems senssible, hadn't seen/read that doc - sorry.

I think for this case I will be able to work around it by pulling that data out of the code and loading it as a file instead as you suggested. Thanks.

I think having the ability to load a Blob will still be quite useful though, and there doesn't seem to be the same concerns there..?

**Comment by pichiste** [comment]
Just to understand the use case, how are you inlining the Blob?

**Comment by mikedotalmond** [comment]
I went back to double check what's going on and I think I misread or misattributed the error messages. I think the actual cause was triggering subsequent errors that lead me down the wrong path. Apologies.

It looks like, rather than coming from a data/blob load of an image and audio stream that I thought it was, it's coming from some 3rd party code that is building a Worker JS file at runtime, encoding as binary, bundling it up as a blob and loading it.... 

Not sure why it's doing that, it's not dynamic, maybe for conveniece to not need a separate js file..? Anyway, I should be able to just extract that resources and load it normally. Feel free to close the issue. Sorry for the confusion.

**Comment by pichiste** [comment]
Well you raise a good point that some 3rd party lib people use might need :blob support... we will consider it but need to look at it more closely when there's a chance.

Can you close the ticket actually? I'm an external contributor (focused on html stuff) and can't! thanks

**Comment by mikedotalmond** [comment]
Ok great 👍😋 thanks, will do!

**Comment by pichiste** [comment]
FYI, had a closer look and looks safe, data: and blob: support coming soon: https://github.com/hicetnunc2000/hicetnunc/pull/354

**Comment by pichiste** [comment]
@mikedotalmond just an update on this, data: and blob: has been enabled for media files
