### ISSUE TITLE
HTML minting preview fails with html-template zip

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#344]
![image](https://user-images.githubusercontent.com/182098/113137511-ea298680-9224-11eb-8343-21616508858d.png)

When trying to mint an HTML template the preview always throws an "index.html" is missing alert box even though the file is included in the zip and even when trying it with the default provided html_template.zip from the repositoy.

This is on Chrome/Linux Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by pichiste** [comment]
@Quasimondo do you have any chrome extensions enabled? If so, could you try turning them off and/or trying in an incognito window? This was the issue for someone else.

Is there anything printed to the console?

Thanks

**Comment by Quasimondo** [comment]
@pichiste I do have a color picker extension, MetaMask and TempleWallet running. I will try again with those fixes, but do you think this is something that can be fixed on our side, since I believe extensions are quite common. At least it would be a good idea to add that to the warnings that are returned.

**Comment by pichiste** [comment]
hopefully we can catch the error and provide a clearer alert, but hard to say without being able to recreate. Haven't been able to do so here. Could you maybe try disabling one by one to see if it helps? It could also be a different issue, service workers seem to be kind of finicky, but necessary for the preview to work (it's how we're able to serve the zip file contents locally before uploading)

**Comment by pichiste** [comment]
@Quasimondo anything you see in the web console would be of great help, thanks!

**Comment by Quasimondo** [comment]
Okay here is an error message I see in the dev console and I can also see that MetaMask is interacting with the page.
![image](https://user-images.githubusercontent.com/182098/113152522-814b0a00-9236-11eb-9fbc-142d72e5f778.png)

So it looks to me like the error must happen in this line
`const fileData = await requestFileData(uid)`
Where the fileData returned is somehow not the right. Unfortunately I do not manage to debug this due to the way the page is loaded and my half-knowlege about the process.

**Comment by pichiste** [comment]
@Quasimondo thanks, one last thing, could you try in a different browser? firefox for example?

**Comment by Quasimondo** [comment]
Okay - I found the culprit: it is MetaMask. My workaround that fixes it is to right click the MetaMask Icon, select "This can read and write site data" and pick "When you click the extension"

**Comment by pichiste** [comment]
Thanks for tracking this down! 🙏

From our side, I think we can at least catch that the file data is empty because of this, and we can display a less confusing alert!

What we really need is some proper documentation for all things HTML NFT. Will try to get that together soon.

**Comment by pichiste** [comment]
@crzypatchwork you can close this, thanks

**Comment by pichiste** [comment]
@Quasimondo FYI, found a workaround for this actually! Proper fix coming in next release. Thanks again for helping track this down
