### ISSUE TITLE
Getting "The transaction is invalid and the node did not accept it" when swapping

### ISSUE THREAD

**Issue by arielm** [hicetnunc2000/hicetnunc#346]
Hi, I'm trying to swap [OBJKT#18435](https://www.hicetnunc.xyz/objkt/18435) but I'm getting "The transaction is invalid and the node did not accept it". Here are the details:
```
[
  {
    "kind": "temporary",
    "id": "proto.008-PtEdo2Zk.michelson_v1.runtime_error",
    "contract_handle": "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
  },
  {
    "kind": "temporary",
    "id": "proto.008-PtEdo2Zk.michelson_v1.script_rejected",
    "location": 962,
    "with": {
      "string": "FA2_INSUFFICIENT_BALANCE"
    }
  }
]
```
It's not clear to me: I want to have 25 pieces at 5 tezos each. Should the swap operation cost something?

**Comment by arielm** [comment]
Update: I think I know what the problem is...
I minted an amount of 1. But then, I asked to swap 25 pieces.

So I minted again ([OBJKT#18474](https://www.hicetnunc.xyz/objkt/18474)), this time with an amount of 10. Then I asked to swap 10 pieces and the transaction did seem to work.

But now, after some time: I still see "Not for sale" after refreshing the objkt page.

**Comment by arielm** [comment]
Update: I tried to swap again but without success (The transaction is [here](https://tzkt.io/opMuzD5UNCqzwygGx2Za3n5A2ZUF5BHfDF6kPM76Q3aN6bf8LVg))

It has been backtracked with error "Storage quota exceeded for the operation". What does it mean?

**Comment by arielm** [comment]
Update: I tried to swap again and it finally worked.

**Comment by simfid1512** [comment]
hello, I am having the same problem. How did you solve it?

**Comment by crzypatchwork** [comment]
you can check your transaction history to see if the swap went through or not. it's likely an indexer problem. which means that our database is not up to date with such event, the state of the swap should be updated whenever the indexer catches up from such lag. It's a known issue and it's being optimised. Any further issues just let us know.
