### ISSUE TITLE
Object appears as [Unknown token] in wallet and can not be sent or sold

### ISSUE THREAD

**Issue by pindarvanarman** [hicetnunc2000/hicetnunc#348]
Minted https://www.hicetnunc.xyz/objkt/18210

In my Kukai wallet it appears as [Unknown token]

Can't send it to anyone.  Also can't burn it.

Why is it an unknown token?

**Comment by andrevenancio** [comment]
this one is showing up without any owners @crzypatchwork ☝🏻

**Comment by pindarvanarman** [comment]
Can you please either burn it or make me owner so I can burn it.

**Comment by crzypatchwork** [comment]
the unkown token is just a misconfiguration in parsing the token info which we have addressed to wallet developers already. the burn issue is being solved today.

**Comment by pindarvanarman** [comment]
Has the burn issue been solved.

If it has, this is a different burn issue.

I can not burn this token.
