### ISSUE TITLE
HTML Preview - Handle error caused by browser extensions

### ISSUE THREAD

**Issue by pichiste** [hicetnunc2000/hicetnunc#349]
It seems some browser extensions (including Metamask) break the HTML preview, which results in an alert reading "Missing index.html". 

There is nothing we can do to fix this, but we should display a clearer error message to the user.

**Comment by pichiste** [comment]
Workaround from @Quasimondo:

_My workaround that fixes it is to right click the MetaMask Icon, select "This can read and write site data" and pick "When you click the extension"_

**Comment by pichiste** [comment]
Found other solution

**Comment by presstube** [comment]
@pichiste what was your other solution?

**Comment by pichiste** [comment]
@presstube the fix is in this PR awaiting merge: https://github.com/hicetnunc2000/hicetnunc/pull/350
