### ISSUE TITLE
Username smart contract

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#35]
I quite like the anonymity of the platform. you only see an ID and that evokes a feeling of an underground that resonates with me particularly. 

However, I've seen some people asking on discord how would they be able to add some personal info, link a display picture or a link to Twitter. Some other platforms allow for this.

It could be an optional feature, allowing the artist to share some details.

**Comment by crzypatchwork** [comment]
I'm thinking on creating a smart contract where you can register a namespace urlencoded/in bytes along some metadata. on chain. it would have some costs but for me it would be the easiest way to achieve this still this week.

There would be need some entrypoints to also verify identities, as an oracle, opening the possibility of adapting other authentication/verification methods latter on. Thoughts?

Yes, it could be optional.

**Comment by djangobits** [comment]
The crucial point is that anyone could fake this stuff, so it will always be up to the user checking it. Many people write it in the description field now, so once we see the "info" that problem is already slightly reduced... so https://github.com/hicetnunc2000/hicetnunc/issues/33 is high prio IMHO.

**Comment by oldominion** [comment]
Could DirectAuth be used to validate/prove ownership of an account automatically against a Twitter/Google/Reddit account, as is done by kukai.app wallet? Since those can be essentially anonymous, it could potentially provide provenance without KYC.

**Comment by oldominion** [comment]
Potential for future integration with DID. https://github.com/spruceid/did-tezos
