### ISSUE TITLE
Can't access mp4 in HTML upload

### ISSUE THREAD

**Issue by n1ckfg** [hicetnunc2000/hicetnunc#351]
HTML upload can't access a small (~8MB) local mp4. Going directly to the ipfs link:
https://cloudflare-ipfs.com/ipfs/QmajcLymiXcy6duNtXT2MpKomCNYuCuUmNNh7QvCZrWk4b/bicycle_360.mp4
...returns the message "ipfs: video streaming is not allowed"

Sample objkt:
https://www.hicetnunc.xyz/objkt/18084

Working (non-flat) example:
https://n1ckfg.github.io/threejs_depth_eqr

**Comment by andrevenancio** [comment]
that seems to be a ipfs configuration. We're considering which server to serve html from, but this will impact other users. I'm not sure if there's a resolution. @pichiste ☝🏻

**Comment by n1ckfg** [comment]
Yeah, I tried again using base64 encoded text, still gets blocked by Cloudflare.

**Comment by n1ckfg** [comment]
Ha--I can do it with base64 encoded text, as long as I leave the dataurl header off the text file, and add it only when finally loading the video in jS! https://www.hicetnunc.xyz/objkt/20543

**Comment by pichiste** [comment]
I don't think there's anything we can do on Cloudlfare side... need to investigate further.

@n1ckfg clever workaround! Just FYI data: and blob: have been been enabled in latest release so you shouldn't have to do the dataurl header fix going forward :)

**Comment by pichiste** [comment]
@n1ckfg sorry I misinterpreted, if you want to load from an external file then I think your solution is basically the way to go!

**Comment by pichiste** [comment]
@n1ckfg update: loading video files works in latest release
https://www.hicetnunc.xyz/objkt/18084

**Comment by n1ckfg** [comment]
Amazing! So the IPFS provider switch worked?

**Comment by pichiste** [comment]
Yep, Infura allows video streaming! It was a Cloudflare-specific limitation

**Comment by pichiste** [comment]
@n1ckfg Could you close this issue? (I don't have admin access) Thanks!
