### ISSUE TITLE
expand allowed domains 

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#353]
We already have some useful domains to call from interactive nfts. I'm opening this issue to discuss the expansion of this list:

- http://ipinfo.io/ (or similar) - would allow an nft to know about the location of the client... more or less. It isn't super accurate, could be completely wrong in cases with proxys, but could at least allow for nfts with some geolocation without allowing the geolocation API.
- https://wiki.openstreetmap.org/wiki/API - lots of geolocated data to pull into an nft 

Please add others or comment on the domains on the list.

**Comment by andrevenancio** [comment]
@veqtor ☝🏻

**Comment by veqtor** [comment]
> * would allow an nft to know about the location of the client... more or less. It isn't super accurate, could be completely wrong in cases with proxys, but could at least allow for nfts with some geolocation without allowing the geolocation API.

Do we really want this though?

**Comment by andrevenancio** [comment]
I'm closing this issue. I think the general consensus after a chat on Discord is that this feature should be transparent to the user. The user needs to explicitely authorise the permission to share location.

It will come in play when we figure out the best way of implementing https://github.com/hicetnunc2000/hicetnunc/pull/219 which has been in PR limbo until we weight in all privacy concerns.
