### ISSUE TITLE
Collectors ID is not showing into the list with Collectors also not showing in Temple Wallet between all others

### ISSUE THREAD

**Issue by FDF01** [hicetnunc2000/hicetnunc#355]
Picked up several pieces yesterday, with 2 of them my ID (https://tzkt.io/tz1PYJbuAbc14ZBLbD7jQszoVDDEbMBpjYKG) is not showing up on the collectors tab below the artwork, these works are also not appearing in my Temple Wallet, other works I bought yesterday are showing up.

They DO appear in my collection tab (https://www.hicetnunc.xyz/tz/tz1PYJbuAbc14ZBLbD7jQszoVDDEbMBpjYKG)  but my ID is missing when click on the object and try to search for it.

https://www.hicetnunc.xyz/objkt/16057
https://tzkt.io/opNMsugAhmkq6VaQd8Y7PWTxkpwanDY2zAHvVKKArARLJZ2umd4

https://www.hicetnunc.xyz/objkt/18926
https://tzkt.io/oozSe7uGeiqMkeSMseEyLPFgmswyXMuWVPWcA1sibJFVrD16vE4

![image](https://user-images.githubusercontent.com/81513899/113263886-a4c39280-92d2-11eb-8bc9-2b20ba8fe2d0.png)

**Comment by mathMakesArt** [comment]
@FDF01 I just checked both of the OBJKTs in question and they seem to both now list your ID.
Sometimes it can take a while for the collectors list to be updated.

As for temple wallet, are they showing up now? Often some of my assets take more than a day to show up in Temple if I've collected a lot of them in a short time period

### Would you be okay with this issue being closed?

**In general, As long as the underlying transaction has succeeded, you can trust that you do have ownership of the NFT and it will show up given enough time**

@andrevenancio sorry for the tag, but I'm not sure how else to mark an issue for closure. Is there any way I can be given the power to add labels or something similar? I'd love to help sort through the issue reports when I get a chance.

**Comment by FDF01** [comment]
Ok thanks, I will close it, I saw another issue that the API was late the last few days, probably that is the reason that they did not show up, as it took > 12 hours ... but apparently I was not alone with this issue, but as you said, if the transaction got processed it ok, I just need some patience probably ;)
