### ISSUE TITLE
Placement of fullscreen button

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#356]
![image](https://user-images.githubusercontent.com/182098/113264987-e99bf900-92d3-11eb-9213-90616e6e936b.png)

I am wondering if it is a technical constraint that the placement of the new fullscreen button is on top of the artworks themselves or if this is a design decision? Whilst I am extremely happy that we have this option now I also feel that it now "encroaches" on the artworks themselves. Also since it is using a white background it becomes a distracting element when used with works that do not have a white background themselves.

Would it be possible to place that button outside the canvas area of the OBJKT

Alternatively if the button has to be inside the canvas, could it be made so it only appears on rollover or click? Similar to the way it works with standard video players?

**Comment by mattebb** [comment]
I agree, I think it would be much less disruptive to the art if it were outside the artwork itself.

**Comment by samuelebonaffino** [comment]
Outside would be the better solution, or at least adjust it with a low opacity when moving the mouse on the canvas. I bet devs already took it into account though. We should open a request feature [here](https://hicetnunc.featureupvote.com/) as well.

**Comment by dreizehnutters** [comment]
I would suggest to auto make it disappear/auto hide on the full screen view and to make the overlay transparent.
Currently on colorful pieces it is quit disturbing -> https://www.hicetnunc.xyz/objkt/14852

**Comment by samuelebonaffino** [comment]
I've also added a feature request [here](https://hicetnunc.featureupvote.com/suggestions/175692/moving-fullscreen-button-outside-of-the-canvas), feel free to upvote if you want.

**Comment by Quasimondo** [comment]
> We should open a request feature here as well.
Voting is open:
https://hicetnunc.featureupvote.com/suggestions/175692/moving-fullscreen-button-outside-of-the-canvas#comment255561

**Comment by scalemodal** [comment]
Agree, on mouseover with opacity or outside.

On this objkt this button is moving now, on different browser resolutions:
https://www.hicetnunc.xyz/objkt/19510


![image](https://user-images.githubusercontent.com/81647978/113273619-20c2d800-92dd-11eb-91d5-42a052daa7c7.png)

**Comment by andrevenancio** [comment]
seems like an easy enough feature for some of you trying to get into open source. I dont think we have enough contributors to all the requested changes. so extra help will be appreciated.

**Comment by Quasimondo** [comment]
> On this objkt this button is moving now, on different browser resolutions:

Uh, that is a bit ugly, isn't it?

**Comment by Quasimondo** [comment]
> seems like an easy enough feature for some of you trying to get into open source. I dont think we have enough contributors to all the requested changes. so extra help will be appreciated.

Maybe someone can chime in whether there are technical constraints. I know that with our iframe construct there are certain things that can only be done from the "outside" and others can likely only be done from the "inside". So my main question is, if that button is actually part of the iframe or part of the containing page.

**Comment by scalemodal** [comment]
I would make this stroke thinner also.

Option A:  thinner+opacity on mouseover. Can be a good option, because full screen button is usually placed on the picture, just common UX (without this button movement glitch)
Outside is harder to find a suitable place. On the right side we have editions and price. Left side is an issuer. 

However, option C seems to me could have a bit better perspective, because now we have inverted position for objkt and issuer. I would move the issuer to the second line. So, we can put the full screen button on the first line, closer to the picture (centered or close to the objkt, as on option B) .

![image](https://user-images.githubusercontent.com/81647978/113275348-fc67fb00-92de-11eb-9b6b-1f184344a26d.png)

**Comment by andrevenancio** [comment]
By parts:
So the button is a feature from the platform. What it does, is to request the hicetnunc website itslef to enter fullscreen and it hides other content like the text descriptions or the menu once it enters fullscreen mode. its never the art itself that has the button.

Safari (iOS) does NOT support fullscreen API. That is not a bug on our end, its a poor design decision on Apple's part. They only allow `<video`> to be fullscreen.

In regards to layout, its hard to me as a developer to find a good place to place it. I'm not a designer, nor do I wanna be. Alternative would be to put the button outside the window, but that would clutter the info pannel below. So I ended up putting it over the art. That can obviously be changed. its just CSS.

I've created an issue #357 which welcomes new contributors.

**Comment by Quasimondo** [comment]
First of all: a big thank you for implementing this @andrevenancio ! It is a great feature to have! Also thanks for clarifying where the button is "living". So that means we can place it anywhere on the page.

Personally my favorite would be the placement of option B in @denscimonk 's proposals. And C as the runner-up.

Admittedly with it being on top of the OBJKT it is easier for most people to discover this option but I also fear that depending on the underlying visuals and their proportions it is hard to guarantee that it will always work aesthetically with the work.

**Comment by scalemodal** [comment]
@andrevenancio I'm a UI/UX designer, I can assist you and other devs on these efforts.

Option B, I don't see as in ideal solution,  but rather a quicker fix, we can test it.
This button should be as close to the picture as possible, in the same time I would not mix it with prices/editions.

**Comment by scalemodal** [comment]
> Admittedly with it being on top of the OBJKT it is easier for most people to discover this option but I also fear that depending on the underlying visuals and their proportions it is hard to guarantee that it will always work aesthetically with the work.

Yep, it's a bit better for UX, but it's not a big deal, because artwork is more important, than common UX patterns.

**Comment by andrevenancio** [comment]
there's a designer starting looking at the site. Come to discord and I'll introduce you. I'm trying to focus more on code than visuals but i agree the importance ui/ix needs. And how it can change the experience for the best. But I need to focus on my day job and I only have an hour or so a day for  hic, which normally I dedicate to build new features instead of focusing on doing my own art which I miss terribly... Hence it's important to me to find other passionate people to take some of the burden off. 😅

**Comment by andrevenancio** [comment]
I've tried to replicate the behaviour of the video player for the fullscreen:
On rollover it shows and on rollout it goes away. It doesn't look good with the icon outside the art.

There's a designer starting to have a look at the overall site, so this can be revisit soon.
On mobile because ios safari doesn't support fullscreen api its been removed.

**Comment by scalemodal** [comment]
> there's a designer starting looking at the site. Come to discord and I'll introduce you. I'm trying to focus more on code than visuals but i agree the importance ui/ix needs. And how it can change the experience for the best. But I need to focus on my day job and I only have an hour or so a day for hic, which normally I dedicate to build new features instead of focusing on doing my own art which I miss terribly... Hence it's important to me to find other passionate people to take some of the burden off. 😅

@andrevenancio Sure, I'm already there under the same name: denscimonk

**Comment by Quasimondo** [comment]
I think the fullscreen button is actually interfering with the normal behavior of HTML folder OBJKTs by capturing the mouse events.

This piece for example should be showing a scrollbar since the text is longer than the viewport but the way it is currently being show the lower part of the text is inaccessible:

https://www.hicetnunc.xyz/objkt/21617

So here is my plea to place the button on the page like it is proposed in layout "B" above.
