### ISSUE TITLE
Fullscreen not working on Safari 

### ISSUE THREAD

**Issue by ertdfgcvb** [hicetnunc2000/hicetnunc#358]
Safari throws: 
TypeError: document.documentElement.requestFullscreen is not a function.   
(In 'document.documentElement.requestFullscreen()', 'document.documentElement.requestFullscreen' is undefined)   
   
Unfortunately the Fullscreen API on Safari still uses the vendor prefix `.webkitRequestFullscreen`…

**Comment by pichiste** [comment]
This one is fixed in PR, just awaiting merge: https://github.com/hicetnunc2000/hicetnunc/pull/354

**Comment by andrevenancio** [comment]
I ended up deciding against pushing that code. on touch devices fullscreen is going to be disabled for now. there was a lot of other considerations to have, specially a around a new AR piece that Raphael published https://twitter.com/sableRaph/status/1377757889868275718?s=20 on mobile there was an overlap of the AR logo and the fullscreen. We can revisit the fullscreen again once Safari supports it.

**Comment by ertdfgcvb** [comment]
This affects also the desktop version of Safari!
The fix is a one-liner and it'd be a pity to disable the functionality for Safari users and not directly related to AR.
The vendor prefix fullscreen is like this since many years and I suspect it's a long forgotten issue in webkit land. I wouldn't rely on them (I'll open an issue in webkit, in any case).
Please re-open, eventually.

**Comment by pichiste** [comment]
@andrevenancio  Re-implemented this to target only desktop in this PR: https://github.com/hicetnunc2000/hicetnunc/pull/369

This still honors the iOS check.

There were issues also with other browsers because of several vendor-specific event/element naming conventions.
