### ISSUE TITLE
Sorting order of OBJKTs in creations tab?

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#360]
I am trying to understand the logic behind the order in which OBJKTs that I have minted appear in my own "creations" tab. There seems to be a mixture of various ordering methods happening at the same time. It is not by OBJKT number or time minted. Maybe there is some hDAO weighting happening? Or is it based on sales prices? I can't figure it out and to be honest I also do not like the order.

Of course in the perfect world we will at some point be able to select which OBJKTs and in which order they should appear, but until then I would prefer it if they were simply shown in descending order by creation date.

**Comment by mathMakesArt** [comment]
I was under the impression that the order is as follows (from the top of the page down):

1. Mints which you have never listed for a swap
(these are sorted in descending OBJKT number order)
then
2. Mints which you have listed for one or more swaps
(also sorted in descending OBJKT number order)

That being said, I don't think much hDAO (if any) has been used to interact with my pieces. So if hDAO weighting plays a role, this might add further complexity.

**I don't have too many creations (two dozen or so) so in my case it might just be a lack of complexity.**

**Comment by andrevenancio** [comment]
I'm not totally sure. They already come ordered from the API which is on another repository. maybe @crzypatchwork can weight. I'm thinking it might be a good idea to order it by number maybe?

**Comment by mescalina** [comment]
Sometimes I feel the need of a Project parameter in the tokens so authors could be able to sort objkts keeping different projects separate. Tags could be used for such a function, in that case people should be able to order their creations depending on a specific tag list.

**Comment by fjenett** [comment]
Since yesterday (?) it seems randomly ordered all of a sudden. Did some change happen?

My creations are pretty curated in terms of order (groups of 2 or 4). So now it is all chaos … not so happy with that.

**Comment by mikesizz** [comment]
Issue:
https://github.com/hicetnunc2000/hicetnunc-api/issues/25

Fix:
https://github.com/hicetnunc2000/hicetnunc-api/pull/24

**Comment by mikesizz** [comment]
@andrevenancio @crzypatchwork ☝️

**Comment by ghost** [comment]
Hi, Hope you're keeping well. I just minted my first artwork :). I don't have the option to "curate" even if the wallet is connected.

Thanks for your help.  @Quasimondo / @andrevenancio

https://www.hicetnunc.xyz/tz/tz1WzpRbYJx4ma3PgAuhdsL6Yb8gmUEVANRK

**Comment by skenaja** [comment]
@saint-meta - Please raise new issues in a separate bug report. The info you need is here: https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-swap-%F0%9F%94%83

**Comment by skenaja** [comment]
@Quasimondo The objects in creations tabs should now be sorted in descending order after a recent API fix, albeit using masonry layout, so a mix of OBJKTS in different aspect ratios will affect the look and feel. I'll close the ticket as hopefully this helps answer the original question, however feel free to comment here with any follow-ups and I'll re-open if required.

**Comment by Quasimondo** [comment]
Thank you - the ordering is now much better!
