### ISSUE TITLE
OBJKT detail page: UI/UX improvements.

### ISSUE THREAD

**Issue by scalemodal** [hicetnunc2000/hicetnunc#361]
Hi,
I have a suggestion how to update the OBJKT detail page, in order to improve user experience and design maturity, since we are working on it already. 
I'm looking for a dev here to collaborate and implement these changes, I will provide needed assets.

Have a look my design below.

Suggestions:
- Artwork title is moving to the main part
- Issuer is moving a bit down, second priority
- Tezos address + issuer name added, if available
- Available/Issued pieces (as before)
- Full screen button outside
- Price button with Tezos sign, always lowest price here
- Upvote button explaining its function on mouseover
- On Collectors, issuer always first (additionally marked with icon), lowest price second line
- Other small UI movements

Did I forget anything to reflect in this design, at least for the first phase of improvements? 
I see other requests e.g. price history, transactions. I guess, we can implement these new features step by step. I can reflect it in design even now, if it's not difficult to implement.

Thanks.

![image](https://user-images.githubusercontent.com/81647978/113318864-2c2ff680-9311-11eb-8104-f202655a173b.png)

**Comment by andrevenancio** [comment]
Appreciate the feedback and apologies for not being clear but Github issues should be more for feature requests and bug reports. A complex suggestion like this, involving multiple design changes and multiple features will not be great to track on github. There's also a designer currently having a look at the site, and this suggestions are better to keep on Discord on the #design channel.
