### ISSUE TITLE
Image doesn't fully load

### ISSUE THREAD

**Issue by neverhood311** [hicetnunc2000/hicetnunc#362]
I have several OBJKTs that are not fully loading, neither in the gallery view, nor in the page for the OBJKT itself.
![image](https://user-images.githubusercontent.com/4615170/113328507-9dec4e00-92d9-11eb-8dd4-65b8814324e3.png)
Here are the links:
https://www.hicetnunc.xyz/objkt/5073
https://www.hicetnunc.xyz/objkt/5076
https://www.hicetnunc.xyz/objkt/5088

What could be going on here?

**Comment by andrevenancio** [comment]
You should be able to properly debug by opening your chrome dev tools and have a look at the requests tab. My educated guess is that its depending on your speed. At the moment if someone mints at high resolution that's the resolution we serve it. In the future we're going to address this issue by including smaller thumnails but for now if someone uploads a 4k image, we're serving that 3k image even if on those small thumbnails.
