### ISSUE TITLE
Dark Mode: Address of collector issuing swap doesn't change

### ISSUE THREAD

**Issue by mathMakesArt** [hicetnunc2000/hicetnunc#364]
### CLARIFICATION: Title should read "doesn't change color". This issue is about a non-functional color change.

![image](https://user-images.githubusercontent.com/68834165/113338261-dfd7bd00-92f6-11eb-9a8e-f65959badaf3.png)

I noticed that in the new "dark mode", addresses normally are readable on the "Collectors" tab. **However if an address has initiated a swap, the color does not respond to dark mode and instead stays black.**

Inspecting the HTML lead me to notice that `color: rgb(0, 0, 0);` is the style used.
I think that if this style were removed, the element would inherit the proper color from parent HTML elements.

*I will first attempt to familiarize myself with the hicetnunc repo, to try to fix this issue myself. I will attach a relevant pull request if I'm able to do so.*

**Comment by mathMakesArt** [comment]
After some further investigation, it seems that [**/src/components/owner-swaps/index.js**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/owner-swaps/index.js) is the file that renders this page content.

Specifically, I think the problem comes from [**line 14**](https://github.com/hicetnunc2000/hicetnunc/blob/54c2a2709f0edca1069a0939e01076b6249261db/src/components/owner-swaps/index.js#L14), or at least lines 13 through 15.

I believe that this
`<Primary>{walletPreview(swap.issuer)}</Primary>`
line is being rendered into the 
`<a style="color: rgb(0, 0, 0);" href="/tz/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71">tz1gs...Cgd71</a>`
line on relevant webpages.

So either the `<Primary>` tag itself or the `walletPreview()` function need to be changed such that they use the correct color.

The relevant SCSS file for the page, [**/src/components/owner-swaps/index.module.scss**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/owner-swaps/index.module.scss), defines the `color` style within the `.container` class definition on [**line 6**](https://github.com/hicetnunc2000/hicetnunc/blob/54c2a2709f0edca1069a0939e01076b6249261db/src/components/owner-swaps/index.module.scss#L6)
<br />
<br />
I am only slightly familiar with generator-based web design, so I'm uncertain if I'll be able to uncover how to control this color property. I will continue to investigate, and report what I learn in this thread in case someone else is more capable of fixing the issue.

**Comment by mathMakesArt** [comment]
The `walletPreview()` function appears to originate from [**/src/utils/string.js**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/utils/string.js) and is probably unrelated to coloring
<br />
The `<Primary>` tag appears to originate from [**line 54**](https://github.com/hicetnunc2000/hicetnunc/blob/54c2a2709f0edca1069a0939e01076b6249261db/src/components/button/index.js#L54) of [**/src/components/button/index.js**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/button/index.js).
Further, it appears to be colored beginning at [**line 20**](https://github.com/hicetnunc2000/hicetnunc/blob/54c2a2709f0edca1069a0939e01076b6249261db/src/components/button/index.module.scss#L20) of [**/src/components/button/index.module.scss**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/button/index.module.scss).

### I am almost certain that this `/src/components/button/index.module.scss` is the file that needs to be changed to fix this issue, but I have a bit more digging to do.

**Comment by mathMakesArt** [comment]
> Further, it appears to be colored beginning at [**line 20**](https://github.com/hicetnunc2000/hicetnunc/blob/54c2a2709f0edca1069a0939e01076b6249261db/src/components/button/index.module.scss#L20) of [**/src/components/button/index.module.scss**](https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/button/index.module.scss).

Because line 20 of the file (quoted above) already reads as follows:
`color: var(--text-color);`
Specifically, because it already uses the `--text-color` variable, I'm not sure why this one aspect of color-changing behavior is broken.

### For now I will leave the issue unresolved, and hopefully my notes are enough for someone more knowledgeable to figure this out.

**Comment by andrevenancio** [comment]
Hi @mathMakesArt thank you for the very insightfull issue report. This has been fixed. I'm waiting on @crzypatchwork to deploy tonight and hopefully fix it. Really appreciate the insightful issue.

**Comment by mathMakesArt** [comment]
Wow, thanks for the fix! I'm very glad that my reported information was helpful.

I'm not the most talented web dev, but I certainly have the skills to report issues at this level. I'll continue to create reports like this in the future for any other problems that I investigate!
