### ISSUE TITLE
sound control in a video disappears

### ISSUE THREAD

**Issue by martinpospech** [hicetnunc2000/hicetnunc#365]
When trying to adjust audio volume in a video, the volume bar disappears and can't be adjusted (tested in Chromium).

**Comment by mathMakesArt** [comment]
Can you be more specific?
Does this happen in every single video on HicEtNunc, regardless of other context, as long as you're using the Chromium browser?

I don't want to completely jump to conclusions, but this seems more likely to be a Chromium (or OS-specific) issue than a problem with the HicEtNunc sound control

**Comment by andrevenancio** [comment]
that's expected when a video has no sound the controls have the audio disabled.

**Comment by martinpospech** [comment]
I am talking about videos that actually have sound. However it seems to work in Firefox and today it also worked fine in Chromium so it was probably some Chromium issue that's already fixed.
