### ISSUE TITLE
mp4 not loading

### ISSUE THREAD

**Issue by tomburtonwood** [hicetnunc2000/hicetnunc#366]
mp4 file is not loading
[https://www.hicetnunc.xyz/objkt/14869 ](https://www.hicetnunc.xyz/objkt/14869 )
it was working previously - not sure why it has stopped. Help!
other mp4 files i have uploaded are working. very odd. sad i  am.

**Comment by mathMakesArt** [comment]
It's loading for me at the time of this comment!

**Comment by andrevenancio** [comment]
tested on Chrome and Safari and works fine.

**Comment by tomburtonwood** [comment]
Great! Thank u all! Sorry! 

 typos are mine
