### ISSUE TITLE
Alert box in the header of the website

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#367]
It would be nice to have an alert box on top of the HEN website (That you can choose to close and doesn't pop up again unless there are new messages to display) where you can show any kind of alert regarding active bugs/problems. So when people open the page they immediately know if burn is not working or anything else going on. I guess it would also save a lot of time and energy from discord and github where the same questions are posed over and over because of a missing clear place to collect them.

**Comment by mathMakesArt** [comment]
Hi @mescalina, I think this is a great idea! But it's better suited as a feature request, not an issue report. The HEN [**Community Feature Request**](https://hicetnunc.featureupvote.com/) page is great for submitting these and I think the community would upvote this idea a lot there.

In the meantime, would you be okay with this issue being closed?
