### ISSUE TITLE
Activate "Projects" and "Wiki" here

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#379]
I think those could be useful tools to keep better track of tasks as well as to collect other useful knowledge regarding the api or FAQs.

**Comment by violetforest** [comment]
I made some wiki markdown files but I don't really know how to contribute them. My google search says that you can't do pull requests for wikis. But there is a separate repo for them that you can clone here 

https://github.com/violetforest/hicetnunc.wiki.git

**Comment by skenaja** [comment]
The github project admins would need to switch them on in the project settings, and create at least 1 wiki page.

@violetforest you'd then be able to directly push your pages to the parent repo (as you have `contributor` rights).
https://gist.github.com/larrybotha/10650410

**Comment by andrevenancio** [comment]
This is a good idea. @violetforest is in charge! She'll be updating these in the next few days. thanks for the suggestion

**Comment by Quasimondo** [comment]
Thank you - I can see the wiki now! One important page that I would like to see is "How to contribute to this wiki" since I am actually not sure about the procedure. I guess I will have to clone it locally and then submit pull requests? A step-by-step tutorial would be very nice to have.

**Comment by skenaja** [comment]
I think the permissions need to be loosened to allow other contributors - I get a 403 error when pushing a change to the wiki:

````
hicetnunc.wiki$ git commit -m "Adds How do I earn hDAO and other sections"
[master dd1dbf5] Adds How do I earn hDAO and other sections
 1 file changed, 11 insertions(+), 2 deletions(-)
hicetnunc.wiki$ git push
Username for 'https://github.com': skenaja
Password for 'https://skenaja@github.com':
remote: Permission to hicetnunc2000/hicetnunc.wiki.git denied to skenaja.
fatal: unable to access 'https://github.com/hicetnunc2000/hicetnunc.wiki.git/': The requested URL returned error: 403
````

https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by andrevenancio** [comment]
Permissions will likely not change. You can clone the repository to your own account and do a pull request from there to hicetnunc repository.

**Comment by skenaja** [comment]
@andrevenancio Unfortunately, pull requests aren't available for wiki content.... 

Some workarounds listed here: https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github#:~:text=5%20Answers&text=GitHub%20doesn't%20support%20pull,but%20I%20can%20understand%20it).&text=Manually%20create%20a%20fork%20of,repository%20on%20your%20github%20account.
