### ISSUE TITLE
Reporting possible copyrighted NFT

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#38]
Would it be possible to have a link within the artworks page to report possible copyright violations. I understand it is buyer beware but with the anonymity which is interesting on hicetnunc it could also lead to a lot of people thinking they are supporting an artist only to find out it is a scam.

I'm not sure if this is the same artist and minting on two different blockchains (maybe that's ok?) but I think it is something you should be critical of scaling up.

https://www.hicetnunc.xyz/objkt/1150
https://zora.co/vrn/1611

**Comment by djangobits** [comment]
It's definitely an issue to look into. Besides of copypasteminters, the platform could also be attacked by rogue uploaders, uploading infringing or illegal stuff, not only turning down other users, but also create legal problems.

A first step might be a blocklist, to block certain OBJKTs from being displayed at the frontend...

**Comment by crzypatchwork** [comment]
one of the strategies could be maintaining the feed, but the main feed would be controlled by hDAO token holders (one can use hDAOs to shill a NFT, the NFT creator is also able to withdraw hDAOs or keep shilling a NFT -- as a sort of ADX). other strategy is to delete the feed and leave only galleries for now along some feed by tags. any suggestions are welcome. 

taking down contents is very unproductive. but I've came to ban them from the feed in some cases indeed. we could add a report section to automate a big moderation. but it will be out of control either way in no time.

**Comment by crzypatchwork** [comment]
I believe hDAOs could have a flow of social networking as well which would bring 'verification'. I'm not verified in no social media so what does that means etc

**Comment by andrevenancio** [comment]
related to [50](https://github.com/hicetnunc2000/hicetnunc/issues/50)

**Comment by raynt** [comment]
I'm not sure about the technical side of implementing a functioning monitoring system. For the time being, I wonder if blatant accounts could be taken down manually. For example:
https://www.hicetnunc.xyz/tz/tz1fMia93yL7vndY2fZ5rGAQPgex7RQHXV1m

it's pretty obvious looking at the collection that this person didn't create all these. One NFT they have minted eight times, I feel this is enough reason to take offline.
