### ISSUE TITLE
Can´t upload items heavier than 40Mb

### ISSUE THREAD

**Issue by malaventuraNFT** [hicetnunc2000/hicetnunc#381]
I can't upload items heavier than 40Mb
Just that, It would be great to have a higher limit to upload files. Trying to put my videoarts there but don't want to have to downsize the files so the quality can be acceptable. Thanks in advance.

**Comment by Quasimondo** [comment]
That is a limit by IPFS and within the normal allowed maximum of pretty much all crypto platforms. Would surely be nice to have more, but  it is not just about flipping a switch.

**Comment by oldominion** [comment]
You can always promise to send owners high quality copies on request.

**Comment by malaventuraNFT** [comment]
Thanks Mario for your quick response. I didn't know that that limitation comes from the IPFS network. Hope that switch can be flipped sometimes in a near future, as you said it would be nice, specially for narrative pieces.

**Comment by andrevenancio** [comment]
I've implemented ISSUE / FEATURE Requests templates. Please don't disregard the templates next time. They help us act faster. thanks.

**Comment by malaventuraNFT** [comment]
Awesome. Sorry for not following the template but the issue was just that. Next time I'll follow the instructions. Thanks
