### ISSUE TITLE
PLEASE READ: before submitting an issue

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#382]
Hi everyone. We're excited to have you here.

Help us manage our code repository by being thoughtful when submitting an issue.

If you're here to report a bug, please make sure there isn't already a bug open for the same issue you're experiencing. If there is one, read it and add your own input if it contributes towards the resolution. Having multiple issues that are duplicates is actually counter productive as we need to tag them accordingly and in many cases close duplicates. 

If you believe that the issue you're experiencing is not yet reported, Please provide as much information as possible. There is a template when you create an issue with clear instructions on how you can document the issue properly. Please read through it carefully before submitting.

On the other hand, if you're here to suggest a Feature request, please be aware that we're prioritising feature request by public voting. Please head over to this [link](https://hicetnunc.featureupvote.com) where you can add your feature request.

Thank you

**Comment by rfpaul** [comment]
Is this guidance still in effect for Feature Requests? The link to the Feature Request board indicates: “Oh no! This board isn't publicly visible anymore.”
