### ISSUE TITLE
WHY THIS?

### ISSUE THREAD

**Issue by tz1ZyS8RyMnTNUjrFehu6onMv75Mmtj1QhEJ** [hicetnunc2000/hicetnunc#384]
Why this message? 

IMPORTANT:

Your zip file must contain an index.html file.
You must also include a cover image and reference it in a meta tag like this:
<meta property="og:image" content="path/to/image.jpg">
Access to external resources is high restricted at the moment. Please include everything in your zip file (libraries, assets, etc).

HTML support is experimental – please report bugs on Github.

**Comment by andrevenancio** [comment]
That is a warning with instructions every time you try to upload a html NFT. was showing up when other media was being minted. but you can ignore it.
