### ISSUE TITLE
Going "back" from minting preview loses all previously entered data

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#387]
**Is your feature request related to a problem? Please describe.**
The preview feature after entering the minting data is very nice, but unfortunately if one notices an error and clicks on "back" one has to enter all the title, description and tag data again.

**Describe the solution you'd like**
It would be desirable if the last entered data in those text fields would be stored in local storage and be preserved

**Comment by scalemodal** [comment]
Yes.
We, actually, had a good thing before, when you can see the preview and form in the same time, even the "back" button is not needed here. It's more convenient to see the output on the same page.

I would also make the description field much bigger, one line is not enough.
