### ISSUE TITLE
When HTML minting pre-check fails the page ends up in an infinite alert box loop

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#388]
**Describe the bug**
When the minting-pre-check detects a problem with the provided zip file (in this case the missing image meta tag inside of index.html) it keeps popping up "missing cover image!" alert boxes, requiring a reload of the page to end it.

**To Reproduce**
1. Mint an OBJKT using the HTML-folder zip, which does not have all the required elements
2. Click on preview
3. See alert box
4. press ok
5. See alert box
6. press ok
7. See alert box
8. press ok

**Expected behavior**
The alert box should only appear once.

**Comment by mescalina** [comment]
Yes, it happens to me too (Chrome on Windows). I usually restart clicking on manage assets first and then on mint again.

**Comment by pichiste** [comment]
@Quasimondo this should be closed in latest release, can you close? thanks
