### ISSUE TITLE
HTML OBJKTS are not scrollable

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#389]
**Describe the bug**
HTML-based OBJKTs that are deliberately bigger than the viewing area do not show scrollbars and are not scrollable

**To Reproduce**
1. Create an OBJKT using the HTML template that is longer than the viewport
2. Check Preview
3. Preview works fine and shows scrollbars
4. Mint it
5. Go to the OBJKT page
6. no scrollbars visible, also no scrolling via mouse wheel is possible, neither in regular nor in fullscreen mode

**Expected behavior**
The final OBJKT should show a scrollbar and be scrollable

**Comment by andrevenancio** [comment]
fixed. should be up in the next deployment
