### ISSUE TITLE
HEN api error on objkt 1117 & 5115

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#390]
HI,

If I call the HEN api to get objkt **1117** data at this endpoint: https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/objkt
I get an answer with total_amount=0 and swaps[0]->objkt_amount=10
But if I try to open it on HEN website it says there are 10 Editions all swapped: https://www.hicetnunc.xyz/objkt/1117

How is it possible that the api says there is 0 in total_amount?

**Edit:**
Same problem on objkt **5115**.
They both appear to have no owners in the api response cause it says: owners:{}

I didn't find any other objkt with the same issue and I checked them all.

**Comment by mescalina** [comment]
Same problem on objkt 5115.
They both appear to have no owners in the api response cause it says: owners:{}

**Comment by Quasimondo** [comment]
Looks to me like the /objkt endpoint is wrong and the site is right. When I use my own script to check the operations related to #1117 I see these 3 actions:

```
{'type': 'swap', 'date': '2021-03-06T14:08:44Z', 'amount': 10, 'price': 40.0, 'from': 'Creator'}
{'type': 'cancel', 'date': '2021-03-06T14:18:44Z', 'amount': -10}
{'type': 'swap', 'date': '2021-03-06T14:20:44Z', 'amount': 10, 'price': 4.0, 'from': 'Creator'}
```
For #5115 it looks like this:
```
{'type': 'swap', 'date': '2021-03-13T01:25:15Z', 'amount': 1, 'price': 4.0, 'from': 'Creator'}
{'type': 'cancel', 'date': '2021-03-14T05:33:59Z', 'amount': -1}
{'type': 'swap', 'date': '2021-03-14T05:37:59Z', 'amount': 1, 'price': 2.0, 'from': 'Creator'}
```

Both have in common that there was an "uncurate" action taken, so maybe the /objkt endpoint somehow does not handle those correctly yet.

**Comment by mescalina** [comment]
Good catch, I think you could be definitely right, let's see if somebody can give us a definitive answer.
I thought the website was using that same endpoint, but I guess it's not.
Thanks for looking into it.

**Comment by mikesizz** [comment]
@Quasimondo What endpoint/script logic gives you the correct number? I was working on a hotfix to correct the ordering of creations and this came up in the discord.

I am not super familiar with the APIs being used to get this data, but I am all about adding a fix if you point me in the right direction.

**Comment by Quasimondo** [comment]
I am using a mixture between api.better-call.dev and api.tzstats.com. I am not at my machine right now so don't have the exact endpoints at hand, but  I am first getting all transactions related to a token from BCD and then i am getting the details of each tx by searching for the tx hash on tzstats and combine the relevant data from both calls. It's not the fastest method for sure.

**Comment by mikesizz** [comment]
So we can definitely get the same information from better-call.dev's transfers endpoint. This technically would give us the info we need to generate the correct object count. The issue still stands that the owners list is empty, so this indicates to me that some corrective action needs to be taken beyond fudging the count.

Perhaps the API just needs to force these tokens to be under the issuer so we can get back to square one. I'm guessing I'm way off here, so any expertise would be appreciated.

One thing I noticed is that the `indexed_time` from the initial mint/cancellation are very close to each other:

#1117
swap time: 1616827025863225
cancel time: 1616827025267542

#5115
swap time: 1616829628832131
cancel time: 1616829628588213

Note that this is different from the `timestamp` value. Is this some indication that both operations are actually being completed at the same time? Maybe some kind of status check is required before committing to the cancellation? Again, prolly way off here. Just shooting from the hip.

**Comment by mescalina** [comment]
André Venâncio on Discord said:

_Based of your screenshot it doesn’t have an owner
Which means it was minted over the 45minute period when we launch HTML where the creators were not defined (a bug was defining them as undefined)
So that means that if you are the person who minted it, you have it in your possession and it shows in your collections
But because it doesn’t have a creator “we” don’t know that you own it
And since it’s on the blockchain we can’t really delete it or edit it
There were a couple of those minted around that time. And based of the fact it has no “creators” it’s likely that is the case_

So I think we can see them on the HEN frontend because they have a creator and they are swapped but they cannot be sold cause they have an empty owners list.
Maybe we should add them to the o.json list in filters so nobody else have to deal with them.
I would personally add in that list ids from 1 to 151 (The non existing objects).

**Comment by mikesizz** [comment]
Thanks for adding that here @mescalina. I've been trying to piece this one together since yesterday.

**Comment by andrevenancio** [comment]
They can't be sold but they can be burned and you can mint again.

**Comment by violetforest** [comment]
seems like this was resolved, closing
