### ISSUE TITLE
augmented reality viewer and usdz support

### ISSUE THREAD

**Issue by atimtakus** [hicetnunc2000/hicetnunc#394]

**Comment by Quasimondo** [comment]
Can you please change the title of this issue so it reflects the feature you want to get? "Feature request" is too generic and very likely people will not even bother to read it. Also please use the template for feature requests and ideally provide some more details  like where to find info about the format you want to have supported.

**Comment by andrevenancio** [comment]
You're hired @Quasimondo 😅. But even with that test I do not understand what the request is. Please provide further information using the template provided, closing this

**Comment by atimtakus** [comment]
I was trying to issue a feature request but i couldn't succeed. I think an ar viewer feature for glb and usdz files would be super cool .
