### ISSUE TITLE
Removing hashtags from tags

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#395]
Pulling data from the api I've noticed that some people are adding the # symbol to each tag and it gets saved together with the data.
Wouldn't be better to remove it from the tags before saving them?
Also maybe tags should be always saved as lower case and without special characters (Maybe allowing allow only - and _ )?

**Comment by Quasimondo** [comment]
I think this is rather something that those who work creatively with tags or analyze them should do in a post-processing step. In general I would vote against making changes to the tags that people create since those are also means of individual creative expression and by "normalizing" them, in particular if that is not obvious to the people who create the tags we limit the possibilities.

**Comment by skenaja** [comment]
I'm adding namespaces to my tags, eg artist:xxxx, copyright:all_rights_reserved

I'd be wary about removing special characters too, especially for users writing in multi byte characters.

**Comment by mescalina** [comment]
Yes, I see your point, and I totally agree. So maybe it would be better to have an info box under the tags field explaining that the # symbol is not needed.
Otherwise if I tag "#fish" but what I meant was just "fish" any platform interacting with the data has to make a decision, it could remove starting hashes, to find the correct "fish" tag, but anyway it would introduce a normalization that would prevent people to have a coherent meaning in that specific symbol they are using.
Maybe the best option would be to allow anything but # so any special character can be assumed to be used for a wanted purpose and not by mistake. I think it stills need reasoning.

**Comment by Quasimondo** [comment]
I always liked the way that flickr is using tags creatively. And ultimately once they are actually being used on the site for categorization or search I believe that certain standards will evolve by itself. For your own analysis I think you could employ techniques like levenshtein distance or BERT to group tags by their various similarities.

**Comment by andrevenancio** [comment]
I improve the messaging on the mint page. Hopefully it wont be confusing to users. but it does say `tags` not `hashtags` :)
