### ISSUE TITLE
Gyro+Accelerometer access for nft iframe

### ISSUE THREAD

**Issue by jacksonzumdish** [hicetnunc2000/hicetnunc#396]
I've been working on a collab with a fellow artist that uses the accelerometer+gyro but I think we need that feature enabled for the iframe?

Here is an actual .zip nft that has been added to hic et nunc: https://www.hicetnunc.xyz/objkt/22459

Pressing gyro button should request permission for sensor access.

Loading the nft directly without the iframe (ie on an iPhone) works as expected: https://bafybeifwdhce3f4ato2gyxhy32qko75xgsd3siajgbqkzky6ooqz3jliwy.ipfs.infura-ipfs.io/?creator=tz1ggkshTXjarWGc7NSNQdM8qGW7bsXP5QN8&viewer=false

And here is how to enable the access for the iframe: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/accelerometer

**Comment by andrevenancio** [comment]
This is disabled by design. We're evaluating security concerns.
