### ISSUE TITLE
OBJKT was created but the content is not displayed

### ISSUE THREAD

**Issue by capoluiz** [hicetnunc2000/hicetnunc#400]
OBJKT#22703 was created but the content, video file, is not displayed.

https://www.hicetnunc.xyz/objkt/22703

**Comment by andrevenancio** [comment]
![image](https://user-images.githubusercontent.com/1734502/113513022-6abaf080-955f-11eb-82a6-e17ae3fdd8c7.png)

**Comment by capoluiz** [comment]
Hi,
the video disappear again.

https://www.hicetnunc.xyz/objkt/22703

Att.




*Capo Luiz*
UX designer
(11) 96316-0894

www.capoluiz.com
***@***.***
