### ISSUE TITLE
Interesting behaviour when fullscreen button toggle

### ISSUE THREAD

**Issue by zmnv** [hicetnunc2000/hicetnunc#402]
**Describe the bug**
Unexpected behaviour of the fullscreen mode.

**To Reproduce**
See the VIDEO: https://imgur.com/VlxHLNI

1. Go to any object
2. Click on FULLSCREEN icon-button
3. You will see the same cropped view.
4. Leave the fullscreen and see actually fullwidth image
5. I can't do anything because the interface is blocked that image

**Expected behavior**
you know ;)

**Screenshots**
<a href="https://imgur.com/VlxHLNI">
![image](https://user-images.githubusercontent.com/25253501/113514842-8b903f80-9579-11eb-87c9-dabec302bcde.png)
</a>

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Browser: Chrome
 - Version: Версия 89.0.4389.114 (x86_64)

**Additional context**

It happens all time for all objects. 
Tested object: https://www.hicetnunc.xyz/objkt/13787 (not mine)

----

PS: with awesome 3d model it is looks a w e s o m e! can you add a new mode 'full width'?) with fixed height ;)

**Comment by andrevenancio** [comment]
I had noticed this before. I think this is Google's <model-viewer> component we use that isn't taking in consideration the fullscreenchange event. If you resize the browser after you exit fullscreen it fixes it. I've tried to had a chat with one of the Google developers we have on the platform but it's not clear yet it how to resolve this.

**Comment by zmnv** [comment]
fixed now. thanks!
