### ISSUE TITLE
Total number issued needs to be displayed

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#41]
To judge the price of an OBJKT, i'ts absolutely crucial to know the number of tokens that were minted. Right now, I only see how many are available at the moment. I see that as a very high prio.

**Comment by raynt** [comment]
Agreed. Other than bug fixes I see this as critical. The site used to have "remaining / edition size" I assume this was removed due to a technical reason?

**Comment by crzypatchwork** [comment]
it was updated. such info was re-aggregated into the API. owners are also fetched for each objkt/on each individual objkt page.
