### ISSUE TITLE
Error When Minting

### ISSUE THREAD

**Issue by Mobtais** [hicetnunc2000/hicetnunc#410]
**Describe the bug**
I get this message when i try to mint:

Storage quota exceeded for the operation

A script or one of its callee wrote more bytes than the operation said it would

The file is only 3,5 MB

**To Reproduce**

Mint an item

**Expected behavior**

Minting the item

**Screenshots**

<img width="389" alt="Skærmbillede 2021-04-05 kl  15 13 39" src="https://user-images.githubusercontent.com/81970401/113577441-8edf0600-9621-11eb-9a78-7e775b511cb4.png">

**Desktop (please complete the following information):**

Safari macOS 10.14.6

**Smartphone (please complete the following information):**

**Additional context**

wallet adress: tz1YBS6LmVCkC37YnErG2MvJ25BBWJgDerT3

operation hash: opDSzyeaZmyUqdDSQuPsmm7t5wjayNLw156xWQX7j43FxS8MRhD

**Comment by ZOOTGHOST** [comment]
I'm having the same issue. Tried twice and got the same error.
![Screen Shot 2021-04-05 at 20 34 08](https://user-images.githubusercontent.com/11487291/113617514-4ee24800-964e-11eb-9797-71f9aaec90f5.png)

**Comment by neverhood311** [comment]
I get this error almost daily

**Comment by andrevenancio** [comment]
The error is on the wallet level. Not on hic et nunc. Just try again 🙏🏻

**Comment by Mobtais** [comment]
Hey, thanks, but every time i try it happens again, and the tez are being withdrawn from my account...
