### ISSUE TITLE
Content Security Policy issue when using DRACOLoader

### ISSUE THREAD

**Issue by borisdiakur** [hicetnunc2000/hicetnunc#411]
Hello :wave:
I'm trying to publish an interactive game made with Three.js and I'm getting errors in the preview. The game loads a heavy GLTF model and uses the DRACOLoader for that (see https://threejs.org/docs/#examples/en/loaders/DRACOLoader). I suspect that the loader uses workers under the hood. And it seems that hicetnunc is blocking access to those workers with the error message

> Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://hicetnunc2000.github.io/39efd702-2e43-e049-8227-ca769b91e0ae (“default-src”).

I think that the path to the worker has a slash in the beginning and that is why the complete URL is not correct and hence is being blocked. Any ideas what can be done in this case? I wonder if I am the first to use the official DRACOLoader in a project on hicetnunc :see_no_evil:

**To Reproduce**
Use the DRACOLoader to load a draco compressed model. Continue as per official documentation.
```
var dracoLoader = new THREE.DRACOLoader();
dracoLoader.setDecoderPath(''); // everything is in the root folder
dracoLoader.setDecoderConfig({type: 'js'}); // optional
```

**Expected behavior**
The compressed model should load and be encoded by the draco loader.

**Screenshots**
![Screenshot 2021-04-05 at 19 41 07](https://user-images.githubusercontent.com/527049/113609595-4426b380-964c-11eb-9f46-86170c7cb29f.png)

**Desktop (please complete the following information):**
 - macOS Big Sur 11.2.2 (20D80)
 - Firefix 88.0b7 (64-bit)

Please help me figure something out 🙏

**UPDATE**: After digging further I think I have found the line that creates the blob url inside the DRACOLoader class: https://github.com/mrdoob/three.js/blob/a382159ab8575857bc042d314019bf45edb14117/examples/jsm/loaders/DRACOLoader.js#L313

**Comment by andrevenancio** [comment]
@pichiste

**Comment by pichiste** [comment]
Hey @borisdiakur, this is caused by the current Content Security Policy that gets applied, which restricts what sources a worker can have using the [worker-src directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src). Adding `blob:` to this fixes the issue – I'll roll this change into an upcoming PR and post here when it's done.

**Comment by borisdiakur** [comment]
@pichiste Sounds great! In the meantime I have managed to reduce the weight of my model by almost 80% using meshlab 😅  so I won't need to use the DRACOLoader anymore. But for future project the issue is still important 😉
Thank you! 🙏

**Comment by pichiste** [comment]
It's a good thing to fix regardless as many packages might be creating workers this way. Fix is on its way.

**Comment by andrevenancio** [comment]
Closing this. approving PR which will fix this issue. will go into the next deployment cycle
