### ISSUE TITLE
Content not displayed

### ISSUE THREAD

**Issue by capoluiz** [hicetnunc2000/hicetnunc#412]
**Describe the bug**
The content is still not displayed. Memos after they acted on.

https://www.hicetnunc.xyz/objkt/22703

**Comment by andrevenancio** [comment]
@pichiste Didn't you changed the video URL?

**Comment by andrevenancio** [comment]
Seems like you uploaded a `mov` file @capoluiz Have you tried to upload a `mp4`?

**Comment by capoluiz** [comment]
Yes, I tried to upload in mp4 and mov, but I had to try more than once
until I was successful




*Capo Luiz*
UX designer
(11) 96316-0894

www.capoluiz.com
***@***.***

**Comment by skenaja** [comment]
Error message when clicking `ipfs` url on objkt-detail: 
> https://cloudflare-ipfs.com/ipfs/QmeMC71Vtio2RoJW2obLczTipAin1Wd2EFAoANqt9XiuyY
> `ipfs: video streaming is not allowed`

**Comment by mbransn** [comment]
Hi all, I've also got an [OBJKT here](https://www.hicetnunc.xyz/objkt/47461) that is a mov file. It is working on safari now, but not firefox or chrome. I tested across all browsers before swapping last month, but now appears to be broken.

**Comment by skenaja** [comment]
That's encoded using H.265 - it's not supported by many browsers: https://caniuse.com/hevc

![image](https://user-images.githubusercontent.com/510285/117589708-1dfca380-b123-11eb-802c-37388f2cfe0d.png)

H.264 has much wider support: https://caniuse.com/mpeg4

**Comment by violetforest** [comment]
this should be added to the wiki

**Comment by violetforest** [comment]
does anyone else have an unresolved issues with this? im going to close it but if anyone else needs help let me know and i  will reopen it.
