### ISSUE TITLE
FAQ link missing

### ISSUE THREAD

**Issue by drycounty** [hicetnunc2000/hicetnunc#418]
FAQ currently goes to:

https://github.com/hicetnunc2000/hicetnunc/blob/main/FAQ.md

Which is a 404.  Just curious when it will be back, thanks!

**Comment by andrevenancio** [comment]
It will NOT be back. We're waiting on a deployment to fix this. The new FAQ is a WIKI. lives here: https://github.com/hicetnunc2000/hicetnunc/wiki
