### ISSUE TITLE
Swapping an objkt for 4.1 tez produces an error "Error: Unrecognized error: F" on Kukai

### ISSUE THREAD

**Issue by matangkuwago** [hicetnunc2000/hicetnunc#419]
**Describe the bug**
Just a minor bug, it seems you cannot swap an objkt with a 4.1 tez price

**To Reproduce**
1. Swap an objkt
2. Enter price as 4.1 tez
3. Kukai would show the error "Error: Unrecognized error: F"

**Comment by skenaja** [comment]
Temple wallet gives this confirmation request for 4.1 tez (but not 4.2 or 4.0) "Warning! Transaction is likely to fail". 

JSON shows a type mismatch int `4099999.9999999995`

![image](https://user-images.githubusercontent.com/510285/113770957-b5cd3300-971a-11eb-87ab-6622e6110a66.png)

````json
[{
	"destination": "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9",
	"kind": "transaction",
	"amount": 0,
	"parameters": {
		"entrypoint": "swap",
		"value": {
			"prim": "Pair",
			"args": [{
				"int": "1"
			}, {
				"prim": "Pair",
				"args": [{
					"int": "14526"
				}, {
					"int": "4099999.9999999995"
				}]
			}]
		}
	}
}]
````

**Comment by skenaja** [comment]
The error is here [swap.js#L28](https://github.com/hicetnunc2000/hicetnunc/blob/9ffec08a086520c85874fc5024ee8454a50f36ab/src/pages/objkt-display/tabs/swap.js#L28)

> parseFloat("4.1" * 1000000)
4099999.9999999995

**Comment by andrevenancio** [comment]
merged! thanks @skenaja
