### ISSUE TITLE
Manage Assets: Sort by ID

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#42]
Would be cool to have an easy sort by ID (for now). Future iterations could add more filters. For now it could be super minimalistic, eg something like this:

![image](https://user-images.githubusercontent.com/40259308/110289638-018c9f80-7fea-11eb-9420-be7c81543a66.png)

**Comment by raynt** [comment]
Also sort by works available? I imagine there is a lot of bandwidth used as people scrolling through the site. It might help with server efficiency?

**Comment by andrevenancio** [comment]
I like this idea! I'll pick it up tomorrow

**Comment by oldominion** [comment]
Simple filters would make a big difference too. Only show works that are currently for sale by default,  for example.
