### ISSUE TITLE
Url to access directly the collection tab

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#427]
I think it would be nice to have the possibility to access directly the collection tab of an address with an url. It could be a different url from the creations tab or just a GET variable like ?tab=collection. 

If you send the link of your collection to somebody you need to specify to click the button which is annoying. Same if you want to share the link somewhere.

Also it could be that, if there are no creations but there are items in the collection, the page opens automatically on the collections tab.

**Comment by yanngraf** [comment]
This would indeed be handy. The feature request is also described here. To be upvoted. https://hicetnunc.featureupvote.com/suggestions/176388/make-users-collection-available-at-tzaddrcollection

**Comment by andrevenancio** [comment]
This has been implemented. Awaits deployment to production

**Comment by skenaja** [comment]
This is now live!!
