### ISSUE TITLE
FAQ dead link

### ISSUE THREAD

**Issue by santi-grau** [hicetnunc2000/hicetnunc#428]
**Describe the bug**
Clicking link to FAQ directs you to an empty github (404) page
url : https://github.com/hicetnunc2000/hicetnunc/blob/main/FAQ.md

**To Reproduce**
1. Go to menu
2. Click on about
3. Scroll down to 'FAQ's are available here'
4. Click on 'here'

**Expected behavior**
Fix link to FAQ

Please include the wallet address (tz...) and/or the OBJKT number.
tz1TQDnNCwU6DYTGFY7HZrFHivNBJW1LthbS

**Comment by skenaja** [comment]
This is fixed in https://github.com/hicetnunc2000/hicetnunc/commit/db70a385a15c32af55518df96310a9c9314b20df which is awaiting deployment to the website by the core team.
