### ISSUE TITLE
Unable to Burn item or change the price of the piece itself

### ISSUE THREAD

**Issue by ALIENGHOST420** [hicetnunc2000/hicetnunc#430]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by andrevenancio** [comment]
This description is not useful. It is a template for you to provide us more information.

**Comment by ALIENGHOST420** [comment]
Hey Andre, 

I would like to BURN one of my minted items i uploaded to your platform yesterday. Your user interface is rather difficult to navigate and I am getting a ERROR each time i attempt to remove it from the blockchain. Is this a more concise question to have asked? hopefully you can help.

cheers,

sam

**Comment by skenaja** [comment]
Hi @ALIENGHOST420 
The template asks for information that help us diagnose your problem.
Please could you confirm: 
* the objkt ID
* The error message - what was it?
  * was it on the hicetnunc website or in the wallet popup?
