### ISSUE TITLE
FAQ are gone

### ISSUE THREAD

**Issue by kenokenobingo** [hicetnunc2000/hicetnunc#432]
The link to the FAQ on [the website](https://www.hicetnunc.xyz/about) doesn’t work: <https://github.com/hicetnunc2000/hicetnunc/blob/main/FAQ.md>.

**Comment by mathMakesArt** [comment]
The FAQ has been replaced with the Wiki, [**which you can find here**](https://github.com/hicetnunc2000/hicetnunc/wiki).

I do agree that this should be made more visible. I'll put together a simple pull request to modify the FAQ link on the website to point to the Wiki instead. Thanks for reporting the issue!

**Comment by mathMakesArt** [comment]
Never mind, as stated by @skenaja [**here**](https://github.com/hicetnunc2000/hicetnunc/issues/428#issuecomment-814391011) this has already been fixed and is awaiting deployment to the live website.

Thanks HEN team!

**Comment by kenokenobingo** [comment]
Ah thanks, couldn’˝t find it on my own! Good to hear that the changes will be deployed soon!
