### ISSUE TITLE
implementing displayUri across the different sections of the site

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#436]
**Is your feature request related to a problem? Please describe.**
With the introduction of thumbnails, we need to adjust it across the site

**Describe the solution you'd like**
the function that renders which media to display, needs to receive an extra parameter that will likely be router location. Its important to know which route we're in in order to decide which asset to load from IPFS

**Additional context**
This seems to be the logic to employ

on `feed` load `displayUri` if available, otherwise default to `artifactUri`
on `tz/xxxx` load `thumbnailUri` if available otherwise default to `artifactUri`
on `objkt/xxxx` load `artifactUri`

on `feed` if `displayUri` is an empty string on old OBJKT
on `tz/xxxx` if `thumbnailUri` is black circle (IPFS_DISPLAY_URI_BLACKCIRCLE on constants.js) load the `artifactUri` if the ipfs link is the same as the IPFS_DISPLAY_URI_BLACKCIRCLE variable.

**Comment by violetforest** [comment]
closing due to this being addressed currently in development
