### ISSUE TITLE
Attempting to burn an objkt that is not in your wallet should generate an error message

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc#437]
**Is your feature request related to a problem? Please describe.**
When a user tries to burn an item that is not in their wallet, the burn operation will appear to be running, and won't return an error.

This can be demonstrated here: https://github.com/hicetnunc2000/hicetnunc/blob/main/src/context/HicetnuncContext.js#L197
When tz.address <> amount.key then amount[tz.address] = undefined, so parseInt will return NaN, and the following async operation will hang. 
An error will appear in the console: `{value: NaN, token: t, name: "NatValidationError", message: "[amount] Value is not a number: NaN"}` which is generated by Taquito attempting to parse the parameters to Michelson code.

**Describe the solution you'd like**
The error message should say something "Burning this OBJKT is not possible as it is not in your wallet"

**Describe alternatives you've considered**
Alternatively the `burn` tab could be hidden if the user's wallet ID is not an owner, or the burn button itself could be hidden.

**Comment by andrevenancio** [comment]
Assigned to you and you should be able to use labels and do some triage!

**Comment by andrevenancio** [comment]
there's a few parseInt on the HicetnuncContext that I suspect should probably be parseFloat too

**Comment by andrevenancio** [comment]
I've hidden the burn menu if you're not the owner of the nft you're looking at. Does that fix this for you?

**Comment by skenaja** [comment]
Sounds good to me!
