### ISSUE TITLE
Can't Swap

### ISSUE THREAD

**Issue by aelisedavis** [hicetnunc2000/hicetnunc#438]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.hicetnunc.xyz/objkt/25497'
2. Click on 'Swap'
4. See error - "The swap is invalid" 

**Expected behavior**

To set a price on my piece.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by skenaja** [comment]
Issue solved in Discord. Noting solution here for people searching for error message. 

Error message shown when you click "swap it" when leaving the amount & price blank. Both need to be entered

![image](https://user-images.githubusercontent.com/510285/113907098-e1a8f100-97cc-11eb-8158-7e8f61ba147f.png)
