### ISSUE TITLE
Move mint page fields explanations outside of the placeholder text

### ISSUE THREAD

**Issue by SableRaf** [hicetnunc2000/hicetnunc#448]
**Is your feature request related to a problem? Please describe.**
In some cases, fields in the mint page will be automatically filled by the browser making them opaque to the user. 

**Describe the solution you'd like**
Could the form have the explanations outside of the placeholder text?

**Describe alternatives you've considered**
Another possible solution in case we want to keep the minimalist look would be to have a tooltip on mouse hover but this is only working on desktop

**Additional context**
There has been quite a few people confused by this in the Discord.

**Comment by DonKarlssonSan** [comment]
This is live, I think this can be closed.

**Comment by skenaja** [comment]
Closing!
