### ISSUE TITLE
Artist Validation not Working

### ISSUE THREAD

**Issue by pindarvanarman** [hicetnunc2000/hicetnunc#451]
Have gone through validation steps to register my twitter ID and information 3 times now.

for wallet address - tz1ekiLhn728uswyyWmzYLzBWZ22GtgktotM

Yet nothing is happening and it has been 2 weeks since my last attempt.

Need help validating my artist ID.

How do I do it?

Thanks,

**Comment by djangobits** [comment]
Hello! tzkt.io is a completely different enity and has nothing to do with hicetnunc. hicetnunc just pulls data from there. Check the contacts on the bottom of this page: https://baking-bad.org/docs/
