### ISSUE TITLE
All new items are coming out of the API with total_amout=0 and no owners!!!

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#455]
Since item 26906 they are all coming out of the api with total_amount=0 and no owners!
I'm using this endpoint: https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/objkt

26906, 26907, 26908, 26909, 26910, 26911, 26912, 26913, 26914, 26916, 26915, 26917, 26918, 26919, 26920, 26921, 26922, 26923, 26924, 26925, 26927, 26926, 26928, 26929, 26930, 26932, 26931, 26933, 26935, 26934, 26936, 26937, 26939, 26938, 26941, 26940, 26942, 26943, 26944, 26945, 26946, 26947, 26948, 26949, 26950, 26951, 26952, 26953, 26954, 26955, 26956, 26957, 26959, 26958, 26960, 26961, 26962, 26963, 26964, 26965, 26966, 26967, 26968, 26969, 26971, 26970, 26972, 26973, 26974, 26975, 26977, 26976, 26978, 26980, 26979, 26982, 26981, 26983, 26984, 26985, 26986, 26987, 26988, 26990, 26989, 26991, 26993, 26992, 26994, 26995, 26996, 26998, 26997, 27000, 26999, 27001, 27002, 27003, 27004, 27005, 27006, 27007, 27008, 27009, 27010, 27011, 27012, 27013, 27014, 27015, 27016, 27017, 27018, 27019, 27020, 27022, 27023, 27021, 27024, 27026, 27027, 27025, 27028, 27029, 27030, 27031, 27032, 27033, 27035, 27034, 27036, 27037, 27038, 27040, 27039, 27041, 27042, 27043, 27044, 27045, 27046, 27047, 27048, 27049, 27050, 27051, 27053, 27052, 27055, 27054, 27056, 27057, 27058, 27059, 27060, 27062, 27061, 27063, 27064, 27065, 27067, 27066, 27068, 27069, 27072, 27070, 27071, 27073, 27074, 27075, 27076, 27077, 27078, 27079, 27080, 27081, 27082, 27083, 27084, 27085, 27087, 27088, 27086, 27089, 27091, 27090, 27094, 27092, 27093, 27095, 27096, 27097, 27099, 27098, 27101, 27100, 27102, 27104, 27103, 27105, 27106, 27107, 27108, 27109, 27110, 27112, 27111, 27113, 27114, 27116, 27115, 27117, 27118, 27119, 27120, 27121, 27123, 27122, 27124, 27125, 27126, 27127, 27128, 27129, 27130, 27131, 27132, 27133, 27134, 27135, 27136, 27137, 27138, 27139, 27140, 27141, 27142, 27143, 27144, 27145, 27146, 27147, 27148, 27149, 27150, 27151, 27152, 27153, 27154, 27155, 27156, 27157, 27158, 27159, 27160, 27161, 27162, 27163, 27164, 27165, 27166, 27167, 27168, 27169, 27170, 27171, 27172, 27173, 27174, 27175, 27176, 27177, 27178

**Comment by mescalina** [comment]
27118, 27119, 27120, 27121, 27123, 27122, 27124, 27125, 27126, 27127, 27128, 27129, 27130, 27131, 27132, 27133, 27134, 27135, 27136, 27137, 27138, 27139, 27140, 27141, 27142, 27143, 27144, 27145, 27146, 27147, 27148, 27149, 27150, 27151, 27152, 27153, 27154, 27155, 27156, 27157, 27158, 27159, 27160, 27161, 27162, 27163, 27164, 27165, 27166, 27167, 27168, 27169, 27170, 27171, 27172

**Comment by mescalina** [comment]
I think the Better Call Dev api returns the correct amount, so I guess the error is just in the HEN api or Cryptonomic.
I checked item 26907 at this endpoint: https://api.tzkt.io/v1/accounts/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/operations?entrypoint=mint&parameter.token_id=26907

and this is the data:

    "parameter": {
        "entrypoint": "mint",
        "value": {
            "amount": "10",
            "address": "tz1fhd4k1jSJRRcNVbkMwVzkKEhX3kzApsfk",
            "token_id": "26907",
            "token_info": {
                "": "697066733a2f2f516d527152646a5539537a4b7975457a325944433667346654456f48415133466a34324846615570664342456b5a"
            }
        }
    },

If this amount is the info I'm looking for it should be fine.

**Comment by skenaja** [comment]
This was caused by problems with the upstream API provider not having up-to-date L2 data. The API is now returning correct results for these objects.
