### ISSUE TITLE
HTML/Interactive OBJKT feature permission management

### ISSUE THREAD

**Issue by pichiste** [hicetnunc2000/hicetnunc#459]
**Is your feature request related to a problem? Please describe.**

There has been several requests (https://github.com/hicetnunc2000/hicetnunc/pull/219, https://github.com/hicetnunc2000/hicetnunc/issues/396, https://github.com/hicetnunc2000/hicetnunc/pull/454) to enable features such as camera, accelerometer, geolocation, file downloads, etc for HTML/interactive OBJKTs. The main reason for not simply turning these on is that, since HTML OBJKTs are embedded in an iframe, the permissions are set site-wide for hicetnunc.xyz. 

To me and several others, this feels like a big security risk. For example: I enable camera and geolocation for a piece by an artist I know and trust. It's now enabled for all other HTML OBJKTs I open without my explicit consent.

This post is partially intended to open up the conversation as to whether we see this as a security risk or not.

**Describe the solution you'd like**

One possible solution:

On the mint page, creators can enable features for their OBJKT. For example:
```
[x] camera
[x] microphone
[ ] accelerometer
[ ] gyroscope
[ ] geolocation
[ ] xr-spatial-tracking
[ ] file download
```

This info is included in the OBJKT metadata, so it's clear which iframe attribute values the OBJKT requires (in this case with regards to `allow` and `sandbox` attributes). These can then be injected into the iframe when displaying, both in preview and OBJKT page.

On top of this, the viewer would need some way to allow features on a per-OBJKT basis. This could be a simple modal that appears before the iframe is loaded on each OBJKT page, or a more fleshed out settings page as suggested by @andrevenancio. The per-OBJKT permissions could be stored in localStorage, and reverted at any time.

Is the above sound, or over the top? Maybe only some of these need explicit permission per-OBJKT (camera, mic, geoloc, file downloads)?

Thoughts? 

@andrevenancio @veqtor @atomantic @mrdoob

**Comment by andrevenancio** [comment]
In my opinion we have two possible solutions:

1) On the back of your suggestions:
We could render the sandbox without anything besides `allow-scripts allow-same-origin` as it currently stands. Then, we can check against the objkt metadata and get those props you suggested, and prompt the user saying: "This NFT want's to use A,B and C". If the user alows for that those props will be added to the sandbox. But that will cause the browser to also prompt those permissions (forcing the user to have to "authorise" twice. One at the platform level, and another at the browser level). Which to me isn't ideal as it will block HTML from loading automatically like it currently does on objk detail page.

2) My initial idea was to have per/platform settings
So we would have a settings page, where you could define what features you want to enable per ALL Interactive NFT (amongs other settings like language, or theme).

So if you enable `webcam` on your settings, the webcam feature will be included in all iframe sandboxes.

this hopefully requires the user to only allow for browser permissions one (if they're persistent across the ipfs domain or not - I need to test it).

**Comment by pichiste** [comment]
> In my opinion we have two possible solutions:
> 
> 1. On the back of your suggestions:
>    We could render the sandbox without anything besides `allow-scripts allow-same-origin` as it currently stands. Then, we can check against the objkt metadata and get those props you suggested, and prompt the user saying: "This NFT want's to use A,B and C". If the user alows for that those props will be added to the sandbox. But that will cause the browser to also prompt those permissions (forcing the user to have to "authorise" twice. One at the platform level, and another at the browser level). Which to me isn't ideal as it will block HTML from loading automatically like it currently does on objk detail page.

Totally agree that double authorization is awkward, but not sure how else to enforce this type of per-OBJKT setting, if we do indeed need it...

Testing with a simple webcam example, it looks like Chrome is the only browser that defaults to remember your choice after the first time you allow/disallow. FF and Safari default to asking each time.

> 2. My initial idea was to have per/platform settings
>    So we would have a settings page, where you could define what features you want to enable per ALL Interactive NFT (amongs other settings like language, or theme).
> 
> So if you enable `webcam` on your settings, the webcam feature will be included in all iframe sandboxes.

If we are ok with feature permissions being global across OBJKTs, then this makes sense, but we still need a way for creators to specify features, otherwise we won't know why certain OBJKTs don't work.

> 
> this hopefully requires the user to only allow for browser permissions one (if they're persistent across the ipfs domain or not - I need to test it).

If we're OK with global permissions across all OBJKTs, then option 3 would be that we just add all the features into the iframe, and let the user decide via the browser prompts :)

I guess the main question is: **Do we need per-OBJKT permissions?** 👀

**Comment by atomantic** [comment]
Per object permissions would seem to require also preventing the object from loading anything until the permission is reviewed--else in Chrome, a persistent choice would be in-effect even without the site wrapping a permissions prompt... feels like this is an awkward over-engineering to me--and feature support/behaviors are going to change over time per browser. As a user, I'd prefer just the native browser prompt and some docs on how to disable allowances if people want to turn it off. Any iframe object could come with a UI element with a helper icon, or an alert icon, warning the user of the implications of allowing device features.

**Comment by pichiste** [comment]
If we disregard geolocation for now, global permissions handled natively via the browser + some generic alert/messaging about permissions seems sensible. It was mainly the scenario of camera + geolocation + wallet address that I found troubling.

One argument for adding the feature selection on the creator/minting side, is that the NFT metadata itself can declare what features are required, in the case of it being embedded on a different platform or website. It's far from a standard, but seems more future-proof.

**Comment by pichiste** [comment]
A new proposal based on the above:

- Feature permissions are global and handled natively at the browser level
- Creators can select features to enable for their OBJT via some checkboxes on the mint page. The choices are:
 ```
camera
microphone
accelerometer
gyroscope
xr-spatial-tracking
allow-downloads
```
- Those flags are automatically injected on the display iframe
- iframes should have an info icon somewhere, that when clicked, opens a modal displaying which features are used by the HTML OBJKT, and making it clear that their wallet address is accessible by the OBJKT.
- The first time a user visits an OBJKT page that has **camera, microphone, or allow-downloads** enabled, the info modal opens automatically. A flag can be saved in localStorage so the modal only auto-opens the first time.

**Comment by pichiste** [comment]
Optionally, we scrap the creator-side feature selection, always include all those flags, and show the iframe warning the first time a user goes to an HTML OBJT page.

**Comment by pichiste** [comment]
Ok, here's a PR with a solution based on @atomantic's suggestion above, and without the creator-side feature selection: https://github.com/hicetnunc2000/hicetnunc/pull/462

@andrevenancio The settings page stuff could be added on top of this if needed.
