### ISSUE TITLE
Update 'Play' icon to improve thumbnails of Interactive OBJKTS

### ISSUE THREAD

**Issue by pjavid** [hicetnunc2000/hicetnunc#463]
Currently, interactive OBJKT thumbnails are displayed with a large 'play' icon in the center of the preview image.

This makes it difficult to appreciate the preview image at a glance, especially in gallery view. And for new users, the 'play' icon might suggest that the piece is a video or animation, not an interactive work.

I suggest two changes:
1) Move the icon for interactive OBJKT thumbnails to a corner of the image
2) Update the icon itself to a symbol that suggests the interactive nature of the work.

A mockup is attached with suggested changes:

![image](https://user-images.githubusercontent.com/9538232/114227299-ab34b880-9929-11eb-9da2-16218a9d2880.png)

**Comment by violetforest** [comment]
the svg has been changed, thank for the feedback!
