### ISSUE TITLE
Gif thumbnails are missing on new HTML NFTs.

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#464]
**Describe the bug**
I was able to upload gif thumbnails with HTML objects but now it looks like this: 
![image](https://user-images.githubusercontent.com/2965842/114245259-cb4f9080-9998-11eb-923f-b6c7a34a5ac3.png)

**To Reproduce**
1. Upload an HTML object with a gif thumbnail.

**Comment by pichiste** [comment]
This is a new bug affecting all HTML OBJKT cover images, not just GIFs. Fixed in this PR: https://github.com/hicetnunc2000/hicetnunc/pull/465

Thanks for reporting!

**Comment by pichiste** [comment]
@bilgekaan this should be fixed now, can you close the issue? (I don't have access) thanks!
