### ISSUE TITLE
Listings/Swap tab on profile

### ISSUE THREAD

**Issue by leonardschoelch** [hicetnunc2000/hicetnunc#467]
Right now it's a bit hard to find the artworks you have listed as they won't show in the collection tab at all as far as I can tell.

It would be great if we could add a third 'Swaps' tab that contain all the NFTs the profile has on offer. This does at a little bit of redundancy with the creations tab, which can contain some of the same NFTs by this profile, but overall this is a feature that is needed I believe.

**Comment by skenaja** [comment]
Hi @leonardschoelch - closing this as a duplicate of #276
