### ISSUE TITLE
Storage quota exceeded for the operation

### ISSUE THREAD

**Issue by 0x666c6f** [hicetnunc2000/hicetnunc#471]
**Describe the bug**

When Hic et Nunc smart contracts are under heavy load, a lot of transactions get backtracked because of the "Storage quota exceeded for the operation" error. It can happen directly at the first contract call from the user, or during internal smart contract calls.

**To Reproduce**

1. Alice sends a transaction that removes data from the Storage
2. Bob prepares a transaction that adds data to the Storage and at the same time Charly also prepares a transaction that will add data to the storage
3. Send both Bob and Charly transactions at the same time
4. The first transaction to get processed will pass, but the last one will get backtracked because the storage size will have changed. At the time of both transaction preparations, the Storage Limit was estimated to 0 by both transactions. Only one will be able to not pay any storage fees, the other one will have to pay. 
5. See error: 
```
"Storage quota exceeded for the operation
A script or one of its callee wrote more bytes than the operation said it would"
```

**Expected behavior**

The Storage Fee estimation should be overvalued by Hic et Nunc front end as if every call would trigger a data storage increase to avoid this error to its users.

**Screenshots**

In the following screenshot, at the time of the transaction preparation, the `mint_OBJKT` call was estimated to 0 Storage Fee, so only 208 bytes were estimated for the whole transaction (the `mint` call).

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
Example of failed transactions:
* https://better-call.dev/mainnet/opg/oocoyyudJyZjiQWJG3jkHq67tTYuNxkTKwHy5TNTuirZJp524YY/contents
* https://better-call.dev/mainnet/opg/ookshraPnN5DYFLEQKeNp6nuxZ4zBniqrfymbjzNsPxto2GBify/contents

On April 9th 2021 it happened 541 times at 18:30 UTC+2.

Request to find the number of errors: 
```shell
curl --location --request GET 'https://api.tzkt.io/v1/operations/transactions?target=KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9&status=backtracked&limit=10000&timestamp.gt=2021-04-09T00:00:00Z' | grep -o -i "storage_exhausted.operation"  | wc -l
```

**Comment by jamesyu** [comment]
What is the workaround for this at the moment? Just keep retrying?

**Comment by IgnacioGioia** [comment]
On dekstop i tried to mint my first NFT
OS: Windows 10
Browser: Google Chrome
Version: 89.0+

https://tzkt.io/oouaMTuHmQwJi9hEej6Dqia8UfQN2STtbFKReaD3FabZn1c7efk

As i said, this was my first attemp at minting an NFT so i don't know how to act, should I wait, try again now or try again later? Some ammount of tezos were deducted from my account, but i don't think is the full minting fee, again, i'm new at this so im a bit lost, any help would be appreciated.

**Comment by 0x666c6f** [comment]
Hello @jamesyu , depending on the wallet you're using, you can over-estimate the storage fees of your transaction using your Wallet. It should prevent this error from happening.
I know it is possible with Temple wallet, but not sure about the others.

**Comment by jamesyu** [comment]
@florianpautot Yep that did work for me! Worth adding this to the FAQ.

**Comment by arielm** [comment]
It's not working for me: even after over-estimating the storage fee to the max, I still get the error from time to time :(

**Comment by skenaja** [comment]
> @florianpautot Yep that did work for me! Worth adding this to the FAQ.

I've raised a ticket to get the FAQs updated #523

**Comment by skenaja** [comment]
FAQ was updated, closing.
