### ISSUE TITLE
Accept .glb upload in file upload dialogue on minting page.

### ISSUE THREAD

**Issue by laoko** [hicetnunc2000/hicetnunc#472]
**Describe the bug**
My understanding is that .GLB files are supported on the site, however when trying to upload one, the file upload filter does not list it as one of the acceptable file types so they do not appear in the file upload dialog. Tried on windows and mac.

This filter can by bypassed on windows (and chrome on mac), and .glb files then previews well. It is confusing though.

**To Reproduce**
1. Open file upload dialog on minting page
2. See list of file types accepted, .glb is not on this list. glb files also do not show up as uploadable.

**Expected behavior**
.glb should be visible in the file upload dialog and possible to select

**Screenshots**
![image](https://user-images.githubusercontent.com/5901135/114274368-f75d2700-9a15-11eb-9e75-119338d1ce0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Mac OS 10
 - Browser: Chrome (win), Opera (win), Safari (mac), Chrome (mac)

**Additional context**
GLFT-binary is included in the upload file accept property, which to me looks like it should work, but unfortunately it does not.

**Comment by pichiste** [comment]
Thanks for reporting – the accept attribute was recently added but it looks like browsers aren't recognizing the mime type properly. 

This PR should fix the issue: https://github.com/hicetnunc2000/hicetnunc/pull/473

**Comment by pichiste** [comment]
Fix has been deployed, @laoko do you mind closing? I don't have repo access! thanks
