### ISSUE TITLE
"swap" tab does not appear for newly minted OBJKTS

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc#477]
**Describe the bug**
No "swap" tab appears for newly minted OBJKTs since today. Worked fine until yesterday and still works for older OBJKTS in my collection

**To Reproduce**
1. Mint a new OBJKT
2. go to OBJKT page once minting has finished
3. only "info" and "collectors" is visible

**Expected behavior**
Swap + burn should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/182098/114362798-08be4480-9b78-11eb-8b65-85bb74c5c4c8.png)

**Comment by VVillar** [comment]
Hello, same issue when creating a NFT, there is not available options to put a price , just info and collectors.
![image](https://user-images.githubusercontent.com/1483310/114366050-0f819300-9b49-11eb-885c-82ac0f3c49e5.png)

**Comment by SVADA8** [comment]
Same issue for me, can't swap NFT's I minted today. Older ones are also not swappable.

**Comment by jkwongjk** [comment]
Seeing the same bug: https://www.hicetnunc.xyz/objkt/30363

![CleanShot 2021-04-12 at 01 52 41](https://user-images.githubusercontent.com/65338025/114367965-d0941300-9b31-11eb-9e14-793ad1144cc2.png)

**Comment by djangobits** [comment]
@Quasimondo check my last twitter DM to you (to cancel the swap)

**Comment by Quasimondo** [comment]
For those who need a temporary workaround - you can use the better call dev api to swap your OBJKTs manually:
https://better-call.dev/mainnet/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/interact?entrypoint=swap

Just watch out - the "xtz_per_objkt" value is in mutez not in tez - so you have to multiply your desired tez value with 1.000.000 (just add 6 "0" to the end of the price) -> 5 tez = 5000000 mutez.

**Comment by IGjvliveh** [comment]
Same here. I just minted and couldn't find the swap button.
Hmmm.... Let me try that temp workaround. Thanks @Quasimondo !

**Comment by skenaja** [comment]
I think there's an issue with the Baking Bad L2 data - the main call used by the HEN API to show holders is returning nil: 
https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=30343
https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=30363

One of mine swapped yesterday working OK:
https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=29621

**Comment by skenaja** [comment]
I've left a comment in the BB telegram group

**Comment by nbieva** [comment]
Yes, indeed. What was minted yesterday is ok. But now:
1. No edition
2. no swap+burn
3. No collectors (which is normal, but I usually see me there :-) )
![cal 2021-04-12 at 11 59 12](https://user-images.githubusercontent.com/17779479/114377178-a7ea3880-9b86-11eb-9503-9fb5290ea822.png)

**Comment by oshema** [comment]
Additionally, it does not appear in my kukai wallet. cannot send it or burn. Is there a time estimation for when you believe this issue will be solved?

**Comment by skenaja** [comment]
Just for info, the code on HEN was recently changed (in d93cda8cfe107cee93fb05deda380677df85c045) to hide the swap & burn tab if you're not defined as an owner based on the upstream data.

@oshema it's likely the Kukai wallet depends on the same upstream data, which is why it's not appearing. I don't have a timeframe for a fix, as the upstream feeds are maintained by a separate group. 

Both Baking Bad (re the API) and Kukai Wallet can be contacted by their Telegram groups:
https://t.me/baking_bad_chat
https://t.me/KukaiWallet

**Comment by Quasimondo** [comment]
@oshema Since this seems to be an issue which probably did not get caused on our end it is hard to tell when the Baking Bad team fixes it.

**Comment by oshema** [comment]
> Just for info, the code on HEN was recently changed (in [d93cda8](https://github.com/hicetnunc2000/hicetnunc/commit/d93cda8cfe107cee93fb05deda380677df85c045)) to hide the swap & burn tab if you're not defined as an owner based on the upstream data.
> 
> @oshema it's likely the Kukai wallet depends on the same upstream data, which is why it's not appearing. I don't have a timeframe for a fix, as the upstream feeds are maintained by a separate group.
> 
> Both Baking Bad (re the API) and Kukai Wallet can be contacted by their Telegram groups:
> https://t.me/baking_bad_chat
> https://t.me/KukaiWallet

I'm not sure what you meant exactly.. I just minted a new object and it appears in my creation but I just can do anything with it. I can't put price/burn/swap although I created it. I want to create and send it to a friend like I used to do at 'hicetnunc' before. As for the moment, I can't find any alternative for my desire to mint an NFT and send it to someone.   Is it going to stay like that or it would be fixed? or maybe there is alternative? 
thanx

**Comment by skenaja** [comment]
Don't worry, it will get fixed! It's happened a couple of times (eg #455), and the BB team are usually pretty good at getting it sorted within a couple of hours.

**Comment by oshema** [comment]
Thank you skenaja and Mario

**Comment by andrevenancio** [comment]
I think @skenaja has provided really good insight already, I dont have much to add. But as curiosity, the frontend only displays those menus (swap + burn) if you're the creator of the piece, or if you own a copy of it (so you can sell on the 2nd market).

With the API response, we're getting `owners = {}` coming as an empty object, which shouldn't.

I can separate the two filters for cases when owners={} which would allow the creator to still see it, but its a patch not a fix. Which means it will only work for the creators of the token not for the owners of the token. the owners still requires that object to come in filled.

**Comment by andrevenancio** [comment]
I've swapped the order in which we verify ownership. By checking against the owners first, and the creator last, should enable the creators to be able to swap and burn, but not the owners (so secondary marker). the secondary market can only be fixed if that property `owners` doesn't come in as empty object. https://github.com/hicetnunc2000/hicetnunc/commit/d93f6d4f05544b7b8159fea75a720e0d50179b2a

**Comment by skenaja** [comment]
It looks like the API is now correctly responding - can everyone check they can now swap?

**Comment by nbieva** [comment]
worked for me!

**Comment by skenaja** [comment]
Closing

**Comment by kenokenobingo** [comment]
I could start swapping now, but my wallet couldn’t handle the transaction although it’s applied.

![Bildschirmfoto 2021-04-12 um 15 26 26](https://user-images.githubusercontent.com/9639767/114401927-a54a0c00-9ba3-11eb-85cf-3d8f1f3a56e7.png)

![Bildschirmfoto 2021-04-12 um 15 28 05](https://user-images.githubusercontent.com/9639767/114401988-b2ff9180-9ba3-11eb-8d2a-3e769edebba0.png)

**Comment by skenaja** [comment]
This is a Kukai wallet issue - from their Telegram group:

> Some users are affected by tokens not showing up in the wallet. We will need to migrate to a new API instance to solve that. We will communicate when that is completed here in the group as well.

https://t.me/KukaiWallet

**Comment by dblock** [comment]
Could https://github.com/hicetnunc2000/hicetnunc/issues/485 be related?

**Comment by skenaja** [comment]
Very likely. The upstream API provider (https://api.better-call.dev/ aka BCD, provided by the Baking Bad team) offers an object "holders" API data feed which gives a summary of all the holders for a specific object. This info is used by HEN to display various tabs to owners and the creator, and allows operations like swap, cancel, burn etc.

Whenever there is a transaction in the underlying blockchain that affects token holders (like swap, cancel swap, transfer & collect), this is meant to trigger a calculation by BCD to reassess who the holders are. They recalculate the data and the API used by HEN should reflect the most up-to-date info. 

Any time there is a time delay in the calculation of the holders, any transactions that took place since it was last calculated (like swap, cancel swap, etc) won't be correctly included in the calculated data, and HEN will not accurately reflect the actual blockchain position. Once the BCD calculation lag has been corrected, BCD's API will return correct data, as will HEN.

**Comment by skenaja** [comment]
Gonna re-open this for a while for visibility - there are still ongoing delays in BCD calculating holders, but at least it's down to minutes rather than hours...

**Comment by andrevenancio** [comment]
Tou can pin it too if you want!

**Comment by clausmithNFT** [comment]
hi! Same here! Not allowing to swap (or burn)
>>> 
![image](https://user-images.githubusercontent.com/82423485/114483177-5077b700-9bde-11eb-824e-e9c67a5a8c89.png)

**Comment by clausmithNFT** [comment]
Hi!
So, any updates about this issue?

**Comment by onimetal** [comment]
![image](https://user-images.githubusercontent.com/82588784/114869031-ed984280-9dcc-11eb-9336-df70e3c3471e.png)
Hello, everyone!
This is happening to me too :O
I can't swap/burn any of my tokens, it still appears me as an owner, but no swap/burn commands and funnily it appears an option for me to buy it...from....myself o.o

**Comment by onimetal** [comment]
> ![image](https://user-images.githubusercontent.com/82588784/114869031-ed984280-9dcc-11eb-9336-df70e3c3471e.png)
> Hello, everyone!
> This is happening to me too :O
> I can't swap/burn any of my tokens, it still appears me as an owner, but no swap/burn commands and funnily it appears an option for me to buy it...from....myself o.o

Hey, forget it, i've just saw i have to "cancel" first 👯

**Comment by mtyka** [comment]
From the last message it sounds like it has been fixed and is actually working (also squares with my recent experience with the site). I'm closing this issue for the time being. If the issue resurfaces, please reopen this issue.
