### ISSUE TITLE
NFT shows up in manage assets but can't see swap or burn tab. also, my address is not listed under collectors tab even though asset is visible in manage assets and the counter for available assets is reduced by the quantity of NFTs I bought from the particular artist.

### ISSUE THREAD

**Issue by hic1etnunc** [hicetnunc2000/hicetnunc#478]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by oshema** [comment]
Also have the same issue

**Comment by skenaja** [comment]
This is a duplicate, so closing. Tracking in #477

@hic1etnunc, it's important when raising defects in Github to edit the issue template text to answer all the questions asked - this helps the developers diagnose the problem.
