### ISSUE TITLE
Ability to send more than 100 hDAO per curate

### ISSUE THREAD

**Issue by fused** [hicetnunc2000/hicetnunc#479]
It seems there are easy ways to circumvent the recommended(?) 100 hDAO spent per curate transaction, which makes difficult and time consuming (if not "expensive") for anyone without the "technical knowledge" to get into the hdao feed.

I'm wondering if this is by design, if yes, then shouldn't anyone be able to do it?

**Comment by skenaja** [comment]
I don't think it's a bug as such, as the smartcontract supports higher amounts as you point out. It's just that the UI has not yet built this feature in.

https://hicetnunc.featureupvote.com/suggestions/174689/upvote-with-more-hdaos

Noting here the workaround to be able to send more than 100 hDAO - submit the relevant parameters here:
https://better-call.dev/mainnet/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/interact?entrypoint=curate

**Comment by violetforest** [comment]
you can set the hdao amount now in the settings page with the hdao curation parameter. does this solve the problem? let me know and ill reopen this if it doesnt
