### ISSUE TITLE
My Object not in my Kukai wallet after minting. Can't giveaway objects because of that.

### ISSUE THREAD

**Issue by oshema** [hicetnunc2000/hicetnunc#483]
**Describe the bug**
I just want to give an object to my friend. I mint an object but it is not in my wallet and I don't have an option to send it.

**To Reproduce**

**Expected behavior**
after minting object it will appear in my Kukai wallet and I can send it.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by skenaja** [comment]
This is a Kukai wallet issue - from their Telegram group: 

> Some users are affected by tokens not showing up in the wallet. We will need to migrate to a new API instance to solve that. We will communicate when that is completed here in the group as well.

https://t.me/KukaiWallet
