### ISSUE TITLE
FAQ: Add allowed domains for interactive NFTs

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#484]
**Summary of change to FAQs you wish to make:**
* Interactive OBJKTs can call a [list of domains](https://github.com/hicetnunc2000/hicetnunc/pull/253/files) to access media or api queries, etc.
* These should be listed in the Interactive NFTs wiki page
* I recommend these changes be added after the [User Data](https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs#user-data) section.

| domain        | img-src | media-src | font-src | prefetch-src | connect-src |
| ------------- |:-------------:| -----:| -----:| -----:| -----:|
| https://ipfs.infura.io/ | ✅ | ✅ | ✅ | ✅ |
| https://*.infura.io/ | | | | ✅ |
| https://infura.io/ | | | | ✅ |
| https://cloudflare-ipfs.com/ | ✅ | ✅ | ✅ | ✅ |
| https://ipfs.io/ | ✅ | ✅ | ✅ | ✅ |
| https://gateway.pinata.cloud/ | ✅ | ✅ | ✅ | ✅ |
| https://fonts.googleapis.com/ | | | ✅ | ✅ |
| https://better-call.dev/ | | | | | ✅ |
| https://*.better-call.dev/ | | | | | ✅ |
| https://*.cryptonomic-infra.tech/ | | | | | ✅ |
| https://cryptonomic-infra.tech/ | | | | | ✅ |
| bootstrap.libp2p.io | | | | | ✅ |
| preload.ipfs.io | | | | | ✅ |
| https://api.etherscan.io/ | | | | | ✅ |
| https://api.thegraph.com/ | | | | | ✅ |
| https://*.tzkt.io/ | | | | | ✅ |
| https://api.tzstats.com/ | | | | | ✅ |
| https://*.wikidata.org/ | | | | | ✅ |
| https://*.coinmarketcap.com/ | | | | | ✅ |
| https://api.openweathermap.org/ | | | | | ✅ |
| https://hicetnunc.xyz/ | | | | | ✅ |
| https://*.hicetnunc.xyz/ | | | | | ✅ |

**Markdown**
* If you've written the update using Markdown, replace the `FAQ in markfown format` below with your markdown-tagged text

      

```Markdown
## Allowed Domains
Interactive OBJKTS can access the following external domains:

| domain        | img-src | media-src | font-src | prefetch-src | connect-src |
| ------------- |:-------------:| -----:| -----:| -----:| -----:|
| https://ipfs.infura.io/ | ✅ | ✅ | ✅ | ✅ |
| https://*.infura.io/ | | | | ✅ |
| https://infura.io/ | | | | ✅ |
| https://cloudflare-ipfs.com/ | ✅ | ✅ | ✅ | ✅ |
| https://ipfs.io/ | ✅ | ✅ | ✅ | ✅ |
| https://gateway.pinata.cloud/ | ✅ | ✅ | ✅ | ✅ |
| https://fonts.googleapis.com/ | | | ✅ | ✅ |
| https://better-call.dev/ | | | | | ✅ |
| https://*.better-call.dev/ | | | | | ✅ |
| https://*.cryptonomic-infra.tech/ | | | | | ✅ |
| https://cryptonomic-infra.tech/ | | | | | ✅ |
| bootstrap.libp2p.io | | | | | ✅ |
| preload.ipfs.io | | | | | ✅ |
| https://api.etherscan.io/ | | | | | ✅ |
| https://api.thegraph.com/ | | | | | ✅ |
| https://*.tzkt.io/ | | | | | ✅ |
| https://api.tzstats.com/ | | | | | ✅ |
| https://*.wikidata.org/ | | | | | ✅ |
| https://*.coinmarketcap.com/ | | | | | ✅ |
| https://api.openweathermap.org/ | | | | | ✅ |
| https://hicetnunc.xyz/ | | | | | ✅ |
| https://*.hicetnunc.xyz/ | | | | | ✅ |

```

**Comment by violetforest** [comment]
Thanks, added!

**Comment by fraguada** [comment]
@violetforest sorry for being picky but could you use another term besides "whitelisted" domains? Maybe just "Allowed" domains?

**Comment by violetforest** [comment]
@fraguada sure, was just trying to make it continue what the last person was saying, but i can change it!
