### ISSUE TITLE
Opening a profile page with PDF objkt automatically downloads the PDF file

### ISSUE THREAD

**Issue by matangkuwago** [hicetnunc2000/hicetnunc#490]
On some browsers, e.g. Android and Firex on macs, when you open a profile page with minted PDF files, the PDF gets downloaded automatically on a new window.

Example profile links:
https://www.hicetnunc.xyz/tz/tz2G5SBeAJVbiE1icji3P59Lx8EvcwMLEHp3
https://www.hicetnunc.xyz/tz/tz1fGQT9WfT5yRVkm876jViSwZTgGhrVDVEg
https://www.hicetnunc.xyz/tz/tz1hb9PiWxQEf6J9xevPsUM6dkuCLnhDMvsp

**To Reproduce**
1. Open a profile page e.g. https://www.hicetnunc.xyz/tz/tz2G5SBeAJVbiE1icji3P59Lx8EvcwMLEHp3
2. Watch a new tab/window gets opened that downloads the PDF file.

**Expected behavior**
Nothing should happen, the PDF should just get displayed.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Firefox
 - Version:  87.0

**Smartphone (please complete the following information):**
 - Device: Android e.g. Samsung Galaxy S9
 - OS: Android 8.0
 - Browser: Stock browser

**Comment by EMES77** [comment]
I noticed this today visiting the creation tab on the first of above mentioned profiles 

Using 
macos 10.14.6 with firefox v87.0

Chrome and Safari don't show the behaviour.

Everytime the site loads e.g. when i switch to collection and back to creations, the pdf downloads.

**Comment by skenaja** [comment]
Should the expected behaviour be to display a thumbnail on the collection/creation tabs instead of loading the PDF?

**Comment by matangkuwago** [comment]
On some systems, I suppose when PDF is not installed, or when PDF is not supported on the browser, I guess displaying a thumbnail is what's expected. But for browsers where the PDF display element (where PDF browsing can be done), I guess the current functionality is good enough.

**Comment by dennisklicker** [comment]
OS: Windows 10

Desktop: Firefox Developer Edition 89.0b1 (64-bit) is giving me a PDF download dialog on a few different pages.

To Reproduce: Load the page

Expected: I don't think anything should happen since I haven't done anything other than open up the link to the page.

**Comment by Dsm0** [comment]
I'm experiencing this same issue using Firefox version 88.0.1 on Manjaro

Edit: have reopened on #682
