### ISSUE TITLE
Swap and Burn options Unavailable for Secondary Owners?

### ISSUE THREAD

**Issue by mathMakesArt** [hicetnunc2000/hicetnunc#494]
**Describe the bug**
Swap creation and burning appear to be unavailable for secondary owners (owners of OBJKTS which were created by someone else).

**To Reproduce**
1. Purchase an NFT on HicEtNunc (or find one in your collection that you already own)
2. View that NFT's OBJKT page
3. Regardless of wallet connection status, the "Swap" and "Burn" options are unavailable. Only "info" and "collectors" tabs appear.

**Expected behavior**
Additional "Swap" and "Burn" tabs should be present, with their own respective functionalities.

*To clarify, all of these functionalities are present for pieces that I created myself. It's only secondary pieces which have this problem.*

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 87.0 (64-bit)

**Additional context**
I have heard the same complaint from other users, so this issue is not just restricted to my own wallet.

Wallet address: tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71
OBJKT that I own and created myself, and so I can swap: https://www.hicetnunc.xyz/objkt/9953
OBJKT that I own but secondarily, and so I can not swap: https://www.hicetnunc.xyz/objkt/13147

**Comment by skenaja** [comment]
Looks like this line will hide secondaryMarket tabs even if secondaryMarket == true

https://github.com/hicetnunc2000/hicetnunc/blob/main/src/pages/objkt-display/index.js#L85

**Comment by skenaja** [comment]
Temporary workarounds via direct contract operations:

1) cancel swap
- find swap_id from the original transaction (eg via your wallet)
- initiate cancel_swap: https://better-call.dev/mainnet/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/interact?entrypoint=cancel_swap
  - enter swap_id, wallet address and 0

![image](https://user-images.githubusercontent.com/510285/114747476-c7c95a00-9d48-11eb-95da-c867fc551e06.png)

2) swap
- initiate cancel_swap: https://better-call.dev/mainnet/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/interact?entrypoint=swap
- enter objkt_id, number of items to swap, tez amount (in millionths, so enter `1000000` for `1 tez`), wallet id, and 0.

![image](https://user-images.githubusercontent.com/510285/114747614-f0e9ea80-9d48-11eb-96f3-8e5c409b8a3e.png)

3) burn
- cancel swap (if required)
- send token(s) to `tz1burnburnburnburnburnburnburjAYjjX` via wallet transfer.

**Comment by mathMakesArt** [comment]
Thanks for the work-around list, @skenaja! I appreciate the screenshots as well, that was very helpful.

Happy to finally be forced into familiarizing myself with better-call.dev

**Comment by yanngraf** [comment]
I'm also experiencing the issue with the swap tab. The whole site feels pretty buggy tonight I must say.
Maybe I'll test your workaround @skenaja thanks for the tip.
