### ISSUE TITLE
Pass in purchases to HTML nft

### ISSUE THREAD

**Issue by jhelf** [hicetnunc2000/hicetnunc#498]
Can we pass a list of purchases that has been made on an HTML nft. That would allow making HTML nfts that can evolve as people purchase it!

**Comment by mescalina** [comment]
I think it is already possible accessing the NFT data on whitelisted providers like https://better-call.dev/
But let's wait the answer from somebody more expert to be sure

**Comment by jhelf** [comment]
Ye the problem is HTML objkts restrict calling external URL, so can’t access that data from within the objkts

**Comment by andrevenancio** [comment]
as @mescalina said, we introduced an allow list. you should be able to do that
