### ISSUE TITLE
User function: Block addresses / Favorites

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#50]
Another feature worth exploring might be the possibility to block certain addresses or to mark them somehow. I see there are people uploading stuff they obviously found online. I'd like to either make them disappear from my feed or to mark them as "not my art".

**Comment by andrevenancio** [comment]
This is probably another good test case for the GIST solution we were talking about earlier.

We could blacklist users who upload art that isn't theirs, and this is a feature that would go well with a "report" button.

But then there's another conversation to have here...
1. How can the platform validate the true ownership of an asset
2. How would that validation process look like?
3. If something is in fact not original, should it be removed from the blockchain? How would it work if a user had bought it? all those kind of questions to me make me think that there's no easy solution.

**Comment by djangobits** [comment]
The idea here was not a central "Block Stuff" function to censor uploads, but a user function. Like the contrary of a "my favorites", the user could have his own blacklist. But maybe we should start with a "my favorites"...

**Comment by andrevenancio** [comment]
This has been implemented already. closing
