### ISSUE TITLE
Account?

### ISSUE THREAD

**Issue by Bildecht** [hicetnunc2000/hicetnunc#511]
Hi, Guys,

how can I get an account to Hicetnunc? Tried to get in via Temple-Wallet but it doesn't work. It says there is not such account in the Blockchain. I can't upload any objects, too.
Please help.
Many thanks.
Matt

**Comment by skenaja** [comment]
This error is due to there being no Tezos in the account. You'll need to add some (eg from Coinbase, Binance etc).

See https://github.com/hicetnunc2000/hicetnunc/wiki/Getting-Started-with-Tezos

**Comment by skenaja** [comment]
Closing. If there's any further updates, feel free to comment here & I'll re-open the issue.
