### ISSUE TITLE
Minted MP4s not playing on Creation Page

### ISSUE THREAD

**Issue by gwitthuhn1** [hicetnunc2000/hicetnunc#517]
my minted MP4 NFTs used to play on my creation page, but now when I preview the page, [they] are just black boxes. Please help.

https://www.hicetnunc.xyz/tz/tz1gyupBZ3ybA5AgSAiGJyPjaeP5QLMhqJ5A

**Comment by dhowe** [comment]
Same issue here: https://www.hicetnunc.xyz/objkt/41495

**Comment by skenaja** [comment]
Both links play the videos on my laptop (Windows 10/Chrome)

Please can you 
* log your environment details as per bug ticket template?
* right-click on browser window, Inspect > Console and let us know if there are any errors listed.


**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Comment by dhowe** [comment]
working now for me, though definitely had an error previously (see below): 

OSX 10.15.7 (19H524)
Firefox 10.15.7 (19H524)

![image](https://user-images.githubusercontent.com/737638/115655020-ee008280-a364-11eb-895d-218eef4a4a92.png)
