### ISSUE TITLE
I (think I) broke my profile, AND the homepage feed

### ISSUE THREAD

**Issue by mathMakesArt** [hicetnunc2000/hicetnunc#520]
**Describe the bug**

Hello!

*Firstly, I'm not certain if this has actually happened, or if the issue I'm experiencing is temporary and unrelated. But I'm posting this preemptively, just in case.*

Tonight, I was playing around with the "mint_OBJKT" functionality on better-call.dev

Minutes before calling the contract from this interface for the first time, I was able to load both the hicetnunc.xyz feed and my own profile page

### After calling the contract for the first time, my profile page does not load any of the actual creation/collection items (only the user data at the top, and the tabs to switch between creation and collection). Also, the hicetnunc.xyz webpage isn't loading at all.

**I'm wondering whether I did something bad in this contract call which is somehow causing the site to get stuck when it tries to load this NFT's data, making it unable to display other page contents.**

### By incrementally hopping forward 1-by-1 starting at 36118 (which I minted minutes before the error) I was able to arrive at [**OBJKT#36128**](https://www.hicetnunc.xyz/objkt/36128) which I believe is causing the problem, because this one OBJKT page does not load but all the others around it do.

**To Reproduce**
### You can view the results of this error on [**my own profile**](https://www.hicetnunc.xyz/tz/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71) or [**the hicetnunc homepage**](https://www.hicetnunc.xyz).

**Expected behavior**
My profile should be loading; it used to look like this. OBJKT#36118 is my most recent mint, and I'm still able to load the actual page for that OBJKT (as well as my previous OBJKTS).
![image](https://user-images.githubusercontent.com/68834165/115100356-12de9b00-9f0a-11eb-958f-58e353a7203c.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)

**Additional context**
My wallet address is [**tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71**
](https://www.hicetnunc.xyz/tz/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71)
And again, [**OBJKT#36128**](https://www.hicetnunc.xyz/objkt/36128) is the "problem OBJKT"

**Comment by mathMakesArt** [comment]
### How I (think I) broke the site:

Here is a screenshot of the contents that executed via better-call.dev:
![image](https://user-images.githubusercontent.com/68834165/115100625-cb590e80-9f0b-11eb-961c-eb9efe09579b.png)

As you can see, my own address is used for the "address" and "source" parameters. 

All the other options should be self explanatory, but I think the **metadata** field is the problem.
The full metadata string I used is:
`697066733a2f2f516d656970694a4342646445386548515148534846644c50624d744e4b7850434d466565566a734d35377138366f`

I know that metadata value is the hexadecimal representation of **ipfs://QmeipiJCBddE8eHQQHSHFdLPbMtNKxPCMFeeVjsM57q86o** but I don't actually know what that link means.

I retrieved this by looking at the contents of the operation for [**my previous mint operation on better-call.dev**](https://better-call.dev/mainnet/opg/opMvsGcyhuBX848QrfEW3oLgxLVQZUPAA2oQ4RehGd4XpZG5Vbc/contents) (OBJKT#36118)

I copied the contents of the @bytes_14 value from [**this page**](https://better-call.dev/mainnet/big_map/521/keys).

After I entered this copied value into the metadata field, I noticed that Temple wallet was no longer giving me a contract failure warning. I took this as a sign that I was doing things correctly, and so I moved forward with executing the mint.

Only afterwards, when the site wouldn't load, did I realize this might've been a bad move.

**Comment by mathMakesArt** [comment]
One last update: I do believe that @crzypatchwork was able to fix the site feed by banning the OBJKT.
### However my [**profile page**](https://www.hicetnunc.xyz/tz/tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71) is still unable to load for some reason.

Do banned OBJKTS get removed from the feed, but remain on individual user pages? **If so, is there any way that this could be remedied?**

**Comment by skenaja** [comment]
The profile page is having a hard time decoding the info behind IPFS link... It's the metadata file stored separately in IPFS alongside the uploaded file(s). You can access them directly from a public IPFS gateway, eg https://cloudflare-ipfs.com/ipfs/QmeipiJCBddE8eHQQHSHFdLPbMtNKxPCMFeeVjsM57q86o

The metadata link you re-used relates to the contract as a whole, not for an objkt... If you minting your own object manually you would ideally have uploaded to IPFS a HEN-standard token metadata file..

The HEN API uses this metadata to construct the profile page, and you can see the difference between the problem object and a good one in the `token_info` section of the API Response.

bad:
```json
...
    {
      "price": 0,
      "receivedOn": "2021-04-17T03:03:14.000Z",
      "action": "Received",
      "ipfsHash": "QmeipiJCBddE8eHQQHSHFdLPbMtNKxPCMFeeVjsM57q86o",
      "piece": "36128",
      "amount": 2,
      "token_info": {
        "authors": [
          "@hicetnunc2000 <hicetnunc2000@protonmail.com>"
        ],
        "description": "OBJKT Swaps and Collectibles Public Mintery",
        "homepage": "https://hicetnunc.xyz",
        "interfaces": [],
        "license": {
          "name": "MIT"
        },
        "name": "OBJKT Mintery/Swap Protocol",
        "repository": "https://github.com/hicetnunc2000/objkts",
        "version": "2.0.0"
      },
      "token_id": 36128
    }, ...
```

good:
```json
...    {
      "price": 0,
      "receivedOn": "2021-04-17T02:52:14.000Z",
      "action": "Received",
      "ipfsHash": "QmPPjjq6LRjCfkjU6h5zjdAivU6uQAb4vAwFkxMMs3giLn",
      "piece": "36118",
      "amount": 1,
      "token_info": {
        "name": "MATH 1",
        "description": "Created by @MathMakesArt (https://mathmakesart) on 2021-04-16. This image contains the generative frame which I typically use as my profile image, cut to a circular profile and surrounded by a ring of inner diameter 1000 pixels and outer diameter 1080 pixels. This mint is intended for experimental purposes and the image is meant to serve more as a visual placeholder and less as art. Royalties are set to 10 percent, the default platform value.",
        "tags": [
          "mathmakesart",
          "math",
          "profile",
          "python",
          "generative",
          "experimental",
          "experiment",
          "tezos",
          "xtz"
        ],
        "symbol": "OBJKT",
        "artifactUri": "ipfs://QmUy7LAPf1jRpu7t2w5GUpsvjqkpPpMBP2jNjR93mF8oMd",
        "displayUri": "",
        "thumbnailUri": "ipfs://QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc",
        "creators": [
          "tz1gsrd3CfZv4BfPnYKq5pKpHGFVdtGCgd71"
        ],
        "formats": [
          {
            "uri": "ipfs://QmUy7LAPf1jRpu7t2w5GUpsvjqkpPpMBP2jNjR93mF8oMd",
            "mimeType": "image/png"
          }
        ],
        "decimals": 0,
        "isBooleanAmount": false,
        "shouldPreferSymbol": false
      },
      "token_id": 36118
    },
```

Here's the front-end response to the profile page:
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at index.js:65
    at Array.filter (<anonymous>)
    at index.js:64
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
```

As a quick fix, I think the API should probably filter out banned objkts using `getRestrictedObjkts` before sending the response in the `/tz/:wallet` call. At the moment, only the `/objkt/:id` call is doing this. This will also have the side effect of removing purchased copymints from people's collections and creations. @veqtor  - what do you think?

If the OBJKT metadata schema is ever going to change long-term (eg to add new keys or change things from string to array), it's going to need some form of versioning to allow the front-end to handle different schemas...

**Comment by mathMakesArt** [comment]
Thank you very much @skenaja.

In the meantime, I was able to find the 36128 token within my wallet. Do you think it would be worthwhile for me to burn it (manually send to the burn address from my wallet)? Or would that not help?

I've actually never burned anything before, so I'm unsure if burning all editions of one of my mints would remove it from the "Creations" tab.

**Update:** I heard from another community member that if no editions have been sold, I can remove corrupted items from my creations tab by burning all copies. Giving that a try now, will see if it helps at all.

**Comment by mathMakesArt** [comment]
Okay yes, burning was successful! I can now load my page again, as usual.

So if Veqtor is opposed to the idea of removing purchased copymints from people's collections/creations, then I don't think the banned objkt filtering needs to be implemented. I guess it's all a matter of preference.

**Comment by mescalina** [comment]
Maybe introducing a separate list for broken objkts could be a solution. A list of blocked that still shows copymints in the collections, and a list of broken objects that always get filtered out, even in collections.
By the way  copymints showing up in collection still need to be properly addressed.
