### ISSUE TITLE
FAQ: Update troubleshooting

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc#523]
**Summary of change to FAQs you wish to make:**

* Add new FAQs
* Edit `Features not yet implemented`

**If it's a new page, which navigation heading does it come under**
* For example: Minting guide, FAQs, Misc

N/A

**Text change**
* Add here the new text (and old text it's replacing if applicable)

1) `Features not yet implemented` - remove "Changing % of royalties when your NFT is resold" - this has now been implemented

2) Add new FAQs - see below for markdown

**Markdown**
* If you've written the update using Markdown, replace the `FAQ in markfown format` below with your markdown-tagged text

```Markdown
### I got "Storage quota exceeded for the operation" error - what happened?

The error _"Storage quota exceeded for the operation. A script or one of its callee wrote more bytes than the operation said it would"_ arises when the Tezos blockchain network is busy with lots of transactions. You might see this as "Backtracked" in the list of operations in your wallet.

The action you were trying to do will not have been completed, and you can retry it safely. Some wallets may have offered you the opportunity to increase the amount of storage fees, and increasing by, say, 3% usually results in a successful transaction.

It's worth noting that all transaction attempts, including failed ones, do incur small blockchain network fees which are not recoverable.


### I got "FA_2 insufficient balance" error when swapping - what happened?

The usual cause for this is trying to swap more items that were minted. If you minted 10 items and try to swap 20, you'll receive this error.
```

**Comment by violetforest** [comment]
Hey thanks! @skenaja Where do you suggest I put the wallet errors?

**Comment by violetforest** [comment]
@skenaja I put it under "Troubleshooting" FAQs, let me know if it should be somewhere else :)

**Comment by skenaja** [comment]
Perfect!
