### ISSUE TITLE
FAQ: Add digital frame maker to Tools page

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#527]
**Summary of change to FAQs you wish to make:**
* Add Digital Frame Maker by shahruz to the tools page
* Suggestion to add it under "Collector Tools"
* other suggestion: change "Collector Tools" to "Galleries" since both of the entries there are related to galleries

Relevant links:
* https://github.com/gimmix-org/primitive-objkts
* https://primitive-objkts.gimmix.org/

**Markdown**

```Markdown
[Digital Frame Maker](https://primitive-objkts.gimmix.org/) by [shahruz](https://github.com/shahruz). [src](https://github.com/gimmix-org/primitive-objkts)
```

**Comment by violetforest** [comment]
@fraguada done!
