### ISSUE TITLE
Assets not refreshing after burn; “transaction likely to fail” warnings

### ISSUE THREAD

**Issue by monirosa** [hicetnunc2000/hicetnunc#529]
Hello! 
Tried to burn an OBJKT last night, which shows as pending on-screen but sent to burn address in my wallet. My assets are not refreshing so I have double now. Also showing “transaction likely to fail” warnings when I test out buying my assets. 

https://www.hicetnunc.xyz/tz/tz1WKhfUW7j5Hcmdy4xZSghHLkX2H5fEAW85

**Comment by skenaja** [comment]
Which OBJKT did you try to burn?

**Comment by monirosa** [comment]
Thank you for your response - I tried to burn OBJKT 37352 a bunch of times and the burn transactions look like they recorded in Temple Wallet but the OBJKT is still visible in my collection/available for purchase.

**Comment by skenaja** [comment]
Regarding 37352, it's still swapped (on sale). You need to cancel the swap on the objkt's swap tab in order to burn it. The burn page will make this clearer in future. 

Please add further comments if you still have problems, and I'll re-open the ticket.
