### ISSUE TITLE
Detail View: SVG's are not displayed anymore

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#53]
the recent update broke the display of SVG files. They were displayed like pictures before. Now they do not display at all, also no explosion emoji. Here's one:

https://www.hicetnunc.xyz/objkt/454

**Comment by andrevenancio** [comment]
Its a missing mimetype. my bad. Will fix tonight

**Comment by andrevenancio** [comment]
I've commited a fix for this.
