### ISSUE TITLE
FAQ: [pt:Home edit content]

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#531]
**Edit pt:home page**
* Include the table of contents of pt: wiki, on the following page: https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Home
* Please, edit just this first one and we will create the others, as soon as I open another issue to create them.

[Início](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Home)

**Guia**
[Introdução](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Introduction)
[Edite seu perfil](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Edit-your-profile)
[Introdução ao Tezos](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Getting-Started-with-Tezos)
[Como cunhar 🌿](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-mint)
[Como anunciar🔃](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-swap)
[Como cancelar ❌](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-cancel)
[Como destruir 🔥](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-burn)
[Como revender 🏪](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-resell)
[OBJKTs interativos](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Interactive-OBJKTs)
[Tutoriais da comunidade](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Community-tutorials)

**FAQ**
[Geral](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:General)
[Solução de problemas](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Troubleshooting)
[Recursos ainda não implementados](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Features-not-yet-implemented)[
hDAO ○](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:hDAO)
[Contribuindo](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Contributing)
[Contribuindo (Guia do Iniciante)](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Contributing-Beginners-Guide)
[Cuidado com os Copyminters!](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Beware-copyminters!)

Misc
[Código de conduta dos criadores de NFT](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:NFT-Creators-Code-of-Conduct)
[Ferramentas feitas pela comunidade](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Tools-made-by-the-community)
[Ensaios e postagens de blogs](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Essays-blogs)

**Comment by violetforest** [comment]
@jovancosta done!
