### ISSUE TITLE
FAQ: [Content Created PT:Introduction]

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#533]
**Add and update the page PT:Introduction **
* new page https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Introduction
* ps: I don't know to insert some elements, please try to keep just the same way of the English page.
* I need to learn how to create a blockquote just like we can see on the last two phrases of the original document in english

### Introdução
Bem-vindo ao guia de criação de hicetnunc! Aqui você aprenderá como cunhar seu primeiro OBJKT.
<hr>
*OBJKT*
1: (substantivo) algo material que pode ser percebido pelos sentidos
2: (substantivo) um NFT em hicetnunc.xyz
</hr>

<hr>
Continue em [Iniciando com Tezos](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Getting-Started-with-Tezos) para aprender como adquirir alguns tezos!
</hr>

Já tem tezos?
Continue em [Como cunhar 🌿](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-mint) para criar seu primeiro OBJKT!
Dica: antes de começar a cunhar, você já pode começar a configurar seu perfil se já tiver uma carteira. Leia [Como configurar seu perfil](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Edit-your-profile)
Dica: Este projeto de código aberto foi lançado em 1º de março e ainda está em seus estágios alfa. Lembre-se de que o site está sendo trabalhado ativamente por colaboradores que trabalham como voluntários, e os recursos são constantemente enviados e atualizados para o site. Este Wiki tentará se manter em sincronia com os recursos mais novos e será atualizado tanto quanto possível, mas se algumas coisas não parecerem coincidir, consulte nosso [Discord](https://discord.gg/9qkgRsqa).

> _Por favor, use a barra lateral para navegar_
> Deseja contribuir com o wiki? Por favor, veja [Como contribuir para o Wiki](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Contributing#how-to-contribute-to-the-wiki)?

**Comment by violetforest** [comment]
sorry i didnt see this :( i just updated! i have to make it look nicer

**Comment by jovancosta-zz** [comment]
Thank you I will launch others soon.

**Comment by jovancosta-zz** [comment]
is it possible to see the right menu in portuguese as well ?
You have all right menu translated on the PT:home

On this way, anyone could easily navigate within PT content.
