### ISSUE TITLE
Objkt 38409 not working on the website and on the API

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#534]
No data coming out for objkt 38409

**Comment by skenaja** [comment]
The API responds with `Object is restricted and/or from a copyminter` text. Probably it should be returned in an error object rather than plaintext. 

Also looks like the front-end doesn't handle this yet.

**Comment by andrevenancio** [comment]
PR's are welcome. I'm a bit swamped today. checks for copyminters are being done on the API too I believe. before the API would return an empty array. there's a code already in place to show a error message when the array comes empty instead of an object (for valid objkt) but I guess the API got merged before.

**Comment by mescalina** [comment]
Thanks guys. I think a proper error handling implementation is necessary in order to allow people to not mess up with data, there is a lot of inconsistency now in errors. Now I get this from the api response data:
```

data: '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '<head>\n' +
      '<meta charset="utf-8">\n' +
      '<title>Error</title>\n' +
      '</head>\n' +
      '<body>\n' +
      '<pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>\n' +
      '</body>\n' +
      '</html>\n'
  },
```

**Comment by mtyka** [comment]
https://www.hicetnunc.xyz/objkt/38409
Error message is being shown now. Closing this issue.
![Screen Shot 2021-05-15 at 10 16 59 PM](https://user-images.githubusercontent.com/1166501/118386295-5c82da00-b5cb-11eb-96eb-3a856a196043.png)
