### ISSUE TITLE
Desktop view: Images are now too big

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#54]
On Desktop, images are now so big, that you need to scroll, to see the metadata. maybe take 1/5 above the pic and 1/5 below for header and metadata..

![image](https://user-images.githubusercontent.com/40259308/110437400-a2945c80-80b5-11eb-82e0-c009171263d4.png)

![image](https://user-images.githubusercontent.com/40259308/110437442-b049e200-80b5-11eb-952a-d1af70f1af3b.png)

**Comment by crzypatchwork** [comment]
the SVG thing being supported I think it was related to an LazyImage tag

**Comment by andrevenancio** [comment]
The SVG is a missing mimetype. easy fix. lets keep that conversation [there](https://github.com/hicetnunc2000/hicetnunc/issues/53)

In regards to this particular issue. I've added it to my TODO list.

**Comment by andrevenancio** [comment]
I've committed a fix for this. waiting on @crzypatchwork to merge it to production
