### ISSUE TITLE
Base64 encoded embedded fonts are stripped from index.html

### ISSUE THREAD

**Issue by edwinRNDR** [hicetnunc2000/hicetnunc#549]
**Describe the bug**
When I upload a zip containing an index.html that has fonts embedded as base64 encoded strings they appear to be removed before publishing the OBJKT.

I have to add, this is new behaviour that I have only encountered since the 20th of april.

The relevant part of the html looks like this:
```
<head> 
    [...]
    <style>
        @font-face {
            font-family: 'IBMPlexMonoMedium';
            src: url(data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAADiYABEAAAAAp+wAADg [...]
            format('woff2')
        }
        [...]
    </style>
</head>    
```

**To Reproduce**
zip work, mint objkt, preview already shows fonts missing.

**Expected behavior**
Base64 encoded embedded fonts are left untouched.

**Comment by andrevenancio** [comment]
@pichiste and @veqtor any idea why this might be happening? Is it intentionally being removed?

**Comment by pichiste** [comment]
The Content Security Policy doesn't allow sources from `data:` in `font-src` at the moment. Pretty sure this is safe to enable but need to look into it.

@edwinRNDR for the time being can you load the font from a file instead?

**Comment by edwinRNDR** [comment]
> @edwinRNDR for the time being can you load the font from a file instead?

Yes this is possible, and this is how I do it now. 

There is just a minor complication with font loading and using fonts in canvas 2d. The advantage of using a data-url is that the font is loaded immediately (at least in my test cases) whereas loading fonts from other locations are async and may be a bit longer to load. I use canvas 2d to prepare some images with text, which I'd like to be prepared in the right font. I don't know if there are proper font load events, and even if so it feels like that's unnecessarily complicating things.

**Comment by pichiste** [comment]
That's a fair point / use case. Let me look into adding that rule.

**Comment by pichiste** [comment]
@edwinRNDR re: loading from file, have you tried this?

```javascript
document.fonts.ready.then(function() {
  // init stuff here, after fonts are loaded
});
```

https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts

**Comment by edwinRNDR** [comment]
> @edwinRNDR re: loading from file, have you tried this?

I haven't, doesn't look as complicated as I thought it would :) Thanks!

**Comment by edwinRNDR** [comment]
Does this affect SVG files too? The problem may be a bit bigger there if so.

**Comment by pichiste** [comment]
No, the CSP is only applied to HTML OBJKTs, though I think SVGs should become restricted as well in the future. In general, I think the idea is to encourage people to use HTML rather than SVG for interactive/generative work.
