### ISSUE TITLE
Profile pages should contain prices

### ISSUE THREAD

**Issue by mjrlowe** [hicetnunc2000/hicetnunc#55]
As well as the object number, the price of the object (if for sale) should be displayed. At the moment, the only way to tell if any of the objects are for sale is to click of them, meaning checking all objects on a profile can take a while. 
Adding a price will allow users to quickly tell which objects are for sale and which ones they can afford.

**Comment by mjrlowe** [comment]
Maybe even display the price instead of the object number, since the ID isn't something most people want to know immediately

**Comment by atomantic** [comment]
would also be great to show the price paid next to each owner in the new Owners display.

**Comment by andrevenancio** [comment]
@atomantic I'm not sure that data is coming in the API. probably a good Issue to add to the API repository.

On the feed, we now include info with number of editions and if set by the creator a price.

**Comment by atomantic** [comment]
The feed is a good start but I've been looking at artist profile pages more when they drop pieces and I want to check up on whether another piece that had unlisted editions is now up for sale. That requires clicking on all the pieces individually to get to the object detail page :(
