### ISSUE TITLE
FAQ: Refrase hDAO info

### ISSUE THREAD

**Issue by DonKarlssonSan** [hicetnunc2000/hicetnunc#550]
I've refrased the hDAO info in the wiki by making a fork and doing the change there:
Forked repo: https://github.com/DonKarlssonSan/hicetnunc-wiki
Specifik change: https://github.com/DonKarlssonSan/hicetnunc-wiki/commit/944ad08d2a32b298065570a720361f51850564c7#diff-4995a260b30c057f47725c40390309d91e816c92a09dbbe66dfd77e735a4007e

**Comment by violetforest** [comment]
@DonKarlssonSan done, thanks!
