### ISSUE TITLE
Mint failed with timeout

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#553]
Object fails to mint after successful preview (.mp4, <15mb)

> Error:  mint error Error: Request timed out after: 30000ms
>     ontimeout taquito-http-utils.ts:135

**Desktop (please complete the following information):**
- OS: OSX 10.15.7 (19H524)
- Browser: Firefox 88.0

Wallet: tz1LBrt4eYvv82VL1d5VsxX22wAE1pxjGcym
OBJKT Address: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9  (?)
No OBJKT number

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/737638/115588435-574eaa00-a301-11eb-9ef7-099286c63702.png">

**Comment by tomburtonwood** [comment]
i am having a similar issue. very perplexing. i can't load the home page feed, i can't mint. 

tried chrome and firefox. 

<img width="1210" alt="Screen Shot 2021-04-24 at 10 32 35 AM" src="https://user-images.githubusercontent.com/8251313/115964175-cb977200-a4e8-11eb-81c5-703c91a2fbd8.png">

**Comment by psychedelicnature** [comment]
Object fails to mint after successful preview (.PNG, 15,2 mb)
I use Brave browser and I am having the same situation but the screen just keeps running as "preparing object", no error message appears or anything... 
![bug](https://user-images.githubusercontent.com/82925229/115972480-e25bba00-a524-11eb-95a8-260e9c9f5050.JPG)

**Comment by hl5hl5** [comment]
me, too *gif  8MG

**Comment by andrevenancio** [comment]
API requests fail after 30s. Some times the IPFS network is just too slow. You just need to try it again.
