### ISSUE TITLE
Error: minted video object (mp4) cannot be played, after successful preview

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#554]
Minted video object (mp4) cannot be played after successful preview:

ERROR: "No video with supported format and MIME type found"

OBJKT: 41495
URL: https://www.hicetnunc.xyz/objkt/41495
WALLET: tz1LBrt4eYvv82VL1d5VsxX22wAE1pxjGcym
OS: OSX 10.15.7 (19H524)
Browser: Firefox 88.0

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/737638/115590209-4b63e780-a303-11eb-9ea2-1969b185705f.png">

**Comment by crzypatchwork** [comment]
that's some codecs possibly missing in your browser

**Comment by dhowe** [comment]
As mentioned, the browser had _already_ played the file in preview. Similarly, it also started to play the file later. It was only just after minting that this error occurs.
