### ISSUE TITLE
Add color coding to objkt numbers to quickly see available objkts

### ISSUE THREAD

**Issue by matangkuwago** [hicetnunc2000/hicetnunc#555]
**Is your feature request related to a problem? Please describe.**
When you visit a creations page, it’s difficult to see which objkts are still available.

**Describe the solution you'd like**
Add a color coding system for sold out and available objkts. Sold out objkts can have objkt numbers styled with light gray font while available objkts can have objkt numbers styled with black font.

**Comment by andrevenancio** [comment]
closing as this is a design suggestion. there's a team working on a rebrand
