### ISSUE TITLE
FAQ: Add link services to community tools

### ISSUE THREAD

**Issue by fraguada** [hicetnunc2000/hicetnunc#557]
**Summary of change to FAQs you wish to make:**
* Add shortlink services to the community tools page. 
* there are currently two that I know of: [hic.link](https://hic.link)  by 1x1 and [hen.link](https://hen.link/)  by playnft

**Markdown**

```Markdown
# Shortlink Services
The following services provide shortlinks to hicetnunc creation pages:
* [hic.link](https://hic.link) by [1x1](https://twitter.com/1x1_NFT) 
* [hen.link](https://hen.link/) by [playnft](https://twitter.com/playnft) 
```

**Comment by violetforest** [comment]
@fraguada done

**Comment by fraguada** [comment]
Thanks @violetforest !

**Comment by fraguada** [comment]
@violetforest I can't seem to get to the community tools page?

**Comment by violetforest** [comment]
@fraguada ahh sorry. i just fixed it
