### ISSUE TITLE
Corrupted object, breaks down collection page

### ISSUE THREAD

**Issue by loackme** [hicetnunc2000/hicetnunc#56]
Something went wrong during the minting of object #1644.
The transaction went through but the token didn't appear in my wallet.
https://tzkt.io/opRXged3LfR3zDGt6tmia3H5FNobHQnxjYKX4EayfgQozZkCHuG

The object page is blank and it breaks down my collection page.
https://www.hicetnunc.xyz/objkt/1644
https://www.hicetnunc.xyz/tz/tz1NgN7FCrSzs4vfMroKXyKE32WsReYD4WPd

**Comment by neocybereth** [comment]
![Screen Shot 2021-03-09 at 10 47 32 PM](https://user-images.githubusercontent.com/14209806/110451832-787c8200-8129-11eb-9d0a-017590e663e5.png)

Here's the error from the console for reference

**Comment by andrevenancio** [comment]
Interesting. what did you try to upload? There's a property called `token_info` that is not present on that API response.

That response is
```javascript
{
    "contract": "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton",
    "network": "mainnet",
    "level": 1374526,
    "token_id": 1644,
    "name": "Unknown",
    "supply": 0,
    "transfered": 0,
    "swaps": [],
    "total_amount": 30,
    "owners": {
        "tz1NgN7FCrSzs4vfMroKXyKE32WsReYD4WPd": "30"
    }
}
```

Any idea @crzypatchwork ?

**Comment by loackme** [comment]
> Interesting. what did you try to upload?

It was a .png file. I really don't know what went wrong.

**Comment by crzypatchwork** [comment]
that's not usual. I would recommend to burn and mint again. would have to test also with other APIs to see if any data was fetched.

**Comment by loackme** [comment]
I don't mind burning it, but how do I do that?
The problem is that I don't seem to see the token in my wallet's assets.

**Comment by loackme** [comment]
On better-call.dev, I see no swap() operation associated to the mint_OBJKT() operation for this object.
I'm very much new to all this but could that be the problem?

https://better-call.dev/mainnet/opg/opRXged3LfR3zDGt6tmia3H5FNobHQnxjYKX4EayfgQozZkCHuG/contents

**Comment by andrevenancio** [comment]
@crzypatchwork Its probably a good idea to add on the About page instructions on "simple" things like burning a NFT. Even I dont know how to do that! :)

**Comment by crzypatchwork** [comment]
this issue is open for a collaborator to create a docs page for the dApp

**Comment by oldominion** [comment]
With regards to burning, it would be nice for the user to be able to do it in one go. Burn, then have hicetnunc hide it from view in the profile page.
