### ISSUE TITLE
Swap & Burn buttons always visible on page

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#568]
As per title.
The buttons are always there no matter if you are the owner of the item. I can see other people have the same issue.

**Comment by skenaja** [comment]
There was a fix put forward for this, but there have been intermittent delays by the upstream API provider of blockchain data in getting the list of owners to the site which caused those buttons to be very slow at appearing after a mint, which caused a lot of worry to creators minting.

A decision was made to show the buttons even if they don't especially apply to you. This will be reviewed when the site has more consistent and timely access to the chain data.
