### ISSUE TITLE
Cancelling then swapping - old data appears to stick

### ISSUE THREAD

**Issue by stumats** [hicetnunc2000/hicetnunc#570]
**Describe the bug**

**To Reproduce**
1. Mint object
2. swap object for price x
3. cancel swap
4. reswap for price: y
5. view raw data in temple wallet - can see "amount: 0"
6.  If swapped, price: x is the value shown as the new swap price

**Expected behavior**
value: y should be the new swap price

**Screenshots**
Screenshots show my attempt to reswap for 1 tez (after cancelling a swap for 0 tez)
![wallet - Untitled-1](https://user-images.githubusercontent.com/6487972/115807807-676ba400-a43d-11eb-9a0d-445535de3158.jpg)
![swap screen  Untitled-1](https://user-images.githubusercontent.com/6487972/115807810-69356780-a43d-11eb-8fa6-aaa3f134bc13.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, with temple wallet
 - Version Win 10

**Additional context**
https://www.hicetnunc.xyz/objkt/43680

**Comment by stumats** [comment]
Raw data complete:
```json
{
  "branch": "BKy3T7XTZfDjuSw3sfrScREA6BufZtvAp8uC...",
  "contents": [
    {
      "kind": "transaction",
      "source": "tz1U8mFPuyGr48BWnULky9kUqAVQk8ewBHtU",
      "fee": "9931",
      "counter": "11999246",
      "gas_limit": "96162",
      "storage_limit": "109",
      "amount": "0",
      "destination": "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9",
      "parameters": {
        "entrypoint": "swap",
        "value": {
          "prim": "Pair",
          "args": [
            {
              "int": "96"
            },
            {
              "prim": "Pair",
              "args": [
                {
                  "int": "43680"
                },
                {
                  "int": "1000000"
                }
              ]
            }
          ]
        }
      }
    }
  ]
}

```

**Comment by stumats** [comment]
Note, this was attempted multiple times, with same result, and after clearing cache. Currently am unable to reswap this item for a different price

**Comment by skenaja** [comment]
The price is currently showing as 1 tez - is this what you were expecting? There might have been a delay in the updated price propagating from the blockchain transactional data to the API provider used by HEN to display the holders on-screen

**Comment by stumats** [comment]
Yeah - I restarted the machine and then could mint it. Prior to that, tried everything I could think of, but that zero tez was very sticky.   I don't think it was about delay - I actually successfully swapped it several times, but always for zero tez, despite putting 1 tez in the amount field.  Seems like caching at my level though, since it appeared to clear after a restart
