### ISSUE TITLE
backtracked transaction

### ISSUE THREAD

**Issue by mfused** [hicetnunc2000/hicetnunc#572]
hi,
this transaction seems to be problematic, 

it says: status failed.
also, it took tezos from my account 
and did not put it back (how is that backtracked?)

transaction hash: 

oooUXxVqjBMxb9RBwZmUdmy8DGASCnCYDVqTqkktahp34ky1i8a
--
my account: https://tzkt.io/tz1WJvfnevqRN6RnDDmaDj9S4tuiK2bJjU6a
sent to yours,
on https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
(first Hic et Nunc account it shows as backtracked) and here it does not appear:
https://tzkt.io/tz1UBZUkXpKGhYsP5KtzDNqLLchwF4uHrGjw

so what should i do? i tried to mint for OBJKT4OBJKT event this w/e.
i wrote to baking-bad-org guys, they answered that i need to ask hicetnunc guys.
thanx a lot,
emfused

**Comment by skenaja** [comment]
Thanks for the detailed screenshots. Please see this wiki page which provides some more explanation.

https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#i-got-storage-quota-exceeded-for-the-operation-error---what-happened
