### ISSUE TITLE
"kind" "Temporary"

### ISSUE THREAD

**Issue by NikiLeSunshine** [hicetnunc2000/hicetnunc#574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by NikiLeSunshine** [comment]
"kind" "temporary"
"id" : "proto.008-
PtEdo27k.storage_exhausted.operation"

Thank you for any help or advice!

**Comment by skenaja** [comment]
https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#i-got-storage-quota-exceeded-for-the-operation-error---what-happened

Please see above link for details, you'll need to retry the operation.
