### ISSUE TITLE
My OBJKTs aren't burning

### ISSUE THREAD

**Issue by alexmcbr** [hicetnunc2000/hicetnunc#576]
I'm trying to burn one of my OBJKTs but it just continues to say 'burning objkt' on the screen without anything more happening.

**To Reproduce**
1. Go to OBJKT#43749
2. Click on the burn tab
3. Click on burn
4. The OBJKT won't burn

**Expected behavior**
I expected the objkt to burn. I don't know if this requires a sign-off from my wallet but it is not getting to the stage where it is requesting for one. 

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser Firefox
 - Version 83.0

**Additional context**
On several occasions yesterday I was minting some new objkts in my collection but after finalising the mint, the transaction would backtrack and the objkt wouldn't mint. I also had someone try to buy an objkt from me but the buying process remained at 'pending' for several hours. He had to buy the piece again before the transaction went through. I don't know if these are all symptoms of a bigger problem with my profile.

tz1eY3XzEW9nQgEU3AeuzanQshJ7GkoaUFk8
OBJKT#43749

**Comment by skenaja** [comment]
Nice photo! 

You need to cancel the swap under "collections" tab before being able to burn.

Backtrack/pending transactions are unfortunately a side-effect of a busy blockchain network, and are not related to your profile. Waiting a few minutes, then retrying the transaction usually works.
