### ISSUE TITLE
Collect button does nothing

### ISSUE THREAD

**Issue by tzatzikisauce** [hicetnunc2000/hicetnunc#577]
When I press the collect button, it does not bring up a tab to make a transaction, nothing happens. I have no pending transactions. I'm unable to collect anything atm. I'm using temple wallet.

**Comment by skenaja** [comment]
There were network issues relating to the 3rd party site (`https://mainnet.smartpy.io`) that connects the site to the wallet and the tezos network. These appear to have been resolved.
