### ISSUE TITLE
Can't swap OBJKT - operations are Backtracked

### ISSUE THREAD

**Issue by moonolog** [hicetnunc2000/hicetnunc#578]
In two days I had 3 failed transactions as trying to swap my OBJKT on HEN. 
XTZ are still taken and not refunded automatically over time.

My wallet address is:
tz1bJ3v7AnyYU5fnjTgjF2YXWegQYGodKZQa
There you can find 3 recent failed transactions in a row.

For your convenience, transaction hash:
ooB5ymX6Hg234dFixezAAUDphAjQySszLaPKTLzmy2eYF2VcPPH
onfS2HHpJSSBXbiv7KuW5fUgpsp8q6oEvc75UZHqaC1UK7SnJX7
ontpJQgpcvVhBm4F9E5eDwPB3ZYg9Bqr25soaWuxM4UxGFVKW7K

 - OS: Windows 10
 - Browser Firefox

I had no issues minting and swapping my first artwork and minting this second one, with witch I am having troubles swapping, so it's unlikely that problem lies with my wallet or the OBJKT itself, since my first and this one are pretty similar.

Thank you for your time.

**Comment by skenaja** [comment]
Hi - please see https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#i-got-storage-quota-exceeded-for-the-operation-error---what-happened

All operations have the risk of being backtracked, so it's best to try again after waiting a few minutes

**Comment by moonolog** [comment]
Hi
By this point I already had 6 operations backtracked, last one failed despite increasing the amount of storage fees by 5%. 
I was planning to mint a lot of my works on the platform, but now I can't be sure in success of that, since there is no certainty in operations going through - process feels like a gamble - and no refund procedure exists as far as I know. I want to use the platform, not want to waste more money.

Could this be fixed at all, or is anyone working on fixing it? Is there a more certain way to swap without losing tez every other operation?
