### ISSUE TITLE
"FAILWITH INSTRUCTION WAS REACHED" Error

### ISSUE THREAD

**Issue by Skyefyre502** [hicetnunc2000/hicetnunc#580]
**Describe the bug**

When clicking the Mint button, I get this error in my Kukai wallet to send xtz to complete the transaction:
Error: A FAILWITH instruction was reached > WrongCondition: (((params.amount > 0) & ((params.royalties >= 0) & (params.royalties <= 250))) & (sp.len(params.metadata) == 53)) & (params.amount <= 10000)
Preview

**To Reproduce**
After completing all the steps to mint an object, I receive the error in Kukai wallet and cannot edit any of the fields.

**Expected behavior**
I expected the transaction to go through since I have enough XTZ to cover the tranasaction

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
V:10

**Smartphone (please complete the following information):**
 -N/A
**Additional context**

**Comment by skenaja** [comment]
The error was due to either the royalties or the number of items minted being incorrectly set. They need to be within the range of 0-25 for royalties and 1-10000 for editions.
