### ISSUE TITLE
attempt to burn has taken hours (and never resolved) 

### ISSUE THREAD

**Issue by nancybakercahill** [hicetnunc2000/hicetnunc#583]
Hi- I have been trying to burn an nft because I realized I wanted to edition it. Tried to burn and it has literally taken hours (still there btw). Any suggestions?

**Comment by skenaja** [comment]
Hard to tell without seeing the OBJKT number. The most common reason is that the objkt is still on sale - swaps first need to be cancelled via the `collection` tab's cancel button
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5

Please report back with further info & I'll reopen the issue if it's still ongoing.
