### ISSUE TITLE
Add "Owners Data" to check if the viewer is also owner

### ISSUE THREAD

**Issue by 360fun** [hicetnunc2000/hicetnunc#585]
First of all "THANKS!" to have finally made an NFT marketplace to sell interactive digital art! 😻

**What I want to achieve**
I would like to be able to check if the viewer is also owner of the NFT, in order to create special features only for who own the NFT.

**Solution**
Taking inspiration from https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs#user-data I would add a variable with the array of the owners.

Something like:
`?viewer={VIEWER_ADDRESS}&creator={CREATOR_ADDRESS}&owners={OWNER_ADDRESS},{OWNER_ADDRESS},{OWNER_ADDRESS},...`
So I can do:
`const owners = new URLSearchParams(window.location.search).get('owners')`
In this way would be possible to check if the **viewer** is also **one of the owners**.

**Describe alternatives you've considered**
Could be easier to just add a boolean "is_owner" but having all owners could open more possibilities.
Would be nice to add a dynamic list thanking who bought the NFT.

**Comment by skenaja** [comment]
Hi! Thanks for the suggestion. This is being tracked in #513. Closing as a duplicate
