### ISSUE TITLE
Burn page should show zero instead of "NaN editions"

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#592]
In some cases, 'Burn' page shows "NaN editions" instead of zero. This can be fixed with a default value in burn.js [here](https://github.com/hicetnunc2000/hicetnunc/blob/90affefb5f65d15400ecd693c884c0a7606a5bae/src/pages/objkt-display/tabs/burn.js#L14)

![image](https://user-images.githubusercontent.com/737638/116184658-c76e8d00-a752-11eb-8f0f-70376852d1a2.png)

- OS: OSX 10.15.7 (19H524)
- Browser: Firefox 88.0

**Comment by skenaja** [comment]
Thanks for reporting!

**Comment by hexangel616** [comment]
yes very annoying and impossible to burn??

**Comment by andrevenancio** [comment]
merged to `main` awaiting deployment
