### ISSUE TITLE
Cannot remove test object from 'creations' page

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#593]
I'm not sure if this is a bug, but I cannot seem to remove a test object from my 'creations' page.

### Description
I created a test (interactive) objkt for my students to learn the process. As part of the demo we collected two of these objkts. Now I want to remove that objkt from my creations page, but it seems impossible. I have already cancelled the objkt so that it reads 'not for sale' (see below) and burnt all remaining copies, so that it reads 'Editions: X/2' (also below).

![image](https://user-images.githubusercontent.com/737638/116185506-4fa16200-a754-11eb-97fd-cd04ad6ca809.png)

<img width="971" alt="image" src="https://user-images.githubusercontent.com/737638/116185463-3bf5fb80-a754-11eb-8f69-5b84c8ce57dd.png">

- OS: OSX 10.15.7 (19H524)
- Browser: Firefox 88.0

**Comment by skenaja** [comment]
Those 2 copies are still owned by `tz1aQC5HSXSqqxEqyLcPchPbEsyZsqu5upXv` and `tz1cfgjfbX2w2VwPFpBZv38RUbUaEQpRZG5b`. Only owners can burn objkts.

These 2 users would be able burn the objkts via the burn page, or by directly sending their copies to `tz1burnburnburnburnburnburnburjAYjjX` via their wallets

**Comment by dhowe** [comment]
@skenaja I am not trying to burn the objects owned by someone else. I just want the object (which, as I said, was a test) off of _my_ creations page. The creator _should_  have control over what shows up on their own page (see #588).

**Comment by skenaja** [comment]
That makes sense - we'll track via #588.
