### ISSUE TITLE
My creations page hasn't been loading for the past few days

### ISSUE THREAD

**Issue by CZakiewicz** [hicetnunc2000/hicetnunc#601]
My creations page hasn't been loading for the past few days. 
When I click on 'Manage Assets' my tokens are not loading. 

Go to https://www.hicetnunc.xyz/tz/tz1SwZ6nfa8Tu4yR6JjmtZXn4e7T3YP8cWZj

I expected my creations to load as there were doing before

<img width="1097" alt="Screen Shot 2021-04-27 at 23 57 53" src="https://user-images.githubusercontent.com/83007623/116322679-6ecfdc00-a7b4-11eb-9e63-e22bb624f81e.png">

I'm using Chrome and Safari on a Mac 10.14.5 running Mojave

tz1g5CZHVEca7gvgPVE3XPcAjN1fsXStLy5y

Many thanks
[](url)

**Comment by skenaja** [comment]
Have you got 2 wallets?

https://www.hicetnunc.xyz/tz/tz1SwZ6nfa8Tu4yR6JjmtZXn4e7T3YP8cWZj
https://www.hicetnunc.xyz/tz/tz1g5CZHVEca7gvgPVE3XPcAjN1fsXStLy5y

The first one you mentioned doesn't have any creations, but the 2nd one does.

This can be confirmed here - there are no `mint` operations.
https://tzkt.io/tz1SwZ6nfa8Tu4yR6JjmtZXn4e7T3YP8cWZj/operations/

**Comment by CZakiewicz** [comment]
I see! 

Yes, I was having problems with my Kukai wallet not showing my Tokens so I tried another wallet. 

Thanks for your help!


CLAIRE ZAKIEWICZ

+44 7920447101
+1 9293255796 (Whatsapp only)

IG: clairezakiewicz <https://www.instagram.com/clairezakiewicz/>
www.clairezakiewicz.com
