### ISSUE TITLE
Support for Unity WebGL Builds

### ISSUE THREAD

**Issue by local306** [hicetnunc2000/hicetnunc#602]
Knowing that hic et nunc supports interactive OBJKTs, it would be neat to see Unity WebGL builds supported as a mime type.

**Comment by tarwin** [comment]
Can you upload it as HTML (ZIP)?

**Comment by local306** [comment]
> Can you upload it as HTML (ZIP)?

I did try with a small project following the requirements for interactive OBJKTS on the wiki. When I go to preview the upload, I get a large screen telling me that the mime type is currently unsupported unfortunately.

EDIT: Or am I dumb and you are asking for a build to test out? haha

**Comment by pichiste** [comment]
@local306 Can you provide us with a zip file to test with? Thanks

**Comment by pichiste** [comment]
I should add that a Unity WebGL build support doesn't have to do with mime types. It's just a web directory like any other, that needs to be zipped and uploaded. What needs to be sorted is whether the current Content Security Policy will allow it to run properly.

**Comment by local306** [comment]
[Builds.zip](https://github.com/hicetnunc2000/hicetnunc/files/6401264/Builds.zip)
@pichiste I've attached my simple cube test project.

**Comment by pichiste** [comment]
Hey @local306, thanks for the sample build.

So something strange: The preview also throws an error for me. However, if I unzip, and re-zip the file, it works! (I'm on macOS 10.15.7)

Can you try with this one?
[Builds 2.zip](https://github.com/hicetnunc2000/hicetnunc/files/6406222/Builds.2.zip)

Also, can you provide some more details about your setup? (OS, browser, etc)

Thanks!

![Screen Shot 2021-04-30 at 4 53 01 PM](https://user-images.githubusercontent.com/111979/116713555-33f8be80-a9d5-11eb-8b60-57fec858d33b.png)

**Comment by local306** [comment]
@pichiste very interesting indeed. 

I tried out the build you posted and it works for me as well oddly enough. Noticing that your provided .zip is a few KB larger than the one I zipped. I've tried both WinRAR and native ZIP actions to no luck on my machine otherwise.

As for specs, I'm using Google Chrome 90.0.4430.92 x64 on a Windows 10 19042.928 x64 machine. Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz 4.00 GHz. 64.0 GB RAM. Nvidia RTX 2080.

**Comment by melMass** [comment]
You need to disable compression in the Unity Player settings, this is a  Unity known bug: https://forum.unity.com/threads/uncaught-referenceerror-unityframework-is-not-defined-at-htmlscriptelement-script-onload-webgl.803967/

I just tested now:

https://user-images.githubusercontent.com/7041726/116832106-bfc84180-abb3-11eb-87cc-d10d4e7bc976.mp4

**Comment by local306** [comment]
@melMass good to know. The nuances of the web, eh? haha

I had also manage to get builds working using 7Zip, and changing the _Path mode_ from the default `Relative pathnames` to `Full pathnames` when tinkering with it this evening.

Going to mark this as closed since it now seems like there are a few possible ways of getting Unity WebGL builds deployed on here.

Just for my knowledge though, what exactly would be the cause of this issue given how the same build can deploy on itch.io for example without having to change anything with the build settings inside of Unity?

**Comment by void3gp** [comment]
![image](https://user-images.githubusercontent.com/60455452/121468075-6c33e980-c9e4-11eb-90b4-bc2d611b7b85.png)

anyone want to teach me about interactive OBJKTs with unity??
i trying and i still dont have a solution for this problem

**Comment by pichiste** [comment]
@local306 @melMass Finally got a chance to test this on Windows. I installed the latest official version of Unity (2021.1.10f1), and created an empty project to test with.

I then exported a version with compression, and one without, zipped both using 7-zip (without modifying any settings), and tried uploading to HEN.

The compressed version didn't work (as expected) – this is a Unity bug, not HEN-related.

The version with compression disabled worked fine:

![Annotation 2021-06-10 091110](https://user-images.githubusercontent.com/111979/121482884-da20e680-c9cd-11eb-9221-0761a53cf0d0.png)

For the versions that didn't work for you, what did you use to create the zip archives? The issue seems to be this, since it works fine with 7-zip.

@void3gp Can you send a screenshot of what shows up in the web console?

**Comment by melMass** [comment]
Hi @pichiste, I'm not sure of what you are asking but on Mac I don't think 7zip is an option, you only have one option and using it breaks the webGL builds

That said, after a few tests I think it's much better to go with a framework like threeJS for HEN, much more compatible and obviously less bloated

**Comment by pichiste** [comment]
hey @melMass, sorry I missed that you were on Mac, my comment was in regards to @local306' issue with creating a working zip file on Windows. Several people have reported generating zip files on Windows that don't work (with or without Unity), so I'm trying to understand what tools/settings aren't working and why so I can fix it.

Just to clarify:  "you only have one option and using it breaks the webGL builds" refers to the Unity's "Compression Format" bug? Or that zip files created on Mac are not working? I'm not having any issues with the latter.

**Comment by melMass** [comment]
Oh gotcha, it's not really related to this issue, 7-zip compression (in Unity not compressing the build for upload on HEN) is available in some versions of Unity, I think that is what he was referring to.

**Comment by void3gp** [comment]
![image](https://user-images.githubusercontent.com/60455452/121571584-6b836d80-ca4d-11eb-9c8f-c765508bacec.png)

https://drive.google.com/drive/folders/1Yrqmtsxz_xD_a7Y_DDS97wJykdXkaBfd?usp=sharing
i dont know whats the problem so if u wanna check u can check the zip files on my drive

**Comment by melMass** [comment]
@void3gp Check the console, those screens aren't giving us any information.

**Comment by void3gp** [comment]
@melMass where's that??

![image](https://user-images.githubusercontent.com/60455452/121579328-cfaa2f80-ca55-11eb-8392-c732bc83a8b4.png)

sry im new in unity

**Comment by melMass** [comment]
@void3gp in your browser

**Comment by melMass** [comment]
@void3gp, I can assist you on the HEN's discord, it's more suited to this kind of support: https://discord.gg/7t9nM5QZ

**Comment by cifu-3d** [comment]
[7.zip](https://github.com/hicetnunc2000/hicetnunc/files/8238072/7.zip)

I uploaded with no compression and follow all the steps no-gzip disable, etc, uploaded it at itchi.io and it worked, even at the HEN (now TEIA) preview works, but when minting it  stays loading forever and then sends an error message... any idea why? I'm using unity 2020.3.25
