### ISSUE TITLE
Cannot access 'burn' page for object

### ISSUE THREAD

**Issue by dhowe** [hicetnunc2000/hicetnunc#603]
Expected: go to burn page
Actual: blank page with errors in console

Errors:

> react-dom.production.min.js:216 TypeError: Cannot read property 'address' of undefined
>     at d (burn.js:14)
>     at ro (react-dom.production.min.js:157)
>     at qs (react-dom.production.min.js:267)
>     at Bc (react-dom.production.min.js:250)
>     at _c (react-dom.production.min.js:250)
>     at kc (react-dom.production.min.js:250)
>     at gc (react-dom.production.min.js:243)
>     at react-dom.production.min.js:123
>     at t.unstable_runWithPriority (scheduler.production.min.js:18)
>     at Hi (react-dom.production.min.js:122)
> ss @ react-dom.production.min.js:216
> react-dom.production.min.js:123 Uncaught TypeError: Cannot read property 'address' of undefined
>     at d (burn.js:14)
>     at ro (react-dom.production.min.js:157)
>     at qs (react-dom.production.min.js:267)
>     at Bc (react-dom.production.min.js:250)
>     at _c (react-dom.production.min.js:250)
>     at kc (react-dom.production.min.js:250)
>     at gc (react-dom.production.min.js:243)
>     at react-dom.production.min.js:123
>     at t.unstable_runWithPriority (scheduler.production.min.js:18)
>     at Hi (react-dom.production.min.js:122)

Object: https://www.hicetnunc.xyz/objkt/45908
Wallet: tz1LBrt4eYvv82VL1d5VsxX22wAE1pxjGcym

- OS: OSX 10.15.7 (19H524)
- Browser: Firefox 88.0 (same on current Chrome)

<img width="873" alt="image" src="https://user-images.githubusercontent.com/737638/116358111-dc6d1e00-a82f-11eb-935e-24b50efc0fe8.png">

**Comment by skenaja** [comment]
I was able to reproduce this error by being unsynced from my wallet and accessing a burn page for an item. Was this the same for you?

Re-syncing my wallet made the page appear OK. I'll submit a fix for this.

**Comment by andrevenancio** [comment]
merged to `main` awaiting deployment
