### ISSUE TITLE
Getting error when trying to mint a glb file.

### ISSUE THREAD

**Issue by manuvision** [hicetnunc2000/hicetnunc#607]
https://user-images.githubusercontent.com/17086939/116384840-3b0daa00-a7e6-11eb-927d-358b38b34d83.mov

As you can see in this video, my file is a .glb and I'm getting a tooltip error preventing me from minting it because of the file format. (Also worth noting that the tooltip also indicates .gltf which is not supported)

Tooltip message:
File format invalid. supported formats include: bmp, gif, jpeg, png, svg, tiff, webp, mp4, ogv, quicktime, webm, glb, gltf, mp3, oga, pdf, html (zip archive)

**Comment by andrevenancio** [comment]
Please have a look at this URL https://jsfiddle.net/andrevenancio/78eng15p/ and take note of the alert text and share it here

**Comment by serkansokmen** [comment]
The same here, I got these on the fiddle, hope that it helps

```
file: model/gltf+json, binary: model/gltf+json
```

and with the same file in .glb format:
```
file: model/gltf+json, binary: model/gltf-binary
```
