### ISSUE TITLE
Display issues on creations and on objkt pages

### ISSUE THREAD

**Issue by erochOnGit** [hicetnunc2000/hicetnunc#61]
I have display issues on creations :
https://media.discordapp.net/attachments/812076819129827358/818835400319565915/unknown.png?width=1401&height=940

And on objkt page : 
https://media.discordapp.net/attachments/812076819129827358/818835626345627648/unknown.png?width=1692&height=727

At : 
https://www.hicetnunc.xyz/tz/tz1iUVyni4mrA18BhTWLCbsZQvwQSJRd9QRt
https://www.hicetnunc.xyz/objkt/1662

For objkt page it seem that the content was not provided :
https://media.discordapp.net/attachments/812076819129827358/818837573408653353/unknown.png
it's not all the objkt tho this one is working correctly : 
https://www.hicetnunc.xyz/objkt/2318
I minted it a day later than the others.

**Comment by andrevenancio** [comment]
#1662 happen because of a missing mimetype. should be fixed soon.
