### ISSUE TITLE
Can't cancel a swap

### ISSUE THREAD

**Issue by jd-thorpe** [hicetnunc2000/hicetnunc#616]
**Describe the bug**
Unable to cancel swap.
I'm sync'd using temple wallet with this address. tz1MT8eCazHtutjK3An7s5WFexpa5pKceC3P
After clicking the cancel option is was applied in my wallet however only 1 instead of the 448 remaining objkts were applied to my wallet.

**To Reproduce**
I can't reproduce the error as the cancel option is no longer available.

**Expected behavior**
As far as I'm aware after clicking cancel and getting confirmation in my wallet the remaining editions should have been moved back to my wallet.

**Screenshots**
Screenshots of wallet confirmation and cancel button not being available.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)

<img width="510" alt="Canel Applied" src="https://user-images.githubusercontent.com/83420680/116590004-2845c300-a915-11eb-8598-8b562b931f84.png">
<img width="529" alt="No Canel option" src="https://user-images.githubusercontent.com/83420680/116590022-2bd94a00-a915-11eb-8a8c-42842b0b9db2.png">

**Comment by Ellados** [comment]
In the screenshot, it seems that the mysterious collector "...8LSKs" grabbed all your objkts and resold them for 0.01
In fact it's a bot and he did that with many free objkt from many poeple, which is not very nice...

**Comment by jd-thorpe** [comment]
Ahhhh! this makes a lot of sense! Thank you for clearing that up for me!

Thanks
Josh
