### ISSUE TITLE
FAQ: Please add shortlink service to Tools Made By Community page

### ISSUE THREAD

**Issue by hetnxyz** [hicetnunc2000/hicetnunc#617]
**Summary of change to FAQs you wish to make:**
* For example: new page `foo.md`, edit to page `bar.md`. 
* If want to reorder any existing page, note this here too.

Hi! Please could you kindly add a new shortlink service under the associated section on the page "Tools made by the community"? This service hetn.xyz launched recently with a proper website and already has several users. The service can be reached at hetn.xyz.

Thank you so much for the change and all your work!
hetn.xyz team

**If it's a new page, which navigation heading does it come under**
* For example: Minting guide, FAQs, Misc

Existing page: Tools made by the community
Existing heading: Shortlink Services

**Text change**
* Add here the new text (and old text it's replacing if applicable)

[hetn.xyz](https://hetn.xyz) by [hetn.xyz](https://twitter.com/HetnXyz)

**Markdown**
* If you've written the update using Markdown, replace the `FAQ in markfown format` below with your markdown-tagged text

```Markdown
Add FAQ text in Markfown format
```

**Comment by violetforest** [comment]
done, thanks!

**Comment by hetnxyz** [comment]
Thank you so much! :))
