### ISSUE TITLE
Telegram icon/link missing in profile

### ISSUE THREAD

**Issue by 360fun** [hicetnunc2000/hicetnunc#620]
**Describe the bug**
I cannot see the Telegram icon/link in my H=N profile, together with other socials!

**To Reproduce**
Steps to reproduce the behaviour:
1. Add your profile informations following the guide (including Telegram link)
2. Check profile socials
3. Telegram is missing (maybe also others socials, I didn't put all of them)

H=N profile: https://www.hicetnunc.xyz/tz/tz1cYe4ueZsd6pErnpyXHNDX4tHBjtJy89w3 👇
![image](https://user-images.githubusercontent.com/844090/116635530-53550480-a95f-11eb-8f92-d3c552de443d.png)
TzKT profile: https://tzkt.io/tz1cYe4ueZsd6pErnpyXHNDX4tHBjtJy89w3/operations/ ☝️

PS
also email is missing but maybe that was intended

**Comment by andrevenancio** [comment]
This is a great opportunity to do a PR @360fun :)

**Comment by 360fun** [comment]
done: https://github.com/hicetnunc2000/hicetnunc/pull/659
I haven't tested it because I don't have time to setup the environment, but the data is there so it should work 😜

I can add also the email if you are ok with it.

**Comment by 360fun** [comment]
I noticed there's a problem with the icon and I've fixed it here:
https://github.com/hicetnunc2000/hicetnunc/pull/713
