### ISSUE TITLE
Wrong Swap 

### ISSUE THREAD

**Issue by justttd** [hicetnunc2000/hicetnunc#622]
I was stripped of 15 coins when I wanted to put the work up for sale in order to make a SWAP!
I wanted to put up for sale 1 copy of the work, it was not put up and the transaction appeared for -15 coins
I had to do it again, and naturally no one returned the coins to me

OBJKT#31876

Before that I made a purchase, everything came to me and I wanted to put this work up for sale, for some reason the coins went to the address "hicetnunc"

My address: tz1LGP5vaVjZvyskCwN1EK99FoVdKoQbQoMt

Transaction:  oojXykshawSVECPzCNh1n1qM6kk8GCAs91W3pGqy8CG32wA7Rwo
![xtz1](https://user-images.githubusercontent.com/54666777/116659210-e6ab2b80-a999-11eb-86f6-2cb8a52b1b28.png)

 - Browser Сhrome 
 -Version 90.0.4430.93

**Comment by skenaja** [comment]
https://better-call.dev/mainnet/opg/oojXykshawSVECPzCNh1n1qM6kk8GCAs91W3pGqy8CG32wA7Rwo/contents
https://better-call.dev/mainnet/opg/oosdbqQFLkTxGb2w7qPGbEpoM2pxAqWcvU7TKdBsKiz8i6iunVa/contents

The above sites make it easier to see the objkt# for those transactions. They shows that the -15XTZ was used to buy OBJKT#31876 again after buying it for 10XTZ (so you bought 2 copies).

When you swap an item (list it for resale), it goes to an escrow wallet, and disappears from your "collection" tab. There will be functionality added in future to more easily track resales (see #276)

**Comment by justttd** [comment]
Thank you, sorry for wasting time(

пт, 30 апр. 2021 г. в 14:01, skenaja ***@***.***>:
