### ISSUE TITLE
Can not burn my tokens

### ISSUE THREAD

**Issue by SashaPetrenko** [hicetnunc2000/hicetnunc#626]
Can not burn my tokens, can not change the price
I go to burn and it shows error when I burn

 - Windows 10
 - Chrome
 - 89.0.4389.128

WN -tz1NxSDPAfYFzJkZmeGVfzEM7r42k3q9mVRp
tokens - https://www.hicetnunc.xyz/objkt/55191
and
https://www.hicetnunc.xyz/objkt/55186

**Comment by skenaja** [comment]
Please cancel any swaps before burning.
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-cancel-%E2%9D%8C
