### ISSUE TITLE
FAQ: Content Creation PT:Edite seu Perfil

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#631]
**Add and update the page PT:Edite seu Perfil**

please edit the following page, with the content below:
https://github.com/hicetnunc2000/hicetnunc/wiki/PT:Edit-your-profile

# Edite Seu Perfil

## Como ser verificado
- ou como faço para colocar meu nome no perfil?

### Resposta curta:
Preencha este [formulário do Google](https://docs.google.com/forms/d/e/1FAIpQLSdlHVqzIxPFL-gAXNxEefyBtI3g3_wiCgcf80bX4tYsXC7b5A/viewform) e espere cerca de 72 horas

--
### Resposta longa:
O hicetnunc busca as informações do perfil em [https://tzkt.io/](https://tzkt.io) , portanto, para obter o seu nome associado ao endereço da carteira, você precisa entrar em contato com o tzkt.io. Eles vão pedir que você preencha um formulário e transfira uma pequena quantidade de tez de sua carteira para provar que é realmente você.

Vá para o seu perfil hic et nunc
1. Clique no link do endereço da sua carteira para navegar para tzkt.io
2. Passe o mouse sobre os ícones de contato
3. Um pop-up será exibido "Você pode compartilhar seu e-mail e outros contatos."
4. Clique no link de compartilhamento
5. Um novo pop-up será exibido, contendo suas informações de contato
6. Eles enviarão instruções sobre como proceder.
7. Eles pedirão que você preencha um formulário com suas informações de contato
8. Eles pedirão que você transfira 0,00177 cor de pele para o endereço deles e forneça a transação no formulário

## Não quero ser verificado por meio do formulário do Google. Existem outras opções?
--
Se os usuários não tiverem contas no Google ou no Twitter, eles podem entrar em contato com o Baking Bad para fazer a verificação manualmente. Preencha o formulário abaixo e envie para seus contatos: twitter, telegram group, slack ou email [Baking Bad contatos](https://baking-bad.org/docs/#contacts)

**Endereço da conta** tz ...

**Alias ​​ou seu nome (2 a 20 caracteres)**

Transação de confirmação da conta Para provar a propriedade da conta, você precisa enviar (por exemplo, 0,003521 tez) de sua conta para `tz1YUigABASqRUWAG97qHfHwYkYEGDk9q2Qv ` e fornecer o hash da transação.

Siga https://twitter.com/TezosBakingBad [AVISO: Sem seguir da conta do Twitter, fornecida abaixo, seu aplicativo não será processado. Se você não tem uma conta no Twitter, entre em contato conosco hello@baking-bad.org]

**Imagem de avatar QUADRADA, 512x512 px, PNG**

**Site de e-mail (apenas https) Twitter Instagram Telegram Reddit Github Facebook**

**Descrição** Apenas algumas frases, apresentando os visitantes do TzKT a você. Somente em inglês, não são permitidos links

## Me Ajude, enviei o formulário há mais de 72 horas, mas nada mudou.
--
Talvez você não os tenha seguido no twitter ou não tenha preenchido o formulário corretamente. Você pode tentar reenviar o formulário e segui-los, ou você pode entrar em contato com a equipe do baking bad diretamente, pois o hicetnunc não tem nenhum controle sobre ele. Você pode tentar contatá-los no [Telegram, Slack ou meail ou reenviar o formulário. Baking Bad telegram group, slack, email, etc](https://baking-bad.org/docs/#contacts)

**Comment by violetforest** [comment]
finalizado! obrigada!
