### ISSUE TITLE
Wrong total editions amount

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#633]
I've noticed that an objkt I published with 500 editions for the O4O event is now showing 520 editions instead of 500.
This is the objkt:
https://www.hicetnunc.xyz/objkt/45200

**Comment by kylegrover** [comment]
A (probably) related bug I noticed today- this OBJKT shows 265/217 editions available https://www.hicetnunc.xyz/objkt/43047

**Comment by andrevenancio** [comment]
investigating

**Comment by skenaja** [comment]
Likely to be #546

**Comment by mescalina** [comment]
> Likely to be #546

I'm not sure it's related, originally for some time the total listed amount was correct, 500 editions, than days or even a couple of weeks later it started to show 520 instead of 500.

**Comment by violetforest** [comment]
duplicate of https://github.com/hicetnunc2000/hicetnunc/issues/546
