### ISSUE TITLE
Token appears to be stuck in HEN minter for several hours

### ISSUE THREAD

**Issue by jaybyron** [hicetnunc2000/hicetnunc#635]
### **Describe the bug**
Hi not sure if this is the correct avenue to get for help, but I asked for support in discord and the only response I got was to make a github issue.

An artist sent me a token as a reward but I have not received it yet. I tried doing some digging, and it looks like the token is currently not in either of our wallets. I did some digging and was able to scrape this piece of JSON on the NFT:

```{
  "result": {
    "objectId": "58975",
    "ipfsHash": "QmXsZ32fPmmuppvNQCRHC9Vq3Z7pznrnVVMzb4oCTyJvqJ",
    "swaps": [],
    "token_id": "58975",
    "total_amount": 1,
    "owners": {
      "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9": "1"
    },
    "token_info": {
      "name": "Rare Artifact X101",
      "description": "UNKNOWN MINERAL. Produced from Research Artifact 01. Created by @alexdelia for Artifact.Quest 2021.",
      "tags": [
        "Artifactquest",
        "artifact",
        "alexdelia",
        "rare",
        "researchartifact",
        "platinum",
        "3d",
        "3danimation",
        "jewel",
        "limited",
        "1/1"
      ],
      "symbol": "OBJKT",
      "artifactUri": "ipfs://QmTJsWvVkZ8gdarjTtYbDH8TLAkjKb5nccjFBgpkoMKt7C",
      "displayUri": "",
      "thumbnailUri": "ipfs://QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc",
      "creators": [
        "tz1MCEixbAooPR3o1bBnEHXC9UAeJiiKBkye"
      ],
      "formats": [
        {
          "uri": "ipfs://QmTJsWvVkZ8gdarjTtYbDH8TLAkjKb5nccjFBgpkoMKt7C",
          "mimeType": "image/gif"
        }
      ],
      "decimals": 0,
      "isBooleanAmount": false,
      "shouldPreferSymbol": false
    },
    "hDAO_balance": 0
  }
}
```

Based on the `owner` property, I looked up the address and `KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9` is actually the `Hic et nunc Minter`. It's been in this state for several hours, and the artist does not really know what to do. 

Another interesting thing is that on the objkt detail page, the `collectors` tab is empty.
URL: https://www.hicetnunc.xyz/objkt/58975

### **To Reproduce**
1. Not too sure how to reproduce getting a token into this state, but we can easily reproduce the token appearing to be missing by looking at the objcet detail page above or looking at the owner address of the wallet

### **Expected behavior**
- The token should be in either the originating artist wallet or the receiver wallet (myself in this case)

### **Screenshots**
On the UI, the collectors tab is rendering null
<img width="1326" alt="Screen Shot 2021-05-02 at 10 34 48 AM" src="https://user-images.githubusercontent.com/6361914/116822281-daa6a180-ab32-11eb-84fe-d35c8c3aed0d.png">

The token seems to be rendering the artist as `undefined`
<img width="1200" alt="Screen Shot 2021-05-02 at 10 44 50 AM" src="https://user-images.githubusercontent.com/6361914/116822407-79330280-ab33-11eb-8a25-088391eba101.png">

### **Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Chrome
- Version 90.0.4430.85 (Official Build) (x86_64)

### **Additional context**
- In the end, I am trying to help this artist out since I am the one receiving the token, and I am familiar with reporting bugs and issues.
- My guess is the minter contract probably errored when minting this objkt. If that is the case, would the next best option be to re-mint?
- If re-minting is the best answer,  how do they remove this buggy objkt out of their wallet/feed

Thank you for any insight or help in advance!

**Comment by skenaja** [comment]
It looks like the artist managed to send it direct to the HEN contract via this transaction:
https://better-call.dev/mainnet/opg/oo8uCcB5qSGBrwMvMNTVFaTPRBBuKTKLmsrsky973P4eqRY4xAR/contents

@crzypatchwork do you know if contract manager `tz1UBZUkXpKGhYsP5KtzDNqLLchwF4uHrGjw` would be able to do this (eg via `update_operators` to either transfer it back or send it to the burn wallet?)

**Comment by howrichi** [comment]
Hi, I was wondering if this problem was resolved? Unfortunately I seem to be in the same situation. I’m new to hic et nunc but followed all the instructions. It seems I managed to Mint my first work but when I was doing the swap there was an error and it was sent direct to the HEN contract. Is there a way I can get contract manager to send it back or burn it?  Would appreciate any help or advice. Thanks

**Comment by skenaja** [comment]
> Hi, I was wondering if this problem was resolved? Unfortunately I seem to be in the same situation. I’m new to hic et nunc but followed all the instructions. It seems I managed to Mint my first work but when I was doing the swap there was an error and it was sent direct to the HEN contract. Is there a way I can get contract manager to send it back or burn it? Would appreciate any help or advice. Thanks

@howrichi - please can you provide some diagnostics - your wallet ID, the objkt ID, we can't help you otherwise.

**Comment by howrichi** [comment]
@skenaja  thanks for the reply. Sure my wallet ID is: tz1ZghGmfapjVymzSvAuxg42hy7BmH3MAAuc  
The objkt ID is: 83295

**Comment by howrichi** [comment]
Seems to have landed here: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9

This is the transfer: https://better-call.dev/mainnet/opg/opQbgSfE6U3D2Wbhce6wmwCVgPR649QSDe9eryJsZPJ8qXgLRqi/contents

**Comment by skenaja** [comment]
> Seems to have landed here: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
> 
> This is the transfer: https://better-call.dev/mainnet/opg/opQbgSfE6U3D2Wbhce6wmwCVgPR649QSDe9eryJsZPJ8qXgLRqi/contents

It's just listed for sale, that's the HEN escrow wallet it sits in until someone buys it. 
Can you see a cancel button here?

![image](https://user-images.githubusercontent.com/510285/118549606-9ed72300-b753-11eb-9133-962994239d7d.png)

That will cancel the listing and bring it back to your wallet if you don't want to let it go to someone else!

**Comment by howrichi** [comment]
> > Seems to have landed here: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
> > This is the transfer: https://better-call.dev/mainnet/opg/opQbgSfE6U3D2Wbhce6wmwCVgPR649QSDe9eryJsZPJ8qXgLRqi/contents
> 
> It's just listed for sale, that's the HEN escrow wallet it sits in until someone buys it.
> Can you see a cancel button here?
> 
> ![image](https://user-images.githubusercontent.com/510285/118549606-9ed72300-b753-11eb-9133-962994239d7d.png)
> 
> That will cancel the listing and bring it back to your wallet if you don't want to let it go to someone else!

Thanks alot, that worked! I got a bit confused, my mistake I didn't realise about the HEN escrow wallet, I thought it may have been stuck in the process. Sorry to bother you with this. I appreciate your help!
