### ISSUE TITLE
Kukai Wallet has returned an error

### ISSUE THREAD

**Issue by JoseMedina1977** [hicetnunc2000/hicetnunc#636]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by andrevenancio** [comment]
closing this issue. You shouldn't just add a "title" and not provide information. Nobody can reproduce the error with these instructions.
