### ISSUE TITLE
FAQ: [summary of change]

### ISSUE THREAD

**Issue by OrderAndCh4oS** [hicetnunc2000/hicetnunc#638]
**Summary of change to FAQs you wish to make:**
* Add @tarwin https://github.com/tarwin/hicetnunc-collection-generator to Gallery Tools. This generates thumbs and a gallery. 
* Add Hic et Nunc API CDK https://github.com/OrderAndCh4oS/hicetnunc-api-cdk to Gallery Tools, this is a trimmed-down API for fetching wallet and objkt data from the blockchain with conseiljs, intended for use by Galleries. By @__orderandchaos
* Add Generate Thumbs and Upload to S3 https://github.com/OrderAndCh4oS/hicetnunc-generate-thumbs-and-upload-to-s3 to Gallery Tools. This can be combined with Hic et Nunc API CDK to fetch and generate thumbs from a given set of wallet ids and upload them to S3. By @__orderandchaos

**Comment by violetforest** [comment]
@OrderAndCh4oS thanks! done!
