### ISSUE TITLE
NaN Editons Owned - Burn Problem

### ISSUE THREAD

**Issue by hulkiokantabak** [hicetnunc2000/hicetnunc#639]
Hello,

I'm trying to burn Object 35323 and constantly the transaction is failing. Then I realized it shows NaN editions. I think this is a bug with hic et nunc. The way it stands I can not burn any of the editions for this and other similar objects.

I have looked at all the objects in the portfolio and all of them show NaN editions owned.

Best regards,
H

Wallet Address is: tz1U4y37SnmE9SYzHE8aNPJDrJtcGtfD9MLN

https://www.hicetnunc.xyz/objkt/35323

You own NaN editions of OBJKT#35323. How many would you like to burn?

**Comment by andrevenancio** [comment]
You can't burn something you don't own... this person owns 50 copies. so those don't belong to you
https://www.hicetnunc.xyz/tz/tz1U4y37SnmE9SYzHE8aNPJDrJtcGtfD9MLN

**Comment by hulkiokantabak** [comment]
That person is me and I am trying to burn the items in the my wallet.
