### ISSUE TITLE
objects listed to resell disappeared

### ISSUE THREAD

**Issue by notthedrphil** [hicetnunc2000/hicetnunc#642]
I tried to list two objects to resell but they have disappeared.

went to manage objects
collection
swap
object amount: 1
tezos: resell price
swap

![image](https://user-images.githubusercontent.com/83624338/116954696-88a27080-ac45-11eb-8df8-ad3ebbdf33c7.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

tz1hZnoyhEMV7vLJF8SouZZXq7Bs2FSqrVbh

**Comment by trailbike** [comment]
same issue just wondering where it went the resell of a collection piece

**Comment by bulkhead72** [comment]
Same issue here as well. Can't seem to find an item that I had listed for sale anywhere. It's no longer in my Manage Assets section, nor in the "collections" section of the OBJKT.

**Comment by kidartprojects** [comment]
I am having the same issue. Tried to list an item from collection for resell and now it has disappeared.

**Comment by andrevenancio** [comment]
When you swap an OBJKT that you purchase, it goes from your collection to the market. Therefore it is removed from your collection because the token is sent to a hicetnunc smart contract.

If you cancel the swap it goes back to your collections.

If you can't remember which objkt number you had purchase, you can check the parameter `swaps` on this api request. simply add your wallet id https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/tz?tz=YOUR_WALLET_ID_HERE

I've just created a new feature where you have `swaps` next to `creations` and `collections`. But this feature hasn't been deployed yet.

Is this worth to add to the WIKI @violetforest ?

**Comment by kidartprojects** [comment]
Nope didn't work. Thanks for being a condescending asshole though

**Comment by bulkhead72** [comment]
I don't think that Andre was being condescending at all...

**Comment by kidartprojects** [comment]
First off, who the hell are you? Second off he assumed I didn't read the
wiki. From your wiki:
cancel

1: *(verb)* to decide not to conduct or perform (something planned or
expected) usually without expectation of conducting or performing it at a
later time

2: *(verb)* to take your NFT off the market
------------------------------

Let’s say I want to raise my price, or set my OBJKTs as “not for sale”.

   1. Make sure your wallet is synced
   2. Click on [collectors] and then [cancel]. This will send the OBJKTs
   back to your wallet. Check your wallet for confirmation.
   3. Now that they are back in your wallet, you can [swap] them again.

If you want to delete your OBJKT, continue to How to burn 🔥
<https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5>


SO HOW DO I CANCEL IF THE OBJECT APPEARS NO WHERE TO ME? HOW DO I DO ANY
INTERACTING AT ALL? IT IS GONE?

**Comment by skenaja** [comment]
There is a [code of conduct](https://github.com/hicetnunc2000/hicetnunc/blob/main/CODE_OF_CONDUCT.md) that everyone must abide by if they wish to receive help here. Please refrain from using insulting language.

Were these the 2 swaps?

https://www.hicetnunc.xyz/objkt/12599
https://www.hicetnunc.xyz/objkt/61326

**Comment by bulkhead72** [comment]
Hi Skenaja, in my case this was the object:

https://www.hicetnunc.xyz/objkt/30342

I had listed it for Swap for 35 Tez over a week ago, but don’t see it in the “Collectors” section (there is one listed for 35 Tez, but by a different seller). Nor do I see it in my collection, so it seems to have disappeared. And I know that I have not sold the piece. The last five figures of my account number are “StxGG”. Thanks!

**Comment by kidartprojects** [comment]
I don't need your help anymore. And don't assume people haven't read your
very weak wiki.

You guys have released the least intuitive worst customer facing platform
I've ever had the displeasure of using. Unfortunately I have no choice as I
am waiting on Kalamint and everyone is using Tezos.

Until you address the fact people are using hic et nunc that might not even
know what a wiki is, you are going to have people like me. You are playing
with real money.  Might want to consider making the platform a touch easier
to use.

**Comment by skenaja** [comment]
Hi @kidartprojects - looks like your objkt was sold (congratulations!) - here's the transaction hash: https://tzkt.io/onjXoYQR8Eh4usBrrJV347NMb7jQb21zY92B2PBaxCEgNZMM1Zg

Thanks for the feedback about site usability.

**Comment by bulkhead72** [comment]
Hi @skenaja when you get a chance, can you kindly look into my issue as well? Posted details a couple of posts above. Thank you!

**Comment by kidartprojects** [comment]
Ok now my entire creations and collections will not load at all....
