### ISSUE TITLE
Empty Creations

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#649]
Hello
I minted my work and it was successful but there is nothing in my gallery!
https://www.hicetnunc.xyz/tz/tz1Wyga6bguEroEMN6iG3tvQc635jkhFC76S

**Comment by andrevenancio** [comment]
Your operations were backtracked. You own no tokens:

https://tzkt.io/tz1Wyga6bguEroEMN6iG3tvQc635jkhFC76S/tokens

**Comment by erphanmalek** [comment]
Why did this happen? The gas fee for minting was decreased from my wallet!

**Comment by skenaja** [comment]
There's more explanation here: https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#i-got-storage-quota-exceeded-for-the-operation-error---what-happened

Wallet software, eg Temple is responsible for estimating blockchain storage needed for an operation, and it can occasionally get this estimate wrong, especially during busy network times.
