### ISSUE TITLE
html <title> that uses issuer's readable name

### ISSUE THREAD

**Issue by wraybowling** [hicetnunc2000/hicetnunc#650]
**Is your feature request related to a problem? Please describe.**
html title on an artist's page is currently their tez wallet address not human readable name. Bookmarked pages in browser show as `hic et nunc - tzabcdefghijklmnopqrstuvwxyz0123456789`. Additionally, on some bookmarking platforms like getpocket.com, the "article title" is interpreted as the content before the hyphen so all saved pages end up with the same title and titles on that platform cannot be manually changed. Example:
<img width="648" alt="Screen Shot 2021-05-06 at 12 03 50 PM" src="https://user-images.githubusercontent.com/1120619/117329940-28891580-ae63-11eb-955e-424972c9fa22.png">

**Describe the solution you'd like**
Use artist's human-readable name first, then site name, like so:
`Pat Jackson - hic et nunc`

**Describe alternatives you've considered**
`hic et nunc - Pat Jackson` could also work, but is not as common as a standard. Typically the favicon helps "brand" a browser tab instead of forcing the name of the site to come first.

**Additional context**
<img width="342" alt="Screen Shot 2021-05-06 at 12 11 40 PM" src="https://user-images.githubusercontent.com/1120619/117330964-3ee3a100-ae64-11eb-813b-a048f01216e3.png">

**Comment by andrevenancio** [comment]
done. awaiting deployment
