### ISSUE TITLE
Content Creation PT:Como Cunhar

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#652]
Add and update the page PT:Como Cunhar

please edit the following page, with the content below:
https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-mint-🌿

# Como cunhar 🌿

### cunhar
Traduzimos o termo **mint** para **cunhar**, pois é a palavra que mais se assemelha ao que fazemos ao publicar uma obra NFT: Associamos essa obra a um NFT, e consequentemente esse NFT poderá ser associado a alguma moeda.

### mint
1: (substantivo) qualquer uma de uma família de plantas aromáticas com uma haste quadrada e um ovário de 4 lóbulos que produz quatro pequenas nozes de uma semente na fruta

2: (verbo) para criar um OBJKT (NFT)

---

Como cunhar em [https://www.hicetnunc.xyz/](https://www.hicetnunc.xyz/)

1. Clique em “Sync”. O seu navegador irá lhe solicitar para sincronizar com a sua carteira.
2. Aprove a sincronização em sua carteira
3. Clique no botão [OBJKTS (mint NFTs)] no menu de hambúrguer
4. Preencha as informações do seu OBJKT. Você pode inserir o preço do OBJKT após a conclusão da cunhagem.
5. Clique na prévia para ver a prévia
6. Clique em [mint]. Aprove da sua carteira e a transação da Tezos será realizada.
7. Verifique em sua carteira se a cunhagem foi confirmada. Os tempos variam de acordo com o tempo que a confirmação deve levar, mas geralmente leva alguns minutos.

**Importante**: Nesse momento, seu OBJKT ainda não tem um preço._

Continue em [Como anunciar 🔃](https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-swap-%F0%9F%94%83) para aprender como definir preços para seus OBJKTs.

---

**Dica**: _Com base no número da edição que você cunhou, você verá uma série de “OBJKTS” em sua carteira de tez. Esses OBJKTs recém-criados agora pertencem a você._

**Comment by andrevenancio** [comment]
Obrigado

**Comment by violetforest** [comment]
💯
