### ISSUE TITLE
Content Creation PT:Como Trocar

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#653]
Add and update the page PT:Como Trocar

please edit the following page, with the content below:
https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-swap 🔃

Traduzimos a palavra swap por trocar, no seu sentido literal. Ao fazer swap(troca) no Hic Et Nunc, um anúncio com preço será feito, possibilitando assim que algum interessado possa trocar seu NFT por uma certa quantia em criptomoedas.

#Como Trocar🔃
Trocar
1: (verbo) entregar em troca; permutar.

2: (verbo) definir um preço para o seu OBJKT

---

1. Clique no link do seu OBJKT para ver os detalhes. Se você ainda estiver sincronizado com sua carteira, deverá ver “Swap” ao lado de “info”(informações) e “collectors”(proprietários). (Se você não ver essas opções, será necessário sincronizar sua carteira novamente.)
2. Clique em trocar
3. Insira quantos OBJKTs de sua edição você deseja colocar à venda. Por exemplo, se você tiver `10 `e quiser manter `1 `e vender `9`, insira `9`. Se quiser vender todos, insira `10`.
4. Informe quanto cada número de edição deve custar em Tezos
5. Aperte o botão [swap] (trocar). Aprove a operação em sua carteira.

**Importante**: _Quando você está trocando, está enviando uma quantidade de OBJKTs de sua edição para fora de sua carteira. Eles estão sendo mantidos em uma carteira de garantia Hic et Nunc, prontos para serem transferidos para o comprador, e é por isso que eles não estão mais visíveis em sua carteira. Assim que a transação do blockchain for concluída, o preço deve ser definido no OBJKT e disponível para compra, e sua carteira deve informar que você enviou essa quantidade de OBJKTs._

Avance até [Como cancelar ❌](https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-cancel-%E2%9D%8C) para saber como retirar o seu OBJKT do mercado ou alterar o preço.

---

Socorro, minha carteira está apresentando um erro de `**fundos disponíveis insuficientes!**`
Você pode estar tentando trocar mais edições do que cunhou, ou seu objeto ainda está à venda e você precisa cancelá-lo primeiro.

**Comment by violetforest** [comment]
💯
