### ISSUE TITLE
Сan't cancel the number of listings

### ISSUE THREAD

**Issue by VartanMarkarian** [hicetnunc2000/hicetnunc#658]
Good afternoon, I can not cancel listings, there is no cancel button in the collectors section. 
![image](https://user-images.githubusercontent.com/81528775/117535655-6f137700-afff-11eb-82fa-d7dc3ab4bcff.png)

**Comment by skenaja** [comment]
Hi @VartanMarkarian - unfortunately, it looks like the objkts have already been bought, perhaps via automated means which the smartcontract permits, and have been offered for resale on the secondary market. As they are owned by another user, you will not be able to cancel or burn the items. You will receive royalties for any resale.

Feel free to join in the discussion relating to this: https://community.hicetnunc.xyz/t/objkt4objkt-improvements/64 or on Discord.
