### ISSUE TITLE
How can I sale my object ?

### ISSUE THREAD

**Issue by anilrinat** [hicetnunc2000/hicetnunc#661]
Hello,
I have just minted a new object - a gif, and I see it's "not for sale"..
I watched a video explaining how to make it for sale, but I still cant see the option tab when doing the same. 

Am I missing something? 

Thank you
Best
Anil

**Comment by fraguada** [comment]
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-swap-%F0%9F%94%83

**Comment by skenaja** [comment]
@anilrinat let us know if you're still having trouble, and I'll reopen the ticket.
