### ISSUE TITLE
Objkts with tags with % symbol cannot load

### ISSUE THREAD

**Issue by kylegrover** [hicetnunc2000/hicetnunc#662]
**Describe the bug**
OBJKT#29859 cannot load, the UI crashes and just shows a grey screen with console errors:
`URIError: Pathname "/tags/96%biomass" could not be decoded. This is likely caused by an invalid percent-encoding.`

It must be the percent in the tag "96%BIOMASS"

**To Reproduce**
1. https://www.hicetnunc.xyz/objkt/29855

**Expected behavior**
Page will load briefly then go grey, console errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.24.82

**Comment by kylegrover** [comment]
I assume the fix is something like uri encoding tag links as in /tags/96%25biomass

**Comment by mtyka** [comment]
This can be closed.
