### ISSUE TITLE
Mints dont go to the feed / site is stuck at your objkt was minted successfully

### ISSUE THREAD

**Issue by m9u** [hicetnunc2000/hicetnunc#664]
- Since a couple of days none of my mints end up at the front page feed. Im not the only one who experiences this issue, as I saw on discord quite a few other people have it too. 

Everyone i spoke to about this were verified users with sufficient hdao. Also this only started to happen a few days ago. 

For me personally this happens with every mint. I saw that for someone else the objkt shortly appeared at the feed but once they swapped it - it was gone. 

It seems that in general the feed skips over multiple objkts each time I refresh a page (like 4 - 5 objkts at a time) so i suspect this issue has impacted even more users than i saw. 

- Together with this issue, and I believe they are connected, hic now gets stuck on your objkt was minted successfully. Before you would get the close button that brought you to manage your objks page. Now the only way to exit the minting page is to refresh/open a different tab. If I open the new tab with my creations I can already see and access my freshly minted objkt/swap it while the minting window still is open and loads in a different tab.

**Comment by m9u** [comment]
FYI the objkts it concerned for me:
66908, 67823, 68381, 69625, 69734, 69931, 70071, 71073

my profile is https://www.hicetnunc.xyz/tz/tz1RFuW2Ajovz4xNxXnWKE8Xtto3SpGb2NRg

https://tzkt.io/ooqYa8NTePe2zYWaXK2CnVbpBCpjxcyEzyuwgjibFKjWPt2VyVv
One of the failed operations

**Comment by skenaja** [comment]
The issue with minted items not appearing on the homepage is being tracked via the API repo
https://github.com/hicetnunc2000/hicetnunc-api/issues/70

**Comment by skenaja** [comment]
@m9u would you mind raising the issue with the minting page getting stuck in a separate ticket? I believe that they're not linked, so we'd want to track them separately.

**Comment by m9u** [comment]
Thanks for reaching out I will do that!

Cheers

**Comment by becopro** [comment]
Hi there! I'm new to hic et nunc and today I've tried to mint my first nft there, but I had the same problem, the screen is stucked at "objkt minted successfully", nothing happens. I 've opened a new tab to check the "manage assets" part, nothing there. On my wallet activity it appears that the operation backtracked but 0.021486 tezos were subtracted from it, I've tried twice to mint an objkt. I don't understand why this fee was subtracted since i didn't succeed...
![hicetnuncmintbug](https://user-images.githubusercontent.com/83929339/117591278-2f858180-b10a-11eb-979b-233685a2911f.jpg)
![hicetnuncmintbug2](https://user-images.githubusercontent.com/83929339/117591279-30b6ae80-b10a-11eb-9925-d086f1b4ffc3.jpg)

I appreciate your help! Thanks in advance.

My profile: https://www.hicetnunc.xyz/tz/tz1a1Nvt3e8vgv5iaWj1j1owawZPqEc9T73Y

**Comment by mescalina** [comment]
> Hi there! I'm new to hic et nunc and today I've tried to mint my first nft there, but I had the same problem, the screen is stucked at "objkt minted successfully", nothing happens. I 've opened a new tab to check the "manage assets" part, nothing there. On my wallet activity it appears that the operation backtracked but 0.021486 tezos were subtracted from it, I've tried twice to mint an objkt. I don't understand why this fee was subtracted since i didn't succeed...
> ![hicetnuncmintbug](https://user-images.githubusercontent.com/83929339/117591278-2f858180-b10a-11eb-979b-233685a2911f.jpg)
> ![hicetnuncmintbug2](https://user-images.githubusercontent.com/83929339/117591279-30b6ae80-b10a-11eb-9925-d086f1b4ffc3.jpg)
> 
> I appreciate your help! Thanks in advance.
> 
> My profile: https://www.hicetnunc.xyz/tz/tz1a1Nvt3e8vgv5iaWj1j1owawZPqEc9T73Y

Fees are paid even if the operation fails cause the smart contract did some work for you. I know it can sound unfair but it's in the very nature of smart contracts. In kukai wallet you can now raise the fees maximum cap which usually eliminates the risk of backtracked operations (180 is a fine value at the moment)

**Comment by becopro** [comment]
#I use Temple wallet, is there any configuration I have to change for it to work? But still, there is the problem with the screen stuck on "objekt minted successfully", even though it didn't mint anything...
Thanks for the reply though @mescalina!

**Comment by violetforest** [comment]
duplicates of https://github.com/hicetnunc2000/hicetnunc/issues/667 and hicetnunc2000/hicetnunc-api#70
