### ISSUE TITLE
Content Creation PT:Como Cancelar

### ISSUE THREAD

**Issue by jovancosta-zz** [hicetnunc2000/hicetnunc#666]
Add and update the page PT:Como Cancelar

please edit the following page, with the content below:
https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-cancel-%E2%9D%8C

cancelar
1: (verbo) decidir não conduzir ou executar (algo planejado ou esperado) geralmente sem a expectativa de conduzi-lo ou executá-lo em um momento posterior

2: (verbo) tirar seu NFT do mercado
--

Digamos que eu queira aumentar meu preço ou definir meus OBJKTs como "não à venda".

Certifique-se de que sua carteira esteja sincronizada
Clique em [collectors]`colecionadores` e depois em [cancel]`cancelar`. Isso enviará os OBJKTs de volta para sua carteira. Verifique sua carteira para confirmação.
Agora que eles estão de volta em sua carteira, você pode [swap]`trocá-los` novamente.
Se você deseja excluir seu OBJKT, continue em [Como descartar 🔥](https://github.com/hicetnunc2000/hicetnunc/wiki/PT:How-to-burn-%F0%9F%94%A5)

Importante: Se você tentar [swap]`trocar` em OBJKTs que estão à venda no momento, sua carteira emitirá um aviso dizendo que você não tem `fundos suficientes`. Isso porque você já sente seus OBJKTs saindo da carteira na primeira troca. Você precisa clicar em [cancel]`cancelar` para colocar os OBJKTs de volta em sua carteira e, em seguida, poderá [swap]`trocá-los` novamente.

**Comment by violetforest** [comment]
💯
