### ISSUE TITLE
Can not upload video object

### ISSUE THREAD

**Issue by zmnv** [hicetnunc2000/hicetnunc#676]
Hello. 38 Mb mp4 file.

1. Upload video. Go to preview.
2. When .mp4 -- I see my video as preview. When .mov -- I can't see my video.
3. Mint
4. I see «preparing OBJKT»

After some seconds I see in console:
```
Failed to load resource: net::ERR_EMPTY_RESPONSE
asyncToGenerator.js:6 Uncaught (in promise) TypeError: Failed to fetch
```

Request failed after N seconds.. a long time actually:
```
https://ipfs.infura.io:5001/api/v0/add?stream-channels=true&progress=false
```

Sometimes I see http polling requests.. sometimes not...
And then nothing happens. I see «preparing OBJKT» and nothing happens..
wait all day ... then night... then today all day....

----

Attemps:

* clean cache
* sync/unsync/sync...
* remove all data from hic local storage in browser (tab Application in google dev tool)

**Comment by zmnv** [comment]
It's maybe some kind of sign... of the universe... it says.... 'dude... video render? seriously?... can you make more interesting work'... I get it.. okay...

**Comment by violetforest** [comment]
@zmnv are you still having this issue?

**Comment by zmnv** [comment]
@violetforest yes. just tried and the same situation.

I can see video in a preview area.

**Comment by violetforest** [comment]
@zmnv what codec r u saving your video as? h.264 isn't supported in most browsers

**Comment by kylegrover** [comment]
h.264 / mpeg-4 is actually probably the best codec to use, it's what I've used for all of my objkts. _h.265_ (aka hevc) is not widely supported. 
see https://caniuse.com/mpeg4 and https://caniuse.com/hevc for browser support details.
@zmnv can you provide your video file, maybe something's unusual.

edit: if you're uncomfortable providing the video file for an unminted piece please provide info about the encoder and settings used, and the dimensions of the file, or email me at kyle@kylegrover.com

**Comment by kylegrover** [comment]
Also have you tried uploading other large files? And have you tried a different browser or different internet connection? Could be more to do with internet connection or browser than with the file itself.

**Comment by zmnv** [comment]
@kylegrover

Can you provide your codec settings? Resolution and bitrate please?

Sorry I forgot to say my video's props:

1. Resolution: 3840x2160 (does it supported? I can see my video in a preview and play it. everything is fine.)
2. Bitrate: i tried aroud 10 000 kbit/s. 
3. codec: I've tried h.264 AVC and HEVC and dont have any problems anywhere to play it.

I have a bad situation only when press 'mint' and see infinit 'preparing' text.

Google Chrome 90.0.4430.212 
windows 10

**Comment by zmnv** [comment]
I've  tried MPEG4 and... it doesnt preview...

![image](https://user-images.githubusercontent.com/25253501/119825019-34ff0c00-beff-11eb-93de-a25e00bf76d9.png)

**Comment by violetforest** [comment]
have you tried an mp4? this is what i usually use @zmnv

**Comment by sodomstar** [comment]
Same problem for me.I cant upload my video. I see «preparing OBJKT» and nothing happens.

**Comment by zmnv** [comment]
I've tried mp4. mov. avc. hevc. h264. mpeg4. ITS ALL WORKS in my browser and other browsers I've checked this and it's works.

the **uploading** doesn't work for my file.

Can you check is any country blocked or something?... I have no problems when upload and play my video to IPFS directly without hic.

**Comment by kylegrover** [comment]
Yeah I don't think it's the video codec. All I can recommend is trying to isolate factors. Can you successfully mint smaller videos? Can you mint images, small or of the same size? Is there any other internet connection or devices you can try? (You can mint from a second account and/or burn after minting to do tests)

**Comment by zmnv** [comment]
@sodomstar try to connect a some VPN service first and then try to upload again. did you try it? 

I can mint my video only from another computer with vpn enabled...... I think this is a some connection issue....

**Comment by sodomstar** [comment]
I can uploaded the video but I can't get preview on some mobile devices.

and I use H264

**Comment by zmnv** [comment]
it was not a actually a internet provider connection issue because it always mints on mac and not mint in windows for me....

**Comment by violetforest** [comment]
@zmnv there have been a lot of infrastructure changes, im going to close this for now
