### ISSUE TITLE
GALLEON VERIFICATION ISSUE

### ISSUE THREAD

**Issue by mrmitchy1211** [hicetnunc2000/hicetnunc#677]
**Describe the bug**
Every time I go to mint an NFT on the site I continue getting a verification error.  "Could not estimate fee due to operation validation failure."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 

**Additional context**
Wallet Address
tz1bmWibYwmyb8thM1jujafY7GGBHGUNMzzk

**Comment by skenaja** [comment]
That wallet address has a successfully minted OBJKT:
https://www.hicetnunc.xyz/objkt/72834

Temple & Kukai wallets both allow you to increase the estimated fees, which helps avoid problems during busy blockchain periods when wallets have more trouble carrying out estimating. Both wallets allow you to import the seed phrase from your existing tz1 address so no need to transfer tokens between the wallets

https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#wallet-errors

**Comment by mrmitchy1211** [comment]
I don't see any way to increase the fee on temple.  Even while following
the guides, I never get the option to choose when the temple pop up comes
up.

**Comment by mrmitchy1211** [comment]
This is what the translation data looks like.

[ { "destination": "KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9", "kind":
"transaction", "amount": 0, "parameters": { "entrypoint": "curate",
"value": { "prim": "Pair", "args": [ { "int": "5479" }, { "int": "73019" }
] } } } ]


M I T C H  M Y E R S

ART DIRECTOR | MOTION DESIGNER | 3D ARTIST

-  MOTION REEL  - <https://www.mitchmyers.tv/reel19/>

P. 636.627.1225     E. ***@***.***

WEBSITE <http://mitchmyers.tv/>  |  VIMEO
<https://vimeo.com/mitchmyersdesign>  |  TWITTER
<https://twitter.com/MrMitchMyers>  |  INSTAGRAM
<https://instagram.com/mrmitchmyers/> | BEHANCE
<https://www.behance.net/mitchmyersofficial> | FACEBOOK
<https://www.facebook.com/mitchmyersofficial/>

**Comment by skenaja** [comment]
Thanks, that's helpful! The button you're trying to press is to upvote an artwork using hDAO tokens. It will give an error if you don't have any. For more info: https://github.com/hicetnunc2000/hicetnunc/wiki/hDAO#what-are-those-little-circles-on-each-post-hdao-what-is-that

**Comment by mrmitchy1211** [comment]
Oh!  Well how do I curate an nft that was uploaded?


M I T C H  M Y E R S

ART DIRECTOR | MOTION DESIGNER | 3D ARTIST

-  MOTION REEL  - <https://www.mitchmyers.tv/reel19/>

P. 636.627.1225     E. ***@***.***

WEBSITE <http://mitchmyers.tv/>  |  VIMEO
<https://vimeo.com/mitchmyersdesign>  |  TWITTER
<https://twitter.com/MrMitchMyers>  |  INSTAGRAM
<https://instagram.com/mrmitchmyers/> | BEHANCE
<https://www.behance.net/mitchmyersofficial> | FACEBOOK
<https://www.facebook.com/mitchmyersofficial/>
