### ISSUE TITLE
Cannot load my assets page

### ISSUE THREAD

**Issue by driangle** [hicetnunc2000/hicetnunc#68]
For some reason when I try to load my "manage assets" page, or even if I navigate to my profile by clicking the "issuer" link on one of my objkts, the page never loads.

Here is a link to my page: https://hicetnunc.xyz/tz/tz1hkZdm9r2L6N77hXuK34PDCwQHHGK38jDj

In the JS console I see:

```
main.593a534b.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'creators' of undefined
    at main.593a534b.chunk.js:1
    at Array.filter (<anonymous>)
    at main.593a534b.chunk.js:1
    at c (2.d4d37d05.chunk.js:2)
    at Generator._invoke (2.d4d37d05.chunk.js:2)
    at Generator.next (2.d4d37d05.chunk.js:2)
    at n (2.d4d37d05.chunk.js:2)
    at s (2.d4d37d05.chunk.js:2)
    at 2.d4d37d05.chunk.js:2
    at new Promise (<anonymous>)
```
I inspected the objects that are printed before this error and one of them looked suspicious. It did not have a `token_info` field like the others:
```
{
    amount: 9
    contract: "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
    level: 1377509
    name: "Unknown"
    network: "mainnet"
    supply: 0
    tk_id: 2862
    token_id: 2862
    transfered: 0
    tz: "tz1hkZdm9r2L6N77hXuK34PDCwQHHGK38jDj"
}
```

I tried first syncing and then loading, as well as going to my page using incognito mode. Same results. Other people's profiles seem to load just fine.

Thanks, really appreciate you making this site.

**Comment by andrevenancio** [comment]
I've seen this error before. I'll try to figure out why it happens. but it seems like some NFT's arent coming with some properties @crzypatchwork . I wonder if this was an API change, where some old NFT have properties that don't exist?

**Comment by andrevenancio** [comment]
I've added a feature that will allow us to sanitize objkt that are broken. Excluding them from the feed, and also displaying an error message if they're dont have the necessary properties. Like this particular example, is missing `token_info`.
