### ISSUE TITLE
Still experiencing issue #490: pdfs automatically/unexpectedly download

### ISSUE THREAD

**Issue by Dsm0** [hicetnunc2000/hicetnunc#682]
I'm still experiencing issue #490, where pdfs download open automatically on load.

To reproduce: 
go to any gallery/profile with a pdf, and it downloads automatically:
ex: [https://www.hicetnunc.xyz/tz/tz28W6Vjx4dM8bTNZs1Eq7EFQ9tgs9EF5qFu](https://www.hicetnunc.xyz/tz/tz28W6Vjx4dM8bTNZs1Eq7EFQ9tgs9EF5qFu)

Expected behavior: 
the pdf should not be automatically downloaded

copy of the original issue:
On some browsers, e.g. Android and Fire on macs, when you open a profile page with minted PDF files, the PDF gets downloaded automatically on a new window.

Platform:
Firefox version 88.0.1
(on Manjaro version 20.2.1)

**Comment by andrevenancio** [comment]
I'm sorry, I can't reproduce this. There's nothing on our end forcing a download. this are browser specific user preferences.

https://www.computerhope.com/issues/ch001114.htm#:~:text=On%20the%20Settings%20window%2C%20under,click%20the%20PDF%20documents%20option.&text=position.,browser%20when%20set%20to%20Off.
