### ISSUE TITLE
Main page gallery and collection not loading

### ISSUE THREAD

**Issue by nikostumpo** [hicetnunc2000/hicetnunc#683]
**Describe the bug**
Hello, I try to simply load my page to try to load the gallery or the collection and it does not load. This affects the objkt listing too, cause after minting I can't manage my files because I can't load the page. If the link is to a direct objkt than that specific page loads .

I asked around and others have the same issues.
Thank you

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by oldominion** [comment]
Seems to be happening with a number of galleries at the moment. 

e.g. jjjjjjjjjohn's profile.. https://www.hicetnunc.xyz/tz/tz1gqaKjfQBhUMCE6LhbkpuittRiWv5Z6w38
Fails to load: 
https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/tz?tz=tz1gqaKjfQBhUMCE6LhbkpuittRiWv5Z6w38
`Error: Request failed with status code 500
    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by crzypatchwork** [comment]
we're working on a database for bringing stability to more persistent data. ETA next week
