### ISSUE TITLE
problem with displaying the object on the mainpage

### ISSUE THREAD

**Issue by ashatheo** [hicetnunc2000/hicetnunc#686]
hi, after I mint a new object, it is displayed on the mainpage, after I expose the swap it disappears. I have a very large collection of 1000 objects. how many hdao do I need so that the objects do not disappear from the main page?

I noticed that recently more and more accounts without verification and hdao get to the main page. some kind of bug or new conditions?

**Comment by ashatheo** [comment]
yesterday this issue was partially resolved, the object gets on the main page and then disappears.


https://www.hicetnunc.xyz/tz/tz1ZaX1MkLJsrUtfc1fpHbg4bRTVbF7mnH39

**Comment by makeitrad** [comment]
I to am experiencing this issue. After mint nothing shows up on the home page. After swap nothing either. :(

**Comment by andrevenancio** [comment]
On the wiki there's an explanation on why works don't show on the main feed. TLDR, if you don't have hDao and aren't verified you won't show up on the feed. If you do have hDao and are verified you have a limit of NFT's you can mint. These measures were brought it to avoid copyminters and bots. Please have a look through it.

**Comment by makeitrad** [comment]
I have hDAO and I am verified. Most users being displayed on the feed are verified but have no hDAO. I mint once a day wich should keep me under the limit. Ive read the wiki and I am in complience. There is some other issue at play.
  

  
Thank you   
  
  
  
  
    
  

  
  
>

**Comment by makeitrad** [comment]
Here are a couple examples. 

Wallet "tz1dAVKwbGe1PVnPBkRZYmYFsecDtTLHjHLK" just posted their work. 
OBJKT#78691
It's on the home page. They have no hDAO in their wallet.

wallet "tz1RkzwUDxY7XYX7wk3fERukJzBiDjCDCUhq" on the home page. No hDAO...
OBJKT#78690

**Comment by skenaja** [comment]
@andrevenancio @taconugget  - this will be fixed when these 2 PRs are merged & deployed which specifically cover the hDAO issue

https://github.com/hicetnunc2000/hicetnunc-api/pull/72
https://github.com/hicetnunc2000/hicetnunc-api/pull/71

Before the deployment, there's still some testing undergoing on the API to try to resolve the intermittent blocking of large collections (via /tz pages)

**Comment by makeitrad** [comment]
@skenaja Thanks for the update! Glad I wasn't crazy!!! Keep up the good work you guys/gals are killing it! :)

**Comment by andrevenancio** [comment]
Good to know. I wasn't aware the API stopped working as it should so I made the assumption they had no hDao.
