### ISSUE TITLE
No sound for video on detail page

### ISSUE THREAD

**Issue by driangle** [hicetnunc2000/hicetnunc#69]
I made an NFT of a video, however the sound is not playing on its detail page.

This is the page: https://hicetnunc.xyz/objkt/2676

When I navigate to the video asset itself on IPFS the sound does play. 

https://bafybeieumwrszw2xsmsedawrxqdufnoi55ubpze77aqb2rtuiffnhbuuze.ipfs.dweb.link/

Is this intentional? or should the sound be playing on the detail page?

**Comment by andrevenancio** [comment]
My bad!

My suggestion, when a video is in line with other content (like on the feed) its muted. Once the user opens it, it can play.

There's only one catch. I don't think it's possible to do autoplay on mobile (iOS) when a video has sound. So this means on mobile we need to choose between autoplaying the video on mute or having sound and not auto play.

@crzypatchwork @djangobits thoughts?

**Comment by andrevenancio** [comment]
video player starts mutted but you can unmute it using the video controls.
