### ISSUE TITLE
image scale template problem (unresolved merge conflict?)

### ISSUE THREAD

**Issue by memoakten** [hicetnunc2000/hicetnunc#691]
The image scale template seems to have an unresolved merge conflict from what I can tell? This is src/app.js

```
<<<<<<< HEAD
import React, { Component } from "react"
import { TransformComponent, TransformWrapper } from "react-zoom-pan-pinch"
import example_img from "url:./large.jpg"
=======
import React, { Component } from 'react'
import { TransformComponent, TransformWrapper } from 'react-zoom-pan-pinch'
import example_img from 'url:./large.jpg'
>>>>>>> main
```

**Comment by andrevenancio** [comment]
Thanks @memo! I'll have a look

**Comment by memoakten** [comment]
btw, I was just looking into this because I have some very large (16384x16384 pixel images :), and because my images are soo large, a tiled based interface might be more suitable?
I had previously implemented this ( http://memo.tv/supergan/ ) using https://openseadragon.github.io/ 
Does this template do that too? Or does it load the full resolution image and perform pan/zoom on that?

**Comment by andrevenancio** [comment]
took me a while! Apologies. this should now be fixed!

**Comment by andrevenancio** [comment]
Yeah it works like that! should be enough for your use case. Let me know if you get stuck and I can help with anything.

**Comment by memoakten** [comment]
Thanks Andre, that sounds perfect.

Unfortunately (after a clean pull and npm install), I'm getting the following error (see bottom):
(I could file this as a separate issue?)

```
C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>git pull
Already up to date.

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>git clean -f -d

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>npm version
{
  'image-scale': '1.0.1',
  npm: '7.7.6',
  node: '15.14.0',
  v8: '8.6.395.17-node.28',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k+quic',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>npm install
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 1366 packages, and audited 1367 packages in 57s

134 packages are looking for funding
  run `npm fund` for details

47 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>npm start

> image-scale@1.0.1 start
> parcel ./src/index.html

ℹ Server running at http://localhost:1234
× Build failed.
@parcel/package-manager: Could not find module "@parcel/transformer-image" satisfying 2.0.0-beta.2.
C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale\package.json:16:5
  15 |   "devDependencies": {
> 16 |     "@parcel/transformer-image": "^2.0.0-beta.2"
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.
  17 |   }
  18 | }

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>npm run build

> image-scale@1.0.1 build
> parcel build ./src/index.html

× Build failed.
@parcel/package-manager: Could not find module "@parcel/transformer-image" satisfying 2.0.0-beta.2.
C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale\package.json:16:5
  15 |   "devDependencies": {
> 16 |     "@parcel/transformer-image": "^2.0.0-beta.2"
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.
  17 |   }
  18 | }

C:\Users\memoa\Downloads\hicetnunc\templates\html-image-scale>
```

**Comment by skenaja** [comment]
Is this discussion relevant? https://github.com/parcel-bundler/parcel/discussions/6163

`transformer-image` might need to be installed separately

**Comment by memoakten** [comment]
Hey, thanks. It might be related, but I'm not sure.

- the error linked to above is `Cannot find Parcel plugin "@parcel/transformer-image"`, whereas the error I'm getting is `Could not find module "@parcel/transformer-image" satisfying 2.0.0-beta.2. [...] **Found this conflicting local requirement.**` (emphasis mine).
- I have no experience with parcel-builder or nodejs, so I'm not sure exactly how to 'install transformer-image' separately. 
   - `npm install transformer-image` didn't work :)
   -  I looked it up and found this https://v2.parceljs.org/recipes/image/ which implies it needs to be installed with `npm install sharp -D`? But I get the same error after running that (`conflicting local requirement`).

**Comment by skenaja** [comment]
I managed to get it to build OK by deleting the entire `devDependencies` entry from package.json. Running `npm start` then made `parcel` automatically download and install the package.

https://stackoverflow.com/questions/66719932/what-is-the-correct-version-of-transformer-image-to-use-with-parcel-2

**Comment by memoakten** [comment]
thanks, yes interestingly that worked for me too, but the entire `devDependencies `entry is added back into `package.json`, exactly as it was before.

**Comment by skenaja** [comment]
It also creates a package-lock.json - maybe this should also be checked into the repo?

**Comment by andrevenancio** [comment]
that sometimes happens to me too. I guess parcel is struggling. I've substituted parcel with webpack.

Please run this from the `templates/html-image-scale` folder

```bash
rm -rf package-lock.json node_modules && npm install
```

To run localhost `npm start` and to build a bundle `npm run build`.

Hope it helps!
