### ISSUE TITLE
hDAO reclaim amount display issues

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc#703]
**Describe the bug**
2 small issues with the new claim_hDAO feature on OBJKT page for creators, raised via Discord
https://discord.com/channels/759930487946215444/837237944208326667/843508469080391691

1. If the API doesn't return a value, the UI shows `-1`:

![image](https://user-images.githubusercontent.com/510285/118404405-a79ffa00-b66a-11eb-9e7c-685e8b3851fb.png)

2 - The UI shows the value in microtez, not tez

![image](https://user-images.githubusercontent.com/510285/118404390-9ce56500-b66a-11eb-87b0-cd4948315543.png)

Expected behaviour:

1. make the button behave as if the objkt has 0 hdao (so default behaviour)
2. divide the amount by 1,000,000 (as per user profile page)

**Comment by skenaja** [comment]
1) upstream API errors were simulated by forcing it [to always return -1 here](https://github.com/hicetnunc2000/hicetnunc-api/blob/master/lib/utils.js#L128)

2) Units now in whole hDAO:
![image](https://user-images.githubusercontent.com/510285/118513569-bf8b8280-b72b-11eb-8760-e03d7289a551.png)

Just to note If you're not the creator, the UI is still a little confusing as it displays the hDAO balance, but still no visual cue what the curate amt will be or what the value means. Users are reporting that it reflects the price to pay for an object, or the button to press for swapping it.

**Comment by andrevenancio** [comment]
> 1. upstream API errors were simulated by forcing it [to always return -1 here](https://github.com/hicetnunc2000/hicetnunc-api/blob/master/lib/utils.js#L128)
> 2. Units now in whole hDAO:
>    ![image](https://user-images.githubusercontent.com/510285/118513569-bf8b8280-b72b-11eb-8760-e03d7289a551.png)
> 
> Just to note If you're not the creator, the UI is still a little confusing as it displays the hDAO balance, but still no visual cue what the curate amt will be or what the value means. Users are reporting that it reflects the price to pay for an object, or the button to press for swapping it.

I dont think the current solution serves the UX properly. Its confusing without context that the same button changes behaviour from "donating" hDAO to "collecting" hDAO.
this part should be revise in the design. I've asked Julio (Designer) to have a look at this.
