### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by clngr** [hicetnunc2000/hicetnunc#704]
The website could automatically switch to dark mode by detecting the system's color theme. Details in:

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Also, a manual override switch dark/light would be welcome, as we can see on a growing number of websites.

1. This could be a standard in every Tezos website
2. Every Tezos related website should follow the same standards/guidelines on its composition

**Comment by skenaja** [comment]
Thanks for the suggestion!

The `prefers-color-scheme` setting was implemented in 02a546e02f1825ded5940cb4bca12b6a8d2e08df

There is a manual override already in place - click menu, then the `o` button in the footer. Not very obvious perhaps!

**Comment by clngr** [comment]
Some issue with my test browser. Thank you.
