### ISSUE TITLE
(http 410) Object is restricted and/or from a copyminter

### ISSUE THREAD

**Issue by mirsadbasar** [hicetnunc2000/hicetnunc#711]
Bought a 'Nft' couple weeks ago. 2-3 days after i bought it, the adress became unreachable, just a blank HEN screen. And i checked it right now and now it says '(http 410) Object is restricted and/or from a copyminter'. 
https://www.hicetnunc.xyz/objkt/59130 You can see it yourself too.

Did anyone had something like that before? I paid some tez for this piece and now i dont know what to do.
![image](https://user-images.githubusercontent.com/83849854/118545731-a6042e00-b75f-11eb-8624-d0a06af4e58c.png)
It can be seen at:
https://objkt.xyz/59130

Desktop 
 - OS: Windows
 - Browser: Chrome, Opera

My wallet address: tz1NzUCqmUr5aKmGZvyGqppjoJqCsYXAbszW

**Comment by skenaja** [comment]
Hi, the wallet you purchased it from was reported as a copyminter (they did not create the artwork nor have the rights to sell the NFTs). The wallet was banned once it was reported to the the moderator team on Discord. Unfortunately, the platform has no way to recover any funds already sent. 

Relevant warnings are provided to collectors here: https://github.com/hicetnunc2000/hicetnunc/wiki/Beware-copyminters!
