### ISSUE TITLE
Interactive 3D model no longer showing textures/lighting

### ISSUE THREAD

**Issue by KimLaughton** [hicetnunc2000/hicetnunc#717]
The .glb files I have uploaded used to display fine but now they show up as black shapes - either a texture or a lighting issue I'd imagine. 

For eg: https://www.hicetnunc.xyz/objkt/37744

Other people's models seem to be ok so it could be a issue that only crops up when the models are exported in a certain way. I'm using the babylon exporter with 3DS Max.

I've attached the .glb used in the above link.

[Possession 7.zip](https://github.com/hicetnunc2000/hicetnunc/files/6508156/Possession.7.zip)

**Comment by mrdoob** [comment]
Damn... Kim Laughton 😮
Sorry about that. We're looking into it.

**Comment by andrevenancio** [comment]
reverted back to version 1.6.0. Awaiting deployment from @crzypatchwork. will revert back to newest version as soon as a patch becomes available from google model-viewer. Closing for now.

**Comment by elalish** [comment]
working on it: https://github.com/google/model-viewer/pull/2411

**Comment by KimLaughton** [comment]
Sorry sorry - delayed response, glad to see it working again!

Not a big deal in this case of course, but I can see that it gets tricky in the NFT future with viewers for more complex formats changing and losing backward compatibility.
