### ISSUE TITLE
FAQ: add https://hicetnunc.tools to wiki/Tools-made-by-the-community

### ISSUE THREAD

**Issue by Pamicel** [hicetnunc2000/hicetnunc#721]
**Summary of change to FAQs you wish to make:**
* Adding https://hicetnunc.tools to the list of tools as "hicetnunc.tools : handy urls for tools"

**Comment by kylegrover** [comment]
I tried to fork the git wiki but apparently that's not really a thing. Anyway here's the markdown for someone with access to add:
`* [hicetnunc.tools](https://hicetnunc.tools) An unofficial list of community hicetnunc projects`

I was also going to add my swaps tool under selling tools if that h=n feature isn't live yet:
`* [hicettum/swaps](https://ufffd.com/hicettum/swaps) by �: View your pending swaps.`

**Comment by violetforest** [comment]
added to "discover tools", thanks guys!
