### ISSUE TITLE
I dont know where else to go for help. I've posted in the discord and no one seems to know how to help.

### ISSUE THREAD

**Issue by TEMAnfts** [hicetnunc2000/hicetnunc#724]
Somone attacked me as a copyminter.

I minted an OBJKT that was a remix/reimagination of another NFT. However mine was:
1. Color Shifted from Green to Purple
2. Rotation of OBJKT was completely REVERSED,
3. Audio was added, the original had none.
4. The original minter said I could do it, I have screenshots of our convo, as long as I didnt make it seem like a collab.
5.  SO I literally put "stolen, derived and minted from the "name of person"

SOME collector of the original reported me and my work on the discord. This is the only piece up there thats a remix. and the other piece i had up there was 100 percent original work that i had 3 collectors on already and was my first mint. I'VE also become a collector on HEN and have a growing collection. i also own a weebit of the hDAO.

I was given to no notice. no one reached out. and now my wallet doesnt even show the objkts i made. they're gone. did they get stolen and burned from my wallet? I thought HEN wasnt supposed to censor this hard.

**Screenshots of the important part of our convo** He didn;t say dont do it. Just dont make it look like a collab.
https://photos.app.goo.gl/gFVmsRAUMChNz9ue9

here's my public temple wallet address: 
tz1NVnCackN4pN7KnCCHuQbuDaKWNa5M9ix5

**Comment by skenaja** [comment]
This is being resolved via dialogue in Discord.
