### ISSUE TITLE
(http 410) Object is restricted and/or from a copyminter

### ISSUE THREAD

**Issue by f1nasf1** [hicetnunc2000/hicetnunc#726]
**Describe the bug**
I own this item https://www.hicetnunc.xyz/objkt/13340, however, when I try to access it I get the following error: (http 410) Object is restricted and/or from a copyminter

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/13340
4. See error: (http 410) Object is restricted and/or from a copyminter

**Expected behavior**
Before I can see this item. I listed it for sale. Now I can't remember what it was.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**
Wallet: tz1fFCF6FogyPLLjSk3FNTG7gVdDWfPCWVni
Object: https://www.hicetnunc.xyz/objkt/13340

**Comment by mtyka** [comment]
Unfortunately this objkt was a copymint and not from the original artist. The copyminting account that minted it 
(https://www.hicetnunc.xyz/tz/tz1X1QzFdfAtzCF7E4UjnGSSFU1ADoXBRhSf) has been banned as have all their copymints.
This is the image the objkt pointed to : https://cloudflare-ipfs.com/ipfs/QmXvcmCBcBc7pAZ1oUHuZCR5fsnFZix1SrYUK9jZ4L6hLE
