### ISSUE TITLE
Video display

### ISSUE THREAD

**Issue by erasta** [hicetnunc2000/hicetnunc#73]
Uploaded asset MOV video file.
On the asset page it is viewed correctly:
https://www.hicetnunc.xyz/objkt/3353
On the main list and on my assets the view is **broken**:
https://www.hicetnunc.xyz/tz/tz1NP8RmKh1nJWkWjrL2DqXMpcRX2BJb78a4
Are there limitations to the video formats?
Thank you
<img width="462" alt="Screen Shot 2021-03-10 at 12 40 06 PM" src="https://user-images.githubusercontent.com/7118772/110616902-c206b480-819d-11eb-90a4-28a318646a16.png">

**Comment by erasta** [comment]
Looked a bit and seems like the video is treated as an image:
<img width="403" alt="Screen Shot 2021-03-10 at 1 14 02 PM" src="https://user-images.githubusercontent.com/7118772/110621157-8e7a5900-81a2-11eb-87c2-770689dee4b4.png">

**Comment by andrevenancio** [comment]
You should be able to see your video on the NFT detail page right?

We're doing some code refactor and it seems like on the feed and on the user profile all videos that aren't mp4 default into an image. This is a known bug it's on our todo list. We'll try to get fixed today.

**Comment by erasta** [comment]
on the NFT detail page it looks good.
Probably becaue there it's shown as a `<video>` tag
https://www.hicetnunc.xyz/objkt/3353
Thanks a lot for your help
<img width="468" alt="Screen Shot 2021-03-10 at 1 34 06 PM" src="https://user-images.githubusercontent.com/7118772/110623333-60e2df00-81a5-11eb-98d8-7003102c2980.png">

**Comment by andrevenancio** [comment]
Yeah this will be fixed tonight. I'm refactoring the feed page and the user page.

**Comment by andrevenancio** [comment]
This should be fixed now
