### ISSUE TITLE
why my nft stuck at "preparing OBJKT"

### ISSUE THREAD

**Issue by rawlikesushix** [hicetnunc2000/hicetnunc#730]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by andrevenancio** [comment]
Please provide actual feedback beyond the title.
