### ISSUE TITLE
FAQ: Add hicetnunc-radio to the Tools made by the community

### ISSUE THREAD

**Issue by lauzaki** [hicetnunc2000/hicetnunc#734]
**Summary of change to FAQs you wish to make:**

Add HEN Radio to the Tools made by the community page

**Text change**

HEN radio: A simple OBJKT audio player By working group 7.2 with @__orderandchaos , during the first Hicathon. Supports MP3, WAV, and OGG. Can be embedded into any websites.

**Comment by violetforest** [comment]
hey @lauzaki do you have the link?

**Comment by MikeiLL** [comment]
I'd like to see this as well. Not finding it via search engine.

**Comment by violetforest** [comment]
done

**Comment by MikeiLL** [comment]
Here it is https://github.com/OrderAndCh4oS/hicetnunc-radio
