### ISSUE TITLE
Hello, can someone help me with the following: when entering my gallery, I only see 4 creations of the 20 that I have

### ISSUE THREAD

**Issue by felipelopezv1** [hicetnunc2000/hicetnunc#735]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
https://twitter.com/hicetnunc2000/status/1396516829208719366?s=20 There was a temporary quick fix that went out about 30 minutes ago to address a serious issue we were having. Some of your OBJKTs might be missing from your creations page but they should still be available in your wallet. We will fix the issue of missing OBJKTS from your creation ASAP. Thank you for your patience :pray:

**Comment by felipelopezv1** [comment]
Muchas gracias , ya esta ok.

Felipe

**Comment by felipelopezv1** [comment]
Hi Violet, I've been doing the steps to customize my profile, photo, name
and twitter for more than 5. days, but there are still no changes, can you
please help me
gracias
Felipe https://www.hicetnunc.xyz/tz/tz2K7ZBbBQ9CBZqdTM5GzMPSASXaQZKbmkQx

Hola Violet,
Hace ya mas de 5. días que realice los pasos para personalizar mi perfil,
foto, nombre y twitter.Pero ahun no hay cambios, puedes ayudarme por favor

**Comment by felipelopezv1** [comment]
Hola, no puedo realizar operaciones de compra ni venta ni nada
https://www.hicetnunc.xyz/tz/tz2K7ZBbBQ9CBZqdTM5GzMPSASXaQZKbmkQx

gracias
