### ISSUE TITLE
My NFT artwork is Disappeared.

### ISSUE THREAD

**Issue by Taezoo** [hicetnunc2000/hicetnunc#737]
Hi Hic et Nunc,

Around one hour ago, I found my NFT artwork is disappeared on your platform. 
I don't know what's going on.

Here is my screen shot, my wallet and page address.
<img width="1060" alt="Screen Shot 2021-05-23 at 1 24 53 PM" src="https://user-images.githubusercontent.com/84681000/119272056-3617fc80-bbd2-11eb-8009-c7c364844b57.png">
Wallet address: tz1Pbpx6455DGPJ1vAfRWgL7cn2BsQ12Zd1r
Page address: https://www.hicetnunc.xyz/tz/tz1Pbpx6455DGPJ1vAfRWgL7cn2BsQ12Zd1r

There were 2 artworks. Each one has 12 editions, and I have started a promotion through twitter and my instagram (https://www.instagram.com/p/CPJ5r38Bp-l/) one day ago.

Please please let me know the reason and when I can get them back.

-Taezoo

**Comment by 2o2es** [comment]
Same issue. I have minted 2 OBJKTs and today neither of them appear under my "creations" tab:
https://www.hicetnunc.xyz/tz/tz1LNVymUKpP8boRCKT7hrEUPAUL13C1K63b

![image](https://user-images.githubusercontent.com/84680934/119273100-526a6800-bbd7-11eb-927c-b33565c25334.png)

The individual OBJKT links still work: 
https://www.hicetnunc.xyz/objkt/92562
https://www.hicetnunc.xyz/objkt/93966

but they do not appear in my profile.

**Comment by violetforest** [comment]
https://twitter.com/hicetnunc2000/status/1396516829208719366?s=20 There was a temporary quick fix that went out about 30 minutes ago to address a serious issue we were having. Some of your OBJKTs might be missing from your creations page but they should still be available in your wallet. We will fix the issue of missing OBJKTS from your creation ASAP. Thank you for your patience :pray:

**Comment by JamDevCore** [comment]
An NFT of mine went completely missing via hicetnunc - I thought maybe it sold but nothing came but but I can see a transfer in the blockchain to hicecnunc but I didn't make this transfer

**Comment by Jryadyr** [comment]
Hi Hic et Nunc,

Since last night, I found my NFT artwork is disappeared on your platform.
I don't know what's going on. I cannot access my artwork on the Creations in the Manage Assets folder. It's just gone. here I attached the screenshots.
![image](https://user-images.githubusercontent.com/88422988/128134433-0b0760a6-280d-4f3f-b924-9e77b238335e.png)

please kindly fix and advise.

Here's my Address
https://www.hicetnunc.xyz/tz/tz1WRP8Py94HxUnor8iRYS3xnTwLnd1vjjd2/creations

Thank You

**Comment by CSEEEE** [comment]
I am also having this issue. Please assist! 

https://www.hicetnunc.xyz/tz/tz1TsUHtiL52A2j9MTapS32KoX6BY1SC5w9v/creations

**Comment by arch-luke** [comment]
Hey I'm having the same issue minted earlier and was showing up (objkt 282905), but is now no longer appearing.

**Comment by violetforest** [comment]
@CSEEEE what issue are you having? do you have an objkt #?

@arch-luke I see the objkt, I'm not quite sure what the problem is

**Comment by violetforest** [comment]
@CSEEEE 

@arch-luke

I'm going to close this issue but I will continue assisting you, so more people don't piggyback off this issue which lacks details.

**Comment by anandhika** [comment]
I'm also have the same issue. I can't access Creations, it's all gone.

objkt/332963

objkt/329346

 Please assist.

**Comment by anandhika** [comment]
![Uploading 20210922_023210.jpg…]()

**Comment by anandhika** [comment]
![20210922_023210](https://user-images.githubusercontent.com/91156432/134236572-7f4fcbec-77e6-4b53-9976-48b7ef34d222.jpg)

**Comment by diegolazzarin** [comment]
Same trouble here!
https://www.hicetnunc.xyz/diego_lazzarin/creations

**Comment by diegolazzarin** [comment]
I had two creations and they completely disappeared... please help.
https://www.hicetnunc.xyz/objkt/334648
https://www.hicetnunc.xyz/objkt/320799

**Comment by tiborsaas** [comment]
Same stuff happened to me. Only those disappeared that I listed for swap. 

https://tzkt.io/oorAQyQqXYtzce9Jnop5yQP9cnfHfkmZnoorAYre9r3SqTcx8GA

**Comment by ileogivel** [comment]
Hey wassup, yesterday i minted and swapped a NFT (OBJKT#336797). and i tried to check today but they completely disappeared. 🌵

**Comment by sydbrz** [comment]
I have the same problem here https://www.hicetnunc.xyz/objkt/333712 I minted yesterday and it disappeared today. I tried to mint another objkt, it was successful but neither the new one nor the other one are showing.

**Comment by valardss** [comment]
Hello, i have the same problem here. I minted yesterday, and today its gone. heres my link objkt https://www.hicetnunc.xyz/objkt/338090
and heres my page link : https://www.hicetnunc.xyz/valard.ss/creations
and my collection is dissapeared too. Please help

**Comment by diegolazzarin** [comment]
Hello, the 2 objkts reappeared in my creations but they were both sold out and now they are still available for trade... apparently the history has been deleted. I have people who got them asking me what happened to their objkt...
Please help!

**Comment by diegolazzarin** [comment]
Looks like is ok now! 👍  Thanks!

**Comment by elsinory** [comment]
Same issue. Help, pleas
I have minted 3 OBJKTs and today neither of them appear under my "creations" tab:
https://www.hicetnunc.xyz/tz/tz1hDDLg41bkhrXq6JL226DQappL7xH9qVZN/creations
tz1hDDLg41bkhrXq6JL226DQappL7xH9qVZN
27881735
27881734
27881732
![image](https://user-images.githubusercontent.com/91197976/134343563-14ac43c8-2055-4285-98e3-270fe4887971.png)

**Comment by elsinory** [comment]
Thank u a lot!

**Comment by Audivit** [comment]
Same issue. Please help me!
tz1LS1dCsovb875VXwaqwNr5Dq8i9CNafJHP
https://www.hicetnunc.xyz/objkt/356182

**Comment by crypticxyz** [comment]
could you help me please 
i minted my artwork 3 times and it doesn't show on my creations page
i am also filming this for a tutorial - really embarassing pls fix
this is the txn id https://tzkt.io/ooB3azzGhjfHSnx2ZNzxtVGvXFAjLMdLrUTLZDUcv8dYR23dwA8

**Comment by crypticxyz** [comment]
https://tzkt.io/ooB3azzGhjfHSnx2ZNzxtVGvXFAjLMdLrUTLZDUcv8dYR23dwA8

https://tzkt.io/ooAaPHoXu8k5q55K6B7BKRfzBj6ZkrHxCevZDWeNTy3L2WPpxUB

https://tzkt.io/opMkZoWxYofm1zzMg9Gjyj7gzqtopqtY74QsCGoMq5wgiK6AbxY

**Comment by yusufziyaunel** [comment]
This OBJKT is disappeared. help
https://www.hicetnunc.xyz/objkt/373120

**Comment by violetforest** [comment]
Please go into the Discord in the #help-channel to get help with your objkt
https://discord.gg/Yx6UN5SkCd

There are more people actively there from the HEN team to assist you
