### ISSUE TITLE
Improve performance: laggy or freezing because objkt previews

### ISSUE THREAD

**Issue by sosias** [hicetnunc2000/hicetnunc#747]
When I open a collection, the page lags and becomes unresponsive. Sometimes when the objects are heavy or many, the whole browser freezes.

This is because all objects are loaded in full size and gifs and videos are played at the same time. A good solution would be to show only a thumbnail and play the animation on hover. Or add an enable/disable button to choose if you want to see the thumbnails or the animations.

Is anyone already working on this solution?

:)

**Comment by andrevenancio** [comment]
There's been a lot of work in the last couple of weeks towards this. Thumbnails need to be generated on old OBJKT and cache layers are being implemented

**Comment by violetforest** [comment]
closing -- this is in development
