### ISSUE TITLE
Failure to detect Temple wallet on Firefox + Windows 10; change suggestion

### ISSUE THREAD

**Issue by earthbound19** [hicetnunc2000/hicetnunc#748]
**Describe the bug**
Under unknown circumstances, Hic et Nunc fails to detect Temple wallet (Firefox addon). Possible path to duplication detailed.

**To Reproduce**
- Install Temple wallet addon with an active (logged in) wallet.
- At Hic et Nunc, click "sync" in the upper right. Maybe this won't work on your first try. But if it does, maybe this will make it not work:
- Log out of Temple
- Open http://www.kukai.app and import the same wallet
- Sync Hic et Nunc to Kukai
- Log out of Kukai, then attempt to sync Hic et Nunc to Temple.

**Expected behavior**
Hic et Nunc should detect Temple wallet as available for pairing and display a button for it.

**Actual behavior**
Hic et Nunc fails to detect Temple wallet as available for pairing, and displays the Temple button as grayed out.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 88.0.1 with container tabs active

**Additional context**
Clearing cache, cookies, logins, history, and offline data, and uninstalling and reinstalling Temple wallet addon did not solve the problem.

Moreover, in my opinion it would be best if Hic et Nunc didn't try to detect available wallets (and possibly fail at that and preclude the user even from attempting to use a wallet). It should just list all possible wallets, and assume the user is smart enough to know which wallet they're using.

At least a few others are experiencing this. Here's a reddit post about it: https://www.reddit.com/r/hicetnunc/comments/mmoemz/hi_i_am_trying_to_sync_temple_wallet_on_hic_et/

**Comment by earthbound19** [comment]
For me, Hic et Nunc also fails to detect Temple wallet on a clean, new install of Chrome + Temple wallet browser extension on Windows 10.

**Comment by earthbound19** [comment]
Until it randomly did just now?! So, intermittent issue. Unreliable enough to be unusable :(

**Comment by skenaja** [comment]
The wallet detection is provided by Beacon, a third-party component. 

This could be a possible cause:
https://github.com/airgap-it/beacon-sdk/issues/137

If you experience this behaviour again, please can you raise a ticket with the Airgap Beacon team? Thanks!

**Comment by earthbound19** [comment]
I may do that, thx.
