### ISSUE TITLE
FAQ: WG 5.7 - Improve Maintenance fees FAQ

### ISSUE THREAD

**Issue by christopheradams** [hicetnunc2000/hicetnunc#752]
**Summary of change to FAQs you wish to make:**

This issue comes from Hicathon WG 5.7 "Where do the fees go?"

* Improve the information in the FAQ about the maintenance fees to increase transparency about how the fees are calculated and where the funds go.
* Add new page `Maintenance-fees.md`

**If it's a new page, which navigation heading does it come under**

Add page "Maintenance fees" under "FAQs" heading in sidebar.

**Text change**
* Replace the entire section of [General#what-is-this-25-fee](https://github.com/hicetnunc2000/hicetnunc/wiki/General#what-is-this-25-fee) with a link to the "Maintenance fees" page. We should keep this section in case there are any other external links to it.

**Markdown**

Text for `Maintenance-fees.md`

```Markdown
## What is this 2.5% fee?
Swaps which carry value are charged a 2.5% fee which goes towards platform maintenance and improvement. The fee is paid by the buyer and deducted from the list price. You should factor this in when setting your prices. Free OBJKTs do not incur a maintenance fee.

For example, if the price of an OBJKT is 10 tez, and royalties are 10%, then at the point of swap, 0.25 tez is paid to the platform in fees, 1 tez is paid to the creator in royalties, and 8.75 tez is paid to the seller of the OBJKT.

The fees are calculated automatically by the [Hic et nunc Minter](https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/operations/) smart contract ([read the source code](https://github.com/hicetnunc2000/objkt-swap)) and paid out to the [hicetnunc2000lab](https://tzkt.io/tz1UBZUkXpKGhYsP5KtzDNqLLchwF4uHrGjw/operations/) wallet. A portion of the collected fees are withdrawn to support operational and development costs of the platform. The remainder is delegated to a community baker which is voted on and governed by the [hDAO](https://github.com/hicetnunc2000/hicetnunc/wiki/hDAO).
```

**Comment by christopheradams** [comment]
@violetforest Can we add the above as a separate wiki page titled "Maintenance Fees" and link to in the sidebar under the FAQs heading?

**Comment by violetforest** [comment]
wiki changes are done, have to do a PR for the faq sidebar

**Comment by violetforest** [comment]
PR done

**Comment by christopheradams** [comment]
Thanks @violetforest!
