### ISSUE TITLE
Storage quota exceeded for the operation

### ISSUE THREAD

**Issue by animanoir** [hicetnunc2000/hicetnunc#758]
**Describe the bug**
I can´t mint a file. 

I was trying to mint a photo with 4160 x 2340 of size, 9mb. Got at first an error saying something like: "Storage quota exceeded for the operation". I tried it again compressing the image and got a [backtracked](https://tzkt.io/op8TeZYfm8LAXtWfxgkxyPF2ggVjueMoaZoWsGVFxD4X7JG1fM4) failure. I tried again and got again the "Storage quota exceeded for the operation". I do have enough tz to pay. 

**To Reproduce**
0. Be me
1. Go to OBJKT minting
2. Try to mint an OBJKT
4. Wait to see the transaction failing.

**Expected behavior**
To mint an OBJKT

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Brave
 - Version [e.g. 22] 1.24.86

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.
tz1UCeiavj9Hz5s7jbwdYYNuhaQRfQv9uxSj

**Comment by violetforest** [comment]
Hey, this is a template wallet issue. Here is some troubleshooting steps: 

https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#help-i-keep-getting-the-backtracked-error-and-im-using-temple-wallet
