### ISSUE TITLE
Loading OBJKT error

### ISSUE THREAD

**Issue by Musikmang65** [hicetnunc2000/hicetnunc#759]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Network error
![image](https://user-images.githubusercontent.com/62971422/119589118-2a7a3080-bda0-11eb-9689-a412361cf000.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 Pro 
 - OS: [e.g. iOS8.1] iOS 14
 - Browser [e.g. stock browser, safari] Safari

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number. XTZ wallet tz2SvgQYvzjzSk3Tk3rSngtDV4mXFK8kxDsM

**Comment by matenji** [comment]
Hello devs, I am also receiving the same error on one my object: https://www.hicetnunc.xyz/objkt/60426

**Comment by AllyAlejandra** [comment]
Hi :) having problem loading OBJKT

![image](https://user-images.githubusercontent.com/84801560/119591011-d6714b00-bda3-11eb-948e-27c48408abbd.png)

**Comment by AllyAlejandra** [comment]
![image](https://user-images.githubusercontent.com/84801560/119591249-48e22b00-bda4-11eb-9227-af6ea750c003.jpeg)

**Comment by AllyAlejandra** [comment]
![image](https://user-images.githubusercontent.com/84801560/119591384-7c24ba00-bda4-11eb-9503-914facf9228b.jpeg)

**Comment by AllyAlejandra** [comment]
1st one
![image](https://user-images.githubusercontent.com/84801560/119592003-a3c85200-bda5-11eb-9ed0-6fb68181b553.png)

**Comment by AllyAlejandra** [comment]
![image](https://user-images.githubusercontent.com/84801560/119593761-88127b00-bda8-11eb-8536-61a3b47da136.jpeg)

**Comment by AllyAlejandra** [comment]
305.850.1525
![image](https://user-images.githubusercontent.com/84801560/119594660-35d25980-bdaa-11eb-8fee-bacd180b3e31.png)

**Comment by AllyAlejandra** [comment]
![image](https://user-images.githubusercontent.com/84801560/119594689-41258500-bdaa-11eb-9164-59768d769f5a.png)

**Comment by AllyAlejandra** [comment]
917.703.0899 
![image](https://user-images.githubusercontent.com/84801560/119595040-e7718a80-bdaa-11eb-8472-bedbb620b808.jpeg)

**Comment by AllyAlejandra** [comment]
![image](https://user-images.githubusercontent.com/84801560/119595058-ee000200-bdaa-11eb-9eb0-43dd7d625dfc.jpeg)

**Comment by jazzcomputer** [comment]
Object not loading here too

https://www.hicetnunc.xyz/objkt/66037

Google Chrome
Version 90.0.4430.212 (Official Build) (x86_64)

Big Sur 11.2.3

**Comment by violetforest** [comment]
This should be fixed, let me know if its not and I will reopen
