### ISSUE TITLE
Problem loading OBJKT

### ISSUE THREAD

**Issue by cindlin** [hicetnunc2000/hicetnunc#761]
I currently own 2 of these objkts and listed 1 for a swap which went through last week, however after checking today noticed my id was not on the collectors section with a current swap order, while still showing I own 2.
I tried to swap again but the transactions did not go through.

https://www.hicetnunc.xyz/objkt/88542

**Comment by mtyka** [comment]
What's your wallet id ?

**Comment by cindlin** [comment]
tz1cxbTVpHuEtdkQWCTnBYAZRPx7tvGBECub

Cindy Lin
***@***.***

**Comment by sodomstar** [comment]
I got same problem!

tz1VxfP7JYR7ANiqfDobivHq88ieJgA4opSY

**Comment by violetforest** [comment]
do you still need help with this? let me know and i will reopen
