### ISSUE TITLE
Cannot navigate to a PDF from a collection page

### ISSUE THREAD

**Issue by christopheradams** [hicetnunc2000/hicetnunc#763]
**Describe the bug**

Since the recent changes that removed the ID overlay from each on a collection page, you can't click on a PDF OBJKT and navigate to its own page.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/tz/tz1LfkiegSFauPXzh4pwsAKC2ddqHgNKy89J
2. You can interact with the PDF but you cannot reach the OBJKT page

**Expected behavior**
You should be able to navigate to https://www.hicetnunc.xyz/objkt/20147

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804
 - Browser: Firefox
 - Version: 88

**Comment by crzypatchwork** [comment]
a hover should be added on every objkt enabling to access the objkt view
