### ISSUE TITLE
FAQ: Discord invitation is out of date, cannot use

### ISSUE THREAD

**Issue by markstock** [hicetnunc2000/hicetnunc#764]
**Summary of change to FAQs you wish to make:**

On "General" page, under "I want to report a copyminter", the link to Discord returns a "Invalid Invite Links" error from Discord.

**Comment by markstock** [comment]
The link on the subreddit is current: https://discord.gg/jKNy6PynPK and the name of the group is #report-copyminters and not #report-abuse, as the FAQ currently states.

**Comment by violetforest** [comment]
updated on reddit and wiki, thanks
