### ISSUE TITLE
Tags do not work

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#765]
**Describe the bug**
I got a blank page and the error below when I try to view a tag.

![image](https://user-images.githubusercontent.com/2965842/119688198-71bffa00-be50-11eb-8fce-b242a2507fe4.png)

**To Reproduce**
1. Click any tag on a post. For example https://www.hicetnunc.xyz/tags/hiceturco

**Comment by crzypatchwork** [comment]
andre some of your commits are bringing issues to the stack. you should reconsider some of these contributions as they are not even tested... while there are some other bugs/fixes of the same genre

**Comment by crzypatchwork** [comment]
I must also say that the use of hooks didn't quite went well in the design of the platform.
