### ISSUE TITLE
inputs missing "name" attribute / no autofill

### ISSUE THREAD

**Issue by kylegrover** [hicetnunc2000/hicetnunc#767]
**Describe the bug**
On the minting page none of the input fields have a 'name' attribute set, resulting in them all defaulting to `name="input-name-not-set"`. As a result of this, the text fields do not remember your previous entries. This is bothersome to users when their mint fails and they lose their description, title, and tags.

**To Reproduce**
Mint an objkt. Return to the mint page and click on an input field. Your browser should show you your previous entries as autofill options, but instead it will show the previous 'title' entries, no matter which input you click on.

**Expected behavior**
Clicking on an input field should show your previous entries as autofill options.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version latest

**Additional context**
[I believe this is the relevant code](https://github.com/hicetnunc2000/hicetnunc/blob/d6fde0bfd6eb37fe01b8497f7bcddff6a41442bc/src/pages/mint/index.js#L257)

**QUESTION:** Is there any reason the fields do not have `name` attributes? Will the form processing logic be affected if I add sensible name attributes to these input elements?

**Comment by andrevenancio** [comment]
@kylegrover would you have time to submit a PR with the proposed change? Looks like its something we should have!
