### ISSUE TITLE
http 410) Object is restricted and/or from a copyminter

### ISSUE THREAD

**Issue by schonschoncrypt** [hicetnunc2000/hicetnunc#771]
*Describe the bug
When I click on the object in my gallery, the following message appears: (http 410) Object is restricted and/or from a copyminter

To Reproduce

Expected behavior
When I click on the object the message above appears

Screenshots
![![image](https://user-images.githubusercontent.com/84883080/119748503-e3487a00-be49-11eb-903a-90e4e96934f6.png)](https://user-images.githubusercontent.com/84883080/119748353-9cf31b00-be49-11eb-9222-6d5f4e4c3187.png)
this is the object in my gallery

This is what I wanted to buy
image

My address is not listed under the collectors:
![image](https://user-images.githubusercontent.com/84883080/119748503-e3487a00-be49-11eb-903a-90e4e96934f6.png)*Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Object number OBJKT#98118

**Comment by kylegrover** [comment]
You must have bought a copymint / counterfeit. People upload john's art a lot and it takes a moment to catch it and take it down. For now it's best to check the wallet that you're purchasing from to see if it's the real one.
