### ISSUE TITLE
Bug report of PDF minted

### ISSUE THREAD

**Issue by lenie-blue** [hicetnunc2000/hicetnunc#778]
![Screenshot_20210528-041928](https://user-images.githubusercontent.com/84947825/119920959-7d551300-bf6d-11eb-8a44-3cebd2060a2d.png)
![unknown](https://user-images.githubusercontent.com/84947825/119920962-7e864000-bf6d-11eb-9154-823c5455728f.png)
![Screenshot_20210528-042710](https://user-images.githubusercontent.com/84947825/119920965-7e864000-bf6d-11eb-8a30-9635c7083ea4.png)

Hi everyone and thanks at the beginning for your responses.
I have minted a PDF of 44 pages with title, description, cover picture and amount. All this details don't coming up to my profil. The PDF only can to be read or downloaded from my profil. The number of this objckt don't appears too. On my phone from my profil address, it appears only with a black square with a automatic download. To swapp isn't possible, the button is not available. However in Kukai, all the informations exist: title, description and cover picture. Some other people have the same bug. My 4G phone and PC connections are very good. I tried many times to mint this ojket and each time during a long moment. What's the problem? 🤔

👉https://www.hicetnunc.xyz/tz/tz1a4cjEPYQZf3FUYPcjWcQqRSmjXmdWuGUp

**Comment by violetforest** [comment]
Hey, are you still having this problem? Do you have the OBJKT number?

**Comment by violetforest** [comment]
I'm going to close thise for now becasue we made a lot of changes to PDF, but if you need help let me know and I will reopen
