### ISSUE TITLE
I can't upload video file

### ISSUE THREAD

**Issue by sodomstar** [hicetnunc2000/hicetnunc#780]
this is a 33mb mp4 video

Uploaded video. Go to preview.
When .mp4 -- I see my video as preview and I can play
Mint
I see **«preparing OBJKT»**

and than nothing happen just stucking forever!

I tried it on another computer and internet connection and another browser.Same situation..

 - OS: Windows10
 - Browser Chrome 
 - Version 91.0.4472.77 

My wallet: tz1VxfP7JYR7ANiqfDobivHq88ieJgA4opSY

**Comment by sodomstar** [comment]
I can uploaded the video but I can't get preview on some mobile devices.

**Comment by violetforest** [comment]
hey, do you have the objkt number? is this still not working for you?

Can you try on a different internet connection?
