### ISSUE TITLE
Problem in (post)minting

### ISSUE THREAD

**Issue by Anshulrawal** [hicetnunc2000/hicetnunc#781]
I submitted my work for minting[Hicetnunc], payment request was received on the wallet (Kukai) and i submitted it. However on the site nothing happened. I checked my [Hicetnunc] profile for my Objkts, nothing seems to appear. 

The minting amount has been deducted. I tried again and same thing happened. Amount has been deducted yet nothing is showing on the mint page or my profile. 

Process that I followed:
1. Enter details of Objkt for minting [Hicetnunc]
2. Review the details[Hicetnunc]
3. Receive payment request in wallet[Kukai]
4. approve the request in the wallet[Kukai]
5. Waiting for something to appear [Hicetnunc]

I have received tokens for the Objkt in my wallet but nothing is in the [Hicetnunc] profile. I have synced/resynced the wallet many times but nothing. 
Wallet: tz1bh4mjs3RDB7dvHHHRhYEmCccKRzCVrCjf

Deductions - ![image](https://user-images.githubusercontent.com/84977894/119999143-0c563f80-bfef-11eb-990e-85f12b1850b3.png)

Empty profile - 
![image](https://user-images.githubusercontent.com/84977894/119999348-46274600-bfef-11eb-99e1-2463ee2d9a5c.png)

Wallet - 
![image](https://user-images.githubusercontent.com/84977894/119999520-766ee480-bfef-11eb-8e58-ea2d002258a1.png)

**Comment by igdeputra** [comment]
I have same issues too.. help!! :(

**Comment by violetforest** [comment]
Hey, it seems you were able to mint. I'm going to close this but if you still need help let me know and I will reopen.
