### ISSUE TITLE
Receiving tezos for swaps

### ISSUE THREAD

**Issue by schonschoncrypt** [hicetnunc2000/hicetnunc#782]
Hi, 
I had to sales 3-4 days ago but did not receive any tezos. How is the transfer from the hicetnunc wallet back to mine happening? And when can I expect them? I use the temple wallet.
Thanks!

**Comment by kylegrover** [comment]
The money goes directly to you from the smart contract, hicetnunc doesn't hold onto it. It should be instant. check your transactions/wallet

**Comment by violetforest** [comment]
please let me know if you still need help and I will reopen
