### ISSUE TITLE
Wrong transaction

### ISSUE THREAD

**Issue by dadadaduts** [hicetnunc2000/hicetnunc#791]
I was collecting an NFT from https://www.hicetnunc.xyz/tz/tz1NMz59VkcbWRqg2ms1rKsebJrnKwFRMidU. When I checked my collections, it did not appear on them. My Temple wallet was deducted 5tz to an unknown account: https://www.hicetnunc.xyz/tz/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9

**Comment by violetforest** [comment]
Hey, are you still having trouble with this? That address is the Hicetnunc escrow wallet. when you swap something and put it on the market it goes to the escrow account. so you are essentially buying the OBJKT from the escrow account.

I'm going to close this but if you need more help let me know and I will reopen
