### ISSUE TITLE
Invisible art on profile. 

### ISSUE THREAD

**Issue by KuismaArt** [hicetnunc2000/hicetnunc#796]
Hi. 
My name is Kuisma. I am an artist. 

This is my profile:
https://www.hicetnunc.xyz/tz/tz1UV4EomFA8SUyE3d291YbNFb9uTS56pjzC

My works are not displayed in the profile. 
Nobody can see my art. I have been unable to sell my NFT for several weeks ... 

It's really sad ;-(

Help me, please!

**Comment by noonenoise** [comment]
I have the same problem . 2 of my artworks are not showing 
hic.art/Noonenoise

**Comment by ShararehFaryadi** [comment]
Hey there, It's Sharareh
I have the same problem,
this is my account link and I just found that one of my works and almost all of my collection is invisible !!!
https://www.hicetnunc.xyz/tz/tz1h1S2w7rTSJ5zSeRPtWtRAoCVEkkCjBsKQ
Please help me!

**Comment by DamsDraws** [comment]
Me too 15mn ago, almost half of the gallery :/
screenshot before/after -> https://imgur.com/l3lMqiC

**Comment by KuismaArt** [comment]
> Hey there, It's Sharareh
> I have the same problem,
> this is my account link and I just found that one of my works and almost all of my collection is invisible !!!
> https://www.hicetnunc.xyz/tz/tz1h1S2w7rTSJ5zSeRPtWtRAoCVEkkCjBsKQ
> Please help me!

My problem was solved!
And ican see your collection too!

**Comment by KuismaArt** [comment]
My problem was solved!
Thanks!!! 
![Uploading IMG_20210601_195044.jpg…]()

**Comment by ShararehFaryadi** [comment]
> > Hey there, It's Sharareh
> > I have the same problem,
> > this is my account link and I just found that one of my works and almost all of my collection is invisible !!!
> > https://www.hicetnunc.xyz/tz/tz1h1S2w7rTSJ5zSeRPtWtRAoCVEkkCjBsKQ
> > Please help me!
> 
> My problem was solved!
> And ican see your collection too!

No, that's only 2 of my pieces, I had more :(
