### ISSUE TITLE
hicenunc.xyz has been blocked by CORS policy

### ISSUE THREAD

**Issue by lurex666** [hicetnunc2000/hicetnunc#798]
hi! 
i'm having problem minting, stays on "preparing objkt" screen forever and the temple wallet pop-up doesn't even appear
tried reinstalling chrome, alternative browsers, reloading the modem, cleaning the cache, kukai wallet... but nothing yet
already tried compressing the file to like 9mb but no success

this is what the codes stuff page shows

![erro](https://user-images.githubusercontent.com/85137823/120246470-b4b21100-c246-11eb-9eed-2c0c780b6cbb.png)

thanksss in advance ♥

**Comment by tenineight** [comment]
It seems like you're trying to fetch data from a url that is not allow-listed.
Here's a list of URLs that are allowed: [https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs#allowed-domains](https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs#allowed-domains)

**Comment by violetforest** [comment]
closing, seems that theres no other solution
