### ISSUE TITLE
objkt page displays wrong edition numbers

### ISSUE THREAD

**Issue by kayaman347** [hicetnunc2000/hicetnunc#802]
**Describe the bug**
https://www.hicetnunc.xyz/objkt/108682 displays 7 editions priced super cheap, so I bought, after the transaction the edition number jumped to 25. asked on twitter what others saw, it was both 7 and 25. 
https://twitter.com/kaya45816520/status/1399732958555250689

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by skenaja** [comment]
I think this is now correctly showing 25.
