### ISSUE TITLE
Thumbnails stop working

### ISSUE THREAD

**Issue by felinoo** [hicetnunc2000/hicetnunc#803]
Hello!
when i minted my NFTs they were all working well, they just stoped working. I know its not the code cause it worked once..
Anyone knows if i gotta do something?
https://www.hicetnunc.xyz/tz/tz1YNGWkQTyNvEvuukFhLehZv7niyAdmuWEp
![image](https://user-images.githubusercontent.com/84288686/120361786-a7496500-c2e0-11eb-912d-8913e76562b2.png)

**Comment by bilgekaan** [comment]
yeah, old interactive nft thumbnails are broken now

**Comment by felinoo** [comment]
oh no
does dthis happen often? do they go back to normal?

**Comment by bilgekaan** [comment]
I opened a bug report about this here https://github.com/hicetnunc2000/hicetnunc/issues/805

**Comment by felinoo** [comment]
UPDATES
I minted a jpg this time and hic said this
![image](https://user-images.githubusercontent.com/84288686/120394399-bc86b980-c309-11eb-8bd3-0842c97ad83b.png)

**Comment by bilgekaan** [comment]
it seems fixed now, you can close this
