### ISSUE TITLE
Older interactive nft thumbnails are broken.

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#805]
**Describe the bug**
Older interactive nft thumbnails are broken. We were uploading them inside the zip file.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/tz/tz1VZUTpbJQiQZvpXE9kTCydgyTTxpW49G5o
2. Last two thumbnails are uploaded with the new method so they are fine. Other thumbnails were inside the zip file.

**Screenshots**
![image](https://user-images.githubusercontent.com/2965842/120380574-02537a00-c32a-11eb-81cc-f5f1297704be.png)

**Comment by SableRaf** [comment]
Looks like it just got fixed. Did https://github.com/hicetnunc2000/hicetnunc/commit/3ab8eb6fe9d77e8c9ec673976df532808447ed55 do it?
