### ISSUE TITLE
/collection showing pieces on secondary already sold

### ISSUE THREAD

**Issue by spacegoodies** [hicetnunc2000/hicetnunc#806]
**Description**
As a user, if I navigate to my profile /collection, I see all pieces owned and being sold on secondary. At the moment, it currently includes pieces already sold on secondary, which should not be shown because the collector no longer owns them.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/tz/tz.../collection
2. Navigate and find an item sold on secondary.
3. Click item.
4. User is not listed as collector on the collectors tab because s/he already sold it.

**Expected behavior**
Already sold items should not appear in user's /collection

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Safari
 - Version 14.1.1

**Comment by crzypatchwork** [comment]
this was troubleshooted. could you share more info though, as an objkt id?

**Comment by spacegoodies** [comment]
Looks like you rolled back... Here's 1 item I regret selling https://www.hicetnunc.xyz/objkt/375 Wallets seem to show sold items as a 0 asset so there has to be a way to isolate what is sold and what is for sale on secondary, which is also displayed as a 0 asset. Thanks for all the great work! Artists and collectors all love the platform.

**Comment by spacegoodies** [comment]
I think this is a Tezos wallet issue that may be difficult to resolve on the frontend. Not sure if tryshowtime fixed this issue, but they had the same problem.
