### ISSUE TITLE
Multiple Prices Are Not Sorted

### ISSUE THREAD

**Issue by atomantic** [hicetnunc2000/hicetnunc#81]
This object has 5 units, 2 are for sale: https://www.hicetnunc.xyz/objkt/3942

The first sale is 1 XTZ
The second is 5 XTZ

The code is simply grabbing the first item in the swap array and showing the 1/5 for sale for 5 XTZ rather than 1 XTZ.

The items should be ordered so the least expensive item is sold first.

```
[{swap_id: "3899", issuer: "tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9", objkt_amount: "1", objkt_id: "3942", xtz_per_objkt: "5000000"},
{swap_id: "3876", issuer: "tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9", objkt_amount: "1", objkt_id: "3942", xtz_per_objkt: "1000000"}]
```

something like:

```
const least_expensive = this.state.objkt.swaps.reduce((sum,item)=>{
        if(!sum || (Number(item.xtz_per_objkt) < Number(sum.xtz_per_objkt))) {
          sum = item;
        }
       return sum;
      })
```

**Comment by crzypatchwork** [comment]
ty that is a initial feature for the secondary market

**Comment by atomantic** [comment]
Thanks for merging the request. Looks like the site is currently down though due to an infrastructure change with the lambda cors settings: 

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/feed. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```
