### ISSUE TITLE
FAQ: [summary of change]

### ISSUE THREAD

**Issue by Mandana-Behdad** [hicetnunc2000/hicetnunc#812]
**Summary of change to FAQs you wish to make:**
* For example: new page `foo.md`, edit to page `bar.md`. 
* If want to reorder any existing page, note this here too.

[*enter change here*]

**If it's a new page, which navigation heading does it come under**
* For example: Minting guide, FAQs, Misc

[*enter navigation change here*]

**Text change**
* Add here the new text (and old text it's replacing if applicable)

[*add new and/or replaced text here*]

**Markdown**
* If you've written the update using Markdown, replace the `FAQ in markfown format` below with your markdown-tagged text

```Markdown
Add FAQ text in Markfown format
```

**Comment by kylegrover** [comment]
You need to actually fill out the issue, this is just the boilerplate text.
