### ISSUE TITLE
Avatar not uploading, can't make profile on HEC

### ISSUE THREAD

**Issue by youtopia2** [hicetnunc2000/hicetnunc#815]
**Describe the bug**
In the create profile google doc, I have been trying to upload my avatar (512px squared PNG) for two days now but it keeps failing. I have tried reducing resolution, reducing px size, I've also been uploading on PC so it shouldn't even be a device problem but it just won't upload and it's keeping me from making an account. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2; OS build 19042.985
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (64-bit)
![1](https://user-images.githubusercontent.com/85218039/120439352-47ca7400-c337-11eb-8244-90c70e898b40.PNG)

**Comment by kylegrover** [comment]
This is handled outside of hicetnunc, contact baking-bad. More info here https://baking-bad.org/blog/2021/05/01/f-a-q-hic-et-nunc/ 
And the upload bug is a problem with Google, you'll need to contact google support (good luck with that) or ask baking-bad for a workaround, I think they respond to email or twitter dms

**Comment by violetforest** [comment]
https://github.com/hicetnunc2000/hicetnunc/wiki/Edit-your-profile

https://baking-bad.org/blog/2021/05/01/f-a-q-hic-et-nunc/


Here is some more info if you need it
