### ISSUE TITLE
Can't upload interactive objkts (HTML)

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#819]
**Describe the bug**
When you try to upload/preview an HTML zip, it stuck at the empty gray screen and I got the error below on the console.

![image](https://user-images.githubusercontent.com/2965842/120498474-eacace80-c3c7-11eb-921b-b27989a31787.png)

**To Reproduce**
1. Try to upload/preview an HTML zip

**Comment by Andmat7** [comment]
same bug

**Comment by CandleCove** [comment]
same

**Comment by pichiste** [comment]
Fix has been merged to `main`, awaiting deployment: https://github.com/hicetnunc2000/hicetnunc/pull/813 @crzypatchwork
