### ISSUE TITLE
Missing a bold weight of new font, resulting in faux bolding

### ISSUE THREAD

**Issue by jamesdelaneyie** [hicetnunc2000/hicetnunc#822]
Currently, there is only a single font used across the site. However <strong> is being used to bold via font-weight: 700, but there is no 700 weight of the font. Resulting in faux bolding. Bad Typography! Naughty!

Full family is available to buy here: https://www.atipofoundry.com/fonts/basier-mono/pay-what-you-want

I'm gonna purchase the font family and figure out how to make a pull request with this fix, it's my first time contributing to anything like this, please be gentle

**Comment by crzypatchwork** [comment]
don't worry we can do this with monospace. but bringing some font/UI fixes are welcome.

**Comment by jamesdelaneyie** [comment]
I'm not sure I follow what you mean when you say you 'can do this with monospace'? using the browser's bolding instead of loading the bold weight of the font designed by the type designer? . EDIT this is a bit curt in tone, apologies

**Comment by melMass** [comment]
This is implemented now

**Comment by jamesdelaneyie** [comment]
Afraid the bold weight for IBM Plex Mono isn't being loaded in, check your google font URL: 

https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&display=swap

Regular weight @ 400 is the only font being loaded here, no bold weight so you're still getting faux bolding!
