### ISSUE TITLE
I minted my nft and my tezos are deducted but my nft is not visible

### ISSUE THREAD

**Issue by Dell95** [hicetnunc2000/hicetnunc#823]
recently i have minted my a nft on hic et nunc and my tezos are deducted but my nft is not visible
please someone fix this issue

**Comment by skenaja** [comment]
Sorry that no-one got back to you! Did you get this resolved? If this is still a problem, please let us know your wallet# and the transaction details from tzkt.io so we can diagnose, and I'll re-open the ticket.
