### ISSUE TITLE
(http 410) Object is restricted and/or from a copyminter

### ISSUE THREAD

**Issue by ghost** [hicetnunc2000/hicetnunc#824]
An objkt appeared on our collection which we don't want. We don't know how exactly this objkt came to our collection. When we try to burn it, the system gives the alert that is the topic of this thread. How can we get rid of it? 
objkt nr is 101611.

Our profile link is; 
https://www.hicetnunc.xyz/tz/tz1f2V6kGGUmBQoQwSFkSDihXcvfSZ7mvZmj

Thanks,
Vodoo Dao

**Comment by kylegrover** [comment]
You can send it to the burn wallet `tz1burnburnburnburnburnburnburjAYjjX` directly from your wallet, the title of this objkt is 'THE SATOSHI DOLLAR'. There will be a better system for this eventually.
