### ISSUE TITLE
Can't swap a piece on HEN

### ISSUE THREAD

**Issue by anaresende0** [hicetnunc2000/hicetnunc#825]
**Describe the bug**
All day I've been trying to swap a piece and a message of error appears:
Error
Failed to send request to https://mainnet-node.madfish.solutions/chains/main/blocks/head/helpers/forge/operations. Invalid request provided or RPC node is temporarily unreachable.
**To Reproduce**
1. Go to 'manage assets
2. Click on swap
3. click on confirm

**Expected behavior**
I expected to swap as aways

**Screenshots**
![image](https://user-images.githubusercontent.com/85322050/120728358-1c6c9400-c4b3-11eb-9384-e485f5ca2392.png)
![image](https://user-images.githubusercontent.com/85322050/120728471-605f9900-c4b3-11eb-90ef-f50da6bf4508.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome 
 - Version  91.0.4472.77 64 bits

**Additional context**
https://www.hicetnunc.xyz/objkt/107607

**Comment by skenaja** [comment]
Are you the creator or wanting to resell the item on secondary market? Could you confirm your wallet address?

**Comment by anaresende0** [comment]
Hi! I am the creator. I managed to swap it for another value. I guess the bug was only happening in the amount I was trying to use. Thanks!
Em 16 de jun de 2021, à(s) 07:23, skenaja ***@***.***> escreveu:

**Comment by skenaja** [comment]
Thanks for coming back with the details, glad it got sorted out.
