### ISSUE TITLE
Media File Not Supported on one objkt 

### ISSUE THREAD

**Issue by wolfbooy** [hicetnunc2000/hicetnunc#829]
Hello!

I am having an issue on my Manage Assets profile page. In the last objkt that i minted it shows me the message, MEDIA FILE NOT SUPPORTED. It is a .png image. Maybe some kind of a bug. When i click the OBJKT everything is displaying fine.
![medi](https://user-images.githubusercontent.com/79932927/120792382-1d96d300-c53e-11eb-91ff-99f592cee59f.JPG)

**Comment by tenineight** [comment]
I'm having the same issue on OBJKT 114287  :/

**Comment by MishtaZero** [comment]
its the same, i've tried to min a JPEG and show me this message:

(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>

**Comment by spicysmoke** [comment]
This has happened to me as well, with a jpg

**Comment by drkoyaanisqatsi** [comment]
I exactly have the same issue. I have tried other resolutions and low PPI versions but all I get is that issue. It will be my 3rd burnt NFTs If I can't get any solution.

**Comment by violetforest** [comment]
this should be fixed, i'm going to close but if its still happening let me know and i will reopen
