### ISSUE TITLE
HTML mint preview shows blank page

### ISSUE THREAD

**Issue by tenineight** [hicetnunc2000/hicetnunc#830]
The page is blank (white/black) when trying to ´preview´a HTML (*.zip) OBJKT during the mint-process.

I already tried to unsync/sync the wallet. Tried another browser. Tried a very simple HTML OBJKT (which I attached for reproduction purpose).

**To Reproduce**
1. Go to '/mint'
2. Upload an interactive HTML OBJKT (*.zip)  '....'
3. Click `preview`
4. See that the page is totally blank (white or black), without navigation or anything else.

**Expected behavior**
A preview of the HTML OBJKT should be visible.

**Screenshots**
_JavaScript Error_
<img width="789" alt="Screenshot 2021-06-04 at 17 09 13" src="https://user-images.githubusercontent.com/1213686/120823410-b2f29100-c557-11eb-9ed8-f75332cbd1be.png">

**Desktop:**
 - OS: macOS Big Sur on a M1 MacBookPro
 - Browser **Chrome 90.0.4430.212 (Official Build) (arm64)** and **Firefox 89.0**

**Additional context**
Somehow only happens with HTML OBJKTs. Images (jpg for example) seem to work fine.
I am using Temple Wallet, even though I don't think it has anything to do with this.
My Wallet-Address: tz1WwLpnjMbjfQEmUpExC8wqNuZP5vTjYqgS

**Example Project**
[HTML_OBJKT.zip](https://github.com/hicetnunc2000/hicetnunc/files/6599510/HTML_OBJKT.zip)

**Comment by tenineight** [comment]
Somehow it now works without doing anything differently.

**Comment by kylegrover** [comment]
Should be fixed with 5cdd24571c7d70a72816d75bda84a186364f047a
