### ISSUE TITLE
Paid for NFT, no NFT in wallet

### ISSUE THREAD

**Issue by holonick** [hicetnunc2000/hicetnunc#831]
**Describe the bug**
I made a purchase last night https://tzkt.io/oo4B4uW54gfwxC4DBJH4quNyEPEvk5eUs3yVrukeMBYmNYKrgsU
I look in my wallet and there is no NFT but the Tez is gone.

**To Reproduce**
1. Go to  https://www.hicetnunc.xyz/objkt/56542
2. Click purchase
3. Maybe it works for you, maybe not, didnt work for me

**Expected behavior**
I expected to have the NFT in my collection.

**Screenshots**

**Desktop (please complete the following information):**
 - windows desktop
 - firefox
 - latest of 05/06/21

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by crzypatchwork** [comment]
it seems that it was just a glitch in the API. it takes some times to update informations from the blockchain.

**Comment by holonick** [comment]
Ok thnak you
