### ISSUE TITLE
Last 3 mints stuck saying "updating metadata info"

### ISSUE THREAD

**Issue by kidartprojects** [hicetnunc2000/hicetnunc#833]
My last 3 mints are not displaying correctly in my collection. They also say this sometimes when I try to open them.

(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>
![KidArtProjects - hic et nunc - Google Chrome 6_6_2021 1_11_06 AM (2)](https://user-images.githubusercontent.com/83752781/120914547-6fd21400-c664-11eb-90e0-820f5303421a.png)

**Comment by laryssavg** [comment]
I have the same problem
![Uploading Captura de Tela (66).png…]()

**Comment by laryssavg** [comment]
I have the same problem
![Captura de Tela (66)](https://user-images.githubusercontent.com/85436613/120920762-6eb5dc80-c68e-11eb-919d-65614f4698bb.png)

**Comment by drkoyaanisqatsi** [comment]
I had also same problem, its gone when Im reset my modem with /flushdns. Idk maybe it will help you too. Goodluck!

**Comment by kidartprojects** [comment]
It also says my objects are 1/x. One of them says x/x. What does this mean?

**Comment by ninapegorini** [comment]
I have the same issue :/

**Comment by violetforest** [comment]
this should be fixed, let me know if its not and ill reopen it
