### ISSUE TITLE
Last mint stuck saying "updating metadata info

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#834]
My last mint is not displaying correctly in my creations.

(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>

![Untitled-1231](https://user-images.githubusercontent.com/83771575/120918467-d4738a00-c6c9-11eb-82e3-43e618fb9318.jpg)

https://www.hicetnunc.xyz/tz/tz1MLJf8TkAZ7gY5jCmNoCauVYZ2cWBsFdfe

**Comment by andrevenancio** [comment]
Seems to work now?

**Comment by erphanmalek** [comment]
Yes, it's working well now
Thank you
