### ISSUE TITLE
I can't see my editions on my last mint

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#836]
![Hic page 0](https://user-images.githubusercontent.com/83771575/120921971-c464a600-c6db-11eb-88d2-cc7fb75747df.jpg)

https://www.hicetnunc.xyz/objkt/116742

**Comment by Stereohopper** [comment]
I had the same problem, but after one hour everything will be fine and there is the right "edition-number" :)

**Comment by andrevenancio** [comment]
Hi @erphanmalek and @Stereohopper It seems like this has been fixed. closing but will re-open if need be.
