### ISSUE TITLE
Error after minting

### ISSUE THREAD

**Issue by JenkM8** [hicetnunc2000/hicetnunc#837]
![image](https://user-images.githubusercontent.com/82592415/120922525-a12cfd00-c6c1-11eb-8bb1-4a42afc342f0.png)

**Comment by LSnapes** [comment]
I get the same error!  If there is a fix on this board please direct us to it!

**Comment by fatehavtarsingh** [comment]
Same problem!

https://www.hicetnunc.xyz/objkt/119381

**Comment by andrevenancio** [comment]
Sometimes there's api errors breaking the site. 

That url works for me. should we close this?

**Comment by fatehavtarsingh** [comment]
Thanks for your response and help.
