### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by SMOYTOO** [hicetnunc2000/hicetnunc#839]
**Describe the bug**
the mintage of the photo did not go well > https://www.hicetnunc.xyz/objkt/117215

(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>

**Desktop (please complete the following information):**
Mac big sur 11.3

 - Browser Chrome
 - Version 91.0.4472.77 

**Additional context**

**Comment by fatehavtarsingh** [comment]
Same problem!
Brave Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64)
macOS Catalina ver. 10.15.7
https://www.hicetnunc.xyz/objkt/119381

**Comment by kylegrover** [comment]
temporary problem, both objkts are loading correctly now

**Comment by fatehavtarsingh** [comment]
Thank you for your reply. I hope everything will be all right.

**Comment by amygoodchild** [comment]
I'm getting this problem as well. It's happening intermittently, about 30% of the time that I load the OBJKT page. On this OBJKT- https://www.hicetnunc.xyz/objkt/127090

Windows 10
Chrome version 91.0.4472.101 (Official Build) (64-bit)

**Comment by fatehavtarsingh** [comment]
I think the problem has already been solved. I just went and checked the link, it works for me, in Safari but in Brave the error.
⬇️
There's a problem loading this OBJKT. Please report it on Github. Network Error.

**Comment by andrevenancio** [comment]
This issue seems to have been fixed. Closing for now, but can re-open if anything changes.
