### ISSUE TITLE
Can't cancel SWAP on OBJKT

### ISSUE THREAD

**Issue by Joustin** [hicetnunc2000/hicetnunc#840]
**Describe the bug**
I can cancel swaps on other objkts, but for some reason... I can not this one.
https://www.hicetnunc.xyz/objkt/113762

**OBJKT** 
113762

**Screenshots**
![image](https://user-images.githubusercontent.com/265066/120942740-e4569280-c6f8-11eb-84ae-73a91be7fd82.png)

I get this error in Kukai:
![image](https://user-images.githubusercontent.com/265066/120942761-ffc19d80-c6f8-11eb-9c44-20e4c0bfbc52.png)

**Comment by Boomsling** [comment]
Same issue user cannot buy it either

thread here with pictures  of error messages.

https://twitter.com/Cruel_Coppinger/status/1402386779643301892

OBJKT : https://www.hicetnunc.xyz/objkt/121326

**Comment by Joustin** [comment]
In the UI... my swap ID was "234549" ... However, when I used **better-call.dev** ... I was able to cancel my swap with "234551" - so... somewhere... the IDs were mixed up.   I canceled my swap... but, in the UI on the site... the old collect/cancel buttons are still there.  Weird.

**Comment by Boomsling** [comment]
thanks, i managed to cancel the swap with better-call-dev and make a new swap, the old swap info is also still there.

https://www.hicetnunc.xyz/objkt/121326
