### ISSUE TITLE
hDao transaction executed instead of objkt mint

### ISSUE THREAD

**Issue by verybadacid** [hicetnunc2000/hicetnunc#841]
Late last night while attempting to mint (using Kukai wallet) the transaction went through as a 'curate call', deducting hDAO from my balance.

I immediately attempted to mint a second time following this error (I'd also informed the discord), and this second mint was successful.

I see NO possible way to initiate a 'curate call' on the mint item page, so I'm at a loss for how to attempt to replicate or explain.

I expected to be able to mint objkt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - 89.0 64Bit

**Additional context**

hicetnunc was having metadata issues last night which was affecting operations on the platform, so I'll assume this issue was generated in relation to this.

TXN# oni6cWzAiqMFpd8VfCrEn94Fvu7eeVhQQbusHrRjSh4F2nqqCvP

Wallet (OUT) address: tz1Xd75PTAwQhK9TAhUZxB7GtdczkE3397Bu

**Comment by andrevenancio** [comment]
Hi @verybadacid Can you provide the OBJKT number or transaction id from https://tzkt.io/ so its easier to track?

**Comment by verybadacid** [comment]
I thought I'd provided transaction number already, but here it is again...

I'll include all connected txn

KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9

oni6cWzAiqMFpd8VfCrEn94Fvu7eeVhQQbusHrRjSh4F2nqqCvP

These transactions were generated from the 'MINT' page, without warning,
when attempting to mint an OBJKT. Subsequent mint was successful.

Regards

_____________
Brendan Forde

An Other Art Space

**Comment by skenaja** [comment]
Can I check whether you have pressed this button at any time?

![image](https://user-images.githubusercontent.com/510285/122202170-ac87e180-ce94-11eb-80da-c4bd0064981c.png)

(that button calls the curate function to effectively upvote an artwork for the hDAO feed)
