### ISSUE TITLE
95 editions disappeared after "Swap"

### ISSUE THREAD

**Issue by fabiofon** [hicetnunc2000/hicetnunc#842]
95 editions (out of a total of 100) were offered for sale and disappeared, they are not on 'collectors'. Soon after, I did a test by putting one more edition for sale. This one worked, but the other 95 simply disappeared. How can I retrieve them?

https://www.hicetnunc.xyz/objkt/117838

![hit et nunc problema2](https://user-images.githubusercontent.com/85465147/120953155-ce5dc780-c722-11eb-9ddd-7c309f0c3f6a.png)
![hit et nunc problema1](https://user-images.githubusercontent.com/85465147/120953166-d289e500-c722-11eb-8274-62c734ebf61f.png)

tz1StMwmzyXH7wcF5QggHtYspNSWcmkDXhfa
OBJKT#117838

**Comment by crzypatchwork** [comment]
this is a glitch in the API. it can be fixed/unglitched anytime, or another alternative fix might happen this week. your objkts are safe in your wallet/smart contract though.

**Comment by andrevenancio** [comment]
Hi @fabiofon It seems like the tokens are with the hicetnunc minter (96 of them). here is the [request](https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/objkt?id=117838). I think this is a temporary issue as crzypatwork mention.

**Comment by fabiofon** [comment]
Hi! Today the tokens are back! Thanks!!!

**Comment by Zepraxis** [comment]
Hey, Fabiofon, How was this resolved? I'm having the exact same issue, everything has disappeared, it's like my account has been reverted back to day one, including my second accoiunt connected to my wallet.

**Comment by fabiofon** [comment]
Zepraxis, the issue has been resolved after an API update (crzypatchwork talks about this above). In practice, I didn't do anything. I think you should open a issue here to the developers know about your problem. I wish it works.

**Comment by Zepraxis** [comment]
> 
> 
> Zepraxis, the issue has been resolved after an API update (crzypatchwork talks about this above). In practice, I didn't do anything. I think you should open a issue here to the developers know about your problem. I wish it works.

Thanks Fabiofon, I have already done so, I hope I can get this resolved, even though I have all my creations saved on my desktop and not all is lost, It's frustrating because of the time, effort and fees that it's taken to list everything over the last week. 

I really appreciate the reply, Take care.
