### ISSUE TITLE
Cnat burn my NFT

### ISSUE THREAD

**Issue by Loriana-Art** [hicetnunc2000/hicetnunc#844]
I want to burn this NFT.  When I created this NFT, the quantity showed 500/1000.   I tried to burn the NFT to minted again and get the correct amount.   The system told me that I had 500 NFT. I burned them all.   Now the quantity appears 500/500.  When I tried to burn, the system tells me that I have 0 (cero) NFT. The NFT is still in my profile. I want to get rid of this NFT. Thanks 

https://www.hicetnunc.xyz/objkt/115986

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by violetforest** [comment]
Hey, you have to cancel the swap and then burn it

You can see a guide here:
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5

**Comment by Loriana-Art** [comment]
Hello Again.  am really having trouble burning my NFTs.     It tells me that I don't own my NFT.  And I have tried to send them to the burn address you provide but  my NFTs does not appears on my wallet . They do appear on my HEN profile.  Thanks

**Comment by Loriana-Art** [comment]
How do you  ([cancel] the curation of this OBJKT ) ?
