### ISSUE TITLE
Multiple pieces listed "Not For Sale" x/1, x/3 etc... 

### ISSUE THREAD

**Issue by Yuloo** [hicetnunc2000/hicetnunc#845]
I tried reading the contributing guidelines, but I can't understand them at all.  so here's a brief description of my issues. I tried uploading a few pieces of artwork to your site to sell. A few of my pieces listed with no problem, some will not. They are minted, and I thought I'd successfully "Swapped" them, but it appears there are not any editions available. they read "x/1"  or "x/3" and "Not For Sale" . I tried increasing the storage parameters to 180 per item. I tried adding more Tezos to my wallet to make sure I had an adequate balance for my transactions. I waited two days and tried again. Still no success. I tried to purchase a piece from another artist, and was no able to get the transaction to complete. It said it was successful, but was unable to be completed? Everything I do seems to generate a different error. I've paid to mint these objkts in good faith that your product would work. It's by no means a lot of money, but its the principle.  My objkt numbers with the issues listed above are 117709, 117727, 117761, 117814. I originally attempted to post these items on 6/6/21. I attempted again today on 6/8/21, with no success. thanks.

**Comment by Yuloo** [comment]
I tried again today, it's 24 hours later, and some of them worked, Others said that the transaction was successful, but it's been at least 30 minutes and it still says "Not for sale"

**Comment by andrevenancio** [comment]
Hi @Yuloo can you provide a bit more information? Like what is your wallet id, or the OBJKT number so I can have a look at this for you?

**Comment by skenaja** [comment]
This ticket will be reopened if more information is provided
