### ISSUE TITLE
Zipped html Objkt cannot load assets in subdirectories

### ISSUE THREAD

**Issue by vbossa55** [hicetnunc2000/hicetnunc#846]
When you upload zipped html objkt, it cannot load any asset from the subdirectories. It happens in the preview and minted objkt.

E.g. https://www.hicetnunc.xyz/objkt/122329

The index.html only has this code

`<img src="img/image.jpg" alt="Ouch">`

![image](https://user-images.githubusercontent.com/81993554/121290629-8e146a00-c919-11eb-90e9-f255a9116967.png)

This is the zip file if you want to try, 
[html.zip](https://github.com/hicetnunc2000/hicetnunc/files/6620996/html.zip)

Image source from Preview:
![image](https://user-images.githubusercontent.com/81993554/121290991-185cce00-c91a-11eb-983f-362d85d237fd.png)

Image source from the minted Objkt:
![image](https://user-images.githubusercontent.com/81993554/121291055-36c2c980-c91a-11eb-841e-7b378ddcd775.png)

Yesterday, all was fine. This just happened a few hours ago.

**Comment by andrevenancio** [comment]
Hi @vbossa55 Did you zip this from a windows machine by any chance?

**Comment by vbossa55** [comment]
Hi Andre,

Yes, the files are zipped from a Windows machine. Does it affect anything?

update: I've zipped this from Ubuntu, and it still doesn't work

**Comment by andrevenancio** [comment]
There seems to be a few reports from windows machines. Which software are u using to zip it? Can you try to zip the same files online or in a mac? just to test if its your zip app?

**Comment by vbossa55** [comment]
i tried zipping the files in Ubuntu with its native zip app, it's still the same

i've also tried zipping the same files online, still it's not working

on Windows, I use 7zip & native windows' file compressor

**Comment by vbossa55** [comment]
![image](https://user-images.githubusercontent.com/81993554/122326085-4c5d7200-cf5e-11eb-8fdd-144e7114a210.png)

this is the message from the browser console

**Comment by violetforest** [comment]
did you try "./img/file" instead of "img/file"?

**Comment by vbossa55** [comment]
thanks violetforest! that's the solution

also the files and folders need to be in one folder down in the zip file

[html-ok.zip](https://github.com/hicetnunc2000/hicetnunc/files/6976032/html-ok.zip)

**Comment by violetforest** [comment]
we can add this solution to the wiki (note to self or for any volunteers)
