### ISSUE TITLE
FAQ: add hicdex

### ISSUE THREAD

**Issue by mescalina** [hicetnunc2000/hicetnunc#849]
**Summary of change to FAQs you wish to make:**
* Update the whitelist addresses on the Interactive OBJKTs page

Add https://api.hicdex.com/ to the Allowed Domains (Is already supported on HEN website)

**Comment by violetforest** [comment]
Hey, I added it, but theres a bunch of checkmarks in the graph and not sure what I should add for the checkmarks

https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs

**Comment by aevin-io** [comment]
> Hey, I added it, but theres a bunch of checkmarks in the graph and not sure what I should add for the checkmarks
> 
> https://github.com/hicetnunc2000/hicetnunc/wiki/Interactive-OBJKTs

just the last column :)

**Comment by aevin-io** [comment]
Also, following up [https://github.com/hicetnunc2000/hicetnunc/pull/820](https://github.com/hicetnunc2000/hicetnunc/pull/820)
services.tzkt.io should be added as well, having a checkmark on 'img-src'

**Comment by violetforest** [comment]
done
