### ISSUE TITLE
Fail when cancelling swap

### ISSUE THREAD

**Issue by WatchHansi** [hicetnunc2000/hicetnunc#851]
I have listed a artwork I bought on sec. marked. 

When I try to cancel the swap, this message appears on HEN with message from Kukai.app wallet:

_Parameters Invalid
Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again._

In my Kukai.app wallet. This message appears: 

_Simulation error: A FAILWITH instruction was reached > WrongCondition: self.data.swaps[params].issuer == sp.sender_

My wallet address: tz2D6aKtMiAFkrNoRV6pwankFTNpAwmhPaNz
The item I cant cancel Swap: https://www.hicetnunc.xyz/objkt/118963

**Comment by Boomsling** [comment]
Posted same issue here #840

**Comment by WatchHansi** [comment]
Thank you so much!! I was able to fix the issue because of this help
