### ISSUE TITLE
STOLEN ART 

### ISSUE THREAD

**Issue by juanchokai** [hicetnunc2000/hicetnunc#853]
I'm reporting this NFT that appears on your platform without my permission:
https://www.hicetnunc.xyz/objkt/124068

This is my dribbble account from where this GIF file was taken: https://dribbble.com/juancasini
And my project on Behance: https://www.behance.net/gallery/75085611/Crypto-Tower

I have no ways to contact the issuer (tz1fdafQop3aY3Uqm9rM4CQFzQtVqJZJ8bxA)
neither the website https://www.hicetnunc.xyz/ **and I want my art removed immediately**

**Comment by kylegrover** [comment]
Banned in 9b537ba726e2df41bcce90e3b15150eec09e59e7 thanks for reporting. Some other community members caught and reported it as well. There's work on an improved reporting systems that should be live soon, until then this is a good route to contact the website, or in the discord.

**Comment by juanchokai** [comment]
Thanks a lot @kylegrover !
