### ISSUE TITLE
OBJKT#121239. Problem.

### ISSUE THREAD

**Issue by invader-303** [hicetnunc2000/hicetnunc#854]
OBJKT#121239 (https://www.hicetnunc.xyz/objkt/121239) cannot be purchased, canceled or burned.
With any action, the wallet reports:

![image](https://user-images.githubusercontent.com/58935237/121519458-8df89500-ca13-11eb-8858-0cd433896412.png)

**Comment by andrevenancio** [comment]
Hi @invader-303 can you provide a bit more information? What is your wallet? are you the creator of this piece? 

Normally you can only burn an NFT that isn't up for sale. So if you have done a swap this is not going to work. It might also be the case that you need to increase gas fees. But let me know a little bit more so I can give you a better answer.

**Comment by invader-303** [comment]
Hello @andrevenancio 
Wallet - Temple.
Yes, I am the creator of this OBJCT.

96 copies sold. And then the problem began.

The problem is that no one can buy / sell this art. People tweet me that they can't buy. Someone has a temple wallet, someone has a kukai.
But they all have one problem.

![image](https://user-images.githubusercontent.com/58935237/121794705-5b75b480-cc2c-11eb-809a-967a6df6ef58.png)

![image](https://user-images.githubusercontent.com/58935237/121794715-6892a380-cc2c-11eb-8f57-1d47d4f5c9aa.png)

![image](https://user-images.githubusercontent.com/58935237/121794724-82cc8180-cc2c-11eb-961a-4888c51d88c1.png)

etc.

**Comment by invader-303** [comment]
![image](https://user-images.githubusercontent.com/58935237/121942773-ab5e9380-cd72-11eb-9f66-4811194ebbe8.png)

**Comment by violetforest** [comment]
this issue seems to have resolved itself, closing but let me know if you need more help and i will reopen
