### ISSUE TITLE
OBJKT #124078

### ISSUE THREAD

**Issue by anaresende0** [hicetnunc2000/hicetnunc#855]
**Describe the bug**
When you click on the objkt's link a message of error appears (no all times, but frequently)

**To Reproduce**
1. Go to 'https://www.hicetnunc.xyz/objkt/124078'

**Expected behavior**
open the objkt 

**Screenshots**
![image](https://user-images.githubusercontent.com/85322050/121526134-7d263000-c9cf-11eb-9d92-b7080ac37bc9.png)

**Desktop (please complete the following information):**
 - windows 
 - chrome 
 - last Version
 - 
**Smartphone (please complete the following information):**
 - Device: iphone 8 plus
 - OS: ios 14.6
 - Browser safari

**Additional context**
I'm losing sales because of the bug :(

**Comment by andrevenancio** [comment]
Hi @anaresende0 This seems to have been fixed. closing this issue.
