### ISSUE TITLE
Swap item for secondary sale, item disappeard on the 2nd day and never sold....

### ISSUE THREAD

**Issue by TJohanson82** [hicetnunc2000/hicetnunc#857]
**Describe the bug**I purchased #121271 for 16 tezos on June 8 at 11:12:10AM and swapped it later for a secondary market at June 8 at 11:30:06. The item was listed all day June 9 and this morning on June 10th my item has not been sold and it is no longer listed for sale on the secondary market. In fact, the total pieces of art is 30 yet I count all all the owners and there is only 29...What happened to my artwork???

https://www.hicetnunc.xyz/objkt/121271
https://tzkt.io/ooM41xPkVtYJcEH62BDzkhVMd9h2S2nkn5BTNaM6oePpDY7gfXz
https://tzkt.io/oo4o34J62jZaSwKi5XADBjt1zAavP2yh2NTSd9LKuVnFb47dzdX

Still shows my swap as active, but it does not show up while reviewing the artwork:
https://hicdex.com/objkt?objkt=121271

2021-06-08T18:30:06Z tz2ScEdNF1p9QDZezWzaDdADJAHgoK4SG4bz put on swap 1 edition for 36.573 tez

**Comment by skenaja** [comment]
This is an occurrence of #645 - I've copied the specifics across to that ticket.
