### ISSUE TITLE
OBJKT#126234 Bug

### ISSUE THREAD

**Issue by pertsevart** [hicetnunc2000/hicetnunc#862]
No one can buy my objkt

**Comment by skenaja** [comment]
What errors to they receive? If it was a case of #645 (which has been happening recently), the wallet popup would say "transaction is likely to fail". Right now, this seems to be working OK.

**Comment by pertsevart** [comment]
Hey)
Oh, now it’s normal. Early it looks like 5/0. Thanks for your reply 🤍

Пт, 11 июня 2021 г. в 14:16, skenaja ***@***.***>:
