### ISSUE TITLE
hi! I am having issue

### ISSUE THREAD

**Issue by lopiart** [hicetnunc2000/hicetnunc#864]
I am getting this error:

There's a problem loading this OBJKT. Please report it on Github. Network Error
![image](https://user-images.githubusercontent.com/85761671/121731673-1cb5f200-caa6-11eb-8967-f950270936a4.png)
also that one!

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/126995

**Expected behavior**
show OBJKT

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 10
 - 

Wallet address:

tz1iEoskV5SAUfKn4w7D6WYXabDXaEyAp4WH

**Comment by andrevenancio** [comment]
Hi @lopiart Thank you for submitting an issue. It seems like there was a temporary hicup. Should be fine now.

**Comment by lopiart** [comment]
All good! Thank you ☺️
