### ISSUE TITLE
objkt 126981

### ISSUE THREAD

**Issue by tz1YsKDo5Kix5zYMr8ott4Nq7KiWNLKaBTpE** [hicetnunc2000/hicetnunc#866]
the objkt 126981 doesnt open. wallet address: tz1YsKDo5Kix5zYMr8ott4Nq7KiWNLKaBTpE

**Comment by spacegoodies** [comment]
These are all objkts at the moment.

**Comment by spacegoodies** [comment]
It should be back now.

**Comment by andrevenancio** [comment]
Hi @tz1YsKDo5Kix5zYMr8ott4Nq7KiWNLKaBTpE The object you mention is opening. Closing this issue for now, will re-open necessary.
