### ISSUE TITLE
User Guide / FAQ

### ISSUE THREAD

**Issue by driangle** [hicetnunc2000/hicetnunc#87]
Even though the site is very easy to use. I suggest adding a few user guides (or FAQ) to help users that struggle with the process.

Suggestions for guides:
* How to mint an NFT + How to offer to sell (curate) an NFT. Should also include how much in fees the site takes per sale.
* How to burn a token. In case the token becomes [corrupted](https://github.com/hicetnunc2000/hicetnunc/issues/56).
* How to report issues with the site.
* How to mint an NFT programmatically (if possible).
* How to contribute to project. Or, at least a link to the contributing guidelines on the GitHub repo.

Don't know if this belongs on the site itself or some external wiki?

**Comment by crzypatchwork** [comment]
this could be an important information to add in the about page

**Comment by andrevenancio** [comment]
The Guides could be written in `.md` (Markup files) here on github and on the about page we simply link to the github link for the markup.

This will allow the files to be updated at any time without requiring a deployment

**Comment by andrevenancio** [comment]
I've created the file on Github. we need someone to write a proper guide.
