### ISSUE TITLE
objkt 12717

### ISSUE THREAD

**Issue by julioglatt** [hicetnunc2000/hicetnunc#870]
(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>
Report

**Comment by andrevenancio** [comment]
Hi @julioglatt It seems like this might have been fixed already! I will re-open if its not, but right now I'm able to see this NFT
