### ISSUE TITLE
I can't add a price to my NFT

### ISSUE THREAD

**Issue by va2rosa** [hicetnunc2000/hicetnunc#872]
I've minted[ this NFT](https://www.hicetnunc.xyz/objkt/127661) and I can't add a price!
I was supposed to price it for only 0.1 tezos, but instead it appears as 0 tezos. When I try to change the price it keeps showing the same bug: '"FA_2 insufficient balance" or parameters invalid. I looked at the troubleshooting page and I'm not trying to swap more than I minted, I even tried swapping less to see if it worked. 
What else can i do?

**Comment by crzypatchwork** [comment]
you should cancel the swap and configure it again with new parameters
