### ISSUE TITLE
Objkt Duplication Added - Instance Error 

### ISSUE THREAD

**Issue by panda0010** [hicetnunc2000/hicetnunc#874]
Hi, on my creations page https://www.hicetnunc.xyz/tz/tz1a6qEPM1igUqjsXsvZYj2K7wyh2cZbn4n8/creations a duplication of this objkt https://www.hicetnunc.xyz/objkt/46362 has appeared (I'm not sure where from) https://www.hicetnunc.xyz/objkt/46323 when I click on this link this error text appears:

**(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html>**

I just wanted to report this error and find out what it is. Am I able to remove this duplicated objkt?
Thanks for your help. This is my first time writing a bug report. Let me know if you need any more info :)

**Comment by skenaja** [comment]
https://api.better-call.dev/v1/contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders?token_id=46323

46323 is burned, and these objkts are now no longer visible on creation pages. There was a temporary API issue where they reappeared which has now been fixed.
