### ISSUE TITLE
Blocked objkt

### ISSUE THREAD

**Issue by thedxtr** [hicetnunc2000/hicetnunc#877]
I did mint 80 objkt and after this, i burned 30, and now my objkt continues in 80, but the collectors cant buy, i cant swap, burn or cancel.

Macbook pro 2020
 - OS: IOS
 - Browser Chrome

My wallet:
tz1PMTbxjywp7jQsTv57WELWvWpFtxp1zcLM
<img width="930" alt="Captura de Tela 2021-06-13 às 23 16 58" src="https://user-images.githubusercontent.com/85855874/121831368-a8de3a00-cc9d-11eb-86d4-afb854f3eaeb.png">

OBJKT: 130383

My email: ledexter@gmail.com

Thank you guys

**Comment by zoudj** [comment]
It seems I experienced the same issue. It cannot properly show how many editions you have. The web page just shows 'You own 0 editions...'

**Comment by andrevenancio** [comment]
Under investigation. thanks for submitting

**Comment by thedxtr** [comment]
Hey you guys, thats fixed !!! Thank you so much !!!

> Under investigation. thanks for submitting
