### ISSUE TITLE
Me and my friends can't burn objkts

### ISSUE THREAD

**Issue by kimwayolic** [hicetnunc2000/hicetnunc#890]
**Describe the bug**
I'm having  trouble with burns, I cancel the swap of my editions then I click on Burn and appears that I have 0 editions, even my wallet shows different and the collector list too D:

My account: tz1NP8VghgiCHyH49kvPG2xY4hspZzXYP7v5

Screenshots:
![19-editions](https://user-images.githubusercontent.com/85878518/122138967-452f4a80-ce1e-11eb-95b5-75b304876ea4.png)
![01-0editions](https://user-images.githubusercontent.com/85878518/122138972-48c2d180-ce1e-11eb-84b5-701de63b986c.png)

**Comment by skenaja** [comment]
That looks like it could be a delay in the number of objkts that you own being updated from the blockchain indexer that HEN uses. What happens if you try to burn the 19 objkts that your wallet owns?

**Comment by violetforest** [comment]
This was a display error but it should be fixed now. Try clearing your browser cache.

If it still doesn't work, you can still burn all them even though it says 0. Go ahead and try it.

In the future, always check whats in your wallet and use that as confirmation. There should be 9988 in your wallet.

If you need anything else Ill open the issue back up
