### ISSUE TITLE
Html NFT display creator & objkt url paramaters are 'false' 

### ISSUE THREAD

**Issue by newyellow** [hicetnunc2000/hicetnunc#897]
![2021-06-16_22-30-49](https://user-images.githubusercontent.com/8190143/122238732-f30c2900-cef2-11eb-8bce-bff602f348ec.png)
When viewing html nfts, the creator & objkt parameter sent to iframe are now always 'false'.
It was working yesterday, and I found it broke this morning.

**Comment by andrevenancio** [comment]
this has been fixed.

**Comment by newyellow** [comment]
@andrevenancio creator has fixed, but it seems objkt is still false right now
