### ISSUE TITLE
hDAO not showing up in profile

### ISSUE THREAD

**Issue by wblut** [hicetnunc2000/hicetnunc#898]
Profile reports 0 hDAO, instead of actual value: https://www.hicetnunc.xyz/tz/tz1TSWEDs9wcBx2KiRzVzyzECsNpRiZaLJ1D
![Frederik_Vanhoutte_-_hic_et_nunc_-_Brave_20210616181514748](https://user-images.githubusercontent.com/3384788/122255892-df4ecb80-cece-11eb-8722-24d6df36dd6f.png)

**Comment by skenaja** [comment]
Thanks for reporting. I'm going to close this issue, as we're tracking it via #821
