### ISSUE TITLE
My works are not loaded

### ISSUE THREAD

**Issue by erphanmalek** [hicetnunc2000/hicetnunc#903]
Just one of my works is loaded on my profile  
The rest of them are disabled 
![qewq](https://user-images.githubusercontent.com/83771575/122446607-19e06300-cfb8-11eb-9340-6465bb61b8a5.jpg)

https://www.hicetnunc.xyz/tz/tz1MLJf8TkAZ7gY5jCmNoCauVYZ2cWBsFdfe

**Comment by violetforest** [comment]
this should be working now, let me know if you still need help and i will reopen it
