### ISSUE TITLE
Edition number available in interactive OBJKTs

### ISSUE THREAD

**Issue by peterschmidler** [hicetnunc2000/hicetnunc#906]
It would be nice to be able to also access the edition in interactive OBJCTs.

`?viewer={VIEWER_ADDRESS}&creator={CREATOR_ADDRESS}&edition={EDITION}`

`const creator = new URLSearchParams(window.location.search).get('edition')`

The value could be a string like this: "20of30" or "20_30".

That way one could make slight differences in the rendering of each edition.

**Comment by kylegrover** [comment]
i don't think there really is such a thing as an edition number for a token, all editions of an objkt are interchangeable

**Comment by newyellow** [comment]
The way ArtBlocks.io try to achieve this, is you mint each edition one by one, and then group all editions into one collection. So if this feature is considered valuable for generative artist, maybe this could be the way?

**Comment by aevin-io** [comment]
im not entirely sure, but i would assume the hicdex.com API has a way to provide this piece of information - there are certainly a field called "Supply" under the 'token'. So it should be possible to query the API using the objkt number to retrieve the number of available editions

**Comment by peterschmidler** [comment]
The number of available editions will change over time. I was rather thinking of something like `totalEditions - availableEditions @time of first purchase`, but I guess this is a little over-engineered, if that info is not available in the underlaying data model.

**Comment by kylegrover** [comment]
The problem there is if somebody buys two and sells one you have to randomly decide which edition is which, no other way to differentiate
