### ISSUE TITLE
Html display objkt id missing

### ISSUE THREAD

**Issue by newyellow** [hicetnunc2000/hicetnunc#907]
hi, thanks for fixing #897 two days ago, but it seems the objkt is still false right now.
Thanks!
![objkt-error](https://user-images.githubusercontent.com/8190143/122499989-8002cf80-d024-11eb-9447-b8ce71b45f28.png)

**Comment by newyellow** [comment]
@andrevenancio  Thank you for fixing the objkt "false" issue. But it seems this still need another edit.
Take my project as example. This project use the URL objkt parameter to fetch it owner list, and then get all the owners' profile image and assemble them into an image:
https://www.hicetnunc.xyz/objkt/133584

I found that the src link has to add another '/' otherwise the ipfs service ignores the URL parameters.
Take my project as example, the src link should be:
https://cloudflare-ipfs.com/ipfs/QmaA2KpviVKKUrssFh7dn5q3Qv3GMndGJWiSPRjE167mwp/?creator=tz1RPZp6NLzn7x4g7jhqHtCkhCQVnhbVMj8y&viewer=tz1RPZp6NLzn7x4g7jhqHtCkhCQVnhbVMj8y&objkt=133584

instead of
https://cloudflare-ipfs.com/ipfs/QmaA2KpviVKKUrssFh7dn5q3Qv3GMndGJWiSPRjE167mwp?creator=tz1RPZp6NLzn7x4g7jhqHtCkhCQVnhbVMj8y&viewer=tz1RPZp6NLzn7x4g7jhqHtCkhCQVnhbVMj8y&objkt=133584

Thank for your time maintaining this wonderful place!

![2021-06-19_17-11-25 copy](https://user-images.githubusercontent.com/8190143/122637653-7a8baf00-d122-11eb-979e-021bf919a87a.png)

**Comment by andrevenancio** [comment]
Also fixed. Needs deployment

**Comment by violetforest** [comment]
did this resolve your issue? if not let me know and I will reopen
