### ISSUE TITLE
interactive objkts doesn't work

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#909]
**Describe the bug**
interactive objkts doesn't work. I got the error below.

![image](https://user-images.githubusercontent.com/2965842/122545701-cf51fb80-d036-11eb-9c5c-17d9bb8df99f.png)

**To Reproduce**
1. Try this one: https://www.hicetnunc.xyz/objkt/112341

**Comment by deadlypixels** [comment]
similar issue here
<img width="959" alt="Untitled" src="https://user-images.githubusercontent.com/86114298/122569427-a2a3e100-d042-11eb-9da3-814d53ded585.png">

**Comment by aebrer** [comment]
happening to me as well, all my interactive HTML objkts are broken, though the direct IPFS link still works

**Comment by scottwilkerson** [comment]
yup error on page shows as

invalid ipfs path: invalid path "/ipfs/zdj7wmkbnn3mttd4hqxzsugva1seab36zaryn3314s7bihccr/": invalid CID: length greater than remaining number of bytes in buffer

**Comment by aevin-io** [comment]
same here.

**Comment by aebrer** [comment]
interactive svgs still work

**Comment by jharryedmiston** [comment]
Currently there is Invalid ipfs path for all interactive objkts on HEN ... Any idea if this is being addressed?  
Would be greatly appreciated as currently a bit of a nightmare with works not loading.

 I can see the pieces if I go through manage assets... 
 but if I follow a link to the piece, it is not possible and error code appears... https://www.hicetnunc.xyz/objkt/124750
 
<img width="764" alt="Screenshot 2021-06-18 at 17 08 12" src="https://user-images.githubusercontent.com/86121140/122589149-d0dfeb80-d057-11eb-8f2d-1548cb3a0723.png">

**Comment by jamesyu** [comment]
Can confirm that all interactive objkts down. Is anyone looking at this issue?

**Comment by codewithfeeling** [comment]
They have been down all day in the UK. Some inexplicable weird commit without testing (again).
That's three times this week our interactive NFTs have gone down for hours. This has to change - it cannot keep happening like this.

**Comment by aebrer** [comment]
seems fixed now!

**Comment by bilgekaan** [comment]
yeah fixed! I will close the report
