### ISSUE TITLE
OBJKT DIDN'T SHOW UP IN MANAGE ASSETS

### ISSUE THREAD

**Issue by soulyasa** [hicetnunc2000/hicetnunc#918]
After I mint my OBJKT the statues on wallet already applied, but on the manage assets it didn't appear. I check on my tryshowtime its available, but when I click the link through the tryshowtime It just show blank pages https://www.hicetnunc.xyz/objkt/140407
![asdadasdsa](https://user-images.githubusercontent.com/86136647/122627985-7ee1a900-d0dd-11eb-87c6-a71c9c482841.png)
![asdsad](https://user-images.githubusercontent.com/86136647/122627987-80ab6c80-d0dd-11eb-9ee4-2c46101816a0.png)
![asdsadwd](https://user-images.githubusercontent.com/86136647/122627992-83a65d00-d0dd-11eb-9881-8020e309e1e7.png)

**Comment by skenaja** [comment]
There was a API issue, should now have been resolved. If not, get back in touch, and we'll re-open the ticket.
