### ISSUE TITLE
"Edition" is Always Swaps Count

### ISSUE THREAD

**Issue by atomantic** [hicetnunc2000/hicetnunc#92]
In this example: https://hicetnunc.xyz/objkt/3942

the first 1/5 was sold for 1 XTZ to tz1c2iwyckUCcicx2qxqtwLEartYFEHg1pvB
the creator holds 3: tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9
the platform holds 1: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9

The Edition for sale is listed as `1/5`, but it should be `2/5` (#2 of 5 is for sale at 5 XTZ)

<img width="1252" alt="Screen Shot 2021-03-11 at 10 58 19 AM" src="https://user-images.githubusercontent.com/70015/110840043-1b7fe980-8259-11eb-8aa3-b0ef3fb420eb.png">

Imagining this could be calculated like so:

```
const editionNumber = Object.keys(owners).reduce((edition, ownerID)=>{
   // not the platform or the creator 
   if(owners[ownerID]!=='KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9' && !token_array.creators.includes(owners[ownerID])){
    // add the count of market owned editions
    // todo: not sure why these counts are stored as strings instead of numbers
    edition = edition + Number(owners[ownerID]);
   }
   return edition;
}, 0);
```

**Comment by andrevenancio** [comment]
Thanks for picking this up! mind submitting a PR?

**Comment by crzypatchwork** [comment]
this along the lowest swap price would fix completely this part
(remaining us to see transactional histories actually)

**Comment by andrevenancio** [comment]
Can you update your lower price PR with this fix too @atomantic ?

**Comment by atomantic** [comment]
I made a new PR with a branch from the lowest_price since they are easy to take one at a time, but if you want to take them both at once it's here: https://github.com/hicetnunc2000/hicetnunc/pull/109 :)

**Comment by skenaja** [comment]
This is now resolved, closing.
