### ISSUE TITLE
Minted but not showing up 

### ISSUE THREAD

**Issue by archtad** [hicetnunc2000/hicetnunc#921]
**Describe the bug**
I minted my piece, awaiting it to show in my collection to swap. Hour has passed, still will not show.
Currently I cannot also purchase an NFT, I get this error Simulation error: A FAILWITH instruction was reached {"int":"155"}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by skenaja** [comment]
There was a API issue, should now have been resolved. If not, get back in touch, and we'll re-open the ticket.
