### ISSUE TITLE
No MP4 playback in interactive objkt

### ISSUE THREAD

**Issue by deadlypixels** [hicetnunc2000/hicetnunc#925]
The interactive OBJKT is now functioning but the mp4 background video no longer plays.

hicetnunc.xyz/objkt/130010

hicetnunc.xyz/objkt/133605

**Comment by deadlypixels** [comment]
![image](https://user-images.githubusercontent.com/86114298/122652351-59cd5480-d136-11eb-925a-d472e155f542.png)

**Comment by violetforest** [comment]
is this working now?

**Comment by deadlypixels** [comment]
It was working yesterday but now it has stopped again. MP3 and MP4 are not
playing as they should. This is becoming rather annoying now as I can sell
or mint anything?

**Comment by violetforest** [comment]
i cant replicate the problem, i see the album cover animating in and out

**Comment by deadlypixels** [comment]
Hi, it's working fine now on all devices. Thank you for your help, much
appreciated.

Regards
