### ISSUE TITLE
Custom URL does not show creations or collection with space "%20" in name

### ISSUE THREAD

**Issue by spacegoodies** [hicetnunc2000/hicetnunc#928]
**Description**
As a user, when navigating to another user's custom URL, nothing is shown when the custom URL contains a space.

**To Reproduce**
1. Navigate to https://www.hicetnunc.xyz/objkt/139481
2. Click user's name, which will bring you to https://www.hicetnunc.xyz/Daniel%20@ferdoropeza
3. Click on 'creations' or 'collection' tab
4. URL switches to https://www.hicetnunc.xyz/tz//collection or https://www.hicetnunc.xyz/tz//creations because of the space "%20"

**Expected behavior**
Navigating to a user's profile page with a space should act as current behavior. Suggest to add _ when space is used for custom URL by users.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome
 - Version 91

**Comment by crzypatchwork** [comment]
could you try an alias without spaces for now? you just need to reconfigure it at hicetnunc.xyz/config

**Comment by spacegoodies** [comment]
Yep, I can but I was mainly commenting for artists I follow. I will reach out to them and ask them to reconfigure. Thanks for all your work!!

**Comment by violetforest** [comment]
this seems resolved, let me know if its not and I will reopen it

**Comment by spacegoodies** [comment]
Confirmed. This account had a space before https://www.hicetnunc.xyz/objkt/144372 Thanks @violetforest!!
