### ISSUE TITLE
Usernames on HEN

### ISSUE THREAD

**Issue by melMass** [hicetnunc2000/hicetnunc#934]
Edit: reformulated better/nicer

Hi,

I wanted to replace my address with my alias and thought it was linked to the TzProfiles process to discover it's not.

IMO the current state of the settings/config page is very confusing. Can't we add descriptions or tooltips to quickly explain the meaning of each controls.

## TLDR
Setting a username though the config UI does not seem to work, and it provides no information if it fails (when using an existing name for instance)

I tried "mel" it did not fail but ultimately never worked because it's already taken (btw can I know by who? The profile seems broken) and melmass with the same behavior 

Thanks

Here are the corresponding operations:
![image](https://user-images.githubusercontent.com/7041726/122807842-5c61b280-d2cc-11eb-88cc-68f4d2fd9d46.jpeg)

**Comment by dfeles** [comment]
I have a very similar issue, probably related to @melMass's comment.

Here is a reproducible bug:

- I filled out TzProfiles
- I open any of my newly created object, and my name displayed as the author instead of my address
- If I click on it, it directs me to a page, that displays an empty wallet

- meanwhile, I've filled out the google form for filling my details and I expect it to get updated within 72h

you can see the problem [here](https://www.hicetnunc.xyz/objkt/143581)

**Comment by melMass** [comment]
@dfeles Yours actually work 🥲

**Comment by dfeles** [comment]
if you click my name, you see my objects? it brings me to an empty page

**Comment by melMass** [comment]
> if you click my name, you see my objects? it brings me to an empty page

Oh that's a different issue, you cannot have spaces. But at least it registered on yours

**Comment by melMass** [comment]
It finally went through

EDIT: but not everywhere... I think this is a bug

**Comment by dfeles** [comment]
Any idea, how I can fix my space issue? meanwhile data got updated from the google forms, but bc I cant change anything on tz profiles, my link is broken on all my objects page.

**Comment by melMass** [comment]
I think something is wrong on the HEN side as it is not showing everywhere for me.

For your issue, I think you are as confused as I was.
TzProfiles or Baking Bad, allows you to have your name/description/logo/links on your profile but not replace your adress by your name. This is handled on HEN using the config as stated earlier.

So you just have to resubmit a new username in HEN's settings without a space and wait a bit for it to be effective.

IMO, it should not accept spaces in the first place that's the most basic form validation ever... I have no idea how issues like that are not resolved right away (I've seen dozens of people in your case)

**Comment by dfeles** [comment]
I've seen profiles though with spaces tho (like other artsists name, who don't use alias) and it is working for them
f.eg: http://hicetnunc.xyz/agoston-nagy

**Comment by melMass** [comment]
It’s not a space he has a middle dash.

![image](https://user-images.githubusercontent.com/7041726/123435415-d8f6d880-d5cd-11eb-804d-66c9f3f6d175.png)

**Comment by violetforest** [comment]
is this resolved? the consensus at the moment is to omit spaces
