### ISSUE TITLE
SVG width expands to full browser window

### ISSUE THREAD

**Issue by ertdfgcvb** [hicetnunc2000/hicetnunc#935]
SVGs are now resized to fit the whole window width, which is undesirable in most cases as the vertical height will be cropped. 
NOTE: this issue might be related to #54, maybe a regression?

Example SVG:
https://www.hicetnunc.xyz/objkt/82658

![Upper half of the window](https://user-images.githubusercontent.com/864073/122807826-579cfe80-d2cc-11eb-8c91-7eb1074e9221.png)

**Comment by ertdfgcvb** [comment]
The behaviour has changed: the iframe doesn't expand anymore (except on small screens which is probably the desired effect).
But the issue is now that the iframe doesn't keep the correct aspect ratio (it was a square before!) and expands the background. 
The size / aspect of the iframe should probably be read out from the size and/or the viewBox of the embedded SVG.

**Comment by violetforest** [comment]
how is it looking now? just made new changes to the way objkts are displayed

**Comment by ertdfgcvb** [comment]
> how is it looking now? just made new changes to the way objkts are displayed

Issue is closed, but I still wanted to say thank you!
