### ISSUE TITLE
Invisible item in the Collection on HICETNUNC

### ISSUE THREAD

**Issue by TheFoodMaster** [hicetnunc2000/hicetnunc#936]
One of my items is not visible anymore in my Hicetnunc collection

**Comment by skenaja** [comment]
Please can you give us some more info to help diagnose the problem - tz wallet ID & objkt number.

The most likely cause is that it's an item you put up for resale - please see https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-resell-%F0%9F%8F%AA

I'll reopen the ticked it more info provided.
