### ISSUE TITLE
No asset after minting

### ISSUE THREAD

**Issue by wblut** [hicetnunc2000/hicetnunc#937]
Minting went smoothly, OBJKT shows up on home feed. But ipfs asset doesn't load
https://www.hicetnunc.xyz/objkt/145843

Cheers,

Frederik

**Comment by skenaja** [comment]
Seems to be working OK. Must have been a temporary issue with IPFS

![image](https://user-images.githubusercontent.com/510285/123541779-26925300-d73e-11eb-81f2-f7740909da3e.png)
