### ISSUE TITLE
Updating metadata info 

### ISSUE THREAD

**Issue by Elmitodaniel** [hicetnunc2000/hicetnunc#938]
![0B19D402-FC5C-4DC6-B77D-C1812B92CF91](https://user-images.githubusercontent.com/86306816/122943043-0da82d00-d34d-11eb-9acc-c6c6eb1a0f29.png)
Can’t burn because it is already swapped

https://www.hicetnunc.xyz/objkt/145997

**Comment by Elmitodaniel** [comment]
![Uploading F7A2621E-22A2-4072-9765-6F2938CB3CA0.png…]()

**Comment by violetforest** [comment]
is this still happening? i will close but if you need more help i will reopen
