### ISSUE TITLE
error when attempting to burn objkt

### ISSUE THREAD

**Issue by datsla** [hicetnunc2000/hicetnunc#939]
H=N newbie here who participated recently in HENthousand and need to burn my unsold OBJKTS but got the following error: H=N: Error: You're trying to burn 9988, but you only own 0. am I missing a step? tried a few times but can't move forward as the same error msg reappears..

**Comment by violetforest** [comment]
This was a display error but it should be fixed now. Try clearing your browser cache.

If it still doesn't work, you can still burn 9988 even though it says 0. Go ahead and try it.

In the future, always check whats in your wallet and use that as confirmation. There should be 9988 in your wallet.

If you need anything else Ill open the issue back up
