### ISSUE TITLE
All Creations No Longer Displayed on Owner Creations Page

### ISSUE THREAD

**Issue by atomantic** [hicetnunc2000/hicetnunc#94]
tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9 created https://www.hicetnunc.xyz/objkt/957

but it doesn't show up anymore on https://www.hicetnunc.xyz/tz/tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9

It appears that all assets that are not owned at least in part by the creator (bought by others or fully on the market) are not showing up.

**Comment by andrevenancio** [comment]
done
