### ISSUE TITLE
content of tokens corrupted or bad replay

### ISSUE THREAD

**Issue by luluxxxxx** [hicetnunc2000/hicetnunc#940]
it concerns this piece : https://www.hicetnunc.xyz/objkt/146461
the original gif is not correctly loaded (or played) . it seems corrupted.
thanks in advance for your consideration.
lulu

**Comment by kylegrover** [comment]
It seems to be working now, is it loading for you? There have been intermittent IPFS gateway issues with the UI. You can also click 'ipfs' at the bottom of the objkt page to load the file directly and copy that string to other IPFS gateways to download it there if you ever need to.

**Comment by luluxxxxx** [comment]
yes its working now. thank you !

**Comment by violetforest** [comment]
gonna close, let me know ifyou need more help and i will reopen
