### ISSUE TITLE
After minting, white screen appears for .glb 3D Object

### ISSUE THREAD

**Issue by Jxke** [hicetnunc2000/hicetnunc#942]
Minted a 9 mb .glb 3D Object. Worked fine during Preview. After minting it's just this white screen. Occasionally I see a loading bar appear that never appears to finish. Used 310 Storage Fee. 

https://www.hicetnunc.xyz/objkt/147218

![Screenshot 2021-06-23 at 11 24 17 AM](https://user-images.githubusercontent.com/42780939/123030666-b8841e00-d415-11eb-9ede-f482ae340c1f.png)

**Comment by Pzn-arts** [comment]
I had the same problem after minting a simple png file, i minted the object again  and worked perfectly, i'm thinking in burn the object, but i guess i'll wait a little bit.

**Comment by Jxke** [comment]
> I had the same problem after minting a simple png file, i minted the object again and worked perfectly, i'm thinking in burn the object, but i guess i'll wait a little bit.

Was glad to see it went up after around 10hours and the white screen was gone. Then now, 2 days later, it's back to being a white screen. A pity the platform is not optimised.

**Comment by crzypatchwork** [comment]
that was an instability on ipfs public gateways. the platform relies on multiple distributed systems keep that coordination effort in mind :)) it seems solved for now this issue with .glb

![Screenshot from 2021-06-25 09-18-09](https://user-images.githubusercontent.com/24375224/123423785-5e5e9680-d596-11eb-96ad-8f721c076347.png)
