### ISSUE TITLE
Mint page font shows as doubled on Iphone

### ISSUE THREAD

**Issue by tagachistudio** [hicetnunc2000/hicetnunc#945]
**Describe the bug**
When a user browses the mint page on Safari browser on an Iphone, hover animation of input fields seems to show 2 different words of the same.

**To Reproduce**
1. Go to 'https://hicethunc.xyz/mint'

**Expected behavior**
There shouldn't be 2 different words for each input field.

**Screenshots**
https://media.discordapp.net/attachments/852921695073337354/857524474111066112/unknown.png?width=536&height=843

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: Iphone12
 - OS: iOS
 - Browser Safari

**Additional context**
This might be caused by the animation library used.

Bug found by @denscimonk

**Comment by tagachistudio** [comment]
This is how it shows on Iphone 12 Pro - iOS 14.3.

![Screenshot 2021-06-24 161928](https://user-images.githubusercontent.com/83205744/123228395-fc575000-d507-11eb-868e-b24af2aec34d.jpg)

This is how it disappears after filling all input fields.
![Screenshot 2021-06-24 162311](https://user-images.githubusercontent.com/83205744/123229017-7ee00f80-d508-11eb-8d63-592d657d49e8.jpg)

**Comment by violetforest** [comment]
this should be fixed -- if not, please let me know
