### ISSUE TITLE
My Hicetnunc Objkt missing

### ISSUE THREAD

**Issue by RiauArts** [hicetnunc2000/hicetnunc#951]
One of my Hicetnunc objkt is missing. 

I had an objkt that I had swapped with 2 editions.  (I bought the objkt instead of minting).  I burned one edition out of the two, so that I had a 1/1. I swapped the remaining 1/1, but I can't find it in either my collections or creations. I am sure I didn't burn the other one.

My wallet address is : riauarts.tez

This is the activity log of my wallet:

![temple](https://user-images.githubusercontent.com/86511118/123505048-83c4d080-d67a-11eb-861b-af9890c6dc10.JPG)

Where did it go? Is there any way I can retrieve it?

Thanks for your help.

**Comment by skenaja** [comment]
Swapped objkts for resale don't appear on your collection pages - see https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-resell-%F0%9F%8F%AA
