### ISSUE TITLE
Objkts are still available to collect for 0.1 tez but x/100 shown

### ISSUE THREAD

**Issue by spacegoodies** [hicetnunc2000/hicetnunc#952]
**Description**
As a user, I should not see "collect for... tez" button if x/100 or other x/editions is shown. This issue was discussed by @poppel20 and @spacegoodies on Twitter. During #HEN100 #100HEN, a collector (possibly a bot script) collected 18 pieces, which could have caused an issue.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/120483
2. Objkt shows x/100 but still shows "collect for 0.1 tez" button.
3. spacegoodies collected at 1/100, thinking it was the last piece, so communicated with @poppel20 on Twitter and realized later that the objkt shows poppel with -19 objkts and 14 objkts for 0.1 tez in collectors tab.
4. Number of objkts collected is 100+ for some reason, and poppel has 0 objkts in wallet.

**Expected behavior**
After x/editions are all collected, creators wallet should show correct number of objkts in wallet per current behavior.

**Screenshots**
<img width="768" alt="Screen Shot 2021-06-27 at 11 15 05 AM" src="https://user-images.githubusercontent.com/20116276/123549899-f09ea000-d738-11eb-86cf-d0a299b72f46.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome 91

**Comment by skenaja** [comment]
Now showing correctly
