### ISSUE TITLE
Problem with profile https://www.hicetnunc.xyz/tz/tz1ZfApCB1rmfyByn9e1jj1w9jLSY1wfu9dm/creations

### ISSUE THREAD

**Issue by Cembasak** [hicetnunc2000/hicetnunc#953]
Problem with profile 
https://www.hicetnunc.xyz/tz/tz1ZfApCB1rmfyByn9e1jj1w9jLSY1wfu9dm/creations

Can view everything, but can do nothing No swap, no cancel, no burn, no buy! Check this out please

**Comment by sf-pixel** [comment]
Are you sure you can't do anything? Could be a wallet issue, someone just bought something a few minutes ago, sounds like a wallet issue on your end.

https://tzkt.io/opYPsKFxnqQ7p4HnLLaqN12aBShKPzhayYm35GpnCVpfxLPzEN3

**Comment by violetforest** [comment]
Collecting has been temporarily disabled on the site, is it connected to this?

**Comment by Cembasak** [comment]
it was before that but its ok now

Violet Forest ***@***.***>, 30 Haz 2021 Çar, 22:54 tarihinde
şunu yazdı:
