### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Loriana-Art** [hicetnunc2000/hicetnunc#957]
I am not sure if this is a question for you or the KUKAi  wallet  or maybe have two different wallets?  
I want to organize my art on collections with the same concept.   I don't think it is possible right now.  Is there a way that   But I can have two can have tow HEN accounts? Maybe I need two wallets, which would fine.  But I would like everything to be connected to the same Twitter account.   Thanks

**Comment by violetforest** [comment]
Hey, yes two wallet accounts is something a lot of people do. This seems to be the only option at the moment. You can submit two applications to verify your profile with baking bad.

https://baking-bad.org/blog/2021/05/01/f-a-q-hic-et-nunc/#i-have-several-tz-addresses-can-i-add-them-from-the-same-account

https://github.com/hicetnunc2000/hicetnunc/wiki/Edit-your-profile

**Comment by violetforest** [comment]
im goign to close this for now but please let me know if you need anything else and i will reopen it
