### ISSUE TITLE
Wrong? cover IMG on IPFS...?

### ISSUE THREAD

**Issue by ComPressOrk** [hicetnunc2000/hicetnunc#975]
1. So when I minted this OBJKT - objkt/97513 - 🗣HEN∞Language🕊 - it was totally good at Hic Et Nunc. It has its own cover image, or the MP4 cover, but not my profile IMG: https://www.hicetnunc.xyz/objkt/97513
 
2. My suspicion: A bot bought all my stuff, and after that my profile IMG flashes up when I load my hic et nunc profile page: https://www.hicetnunc.xyz/tz/tz1PXmUnJDh9zPKQxZLtSZ11DZbPki6XmWfP/creations  , but then it disappears...and the original mp4 shown up. 

!!! - I do not upload my profile image here ever - !!!

3. So in objkt.bid - on my creation page - I just see only my profile image!!!...not the original cover image or mp4 like on hic et nunc.xyz...
https://www.objkt.bid/profile/tz1PXmUnJDh9zPKQxZLtSZ11DZbPki6XmWfP/creations

How could it be? I like myself, but don't want to see it here :)!!!
I know IPFS can't be changed and I realized maybe @objtk.bit can show just the cover metadata on my profile page, but how could it happen? The first time it was totally ok. It hasn't got my profile pic, now it has...& I never uploaded my profile image for this OBJKT!!! Could you see what happened on the metadata?

Thank you so much.
Tamas

**Comment by skenaja** [comment]
This was resolved https://discord.com/channels/759930487946215444/812076819129827358/860870811559395348

The issue was the image in question was added as the "cover image" that is required when uploading mp4 files to act as a static summary image. HEN doesn't currently use this image, but other sites do, including objkt.bid.
