### ISSUE TITLE
Account logos no longer appear on profile pages

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc#980]
tzkt.io have deprecated/removed `logo` from their account metadata call.

https://api.tzkt.io/v1/accounts/tz1fb6jz7rh4H7AojLShvhiXKaSNDyvkH7sM/metadata
```
{"kind":"person","alias":"bors__nft","description":"NFT Super Sketch Artist",
"site":"https://bors.carrd.co/","twitter":"bors___","instagram":"bors__nft"}
```

From their Telegram group:
> There is a kind of rule on tzkt.io - if a user has an alias, then he should have a logo as well. So, if a user doesn't have an alias, then you can use your placeholder.

https://github.com/hicetnunc2000/hicetnunc/blob/3b4c5e0721c784c4581a2cb3b1d397a35b08dd39/src/pages/display/index.js#L299
`(data.data.logo)`  will now return false.

**Comment by crzypatchwork** [comment]
we're gonna disable all tzkt profiles and start using subjkts only this week

**Comment by skenaja** [comment]
avatars now implemented under `/config` page
