### ISSUE TITLE
Broken Interactive NFT

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#982]
**Describe the bug**
I'm getting a 503 error on one of my interactive NFT's.

https://www.hicetnunc.xyz/objkt/25969
on IPFS https://ipfs.io/ipfs/QmbZBeTzDtgrYEy3CxHrGKPGUr9QQyBSxtXn21pE9ru86S

<img width="1231" alt="Screenshot 2021-07-07 at 16 44 57" src="https://user-images.githubusercontent.com/1734502/124790122-cfad2a80-df42-11eb-92a8-3dfd5bcac997.png">

**Comment by bilgekaan** [comment]
Same, some of my nfts won't load https://www.hicetnunc.xyz/play/creations

**Comment by violetforest** [comment]
is this still happening? @andrevenancio

**Comment by crzypatchwork** [comment]
I couldn't reproduce many of these reports, but sometimes we can face ipfs/rpc instability. we're not having breaking changes in the providers for now to not cause more instability, but we'll gradually review them.

**Comment by andrevenancio** [comment]
Yeah, it seems to be working fine now. I'm not sure exactly what caused the issues. All seems right! I'll close this! Thanks everyone
