### ISSUE TITLE
Can I change the description of a minted objkt?

### ISSUE THREAD

**Issue by SeanPedersen** [hicetnunc2000/hicetnunc#986]
Simple question, could not find it answered in the FAQ. Thanks for any pointers.

**Comment by skenaja** [comment]
Hi Sean, sorry, that's not currently possible - see this for details:

https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#how-do-i-edit-the-description-of-my-nft-after-i-minted-it
