### ISSUE TITLE
random page crashes. c is undefined

### ISSUE THREAD

**Issue by wraybowling** [hicetnunc2000/hicetnunc#990]
**Describe the bug**
https://www.hicetnunc.xyz/random whitescreens. React scheduler is falling over on something.

**To Reproduce**
1. visit https://www.hicetnunc.xyz/random
2. open the console
3. see `c is undefined` error a bunch of times

**Expected behavior**
a page with stuff

**Screenshots**
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/1120619/125012046-84c10f00-e037-11eb-8165-7c068d68e0f1.png">

**Desktop (please complete the following information):**
 - System: MacBook Pro (15-inch, 2018)
 - OS: MacOS 11.4
 - Browser: Firefox
 - Version: 89.0.2

**Comment by violetforest** [comment]
random page is fixed, thanks
