### ISSUE TITLE
Cancel Swap errors due to old contract

### ISSUE THREAD

**Issue by Asong64** [hicetnunc2000/hicetnunc#992]
Unable to cancel swap from HEN using Temple and Kukai wallets. Error codes for both. 
Temple wallet - Transaction Likely to Fail
Kukai wallet - Simulation error: A FAILWITH instruction was reached
Owned editions show up in Hicdex, but not in HEN collectors tab. (only purchased editions show up in HEN)

**To Reproduce**
1. Go to HEN
2. Click on V1 Swaps
3. Click on Cancel Swap for an item
4. Wallet brings up window
5. Click confirm
6. Error shows: The transaction is invalid and the node did not accept it.

**Expected behavior**
Wallet should bring up window allowing for adjustment of storage value. (without "transaction likely to fail" messaging)
Click confirm, then wallet should continue with transaction. 

<img width="474" alt="Screen Shot 2021-07-09 at 7 29 31 PM" src="https://user-images.githubusercontent.com/85418875/125149150-15592700-e0ec-11eb-8b47-8ac9b446161f.png">

**Desktop (please complete the following information):**
 - macOS Mojave 10.14.6
 - Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
I believe that this may be due to something with the old contract. Someone on the discord sent me this screenshot:
![unknown](https://user-images.githubusercontent.com/85418875/125149178-4b96a680-e0ec-11eb-8057-2cb851a94f34.png)

**Comment by tenineight** [comment]
I have two separate accounts and only one of them shows the same issue. In case you need to deep dive: tz1dqCHsxC2npF9iu8MBrEn6rwLPMUbxNjeg <-- this is where the OBJKTs seem to be stuck on v1

**Comment by skenaja** [comment]
It looks like the batch_cancel function is calling the v2 cancel_swap method, and which will fail as the swap ids don't exist in the v2 contract.

![image](https://user-images.githubusercontent.com/510285/125164012-dc6e9000-e187-11eb-90d7-1da9611847b3.png)

Temple popup operation has wrong destination:
`[ { "destination": "KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn", "kind": "transaction", "amount": 0, "storageLimit": "310", "parameters": { "entrypoint": "cancel_swap", "value": { "int": "219019" } } } ]`

V1 swaps look OK for cancelling:
- https://api.tzkt.io/v1/bigmaps/523/keys?value.issuer=tz1gLMknmiBiwDpUzJihHY69DWE7eH3J4bLR&active=true
- https://api.tzkt.io/v1/bigmaps/511/keys?key.address=KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9&select=key,value,active&limit=10000&key.nat=92845

**Comment by skenaja** [comment]
Here's the workaround pending a fix:

1. https://old.objkt.bid/profile
2. sign in with your wallet
3. clear the active v1 swaps with this button

![image](https://user-images.githubusercontent.com/510285/125164134-a1209100-e188-11eb-9ede-45b672bc874b.png)

**Comment by tenineight** [comment]
@skenaja Thank you that worked!

**Comment by Asong64** [comment]
Thank you, but I'm still getting the same errors as before. (please see
attached image)

**Comment by Asong64** [comment]
Thank you, but I'm still getting the same errors as before. (please see
attached image)
![Screen Shot 2021-07-10 at 8 55 40 AM](https://user-images.githubusercontent.com/85418875/125169043-4b82bf00-e15d-11eb-9439-8cadd534176c.png)

**Comment by skenaja** [comment]
This should be fixed by 10f0c5e71f3444f9303859f079c976f217bda850.

The new fix might cause backtracks as it doesn't default the storage amount, so increase storage to 310 if you use temple

**Comment by skenaja** [comment]
@Asong64 - that's a bug with objkt.bid, you can contact them for support on their discord https://discord.gg/5yDdS5xY

The cancel bug should now be fixed on hicetnunc if you want to try again

**Comment by Asong64** [comment]
Thank you! I have successfully cancelled and relisted my editions! I
appreciate all your hard work over there. Take care.
